### ISSUE TITLE
Audio Workers: number of input/output channels and inputs/outputs

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#1]
> Originally reported on W3C Bugzilla [ISSUE-17534](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17534) Mon, 18 Jun 2012 11:27:42 GMT
> Reported by Marcus Geelnard (Opera)
> Assigned to 

The JavaScriptAudioNode does not have the ability to dynamically change its number of input/ouptut channels after creation.

This makes it impossible to re-implement nodes such as AudioGainNode (depends on number of input channels) and ConvolverNode (depends on number of AudioContext output channels - according to [1]).

[1] https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#Convolution-reverb-effect

**Comment by joeberkovitz** [comment]
I believe this is covered as part of the resolution to #113. Closing
