### ISSUE TITLE
maxChannelCount = 0 for stereo hardware?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1000]
In https://webaudio.github.io/web-audio-api/#widl-AudioDestinationNode-maxChannelCount, there's the sentences:

> If this value is 0, then this indicates that channelCount may not be changed. This will be the case for an AudioDestinationNode in an OfflineAudioContext and also for basic implementations with hardware support for stereo output only.

I read this as meaning hardware with only stereo output sets `maxChannelCount` to 0.  Why? Wouldn't it make more sense to just set it to 2 for stereo hardware?

**Comment by mdjp** [comment]
I agree, setting to 0 is very confusing and inconsistent in the case that there is higher channel count available. it is also inaccurate as the maxChannelCount is of course 2.

**Comment by padenot** [comment]
Agreed. Gecko always has returned the number of channels of the hardware, and has never returned 0.
