### ISSUE TITLE
Consider downloading a tidy binary

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1006]
We currently download the sources for tidy and checkout version 5.2.0 before building it.  A precompiled binary for this is available at http://binaries.html-tidy.org/

Consider downloading a binary instead of building from sources.  This might speed up checks as well; it takes some 7 sec to download cmake and 16 sec to build and install tidy.

**Comment by hoch** [comment]
See https://github.com/WebAudio/web-audio-api/pull/1012 for more information on this improvement.
