### ISSUE TITLE
AudioListener initial forwardZ orientation value

### ISSUE THREAD

**Issue by alvov** [WebAudio/web-audio-api#1032]
In issue https://github.com/WebAudio/web-audio-api/issues/907 the initial value for `forwardZ` attribute of `AudioListener` was fixed from 0 to -1, but now it seems to be 0 back again. I believe it got broken in cc27443.

**Comment by rtoy** [comment]
Thanks for the note.  It should be -1, as you say.  We'll fix this soon.

**Comment by alvov** [comment]
Thanks!
