### ISSUE TITLE
[question] PannerNode initial orientation value

### ISSUE THREAD

**Issue by alvov** [WebAudio/web-audio-api#1033]
The `PannerNode` initial orientation is `(1, 0, 0)`, which means that it is oriented along axis X. I find this a little bit confusing, as the initial listener's forward orientation lies along axis Z, so I expect that the panner should by default be facing the listener.

So my question is, why is it so that `orientationX` initial value is 1? And I wonder, wouldn't it be more intuitive if the `PannerNode` initial orientation value was `(0, 0, 1)`?

Thank you.

**Comment by rtoy** [comment]
I don't know why it's set this way, but it looks like it's always been this way in the spec.  I would be reluctant to change the default now; it would break all uses of the panner today.

**Comment by padenot** [comment]
Agreed.

**Comment by alvov** [comment]
Ok, that's reasonable. Thanks a lot for responses.
