### ISSUE TITLE
decodedAudioData() should probably reject a TypeError

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1037]
Hi, I just found something which I think might be a little mistake. The current version of the spec says the decodeAudioData() promise might be rejected with a "DOMException whose name is "TypeError"". Everywhere else in the spec TypeErrors are regular TypeErrors which are not somehow wrapped in a DOMException, that's why I guess this might be a mistake. As far as I remember it was once a NotSupportError DOMException, which might be the reason for that.

If my assumptions are right and you agree, I'm happy to turn this into a pull request.

**Comment by padenot** [comment]
Yep, good catch.
