### ISSUE TITLE
Multiple sound card support

### ISSUE THREAD

**Issue by rektide** [WebAudio/web-audio-api#1043]
I'd like to use the web platform to develop a whole house ambient sound generator demo. Yet it seems AudioContext is always fixed, hardcoded to the default sound device.

Another example of a possible need for this might be [Gamepad](https://github.com/w3c/gamepad), which for the past couple years has been an attached controller with it's very own audio output device. If gamepads are to be useful, usable things in on the web platform, we will need multiple sound card support.

**Comment by padenot** [comment]
This is handled in another spec, because we want it to work with regular `HTMLMediaElement` as well: <https://github.com/w3c/mediacapture-output/>.
