### ISSUE TITLE
Source node lifetime with connected AudioParam input?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1044]
For the most part, I expect `ConstantSourceNode` to behave like an `OscillatorNode`:  when `stop()` is called, the node stops and can disconnect its output from the rest of the graph, allowing GC to happen.

However, unlike other source nodes, what should happen if there is another active node connected to the single `offset` AudioParam of the constant source node?  Since we called `stop()`, I think the connected AudioParam should also be stopped.  This is a bit different from other nodes with AudioParams which would keep the node alive if the AudioParam were connected to other nodes.

We should make it clear that the `offset` AudioParam of a `ConstantSourceNode` is effectively disconnected when `stop` is called.

**Comment by rtoy** [comment]
Actually, all other source nodes have the same issue. Does the connected AudioParam keep the node alive even after `stop()` has been called. I think it should not.

**Comment by joeberkovitz** [comment]
I raised this question some time in the last few months on the list. I agree it's a general issue, not just for ConstantSourceNodes.

I agree with you that connected AudioParams in general should not retain a node in memory. My PR #1056 (fixing #944) amends the spec to clearly say this, if we accept it.

**Comment by joeberkovitz** [comment]
Closed via #1056
