### ISSUE TITLE
Behavior of source node with connected AudioParam?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1048]
Consider this bit of code:

```
// @channels 1
// @duration 1.0
// @sampleRate 48000

var osc = context.createOscillator();
osc.frequency.value = 10000;

var mod = context.createOscillator();
mod.frequency.value = 1;
var modGain = context.createGain();
modGain.gain.value = -10000;

mod.connect(modGain);
mod.start();

modGain.connect(osc.detune);

osc.connect(context.destination);
osc.start(0.25);
```

(You can run this in [Canopy](hoch.github.io/canopy))

What should the output be?  When the `osc` starts at time 0.25, what is the instantaneous frequency of the oscillator?  One answer is that the frequency is 10000 because `mod` doesn't actually generate any data until `osc` starts.  At that point the value of `mod` is 0, so the frequency of `osc` is still 10000.

However, one can think that `mod` has been running from 0.25 sec already.  At this point, the value of `mod` is 1 (1/4 quarter wave has passed), so that `modGain` output is -10000.  This combined with the `osc` frequency means that the instantaneous frequency is 0.

Which of these is the correct output?

The [spec, item 8](https://webaudio.github.io/web-audio-api/#rendering-loop) isn't super clear about this, but doesn't mention any special cases for source nodes (other than generating some output).  We should make this clearer.

**Comment by joeberkovitz** [comment]
It seems very strange that `osc`'s start time would affect the state of `mod` in any way. The independence of nodes is essential to the intuitive "patch cable" model underlying Web Audio.

**Comment by rtoy** [comment]
Firefox starts with a very low frequency. That is, `mod` has been running for 0.25 sec when `osc` starts.
