### ISSUE TITLE
Convolver diagram needs mono input 4-channel response

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1050]
Based on the convolver node settings of `channelCount` and `channelCountMode`, it is valid to have a mono source with a 4-channel response.  The mono source is upmixed to stereo and the normal true-stereo processing occurs.

There's no diagram for this.  Should there be?

**Comment by joeberkovitz** [comment]
Missing diagram should depict same as "true stereo" but with mono upmixing
