### ISSUE TITLE
Exposing BaseAudioContext

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1060]
Now we have decided to keep the BaseAudioContext class, there are two things to be re-confirmed and clarified:

1. Expose the non-instantiable BaseAudioContext interface.

I guess this is what we already have in the spec. The purpose of exposure is to allow developers to touch the prototype of BaseAudioContext. Then all other audio context variants will inherit the same interface.

2. Rearranging `suspend()` methods to AudioContext and OfflineAudioContext.

The method signature of suspend() method in these two contexts are different, so it is reasonable to separate them. See the following:

```webidl
partial interface BaseAudioContext {
  Promise<void> resume();
}

partial interface AudioContext : BaseAudioContext {
  Promise<void> suspend();
  Promise<void> close();
}

partial interface OfflineAudioContext : BaseAudioContext {
  Promise<void> suspend(double time);
}
```

**Comment by joeberkovitz** [comment]
Clarified - yes this makes sense.

**Comment by hoch** [comment]
I reopening this because we haven't actually fixed the spec yet.
