### ISSUE TITLE
ConstantSourceNode behavior on start() / stop()

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#1068]
I think these points are not clear in spec. : 

* What value is output the ConstantSourceNode before start(), maybe zero?
* Is the ConstantSourceNode after stop() output return to zero or remain the last output?

the AudioScheduledSourceNode start()/stop() description use the word 'sound', but it
may not match to ConstantSourceNode.

**Comment by rtoy** [comment]
Yes, the output before starting and after stopping should be 0, just like for `AudioBufferSourceNode` and `OscillatorNode`.  This is probably best handled when the `AudioScheduledSourceNode` base class is added.
