### ISSUE TITLE
Description for the value when reading AudioParam.value

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#1081]
The description, "Subsequent accesses to this attribute's getter will return the same value."
in 2.6.1 AudioParam.value description is confusable.

This explanation has caused a difference in interpretation between Chrome and Firefox for a long time.
I think it would be better to improve the description to make the specification unambiguous.

**Comment by rtoy** [comment]
Yeah, this needs clarification.  See https://github.com/WebAudio/web-audio-api/issues/318#issuecomment-248006232.  The issue of `getValueAtTime` was punted to version next, but I think the consensus was that having the getter returning the value from the setter is not very useful when you can have automations on the AudioParam.

**Comment by joeberkovitz** [comment]
Current proposal: 

The value getter returns the last-computed value of the parameter at the end of the last-rendered block (or the intrinsic value, if the context has not rendered yet).

**Comment by joeberkovitz** [comment]
From F2F meeting: adapt step 8.1 in https://webaudio.github.io/web-audio-api/#rendering-loop to queue a message to the control thread for each AudioParam communicating its current value at the end of the render quantum.
