### ISSUE TITLE
What happens when process() throws?

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#1084]

**Comment by joeberkovitz** [comment]
A proposal coming out of today's WG discussion suggested that the AWP should be "nuked" if this happens, preventing its process() method from ever being called again, to prevent a vast number of error messages clogging the UA.

**Comment by hoch** [comment]
A related bit from CSS Painting API: https://drafts.css-houdini.org/css-paint-api-1/#paint-valid-flag

**Comment by hoch** [comment]
In order to do this, `WorkletGlobalScope` needs to support the error reporting: https://github.com/WebAudio/web-audio-api/issues/1194#issuecomment-293068672

**Comment by hoch** [comment]
Since the idea of exposing such state in JS API surface is under the discussion in #1247, I am closing this issue.
