### ISSUE TITLE
Gain being ignored in Chrome

### ISSUE THREAD

**Issue by root66** [WebAudio/web-audio-api#1086]
Chrome has recently started ignoring my gain settings, which has broken a lot of projects which were previously working. The following snippet demonstrates the issue. I am currently using Chrome 54.0.2840.99 m (64-bit). Firefox seems to be working fine.

`var audioContext = new (window.AudioContext || window.webkitAudioContext)();`
`var master = audioContext.createGain();`
`master.connect(audioContext.destination);`
`master.gain.setValueAtTime(0.01, audioContext.currentTime + 0.1);`

`var osc = audioContext.createOscillator();`
`osc.type = "square";`
`osc.connect(master);`

`osc.start(audioContext.currentTime + 0.2);`
`osc.stop(audioContext.currentTime + 0.25 + 0.2);`

In Firefox, the sound is very quiet (the gain is set to 0.01). In Chrome, it seems to ignore the gain and play at full volume. The delays of 0.1 and 0.2 were added to demonstrate that this is not a race condition caused by using currentTime directly.

**Comment by rtoy** [comment]
That's a Chrome bug, not a spec bug.  Please file a Chrome bug at crbug.com/new.

Closing this.
