### ISSUE TITLE
 "Asynchronously perform the remaining steps" is not well-defined

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1092]
You probably want to use https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel so that the promise-manipulation done from the async sections makes sense.

**Comment by padenot** [comment]
The report at <https://github.com/w3c/browser-payment-api/issues/341> links to a /TR/ spec, the editor's draft has been fixed a while back (we have our own mechanism to handle this, because threading in audio is quite special).

**Comment by bzbarsky** [comment]
Ah, indeed.  Sorry, I thought I had checked the editor's draft.  :(
