### ISSUE TITLE
Multiple definitions of block processing size

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1094]
The [AudioParam Interface section](https://webaudio.github.io/web-audio-api/#AudioParam), third paragraph, says block processing must be done.  That seems like a weird place to say this.

[AudioNode Interface](https://webaudio.github.io/web-audio-api/#the-audionode-interface), paragraph 7 also says the same thing, in more detail.

This needs to be fixed up and defined in exactly one place.  The more detailed text from this section should probably be moved to the definition of [render quantum](https://webaudio.github.io/web-audio-api/#dfn-render-quantum)

**Comment by svgeesus** [comment]
Isn't this addressed by the PR https://github.com/WebAudio/web-audio-api/pull/1170 ?

**Comment by joeberkovitz** [comment]
Yes it is, closing!
