### ISSUE TITLE
Inconsistent description of `loop` attribute behavior

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1095]
@cwilso pointed out to me that https://webaudio.github.io/web-audio-api/#looping-AudioBufferSourceNode says

> If the loop attribute is true when start() is called, then playback will continue indefinitely until stop() is called and the stop time is reached.

This is inconsistent with what is described in https://webaudio.github.io/web-audio-api/#looping-AudioBufferSourceNode which implies that `loop` can be dynamically modified.

**Comment by jakearchibald** [comment]
Should those links be different?

**Comment by rtoy** [comment]
Oops.  The second link should be https://webaudio.github.io/web-audio-api/#widl-AudioBufferSourceNode-loop which describes the `loop` attribute.

**Comment by joeberkovitz** [comment]
From F2F: Need to rewrite the looping section to be correct and conform to the algorithm.
