### ISSUE TITLE
AudioContextLatencyCategory and baseLatency in wrong class

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1097]
Currently [AudioContextLatencyCategory](https://webaudio.github.io/web-audio-api/#idl-def-AudioContextLatencyCategory) and  [baseLatency](https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-baseLatency) are defined as part of the BaseAudioContext.

But these don't really make sense for an OfflineAudioContext which inherits from the BaseAudioContext.  Thus, these items should be moved to an AudioContext.

**Comment by joeberkovitz** [comment]
This appears to be an oversight - we should rectify.
