### ISSUE TITLE
AudioContext.sampleRate for a closed context?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1099]
Currently in Chrome for a closed AudioContext, sampleRate = 0.  In Firefox, it is the sample rate of the context before it was closed.  This didn't really matter before, but since you can now say `new AudioBuffer(c, {length:1})`, this matters because the sample rate of the buffer defaults to the context rate.

Also, in Firefox the closed context context.destination is an AudioDestinationNode.  In Chrome it is set to null.  There are also other differences between the two implementations.

I think we should explicitly state that the sampleRate must be preserved for a closed context, and all other attributes are implementation-defined.

**Comment by padenot** [comment]
If nothing is said in the spec, nothing changes when `close` is called. In general, specs should say what else has to happen when something happens, not what does not happen when something else happens.

I don't think closing a context should have any impact on the `AudioDestinationNode`, or the samplerate, or anything else apart from what is currently specced (i.e. preventing the creation of new `AudioNode`s, stopping `currentTime`, rejecting some promises, etc.).

**Comment by rtoy** [comment]
I see your point.  But on the other hand, if you don't say, then anything is valid because you didn't say.  And because we don't say, Chrome's behaviour is perfectly valid.

**Comment by padenot** [comment]
It's the other way around. Specs only state what should happen, and should state everything that should happen. Anything that is not stated should not happen.

**Comment by joeberkovitz** [comment]
How we resolve this depends on whether we address #370 by decoupling buffer construction from AudioContext

**Comment by rtoy** [comment]
It wasn't captured in the minutes of the telconf, but @cwilso mentioned that maybe the right thing is to say that the destination node is set to null.  Please correct me, if you didn't actually say that @cwilso!

Note also that an AudioDestinationNode is an AudioNode which has a reference to the context.  And a context has a reference to the destination node.  Wouldn't this cycle prevent a context from ever getting collected?

**Comment by rtoy** [comment]
I guess whether the context goes away depends on the kind of GC being used by the javascript engine.  If the context is not reachable, everything should go away.

**Comment by joeberkovitz** [comment]
Resolved: nothing happens when a context is closed. No sample rate change, no disappearance of the destination node.
