### ISSUE TITLE
Should specify what happens if an out-of-range value is set for PannerNode.panningModel and PannerNode.distanceModel

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#11]
> Originally reported on W3C Bugzilla [ISSUE-19871](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19871) Tue, 06 Nov 2012 01:43:29 GMT
> Reported by Ehsan Akhgari [:ehsan]
> Assigned to 

We should probably throw INDEX_SIZE_ERR.

**Comment by rtoy** [comment]
From the comment by padenot@, nothing should be done.  Closing this.
