### ISSUE TITLE
Sample format: what do +/-Infinity and NaN mean?

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#110]
> Originally reported on W3C Bugzilla [ISSUE-17394](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17394) Tue, 05 Jun 2012 12:14:04 GMT
> Reported by Michael[tm] Smith
> Assigned to 

Audio-ISSUE-19 (SamplingFormat): Define sampling format [Web Audio API]

http://www.w3.org/2011/audio/track/issues/19

Raised by: Marcus Geelnard
On product: Web Audio API

In the internal sample format the interpretation of Float32 NaN, +-Inf etc is not defined. More generally, it seems to not be defined what the sampling format of everything is (AudioBuffer, WaveShaperNode, etc).

**Comment by rtoy** [comment]
Close this as wontfix or something?

**Comment by cwilso** [comment]
Left open for adding informative comment to spec.

**Comment by billhofmann** [comment]
Comments above suggest that the appropriate informative comment might be in AudioDestinationNode.  Another place that makes sense to me is AudioBuffer.

However, I'd suggest that this may be "not an issue" if the web idl definitions are float (http://www.w3.org/TR/WebIDL/#idl-float), which is finite by definition (vs unrestricted float).  For clarity, we might change less strict discussions (e.g. in AudioBuffer) to say "finite IEEE ..."

Your thoughts?

**Comment by rtoy** [comment]
I think the right place is AudioDestinationNode.  Anything can happen between an AudioBuffer to the destination. 

But what do we want to say?  Values above 1 in magnitude are very likely going to cause problems too (clipping).
