### ISSUE TITLE
BaseAudioContext should have a factory method for creating AudioWorkletNode

### ISSUE THREAD

**Issue by bakulf** [WebAudio/web-audio-api#1109]
Each AudioNode has two ways to be constructed: the WebIDL Constructor and the factory method.
But AudioWorkletNode just has the WebIDL Constructor. I suggest to add:

`AudioWorkletNode       createAudioWorklet(DOMString name);`

to the BaseAudioContext interface.

**Comment by rtoy** [comment]
I think we made a conscious decision not to do this.  But I'm not sure.  Any one else remember? @joeberkovitz , @hoch , @padenot

**Comment by joeberkovitz** [comment]
The reason is that we expect (and should encourage) developers to subclass AudioWorkletNodes and to instantiate subclasses. A plain vanilla AWN won't have much messaging capability to communicate method calls or property value changes with its AWP in any meaningful way.

**Comment by joeberkovitz** [comment]
Closing since subclassing is recommended.
