### ISSUE TITLE
PeriodicWave's constructor is not valid IDL

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1116]
The dictionary without required members in trailing position needs to be optional, per IDL.

**Comment by rtoy** [comment]
In https://webaudio.github.io/web-audio-api/#periodicwaveoptions, the text says that one of real or imag dictionary member is required.  Can that be expressed in IDL somehow?  Or maybe we can default both of them to some sensible default and thus make both members truly optional?

**Comment by bzbarsky** [comment]
> Can that be expressed in IDL somehow?

Not at the moment.

> Or maybe we can default both of them to some sensible default and thus make both members truly optional?

It's hard to say, because the behavior of this constructor is pretty much completely undefined.  See https://github.com/WebAudio/web-audio-api/issues/1120

**Comment by rtoy** [comment]
In the teleconf, a couple of things were suggested:

1. Leave it as is
2. Make dictionary optional, and make the real and imag members truly optional. This can having PeriodicWave default to a sine wave if PeriodicWaveOptions is not given.

**Comment by bzbarsky** [comment]
You can't leave it as is, because as is is not valid IDL....

**Comment by rtoy** [comment]
The proposal in PR #1116 is option 2:  Make the dictionary optional, and specify what happens if both real and imag are not given.
