### ISSUE TITLE
Would be nice to have the "IDL index" section

### ISSUE THREAD

**Issue by bakulf** [WebAudio/web-audio-api#1123]
This section should contain all the WebIDL definitions.
For instance: https://w3c.github.io/FileAPI/#idl-index

**Comment by padenot** [comment]
This is now supported by respec: https://github.com/w3c/respec/issues/159

**Comment by padenot** [comment]
It's not supported in our local copy, nor in the w3c distribution, so we'll have to wait a bit. @marcoscaceres, when is the w3c copy of respec updated?

**Comment by rtoy** [comment]
Note that we're using our own copy of respec because at one point it totally broke our spec. (Items left out, poor formatting).  Perhaps it's time to update or look at the options available.

**Comment by padenot** [comment]
I tested a new version of ReSpec today ([the w3c-hosted version](https://www.w3.org/Tools/respec/respec-w3c-common)), and it did have a number of cool features, but of course it produces a document that has 303 warnings because we don't use contiguous IDL. I don't think we want to switch right now.
