### ISSUE TITLE
Are the input and output arguments of AudioWorkletProcessor.process reused and mutated?

### ISSUE THREAD

**Issue by lukewagner** [WebAudio/web-audio-api#1127]
Reading the description of the call to the AudioWorkletProcessor `process` method, I was trying to determine whether it created garbage from the `input`/`output`  parameters.  I expect the intention is 'no', because the point is to alias and reuse the buffers between nodes of the graph.  But this reuse would technically be visible to JS so it seemed like the spec would need to explicitly say that the input/output objects are allowed to be arbitrarily mutated/reused after `process` returns. (cc @bakulf)

**Comment by joeberkovitz** [comment]
We're going to discuss this in the WG shortly, but I don't presently see why the spec needs to speak to this question. It should be up to the UA to implement any sort of sensible buffer management policy it likes, without creating dependencies on that policy (even if it's possible for JS to discover certain aspects of the policy by stashing buffer references and seeing if they're reused elsewhere).

**Comment by lukewagner** [comment]
Thanks!  At least from my experience in other parts of the web platform, it's not about JS *discovering*, but rather JS implicitly *depending* which can later come back to bite.  E.g., let's say some browser creates a fresh buffer on each `process` call and then some popular library or app is created which only tests on that one browser and it ends up holding onto buffers for a few frames and now this breaks on some browser that attempts to reuse buffers.  We can say "it's the app's fault" but it's still the latter browser's problem.

**Comment by joeberkovitz** [comment]
This question will be resolved by #1079.

As a preview of the answer, buffer reuse across calls is likely to be permitted since otherwise there will be performance issues.
