### ISSUE TITLE
AnalyserNode attribute inconsistencies with implementations.

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1129]
Consider this bit of code:
```
c = new AudioContext()
n = c.createAnalyser()
n.smoothingTimeConstant
```
The printed value for `smoothingTimeConstant` for both Chrome and Firefox is 0.8. If it were truly a float, the result should be 0.800000011920929. Inspecting the source code for Chrome and Firefox shows that both define the internal attribute and getters and setters to be doubles not floats.

Question: Is this a bug in the implementations or the spec?  Because Chrome and Firefox (and Safari) implement these as doubles, I have a preference to modify the spec to say that the attributes are actually doubles, not floats. This also means the AnalyserOptions dictionary needs a corresponding change.

I assume Edge behaves the same Chrome and Firefox, but I did not test there.

**Comment by padenot** [comment]
Let's align the spec on implementations on this one.
