### ISSUE TITLE
loopStart and loopEnd independent of detune?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1138]
In https://webaudio.github.io/web-audio-api/#widl-AudioBufferSourceNode-loopEnd, `loopEnd` is independent of the value of `playbackRate`.  It should also be independent of `detune` since `detune` and `playbackRate` form a compound parameter that affects playback.

Same holds for `loopStart`.

**Comment by joeberkovitz** [comment]
I think this will be addressed by the PR https://github.com/WebAudio/web-audio-api/pull/1143

**Comment by rtoy** [comment]
The description for `loopStart` and `loopEnd` reference `playback position`, which states that the playback position is independent of `playbackRate` and `detune`.

So, this is all set.  Closing.
