### ISSUE TITLE
Behaviour when navigating away from a document using the Web Audio API

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1139]
(This issue is in reponse to a [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1325215#c22), comment 22 onwards, where Boris mentions that what happens on navigation is not defined (comment 28), and Domenic explain what happens with document navigation and promises (comment 34)).

For now, this is not specced. What happens if you're calling `AudioContext.decodeAudioData`, or `AudioContext.resume`, etc., and immediately navigate away from the page? Should the sound stop when navigating away from the page ? Should `OfflineAudioContext`'s rendering stop as well?

In general, I think we want to stop everything (more or less what is being done by implementations):
- Reject any promise in flight (i.e. a promise that has been created but has not been resolved or rejected). We could also drop them on the floor. 
- Do something like `AudioContext.close` (without involving the promise, i.e., do the same operation): stop the sound, stop the clock, allow freeing resources, etc. This would require splitting up the text for `close` into its own abstract operation and calling that from the steps to to execute when unloading a document, and from the `close` method itself.

Practically speaking, we need to insert a bunch of checks for an "active document" throughout, register all promises used on private slots on the `BaseAudioContext` so we can access them at any time, and add a section that explains the "unloading document cleanup steps".

There is already a difference in behaviour between Gecko and Blink on this: Blink rejects the promise, Gecko does not (they are just dropped). We need to decide what to do, and I can write the text once we decide what to do.

**Comment by domenic** [comment]
Thanks for opening this; it's great to get interop on these cases.

To clarify one thing I didn't spell out in detail, the reason you need to

> insert a bunch of checks for an "active document" throughout

is to take care of code like this:

```html
<iframe></iframe>
<script>
const OldAudioContext = frames[0].AudioContext;
iframe.onload = () => {
  // Can I still use OldAudioContext to play sound? The spec currently allows it, I believe.
  const ac = new OldAudioContext();
  const source = ac.createBufferSource();
  source.buffer = dogBarkingBuffer;
  source.connect(context.destination);
  source.start(0);
};

iframe.src = "http://example.com/";
```

Similarly, you'd need a check in the methods (creatBufferSource/connect/start) since I could have done some of those steps before navigation and some of them after.

**Comment by padenot** [comment]
Just a note to self: this needs to prevent creating new nodes on the context in a synchronous manner. As soon as the document goes away, node creation is not allowed anymore. 

`close()` kind of does this, but in an asynchronous manner, `AudioNode`s can still be created until the `AudioContext.state` is `"closed"`.

**Comment by jan-ivar** [comment]
> Reject any promise in flight (i.e. a promise that has been created but has not been resolved or rejected). We could also drop them on the floor.

> Blink rejects the promise, Gecko does not (they are just dropped)

@domenic Under-specification here seems to be a general issue, not necessarily unique to web audio. Are there general guidelines or design principles to guide us here?

From dicussions with @bzbarsky, my impression is gecko's general principle here has been that it's undesirable to potentially call lots of JS callbacks (including promise rejections or thrown exceptions) on shutdown, and maybe on unload as well?

**Comment by domenic** [comment]
So far the trend has been to reject promises on document unload. Shutdown is separate, especially since it can happen without a chance to run any code at all (e.g. OS/OOM process-killing).

**Comment by jan-ivar** [comment]
> So far the trend has been to reject promises on document unload.

@domenic Thanks, do we know if the trend is based on a rationale, or what the use-cases are?

On the surface, code running on [unload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunload#Notes) seems like a [bad pattern](https://stackoverflow.com/a/291684/918910). What happens to new async calls from those callbacks?

**Comment by domenic** [comment]
The idea is that code should be able to clean up after itself, restore invariants, dispose of resources, etc.

> What happens to new async calls from those callbacks?

It depends on how they are scheduled. Some mechanisms of scheduling, such as setTimeout or most I/O APIs, will not do anything on non-active documents. Some will.
