### ISSUE TITLE
Number of outputs for MediaStreamAudioDestinationNode?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1151]
A while ago, we changed `AudioDestinationNode` to have a single output.  Currently `MediaStreamAudioDestinationNode` is defined to have no outputs.  Should it also have a single output to match `AudioDestinationNode`?

**Comment by hoch** [comment]
I think it should be configurable. Do you mean that it matches `AudioDestinatioNode` by default and user can change it later?
