### ISSUE TITLE
OfflineAudioContext options dictionary?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1152]
Now that we have constructors for all of the nodes and they take an options dictionary and even `AudioContext` has an optional dictionary, wouldn't it be nice and consistent if `OfflineAudioContext` also supported a dictionary?

Then you could do
```
new OfflineAudioContext({numberOfChannels: 3, length: 99, sampleRate: 12345})
```
in addition to
```
new OfflineAudioContext(3, 99, 12345)
```

**Comment by joeberkovitz** [comment]
This seems to make sense, we should discuss.

**Comment by rtoy** [comment]
An additional feature:  Allow setting some of the attributes of the destination node of the context.  Then instead of

```
c = new OfflineAudioContext({numberOfChannels: 3, length: 99, sampleRate: 32767});
c.destination.channelInterpretation = 'discrete';
c.destination.channelMode = 'max';
```
we can say
```
c = new OfflineAudioContext({
  numberOfChannels: 3,
  length: 99,
  sampleRate: 32767,
  channelInterpretation: 'discrete',
  channelMode: 'max'});
```
However, this makes it somewhat different from the options dictionary for other nodes.

**Comment by rtoy** [comment]
In the teleconf, it was mentioned that maybe `OfflineAudioContextOptions` could inherit from `AudioNodeOptions`.  We can, almost, if we interpret `channelCount` from `AudioNodeOptions` to be the number of channels for the context.  However, I think the connotation is different, so it's not clear.  On the other hand, we explicitly say that the `channelCount` for an offline context is set equal to `numberOfChannels`.  Maybe this is ok?

Thus:
```
dictionary OfflineAudioContextOptions {
  unsigned long numberOfChannels = 1;
  required unsigned long length; /* Or default to 1? */
  required float sampleRate;
  ChannelCountMode channelCountMode = "explicit";
  ChannelInterpretation channelInterpretation = "speakers";
}
```
Or if we inherit:
```
dictionary OfflineAudioContextOptions : AudioNodeOptions {
  required unsigned long length; /* Or default to 1? */
  required float sampleRate;
}
```
But `channelCount` is optional in `AudioNodeOptions`, so needs to be required or maybe default to 1 if not given?

Also the description of the constructor needs a special case added to the work that @padenot is doing for describing the constructors.

I think I have a slight preference for the first case (no inheritance from `AudioNodeOptions`)

**Comment by rtoy** [comment]
On closer inspection, `numberOfChannels` is not an attribute of `OfflineAudioContext`.  In fact, the argument `numberOfChannels` for the 3-arg constructor basically sets the `channelCount` to `numberOfChannels` in the destination node of the context.

Hence, it does make sense for `OfflineAudioContextOptions` to be a subclass of `AudioNodeOptions`.  These options get applied to the destination node.  Since these aren't required, we should default them to 1 channel, a mode of "explicit", and interpretation of "speakers" which are the defaults for an offline context.

**Comment by joeberkovitz** [comment]
This can go now that @padenot finished the ctor changes.
