### ISSUE TITLE
ABSN computed playback rate describe in a funny place

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1155]
https://webaudio.github.io/web-audio-api/#methods-7 describes how to compute the effective playback rate from `detune` and `playbackRate`.  But this section is entitled "Methods".  That seems to be a funny place to describe this.

I think this should either be moved to the previous section that describe the attributes, or maybe in its own section.  Wherever it goes, the "Method" section seems to be the wrong place.

**Comment by joeberkovitz** [comment]
@rtoy In the PR for #95 this has been moved to the algorithmic desription for ABSN playback. So I think this should be closed when #95 is closed.

**Comment by joeberkovitz** [comment]
Duplciate of #95
