### ISSUE TITLE
What happens to the `HTMLMediaElement`s or `MediaStream`s when the context is closed

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1162]
I think it should be the same as with `suspend`, i.e., nothing, everything continues as usual.

**Comment by joeberkovitz** [comment]
@rtoy will investigate.

**Comment by rtoy** [comment]
What does "continue as usual" mean?  I tested this with Chrome.  `suspend()` pauses the audio tag. `resume()` resumes the audio where it left off.  `close()` stops the audio.

Not sure whet the right behavior should be. I can imagine that suspend/resume pausing the audio tag makes sense.  And I can also see that closing the context should disconnect the audio from the context, allowing the audio to play.

I didn't do any tests with GC where all reference to the media node are dropped and GC happens to the node.  My guess is that in Chrome such a node is never collected.

**Comment by padenot** [comment]
Quoting the spec:

> While an AudioContext is suspended, MediaStreams will have their output ignored; that is, data 
> will be lost by the real time nature of media streams. HTMLMediaElements will similarly have their 
> output ignored until the system is resumed. 

`suspend` does not "propagate" (short of a better term) upstream to sources and pause them. I propose that we do the same for `close`. We should also define what happens when you use both `captureStream` and `createMediaElementSource` on the same `HTMLMediaElement`.

Whenever an `HTMLMediaElement` has been used with the Web Audio API, it does not seem possible to "disconnect" it from the Web Audio API, and resume with normal playback.

Invoking the `load` algorithm on the `HTMLMediaElement` with an invalid source, and dropping all references to the `HTMLMediaElement`, and the `MediaElementAudioSourceNode` should result in GCing the `HTMLMediaElement` and the `MediaElementAudioSourceNode`.

**Comment by rtoy** [comment]
I believe you, @padenot, wrote that part of the spec :-) , so it's natural that it reflects what Firefox does.  (And it's my fault for not noticing before.)

For an historical perspective, in Chrome and Safari, WebAudio manages the processing of the media elements.  WebAudio is responsible for asking for data from these sources.  From that view point, it makes sense that `suspend` would stop asking for data, just like it stops asking oscillators for data.

**Comment by padenot** [comment]
Chris Wilson wrote this bit of the spec in https://github.com/WebAudio/web-audio-api/pull/374, I merely implemented it in Firefox from his text. I wrote the implementation after the spec had been written, patching a couple things in the spec along the way (just some clarifications).

Affecting the downstream or upstream `HTMLMediaElement` on `suspend` breaks the whole model because:
- You wouldn't pause a `MediaStream` when using `createMediaStreamSource`, it does not make any sense to pause an `HTMLMediaElement`, that might be playing a `MediaStream` already. `MediaStream` are real-time objects, they are not suppose to do any buffering internally (apart from technical reasons, like buffering between `AudioContext` or such, but this buffering is bounded and short).
- You don't pause an `HTMLMediaElement` that are is playing a `MediaStream` resulting from a `createMediaStreamDestination` when the `AudioContext` has been suspended.
- `HTMLMediaElement` can be `captureStream`ed and piped to another `AudioContext` or `HTMLMediaElement` in addition to being fed into a first `AudioContext`, it seems weird that this second `AudioContext` would suddenly lose its input data.

**Comment by rtoy** [comment]
Haha!  I wonder why Chris wrote it one way and (the other) Chris implemented a different way.

We'll have to fix this in Chrome.

**Comment by padenot** [comment]
@rtoy, regarding this specific issue, do you agree that `suspend` and `resume` should behave similarly?

**Comment by rtoy** [comment]
The bit of the spec you quoted is pretty clear on this.  `suspend` drops any data and `resume` picks up from wherever the media element/stream is at.  `close` should do the same; we're closing down WebAudio, not any existing media elements/streams.

**Comment by Kuranes** [comment]
Cannot find any clarifications on if "suspend" is supposed to help with the "cannot create audioContext, 6 audioContext is the limit" I'm hitting ?
(specs say it "free hardware" but trying with https://mdn.github.io/webaudio-examples/audiocontext-states/ It doesn't work) 

For now I have to delete everything each time user focus is not on my tab/iframe, and it's not easy to do so as I have to "rely" on GC (related: https://github.com/WebAudio/web-audio-api/issues/1202 )

**Comment by rtoy** [comment]
@Kuranes 
The message "6 audioContext is the limit" sounds like a Chrome issue.  If you have issues with a specific browser implementation, file a bug against the browser.

If you have questions on how to implement something, this is not the place for that.  Try Stackoverflow or your favorite forum.

If the spec is unclear about some behavior, this is the place.  Your comments, however, don't appear related to HTMLMediaElement`s or MediaStream's.  File a new issue and explain clearly what is unclear about the spec.

**Comment by Kuranes** [comment]
Sorry, have mixed too much topics., will try to be clearer

Specs says:
'This context has been released, and can no longer be used to process audio. All system audio resources have been released' 
It doesn't say what happens to all nodes connected to the context, including mediaElement.
(I expected all them to be disconnected from the context.)

**Comment by joeberkovitz** [comment]
From F2F: way is clear for @rtoy to resolve by July 1.
