### ISSUE TITLE
Time elapsed of a song using createBufferSource

### ISSUE THREAD

**Issue by DracotMolver** [WebAudio/web-audio-api#1163]
I can't find a sort of method to get the time elapsed when a song is playing. This is possible if I create the  `<audio>` tag.
When I create a `createBufferSource` I just have the `stop()` and `start()` function. So, to get the time I've been using `setInterval`, `setTimeout` and `requestAnimationFrame`, but I faced some issues when I minimize the browser, this is because they don't run in a separated thread. Therefore, I used workers, but I'm still facing the same problem and I lost a few second of the song, eg:
` the song ends to 5:50 but the real ending time is 5:54 `. In a few words, I wanna recreate the time elapsed per second of the song.
So, I wanna know if there's an update function or I have to keep using my way of solving this?. Thanks for any advice or information.

**Comment by rtoy** [comment]
First, this issue list is for issues with the spec, not a general WebAudio issue list.

However, it looks like you want a playback position so that at a particular instance in time, you can figure out how much of the song has been played.  If so, you're probably interested in #296.

**Comment by DracotMolver** [comment]
oooh ok, sorry. Thanks anyway.
