### ISSUE TITLE
A time delay between each loop (loopStart -> loopEnd -> delayToWait -> loopStart -> etc.)

### ISSUE THREAD

**Issue by Mr21** [WebAudio/web-audio-api#1164]
Hi :)

Actually we can `.start()` a buffer in a loop with `.loop = true`. We can also set `.loopStart/End` to *loop* a precise section of the buffer.

But if I want to *loop* a buffer with a delay of 1 second between **each** loop, how can i do?

``` javascript
for ( var i = ctx.currentTime; i < Infinite; ++i ) {
	var src = ctx.createBufferSource();
	src.buffer = audioBuffer;
	src.connect( ctx.destination );
	src.start( i, loopStart, loopEnd - loopStart );
}
```

Obviously, I can't run an infinite loop, so we have to use `setInterval()` and we have to deal with these two different clocks.

It's really possible i've done it already, but it's seem to me better if the API handle it for me, no?

**Comment by rtoy** [comment]
Looping a buffer but forcing a delay between loops seems really odd.

Anyway, since it seems you are not changing loopStart/loopEnd or doing any automation of the playback rate, I think you can achieve what you want by taking your audio buffer and inserting 1 second of silence after loopEnd and then when you play the ABSN, set the loopEnd to be 1 sec more than you had originally.  So now you have 1 sec of silence before starting over at loopStart.

**Comment by Mr21** [comment]
It's not so odd, if you imagine a DAW, you have to let the user capable to loop a specific section of the entire composition who contains a lot of different ABSN scheduled.
Or if the `.loopStart/End` could be okay to be `> .duration` or `< 0` it would be good.

The silent technique is good :) but maybe tricky. The prob

**Comment by rtoy** [comment]
So you're saying you might want to have loopEnd greater than duration, and have the ABSN output silence from buffer end to loopEnd and then start playing again at loopStart?

I suppose that would be possible, but would require a spec change.

**Comment by Mr21** [comment]
Hmmm yes, but finally it's not a solution for what I said in the first post, sorry.

Please see this :
![img](http://i.imgur.com/Nqq7nd0.jpg)
Here, we can understand that if I schedule each ABSN with the correct `.loopStart/End` I can play this loop forever, without using the JS clock.

But in this scenario:
![img](http://i.imgur.com/g6Vj1dj.jpg)
It's really different, I can't use `.loopStart/End` at all, I have to use a fix `setInterval()` who will call many `.start(when, offset, duration)` etc.

**Comment by Mr21** [comment]
So, if we can set up something like:

`ABSN.loopDelay` who will be at `0` by default, and used only if `ABSN.loop === true`.

It would be amazing, but I don't know if this delay has to be accelerate in function of `.sampleRate`...

**Comment by hoch** [comment]
So this is to support "the loop outside of buffer source" with the "internal loop" feature in ABSN. I think you're approaching this in a wrong angle.

In order to do this, you have to implement a scheduling system based on sliding window. See @cwilso's [post](https://www.html5rocks.com/en/tutorials/audio/scheduling/) first. The sliding window is the one should be looped and the WebAudio scheduler will schedule things in the loop region properly.

From my perspective, this is something should be handled by the application, not the API.

**Comment by rtoy** [comment]
And given how hard it has been to specify what looping just in an ABSN actually does (see #1143), I'm really hesitant to further complicate ABSN with even more features that make it even harder to define.

**Comment by Mr21** [comment]
@rtoy, yeah I know that infinite PR... but I don't want to modify anything about the loop itself, the `.loop` and `.loopStart/End` don't have to be changed. But I don't know at which point adding the *loopDelay* will require some work on the loop code.

@hoch, I have done it before already, you can see how well it's work [here](https://gridsound.github.io/daw). But it's seems wrong to me if `setInterval()` is needed for the sound part...

**Comment by joeberkovitz** [comment]
@mr21 `setInterval()` doesn't actually schedule the sound. It just wakes up the application so that it can schedule the next N instances of the sound, on a sample-accurate basis, by creating ABSNs and calling `start()` on them.

**Comment by Mr21** [comment]
Yeah, and the `N` has to change in function of the size of the temporary loop, I can't schedule 5000 times a loop of 5 minutes with 500 absn in here. But I have to do it if the loop is 20ms long...

(I have defended the presence of `setInterval()` in the code a lot of time, and now the situation is reversed haha :D)

Anyway, the code for that is in a separate library, so it's not the biggest problem. But after all the code I wrote for the scheduling, I can say that loop is the worst and most complex part. And if something major has to be added in this section of the API, it's IMHO this.
An `loopDelay` after (or before) `loopEnd` will cover all the scenario.

**Comment by hoch** [comment]
Although the size of sliding window is completely up to your application, I think it should be somewhere around 20~50ms. Otherwise the user interaction on the playhead will loose the responsiveness significantly.

The point that I am trying to make here is - if you have 5000 events to schedule in 20ms of timeframe, you will have the same issue with even in the common DAWs.

**Comment by Mr21** [comment]
You are right, but in most cases, the longer the loop is, the more samples there are, but I use always the same value (1000 ms) for `setInterval`, and I schedule N instances of the loop regardless the number of samples.

But since my first message, I know it's possible but I was wondering if you think it's simple to code (for the browsers) so maybe, by changing the spec by adding a simple attribute who is not an AudioParam may decrease the difficulty of the JS part.

I just want you to know, that i think it can be useful for other. After that, rtoy says it's not the best moment for thinking to add new features in the loop right now.. I will rewrite my encapsulation again anyway, so I will see.

Thanks you for your attention and your advices 👍

**Comment by joeberkovitz** [comment]
I'm going to move this to the next milestone since it seems we have concensus that this is not something we can address now.

**Comment by joeberkovitz** [comment]
After reviewing today, WG feels this is a complex use case for normal start/stop scheduling at the application level, not a reason to extend the ABSN functionality.

**Comment by hadassegal** [comment]
Hi,
I'm looking for the same solution to this issue as @mr21  was looking for 3-4 years ago.
Is this possible today?
I'd like to add a delay before the loop starts again, or in other words make the loop longer than the audio buffer duration.
For example, in my case I have ~5 seconds audio and I'd like it to start looping after more than 5 seconds.
I expected that if for example, loopEnd = 10 then it will work, but I see the max loopEnd is the audio buffer duration.
Is it possible?
And if not I saw a suggestion by @rtoy to add slience to the audio buffer, how can I do that without changing my audio recording? I want the silence to be dynamic.
link to the suggestion comment https://github.com/WebAudio/web-audio-api/issues/1164#issuecomment-286519791

**Comment by padenot** [comment]
Implementing your custom player with an audioworklet is the way to go for all non-standard playback.

**Comment by goto920** [comment]
Hi,

Is it about adding interval between successive loops?

If so, my solution is to NOT using source.loop function. Use onended function.

playAB (delay, timeA, timeB) { // called when Play button pressed (used in React App)
  // omited
  source.start(audioCtx.currentTime + delay, timeA, timeB - timeA); 

  soure.onended = function () { // works only when source.loop is not set true
        if (this.state.loop) this.playAB(2, timeA, timeB); // adding 2sec interval
   }

} // end playAB()

Full code of my current program: https://github.com/goto920/simple-mixer
