### ISSUE TITLE
Should ABSN playbackRate and detune be a-rate?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1165]
Currently the `playbackRate` and `detune` AudioParams for an `AudioBufferSourceNode` are defined to be k-rate parameters.  Should they be a-rate?

If you create a buffer containing a simple sine wave and use that for an ABSN, you can't automate the detune parameter and make it simulate what an OscillatorNode would be able to do with its detune parameter.

And given the current (in-progress) description of the playback algorithm for ABSN, it's pretty clear that we could make `detune` and `playbackRate` a-rate parameters.

**Comment by padenot** [comment]
It's a bit hard to have a-rate automation with a high-quality resampler. Or so I think, I haven't tried.

**Comment by joeberkovitz** [comment]
@rtoy should we leave this open given that some UAs may elect to always use resampling at the start of a render quantum, as per the previous quantum?

**Comment by joeberkovitz** [comment]
@padenot It is also possible that UAs could fall back to cheap linear interpolation if the AudioParam is being automated rather than using a constant value. Does that ease your mind about adopting a-rate?

**Comment by padenot** [comment]
It would be weird to change the resampling algorithm depending on whether or not you've added an event to the timeline. Surely there is a way to have non-linear a-rate resampling, but I haven't had a chance to think about this too much.

**Comment by joeberkovitz** [comment]
If we ever do this, might be best to push to an entirely different node.

**Comment by mdjp** [comment]
If required, should be proposed with use cases and considered as another node.
