### ISSUE TITLE
Signaling TypeError in decodeAudioData detached buffers

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1166]
In many places throughout the spec, we specify that a `TypeError` must be thrown for the error.  For example, in `decodeAudioData`, a `TypeError` if the buffer is detached. In Chrome, this is not possible.  `TypeError` is handled at the Javascript binding layer and a DOM exception cannot be created of this type. (It is, however, possible to do this if we immediately throw the exception, but if we need an exception for, say, a callback, Chrome cannot do this.)

For `decodeAudioData` we are probably going to return a  `DataCloneError`.

**Comment by rtoy** [comment]
This also happens for automation methods.  Negative values are currently spec'ed to signal a TypeError.

**Comment by padenot** [comment]
Maybe this should be handled by WebIDL itself, but I don't see language we could use.

Also, negative value being a type error sounds weird, shouldn't it be a `IndexSizeError`, which is often abused to mean "it's outside of the range for this attribute" ?

**Comment by rtoy** [comment]
What can be handled by WebIDL?  The decodeAudioData issue?

`IndexSizeError` is ok, but I always think of an index as being some integer quantity, not a float.  I think Chrome already uses `IndexSizeError` for some invalid float values already.

**Comment by padenot** [comment]
Yeah, same, `IndexSizeError`, to me, is about integers, but it's too late to fix this.

There could be a WebIDL construct to handle this automatically, something like a `NonDetachedArrayBuffer` type, like `float` being the common case, and `unrestricted float` that allow `NaN` and `Infinity`.

In general (haven't checked, but it's plausible), you don't want to pass a detached buffer in a function or method, so it would save some time to have something directly in WebIDL.

**Comment by rtoy** [comment]
Updating issue title to reflect the actual issue being solved here; we're only concerned about decodeAudioData and detached buffers here.

The resolution from the teleconf is to use `DataCloneError` instead of `TypeError`.
