### ISSUE TITLE
An empty string for AudioWorkletProcessor name.

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1172]
```
registerProcessor('', class { /* ... */ });
```

Should we allow this? An empty string is still a valid string and can be defined a valid key within a JS object. I prefer to throw an exception, but would love to hear WG's opinion.

**Comment by joeberkovitz** [comment]
I don't see why it is a problem as the content of the string is not used elsewhere. (speaking as member not chair)

**Comment by joeberkovitz** [comment]
We're going to disallow the empty string.

**Comment by hoch** [comment]
@joeberkovitz Perhaps this is ready for editing?
