### ISSUE TITLE
OscillatorOptions periodicWave and type behavior defined inconsistently

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1173]
In https://webaudio.github.io/web-audio-api/#dictionary-oscillatoroptions-members, the description for the `periodicWave` member says

> The PeriodicWave for the OscillatorNode. If this is specified, then the type member must either be unspecified or set to "custom". 

It's not possible for the `type` member to be unspecified because it has a default value of "sine".

Two options here:

1. Remove the default value for `type`, so that if you specify a periodicWave, the type defaults to 'custom' and otherwise throws an error if the type is given and not "custom".
2. Change the description and remove the part about `type` being unspecified.  If you want a `periodicWave`, you have to specify explicitly a type of "custom"

Option 1 is convenient; option 2 is more strictly defined.

Not sure which is better.

**Comment by rtoy** [comment]
Option 1 has the potential to break existing uses of `OscillatorNode` constructors.  For example, Chrome launched the constructors without these defaults (because they weren't defined at that time).  This means `new OscillatorNode(c, {periodicWave: wave})` would now signal an error with option 1 because `type` defaults to "sine", which isn't compatible.

A third option:  if `periodicWave` is given, then any value for `type` is ignored; it is treated as if `type` were set to "custom".  I think this would it backward compatible.

**Comment by joeberkovitz** [comment]
We're going with option 3: if periodicWave is given, then any value for type is ignored; it is treated as if type were set to "custom".
