### ISSUE TITLE
(AudioBufferSourceNodeResampling): AudioBufferSourceNode resampling

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#118]
> Originally reported on W3C Bugzilla [ISSUE-17377](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17377) Tue, 05 Jun 2012 11:59:42 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-92 (AudioBufferSourceNodeResampling): AudioBufferSourceNode resampling [Web Audio API]

http://www.w3.org/2011/audio/track/issues/92

Raised by: Philip Jägenstedt
On product: Web Audio API

AudioBufferSourceNode has a playbackRate attribute which will require interpolation/resampling of some kind. However, it is not defined how to resample. Possibly it should be as close as possible to an ideal resampling, in which case that should be stated. Alternatively, it could be possible to specify which kind of resampling to perform via an attribute: nearest, linear, cubic, sinc, etc...

It also needs to be defined what should be done about folding when the net result of the sample rates and playback rate is a downsampling, if anything.

**Comment by joeberkovitz** [comment]
This doesn't seem to be agreed yet. We can review in WG but I also think it's a reasonable option to leave till V.next as leaving this unresolved is rather similar to Paul's suggestion, which I like.

**Comment by joeberkovitz** [comment]
TPAC: Adopting Paul's suggestion of letting UAs compete. Closing.

**Comment by CWBudde** [comment]
I think Paul's suggestion is good to have at least a switch to choose between speed and quality. However, I think it should have at least 3 options: speed (for something like the poor linear resampling), normal (for some good resampler) and quality (for a high sophisticated sinc interpolator or something equal to that).

The latter can be important if you want to resample filter kernels from an offline context. The performance doesn't really matter here as the kernels typically are very short. However, the quality must be higher than for normal resamplers.

**Comment by rtoy** [comment]
On the other hand, if it's important enough for you to have quality, only you know what quality you really need so the only way to be sure is to do the resampling yourself, either offline or online.  

Alternatively, vote for adding a sample rate option when constructing an AudioContext so you can specify the rate that matches kernel sampling rate.  Of course, you're then at the mercy of whatever resampling the AudioContext needs to do to get the audio out to the device.

**Comment by CWBudde** [comment]
I don't mind implementing the resampling myself and that's what I need to do now anyway. But one reason why I picked JS for in the first place is because it already offers the WebAudio API out of the box and without the need to implement something by myself.

How can I vote for adding the sample rate option? At least in terms of development speed this would eliminate adding the offline renderer step for my application (for the first draft).

**Comment by haywirez** [comment]
Also related to a [v2 issue](https://github.com/WebAudio/web-audio-api-v2/issues/25), especially @padenot's old comment https://github.com/WebAudio/web-audio-api/issues/118#issuecomment-61623298
