### ISSUE TITLE
Signaling TypeErrors

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1182]
This is a continuation of #1166 which was about TypeError in general but has been changed to be just about `decodeAudioData`.

As mentioned in https://github.com/WebAudio/web-audio-api/issues/1166#issuecomment-287477247, there are other cases where we specify a `TypeError`.  

I think we need to consider this carefully (and also any other specified error types that we signal).  I think it's important to get this right the first time.  Changing it in v.next will break all kinds of code if any one depending on the error type.

**Comment by rtoy** [comment]
Here is a list of places where we say `TypeError` is thrown but aren't really `TypeError`'s at the binding layer.  Typically we say this for floats that aren't positive.

- [cancelAndHoldAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-cancelAndHoldAtTime-AudioParam-double-cancelTime)
- [cancelScheduledValueAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-cancelScheduledValues-AudioParam-double-cancelTime)
- [exponentialRampToValueAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-exponentialRampToValueAtTime-AudioParam-float-value-double-endTime)
- [linearRampToValueAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-linearRampToValueAtTime-AudioParam-float-value-double-endTime)
- [setTargetAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-setTargetAtTime-AudioParam-float-target-double-startTime-float-timeConstant)
- [setValueAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-setValueAtTime-AudioParam-float-value-double-startTime)
- [setValueCurveAtTime](https://webaudio.github.io/web-audio-api/#widl-AudioParam-setValueCurveAtTime-AudioParam-Float32Array-values-double-startTime-double-duration)
- [start](https://webaudio.github.io/web-audio-api/#widl-AudioScheduledSourceNode-start-void-double-when)
- [AudioBufferSource start](https://webaudio.github.io/web-audio-api/#widl-AudioBufferSourceNode-start-void-double-when-double-offset-double-duration)
- [stop](https://webaudio.github.io/web-audio-api/#widl-AudioScheduledSourceNode-stop-void-double-when)

**Comment by rtoy** [comment]
Maybe `RangeError` would be the best: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError

**Comment by rtoy** [comment]
Or maybe not `RangeError`.  In Chrome, `RangeError` is implemented in the binding layer. I'll have to ask around about this.

**Comment by rtoy** [comment]
Talked to @domenic and others about this.  `RangeError` seems fine.  If it can't be used in Chrome, that's a Chrome bug.

For reference: https://heycam.github.io/webidl/#idl-DOMException-error-names, so we should avoid the deprecated terms. (@domenic also mentioned that `IndexSizeError` should be deprecated as well in favor of `RangeError`.  Not proposing we change the existing uses of `IndexSizeError`.)

**Comment by padenot** [comment]
That's good. I like `RangeError`.
