### ISSUE TITLE
PannerNode spacialization question/suggestion

### ISSUE THREAD

**Issue by waterplea** [WebAudio/web-audio-api#1184]
Hi everyone.

I'm working on a video game with web audio and I love PannerNode spacialization capabilities. However I noticed that when my source is directly on one side from the listener there is too little audio coming to the opposing channel, i.e. sound is too strongly panoramed to a single side. Since I'm using HRTF panning mode I would expect more sound coming to opposite ear as it would in a real life. Is there some way to control strength of this panning effect? If not, it could be a nice addition for cases like mine. So far, only 2 solutions I came up with are these:

1) Create duplicate panner with opposing position on the axis but much farther so it balances out the second ear
2) Recalculate coordinates with math function that would disallow panner getting directly to the side of the listener. The last one works pretty well for me but I would love panner/listener positions to represent the actual game state in game world's physics to simplify logic, rather than have those values calculated.

**Comment by rtoy** [comment]
Can you provide information on exactly the settings you're using for the panner?  Things like the position of the source and the listener, the corresponding orientations?  Also include the distance model used along with related distance parameters.

**Comment by waterplea** [comment]
I just used basic setting, default HRTF with omnidirectional sources. Kinda like on this demo:
https://googlechrome.github.io/web-audio-samples/samples/audio/simple.html
Try setting HRTF, remove ambiance reverb and set the source directly on one side, if you use headphones it sounds really weird.

**Comment by waterplea** [comment]
Since I'm using 2d model I could also have 3rd coordinate be different from 0 which would also help making panning not so dramatic in case of 0 Y and positive/negative X coordinates but that's kind of faking it and when X absolute value is big enough, that 3rd coordinate gets neglectably small in comparison and it still sounds to much panned to one side, just quieter.

**Comment by rtoy** [comment]
I tried the panning/reverb demo you mentioned.  Using chrome and following your instructions, I do hear audio in both ears, if I place the red dot close to the green dot.  Doesn't matter which said, I hear audio in both ears.  It's pretty hard to hear if you move the dot farther away from the center.  Doesn't matter too much which distance model is used as long as the red dot is close to the green dot.

Don't know what you mean by "really weird".

**Comment by waterplea** [comment]
Did you also put the red dot on the second control on the same horizontal line as green one so there is no 3rd coordinate? Ok, well that's my personal perception then, nevermind, sorry for the needless issue :)

**Comment by rtoy** [comment]
Yes, I did keep the red dot on the same horizontal line.

Perhaps you should file a bug against the browser you're using.  It could be a bug in the implementation.  You'll have to describe "really weird" better though.
