### ISSUE TITLE
Audio nodes abrupt stop

### ISSUE THREAD

**Issue by waterplea** [WebAudio/web-audio-api#1185]
When working with any sounds you are pretty much obligated to create them in pairs with GainNodes so you could stop sounds with quick exponential volume decay, rather than just calling stop on them which could cause clicking noise if waveform was far from 0 at that point.

I'm not sure if that was discussed before but I think it would very helpful to have sounds decay quickly before stopping. And if that is bad for some cases where really immediate stop is required, maybe a separate method could be introduced.

Is it just me or was it on anyone else's mind?

**Comment by mattlima** [comment]
I understand your need but the idea behind the Web Audio API is a set of discrete building blocks with tightly defined work scopes. Controlling the amplitude of the bitstream is the domain of the Gain node, whether the change is instantaneous or over a few milliseconds. There are many libraries out there that will provide a helpful layer of abstraction. In fact, I wrote one. It's by no means the best or the only one; I just know it better than the others. It allows you to gather node chains into a single '[Track](https://github.com/mattlima/mooog#the-track-object)' object and then manipulate it as a single thing using the `SetValueAtTime` and other functions.

**Comment by padenot** [comment]
I think @mattlima explained the situation correctly. It is unlikely this will ever be added to the Web Audio API.
