### ISSUE TITLE
Getchanneldata always return 0 values for the first MP3 frame (1152 samples)

### ISSUE THREAD

**Issue by nywhere** [WebAudio/web-audio-api#1186]
Hi,

I'm passing from the server 500 mp3 frames. The buffer is 192000 bytes long = 576000 samples = 12 seconds. I receive this buffer with XHR, use context.decodeAudioData then decodedData.getChannelData(0).

Wherever I start in the MP3 file (I tried also another file), whatever number of frames I grab (I tried 500, 250, 489, 501), I always have the same problem after decodedData.getChannelData(0): the Float32Array returned contains only 0 for more or less the 1000 first samples.

I'm running out of idea and even don't know what more to test. Any advice?

**Comment by rtoy** [comment]
Are you saying the WebAudio specification is deficient in some way?  

If not, I'd file a bug against the browser implementation if you think it's incorrect.  (Be sure to include an complete but simple example that illustrates the problem!)

**Comment by padenot** [comment]
This sounds like an implementation bug, please file a bug in the vendor's bug tracker:

- WebKit (Safari): https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Web%20Audio (WebKit bugzilla account needed).
- Blink (Chrome): https://new.crbug.com/ (Google account needed).
- Gecko (Firefox): https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Web%20Audio (GitHub or Mozilla Bugzilla account needed).

If that's not the case, and is indeed a specification issue, please reopen.
