### ISSUE TITLE
A standard "DoNothingNode" to do nothing except joining other AudioNodes

### ISSUE THREAD

**Issue by Mr21** [WebAudio/web-audio-api#1188]
Hi :)

Currently if I want to create a Node who does nothing except making a link between two nodestacks, I have to create some GainNodes. Maybe it can be cool to have something standard to use for these *joining-node* operations.

I understand that many GainNodes linked one after another is possible to optimize (like reduce them to one), but I speak about a node who does really nothing, so maybe inside the browser these nodes can disapear to not impact anything.

It's seems not important but after that, we can imagine every "webaudio inspector" taking into account the fact that the majority of the AudioNode in the application are just here to join others node together.

**Comment by rtoy** [comment]
Why do you want a "do nothing" node?  Why not just connect the two nodes (or node stacks) together directly?

**Comment by Mr21** [comment]
Imagine you have a console mixing, in each column you have several basic control like Gain, Pan, Bass, etc. but you can also add some effects with your own order. And it's important to be able to reorder them when you want.

So you can imagine an Array of effect. `[0]` for the first one who is linked to the `[1]` second one etc. it's a lot more simple if this effectstack doesn't have to make a huge forloop to reconnect all the samples to it, just because we have swapped the two last nodes.

Or imagine or group of ABSN to schedule, and the whole group to some effects. It's better if I link all them to a unique GainNode, and after the whole groupe is connectable rapidly.

You can imagine that for everything, imagine a complex EQ, it's a compilation of 5, 7, 16 biquadFilter together, it's more simple if they are all connected to one node, so in this case, we have one GainNode before and after.

**Comment by rtoy** [comment]
I think that is exactly what a gain node is for.  Your do nothing node has to do everything the gain node would do (except checking for automations and checking the gain value, which should both be very cheap).

And you can't really optimize away the do nothing node because you can connect or disconnect nodes from it at any time, so it can't be replaced.

**Comment by Mr21** [comment]
I understand, it was the part i didnt know. There is still the idea of making an aliases (a real one in c++ for create of different type of instance) on GainNode to let the inspector knows that these nodes are just some links, to draw them differently, but this is "sugar" idea...

**Comment by rtoy** [comment]
Discussed this on webaudio slack channel, and I think what's desired is a `passThrough` attribute for a `GainNode` to indicate that it is truly just a summing junction that always has unity gain and can't be automated or changed in any way.

This should be quite easy to implement, but it will take a bit of work to specify exactly how this works in detail with other properties of a `GainNode`.

**Comment by padenot** [comment]
Gecko implements something like this, `GainNode` are essentially free (even more free if they have gain.value == 1.0) if not automated.

Gain is always applied as part of another operation, later in the chain.

Taking a step back, I don't think this would be very useful. Just use `GainNode`s to connect your effects, very often in audio processing, you need a pre and post gain for processing anyways.

**Comment by joeberkovitz** [comment]
Closing since `GainNode` provides this ability already, it's the basic summing functionality in Web Audio.
