### ISSUE TITLE
HTML output for AudioBuffer is broken

### ISSUE THREAD

**Issue by SaschaNaz** [WebAudio/web-audio-api#1190]
![image](https://cloud.githubusercontent.com/assets/3396686/24581537/4e0e409c-1758-11e7-9e22-47e0fddfffbb.png)

Not sure why but there is no closing brace and the sampleRate attribute also has its semicolon missing.

**Comment by hoch** [comment]
I think that respec doesn't handle the text in the "title" propery in `<dl>` tag. The constructor parameters are supposed to be spelled out in `<dt>` and `<dl class="parameters">` but we don't  do that in some places. This is one of them.

**Comment by hoch** [comment]
https://github.com/WebAudio/web-audio-api/pull/1192 fixes this issue.

**Comment by rtoy** [comment]
#1192 landed and fixed this issue.  Closing.
