### ISSUE TITLE
Inconsistent types for createPeriodicWave and PeriodicWave constructor

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1195]
The new `PeriodicWave` constructor takes a dictionary where the real and imaginary coefficients are of type `sequence<float>`.  Hence, non-finite values will produce a `TypeError`.

However, `createPeriodicWave` takes `Float32Array`s for the coefficients.  These are unrestricted.

To make these more consistent, I propose `createPeriodicWave` be changed to take `sequence<float>` types.  This is backward compatible with existing code and makes the behavior between the factor method and the constructor more consistent.

**Comment by padenot** [comment]
It's not backward compatible, it will probably throw if a float in the `sequence` is non-finite. However, this would have been an error regardless. I agree we should use `sequence<float>` everywhere.

**Comment by rtoy** [comment]
Yes, you're right. But anyone doing that was already in their own strange world so I don't care too much about that. :-)
