### ISSUE TITLE
Enhancement: Stream metadata access from Icy-Metadata

### ISSUE THREAD

**Issue by vandys** [WebAudio/web-audio-api#1196]
Most Internet streams provide metadata (ala, "now playing").  <audio> elements play these just
fine.  If compatible with W3C interests, I'd like to add an enhancement to <audio> elements so
they can (1) use the Icy-Metadata HTTP header, (2) collect the resulting metadata events, and
(3) provide both attribute and event interfaces to the values received.

Overview of this mechanism:
    smackfu.com/stuff/programming/shoutcast.html

**Comment by rtoy** [comment]
WebAudio doesn't do any streaming of media by itself.  Streaming media comes from an HTMLMediaElement or MediaStream.

**Comment by vandys** [comment]
Sorry, did my best to pick the right destination!  I will try again.
