### ISSUE TITLE
exponentialRampToValue throws NotSupportedError for value of 0

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1210]
The [spec](https://webaudio.github.io/web-audio-api/#widl-AudioParam-exponentialRampToValueAtTime-AudioParam-float-value-double-endTime) currently says that setting the value to 0 for an exponential ramp throws a `NotSupportedError`.  Perhaps this should be `RangeError` to match what is being done in for #1182

**Comment by mdjp** [comment]
RangeError make most sense.
