### ISSUE TITLE
Update link to MIDI specification

### ISSUE THREAD

**Issue by eyqs** [WebAudio/web-audio-api#1215]
The current link to http://www.midi.org/techspecs/index.php redirects too many times, and its URL should be updated to https://www.midi.org/specifications instead.

**Comment by rtoy** [comment]
Did you mean to file this issue against the WebMIDI spec? I can't find any link to MIDI in the WebAudio spec.

**Comment by eyqs** [comment]
Yes, sorry. Closing the issue now.
