### ISSUE TITLE
Can ABSN.buffer be set to the same buffer again?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1216]
In https://webaudio.github.io/web-audio-api/#widl-AudioBufferSourceNode-buffer, we give an algorithm on what should happen when the `buffer` attribute is set.  Is it possible to do something like:
```
s = new AudioBufferSource(c);
b0 = new AudioBuffer(...);
s.buffer = b0;
s.buffer = b0;
```
That is, do we still throw an error for the second attempt to set the `s.buffer` to the same audio buffer?  The spec says no. Perhaps we should be a bit more explicit about this case?

**Comment by padenot** [comment]
We should throw, because of the semantics of "acquiring the content" (that is invoked when calling `start` on `AudioBufferSourceNode`) and the possible implicit copying that happens. `b0` could have a different content (not strictly in your example, though).

Reading the algorithm for the `buffer` setter, it throws, doesn't it?

**Comment by joeberkovitz** [comment]
Good point @padenot I think that's correct

**Comment by rtoy** [comment]
Yes, as currently written, the algorithm does say it throws. I just wanted clarification if that was the intent and whether it should be more explicit.

**Comment by padenot** [comment]
I don't know that we can be more explicit than an algorithm, but we can certainly add a note.

**Comment by rtoy** [comment]
This came up when I noticed Chrome wasn't following the spec here and started implementing it and wondered what should happen if you set it to the same buffer twice.

**Comment by joeberkovitz** [comment]
F2F decision: we can close this, no need to make an exception for the case where setting same buffer (since the new contents could be different w/r/t the previously acquired contents).
