### ISSUE TITLE
Missing AudioMediaStreamTrack definition

### ISSUE THREAD

**Issue by SaschaNaz** [WebAudio/web-audio-api#1217]
There is a changelog regarding the removal of AudioMediaStreamTrack in WebRTC and Media Capture and Streams specs. Is this a deprecated interface?

From [WebRTC](https://www.w3.org/TR/webrtc/):

>Changes since Dec 12, 2012
>* Changed AudioMediaStreamTrack to RTCDTMFSender and gave it its own section. Updated text to reflect most recent agreements. Also added examples section.

From [Media Capture and Streams](https://www.w3.org/TR/mediacapture-streams/):

>Changes since February 18, 2014
>* Removed videoMediaStreamTrack and audioMediaStreamTrack since they are no longer necessary.

**Comment by joeberkovitz** [comment]
Apparently it is deprecated because WebRTC didn't assign it the same role in their API that Web Audio thought it had. We'll have to refer to MediaStreamTrack or some other available interface instead.

**Comment by padenot** [comment]
We can simply pass in a `MediaStreamTrack`, use its [`kind`](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-kind) attribute, and throw if the track passed is not `"audio"` instead.

**Comment by joeberkovitz** [comment]
Thanks @padenot I'll take that approach.
