### ISSUE TITLE
[audioworklet] Rename audioWorklet.import() to addModule().

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1219]
Source: https://github.com/w3c/css-houdini-drafts/issues/374

This looks like a simple renaming, but we should review potential functional changes. We also need to rework [our examples](https://webaudio.github.io/web-audio-api/#AudioWorklet-Examples) according this change.

**Comment by andremichelle** [comment]
Will it be possible to run web-assembly code inside an audio-worklet node?

Or is there another way to output the web-assembly computed audio-stream directly to the sound-card (without the detour over the main-thread)?

Thanks.

~
André Michelle
http://www.audiotool.com

**Comment by rtoy** [comment]
Are you saying the spec disallows running web-assembly in an `AudioWorklet`?  AFAICT, any valid Javascript should be able to run in an `AudioWorklet`.
