### ISSUE TITLE
Add some ways to set the audio buffer size / know the audio buffer size + make latency manageable

### ISSUE THREAD

**Issue by micbuffa** [WebAudio/web-audio-api#1221]
Hi! I made lots of measurements for my WebAudio guitar amp, using Mac OS + Chrome/FF + two different sound cards. I measured the latency from the guitar (pasted a piezo on the guitar body) to the real physical output (speakers / output of the sound card). All measures are available (graphs, wav files, our measures, etc) at https://wasabi.i3s.unice.fr/AmpSim3/latency.html I made these measures for a research paper we submitted to the WebAudio conference 2017.

On windows, latency was so high that we could not even play guitar in real time.

I had to talk with Paul Adenot and Raymond toy in order to guess what the size of the audio buffer was in Chrome/FF, and discovered that it is 256 samples double buffered on Chrome, and it "should" be similar on FF (Paul was not sure about it). 

On real time apps, it's essential to be able to set the buffer size, or at least being aware of its size. Chrome dev has ctx.baseLatency that gives sampleRate/audioBufferSize, we've got nothing on other browsers.

So  I would suggest first to propose a standard way in the API to consult the size if this buffer, and second, to propose a mean to set the buffer size. 128 samples is a common size for real time audio apps.

Then, there is the problem of the lack of low latency driver support on windows. Paul suggested that Jack could act as a proxy between browser vendors and audio driver providers (asio...), but I'd like the audio working group to start an open discussion about that.

On Mac OS, with a decent sound card, it's possible to get very low latencies. I had my WebAudio guitar amp sim tested by some professional guitar players, that could not notice the latency (see this video for example: https://www.youtube.com/watch?v=NlcNXdRk6qM and measures showed that for the same audio buffer size, we're very very close (3ms) to the best native amp sim (guitar rig or amplitube)

So.... let's start talking about low latency / audio buffer size settings / audio drivers please..... :-)

**Comment by rtoy** [comment]
This is what the [latencyHint](https://webaudio.github.io/web-audio-api/#widl-AudioContextOptions-latencyHint) is for.  Chrome just recently added support for numeric values in addition to the categories.  However, we don't currently allow you to set the latency (buffer size) below the value for "interactive", althought we are thinking of allowing that, on the assumption you know what you're doing and what machine you're running on.  No current plans to implement that right now, though.

**Comment by micbuffa** [comment]
Thanks Raymond, but when I read the specification, it says that "interactive" is the default value, and in the current version Chrome does not allow a numeric value less than the one for "interactive". In other words: we are stuck for now with a 256x2 audio buffer size, meaning an intrinsic latency of 512/44100 = 11 ms.

Isn't it possible to set this to 128, and when the audio context dies, set it back to the default value? Only WebAudio developers will do that, and you can imagine, like for the webcam access, issuing a warning for users of an app that changes this value... "This app request for a lower audio buffer size. We recommend closing other tabs, or you may encounter audio glitches, would you like to proceed?" YES/NO/REMEMBER MY CHOICE

Who knows what other browser vendor plans are?

**Comment by rtoy** [comment]
Chrome has not implemented the part about allowing the latency to go below "interactive".  For OSX, the buffer size used to be 128*2 but was increased to 256*2 because it made webrtc sound bad.  (Buffer size too small for webrtc.)

This is something we would like to do, but experimentation needed on all 4 supported platforms needed to see what happens over a variety of machines.

**Comment by joeberkovitz** [comment]
Because the spec already gives the ability to hint the latency, closing this issue (the fact that Chrome doesn't take the hint is a matter for Chrome, and it's not required that any implementor respect these hints).
