### ISSUE TITLE
An alternative way to populate triangular periodic wave

### ISSUE THREAD

**Issue by khoin** [WebAudio/web-audio-api#1225]
At [line 10604](https://github.com/WebAudio/web-audio-api/blob/gh-pages/index.html#L10604) suggests a way to populate coefficients of the triangular wave for the PeriodicWave:
![image](https://cloud.githubusercontent.com/assets/4620399/26042321/2fe65156-38e9-11e7-89d8-bfd923bdbd25.png)

Let's focus on the: `sin(nπ/2)` part where the its output would return the sequence (1): `0, 1, 0, -1, 0, 1,...`.

I would like to suggest another way to generate such sequence, without the need of the sine function, defined like so:
![image](https://cloud.githubusercontent.com/assets/4620399/26042854/9434c260-38ed-11e7-86f0-8d21737e2ecc.png)

This way of generating sequence (1) does not depend on the sine function, and would not result in float inaccuracies. 

The above function could also make use of some bitwise operations (as n is integer), so results:
![image](https://cloud.githubusercontent.com/assets/4620399/26042859/ab09ef60-38ed-11e7-8644-d74ef7dbc037.png)

Multiply this with `8/(nπ)²` should give you the coefficients for triangular wave.

However, so far I have not seen a significant benefit in computational time (both yields 101ms on my machine). Here's a test I wrote in Javascript: https://jsbin.com/cutijutocu/edit?js,console

You can also see that I have to wrap `Math.round` because calling `Math.PI`, `Math.sin` would end up with some number really close to 0 but not 0. 

Hope this helps.

**Comment by rtoy** [comment]
Thanks for your suggestion, but the formula is correct as is.  It's up to the browser to optimize (or not) this computation. I assume all browsers are doing essentially what you suggest, but it is not a requirement from the spec.
