### ISSUE TITLE
[audioworklet] AudioParamDescriptor issues

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1230]
In https://webaudio.github.io/web-audio-api/#AudioParamDescriptor we have:

```
dictionary AudioParamDescriptor {
             DOMString name;
             float     defaultValue = 0;
             float     minValue;
             float     maxValue;
};
```

First, shouldn't `name` be required?  Second, I think both `minValue` and `maxValue` should have defaults, say, most positive and negative single floats, or, for simplicity, an appropriate signed infinity.

**Comment by hoch** [comment]
1. Yes, `name` should be |required|.
2. For max(min) value, we can use (-)3.4028235e38 as you suggested offline.

**Comment by rtoy** [comment]
And for the record, 3.4028235e38 is the exact most positive IEEE single float value (assuming the floating point reader converts that correctly).

**Comment by hoch** [comment]
PR: #1230
