### ISSUE TITLE
Use a term more generic than "JavaScript" for worklets

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1239]
They should be able to run webassembly code as well.

**Comment by hoch** [comment]
What would be the more inclusive term for this purpose? Not sure if there is one yet. I discussed this within our platform team but could not draw an answer. It is going to be either 1) making up a new name for it or 2) just saying "JavaScript and WebAssembly".

**Comment by padenot** [comment]
Maybe just "script" ? That's what, for example, the [Web Worker spec](https://html.spec.whatwg.org/multipage/workers.html#importing-scripts-and-libraries) is using.

**Comment by hoch** [comment]
WFM.
