### ISSUE TITLE
(LinearConvolution): Linear convolution effect is defined by Wikipedia

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#125]
> Originally reported on W3C Bugzilla [ISSUE-17403](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17403) Tue, 05 Jun 2012 12:28:55 GMT
> Reported by Michael[tm] Smith
> Assigned to 

Audio-ISSUE-69 (LinearConvolution): Linear convolution effect is defined by Wikipedia [Web Audio API]

http://www.w3.org/2011/audio/track/issues/69

Raised by: Philip Jägenstedt
On product: Web Audio API

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#ConvolverNode

links to

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#Convolution-section

links to

http://en.wikipedia.org/wiki/Convolution

The definition should be in the specification itself. A problem that is not addressed at all is how phase/latency depends on the length of the convolution buffer. In other words, it must be defined exactly how each sample value is calculated from the the input signal and the impulse response buffer.

**Comment by rtoy** [comment]
Does this mean removing all of section 7 (Linear Effects using Convolution)?

**Comment by rtoy** [comment]
Actually, section 7 is a bit of a mess and isn't just about convolution.  So presumably, only sections 7.1 to 7.4 need to be removed.  The remaining sections need some other changes, unrelated to this.
