### ISSUE TITLE
AudioContext constructor has a parameter

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1261]
Section https://webaudio.github.io/web-audio-api/#constructors says there are no parameters, but the constructor does take one optional `AudioContextOptions` parameter.

**Comment by rtoy** [comment]
This is probably generated by respec. Not sure if there's anything we can do about that except move to contiguous idl and hope that fixes it.

**Comment by mdjp** [comment]
WIll remove this issue from the blockers list but reference it in #833

**Comment by mdjp** [comment]
I belive this has been fixed by #833 contextOptions now listed as a parameter.  Closing
