### ISSUE TITLE
[audioworklet] Ensure MessagePort is exposed in audio worklets

### ISSUE THREAD

**Issue by annevk** [WebAudio/web-audio-api#1266]
#1233 didn't address this as far as I can tell.

**Comment by hoch** [comment]
@annevk Can you elaborate? AudioWorkletNode and AudioWorketProcessor now have a port as its member. The creation of the message channel is also described [here](https://github.com/WebAudio/web-audio-api/pull/1265).

**Comment by annevk** [comment]
You need to change HTML so that [Exposed=...] for MessagePort includes AudioWorklet (or some such, whatever the [Global=...] name is).

**Comment by hoch** [comment]
You're right. Thanks for catching this!

**Comment by annevk** [comment]
You also need to do it for `MessageEvent`, `EventTarget`, and `Event` I just realized. There might be more?

**Comment by hoch** [comment]
@bfgeek Does Worklet infra need this? Or should I just limit the scope to AudioWorklet? Domenic might also have opinions on this. (@domenic) 

```webidl
[Exposed=Window,Worker,AudioWorklet]
interface MessagePort {...}
```

**Comment by annevk** [comment]
Pretty sure just audio worklets for now. Also, you need parenthesis around the list.

**Comment by bfgeek** [comment]
Just AudioWorklet. :)

**Comment by domenic** [comment]
My opinion is @annevk has got it right :). Ideally we should PR the DOM and HTML specs as appropriate.

**Comment by hoch** [comment]
Yes, I was pretty sure that @annevk was right. :) I was just wondering if Worklet needs this.

**Comment by joeberkovitz** [comment]
@hoch @domenic Is the Audio WG still responsible for this issue? Need to decide if part of CR entry requirements.

**Comment by annevk** [comment]
@joeberkovitz yes and it's definitely something you need to have fixed as it would be a normative change moving you right back to CR if you fix it after.

**Comment by joeberkovitz** [comment]
Thanks!

**Comment by hoch** [comment]
I've been meaning to work on this. (...and it's already assigned to me.)

**Comment by joeberkovitz** [comment]
@hoch that's cool, we were just making sure whether it was a V1 blocking issue. And it now is :-)

**Comment by hoch** [comment]
With these 2 PRs, I think now we can close this issue:
- https://github.com/whatwg/html/pull/3082
- https://github.com/whatwg/dom/pull/516

**Comment by annevk** [comment]
Yeah, I think so. Thanks!

**Comment by annevk** [comment]
I'll reopen in case there's some protocol for closing that I'm not familiar with.

**Comment by hoch** [comment]
@annevk The work is done, but I think we'll discuss the closure of this issue on the next telecon.
