### ISSUE TITLE
DynamicsCompressor channelCountMode cannot be "max"

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1267]
In issue #906, we resolved that the `DynamicsCompressorNode` only supported 1 or 2 channels.  For this to make sense, we also need to specify that `channelCountMode` cannot be 'max' because that would imply that `channelCount` is ignored.

Thus, we need to constrain the mode not to be "max".  This is consistent with what we do with `StereoPannerNode` and `PannerNode`.

**Comment by padenot** [comment]
lgtm
