### ISSUE TITLE
startRendering and AudioBuffer creation

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1274]
In https://webaudio.github.io/web-audio-api/#widl-OfflineAudioContext-startRendering-Promise-AudioBuffer, the second set of bullet items seems to imply that the `AudioBuffer` for the result is created in the rendering thread.  This also kind of implies that the rendering thread has a Javascript context to go with it since an `AudioBuffer` is a Javascript object.  Is that the intent?  Chrome's rendering offline rendering thread doesn't have this ability.  (Although perhaps when AudioWorklet is implemented, this will be true.)

Also, the l[ink for what a rendering thread](https://webaudio.github.io/web-audio-api/#dfn-rendering-thread) is says that for an offline audio context it's a "normal thread".  What's a normal thread?

**Comment by joeberkovitz** [comment]
Duplicate of #1277, Fixed by #1281
