### ISSUE TITLE
startRendering behavior changed

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1277]
When adding support for the construction of an `OfflineAudioContext` with a dictionary, the behavior of `startRendering()` changed somewhat.  Previously, it said http://rawgit.com/WebAudio/web-audio-api/d99de23/index.html#widl-OfflineAudioContext-startRendering-Promise-AudioBuffer.  In the second list, this says that the `AudioBuffer` is called when `startRendering()` is called.  In the current version of the spec, the buffer is created when `OfflineAudioContext` is constructed.

I think it actually makes sense to create the `AudioBuffer` when `startRendering() is called. Thus, we should put back the old behavior.

Note also that the old behavior isn't well-defined. It's possible the `OfflineAudioContext` is called with valid values for the number of channels, length, and sample rate, but creating the `AudioBuffer` when `startRendering()` is called may fail. (Most likely out of memory).  We don't specify what should happen in this case.  Presumably `startRendering()` will reject the promise with some error code.

**Comment by joeberkovitz** [comment]
@padenot and I talked today, he feels this is a good change.
