### ISSUE TITLE
Note that setting AudioParam.value will be ignored when any automation events have been set on the object

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#128]
> Originally reported on W3C Bugzilla [ISSUE-19765](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19765) Mon, 29 Oct 2012 23:07:00 GMT
> Reported by Ehsan Akhgari [:ehsan]
> Assigned to 

We should note that if the author sets the value property on an AudioParam which has any automation events scheduled, the new value will be silently ignored without any exception being raised.

**Comment by rtoy** [comment]
Issue #172 is related and says setting AudioParam.value effectively cancels the automation and sets the value.

**Comment by notthetup** [comment]
The other related issue here (maybe this should be a separate issue) is the getter for `AudioParam.value` outputs the last stable? (from setter or from `setValueAtTime`) value.  Should this be specified in the spec?

**Comment by adelespinasse** [comment]
I still don't understand why param.value = x isn't equivalent to param.setValueAtTime(x, context.currentTime). The difference causes a lot of confusion. I suspect the reason is "it's too late, changing it now would break code". But it sounds like the semantics aren't really that well defined, so maybe it's not too late.

**Comment by joeberkovitz** [comment]
The reason is that `param.value = x` causes de-zippering to take effect, an implicit ramping of the value to avoid glitches (see #76). `setValueAtTime()`, on the other hand, does exactly what you ask it to do.

**Comment by adelespinasse** [comment]
Oh yeah, I wasn't thinking about dezippering. But that seems like a separate issue from how the value setter interacts with automation methods. You could instead say that `param.value = x` is equivalent to `param.setValueAtTime(param.value, context.currentTime); param.linearRampToValueAtTime(x, context.currentTime + 0.02)`, or however you want to specify the dezippering. At least that way you wouldn't get very nonintuitive behavior when you mix setter calls with automation. It might be a nice, concise way to specify how dezippering works, too.

**Comment by joeberkovitz** [comment]
@adelespinasse Yup, I think that this is buried in the details of #76 and dezippering is essentially, as you say, an alias to calling a pair of primitive ramp automation methods. So the interaction between dezippering and automation is really just the interaction between, um, automation and automation.

**Comment by hoch** [comment]
@adelespinasse To be precise, there are some differences in using the setter and a chain of automation methods.

The setter does not rely on `currentTime` value at all. It just happens at the beginning of the next (if possible) rendering quantum. Also it is not a linear ramp. In that sense, the closest one to the current setter's behavior is `setTargetAtTime()` method. 

Raymond and I talked about the possibility of replacing the setter with `setTargetAtTime()` internally, but this will impose some overheads to the sample rendering: although the setter guarantees the sample-accurate smoothing over time, it does not require another sample array to do the smoothing. Instead, it just uses a smoothing constant (or coefficient). On the other hand, any AudioParam automation needs an extra array for smoothed parameter values that matches the render block input array sample by sample.

Back to the original question: 
> I still don't understand why param.value = x isn't equivalent to param.setValueAtTime(x, context.currentTime).

In my opinion, the setter is designed to be abused when the strongly-timed transition is not needed. It is relatively cheap and easy to use. The unfortunate thing to know is once you use the automation method, there is no going back. (the setter won't work) It might matter when the client has low memory or processing power.

**Comment by rtoy** [comment]
On Thu, Apr 9, 2015 at 1:35 PM, Hongchan Choi <notifications@github.com>
wrote:

> @adelespinasse <https://github.com/adelespinasse> To be precise, there
> are some differences in using the setter and a chain of automation methods.
>
> The setter does not rely on currentTime value at all. It just happens at
> the beginning of the next (if possible) rendering quantum. Also it is not a
> linear ramp. In that sense, the closest one to the current setter's
> behavior is setTargetAtTime() method.
>
> Raymond and I talked about the possibility of replacing the setter with
> setTargetAtTime() internally, but this will impose some overheads to the
> sample rendering: although the setter guarantees the sample-accurate
> smoothing over time, it does not require another sample array to do the
> smoothing. Instead, it just uses a smoothing constant (or coefficient). On
> the other hand, any AudioParam automatio
> ​n​needs an extra array for smoothed parameter values that matches the
> render block input array sample by sample.
>
>

​I think this is an implementation detail of Chrome.  Currently, Chrome
would need a (small 128 element) array to do the smoothing.

I think Hongchan and I agreed that this has a certain appeal to make
everything uniform and relatively easy to explain.  But it would also
require further changes since there is now no longer an "intrinsic" value
for the getter to return.  There are probably also some corner cases that
we need to think about.​


> Back to the original question:
>
> I still don't understand why param.value = x isn't equivalent to
> param.setValueAtTime(x, context.currentTime).
>
> In my opinion, the setter is designed to be abused when the strongly-timed
> transition is not needed. It is relatively cheap and easy to use. The
> unfortunate thing to know is once you use the automation method, there is
> no going back. (the setter won't work) It might matter when the client has
> low memory or processing power.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/128#issuecomment-91349202>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
It sounds like my earlier comment about dezippering mapping to internal automation calls may have been inaccurate. But if there is a way to make such a mapping official, it would be simpler and more economical. I think that the question of what internal state the getter returns can be layered on top of this mapping.

**Comment by notthetup** [comment]
Another idea to throw into this discussion:

The setter could be defined to specifically cancel all automation when it's called. So using the setter basically says "I want to set the the value to X (with dezippering?), and that over-rules everything else I said earlier". 

That way just as it's easy to switch into the automation mode (by calling any of the automation methods) it would be easy to switch out of automation.

**Comment by rtoy** [comment]
Why not just use cancelScheduledValues()?  At least on chrome, that seems
to allow the setter (and getter) to work again.  And it seems to cause the
getter value to be set to the value at the time of cancellation.

On Thu, Apr 9, 2015 at 5:28 PM, Chinmay Pendharkar <notifications@github.com
> wrote:

> Another idea to throw into this discussion:
>
> The setter could be defined to specifically cancel all automation when
> it's called. So using the setter basically says "I want to set the the
> value to X (with dezippering?), and that over-rules everything else I said
> earlier".
>
> That way just as it's easy to switch into the automation mode (by calling
> any of the automation methods) it would be easy to switch out of automation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/128#issuecomment-91387903>
> .
>



-- 
Ray

**Comment by rtoy** [comment]
My mistake.  cancelScheduledValues() doesn't allow the getter/setter to
work again.  setTargetAtTime seems to allow the getter and setter to work,
but the other automation methods appear not to.


On Thu, Apr 9, 2015 at 5:41 PM, Raymond Toy <toy.raymond@gmail.com> wrote:

> Why not just use cancelScheduledValues()?  At least on chrome, that seems
> to allow the setter (and getter) to work again.  And it seems to cause the
> getter value to be set to the value at the time of cancellation.
>
> On Thu, Apr 9, 2015 at 5:28 PM, Chinmay Pendharkar <
> notifications@github.com> wrote:
>
>> Another idea to throw into this discussion:
>>
>> The setter could be defined to specifically cancel all automation when
>> it's called. So using the setter basically says "I want to set the the
>> value to X (with dezippering?), and that over-rules everything else I said
>> earlier".
>>
>> That way just as it's easy to switch into the automation mode (by calling
>> any of the automation methods) it would be easy to switch out of automation.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WebAudio/web-audio-api/issues/128#issuecomment-91387903>
>> .
>>
>
>
>
> --
> Ray
>



-- 
Ray

**Comment by notthetup** [comment]
Yup. It's some sort of "last stable" value.

**Comment by hoch** [comment]
@notthetup Yes, that was the one of ideas. I think this is reasonable thing and a useful escape hatch.

> "I want to set the the value to X (with dezippering?), and that over-rules everything else I said earlier".

However, what if the setter was triggered at _x_ second and the scheduler has some value scheduled later than _x_? Also we have to consider that the timing _x_ second will not be sample-accurate. So basically it is about deleting sample-accurate scheduled values with a non-sample-accurate manner.

I like this idea but its flakiness slightly bothers me.

**Comment by notthetup** [comment]
Yup. Makes sense. This is something that will be hard to pin down when going from the sample-accurate (automation) 'mode' into the non-sample-accurate (non-automation) 'mode'. Both with setters and getters.

**Comment by joeberkovitz** [comment]
Can't help but think this would be simpler if someone could propose a way to determine -- with sample accuracy -- the exact block-boundary time at which a setter-caused value change would take place.

I also think it makes sense to consider allowing cancelScheduledValues() to restore the getter/setter action.

**Comment by cwilso** [comment]
Isn't currentTime an accurate determination of that?  It represents the beginning of the next sample block.

**Comment by mark-buer** [comment]
Audio-time marches on :) Perhaps mid-way through a JS calculation.

Waiting for a render doesn't offer much help either:
```
var t = ac.currentTime;
while (t === ac.currentTime) {
    // wait for the next render
}
// now do stuff that is time dependent that we wish to be applied within a single known render quanta
// (lets just hope that a GC doesn't thwart our plans)
```
(I'm not suggesting that anyone actually uses this)

In the spec, currentTime doesn't seem very well defined.
Does the implementation increment currentTime before or after a rendering quanta?
Rendering a quanta within the audio thread takes a non-zero amount of time, and the audio nodes are traversed in an undefined order. Thus, if currentTime is updated "before", it is possible that the above code snippet could actually make the application of param values less predictable.

**Comment by joeberkovitz** [comment]
See #381... agreement on the definition not so simple apparently.

**Comment by joeberkovitz** [comment]
Resolution: state that setting the .value attribute is equivalent to 1) calling `setValueAtTime(context.currentTime, value)` and 2) setting the internal cached intrinsic value that will be returned by the `.value` getter. There is no cancellation of any existing automation events.

**Comment by joeberkovitz** [comment]
@cwilso and @rtoy and @hoch said they have some other proposal on this resolution; need to discuss.
