### ISSUE TITLE
Corrupted sound with USB Hub  (no external power)

### ISSUE THREAD

**Issue by ItamarShDev** [WebAudio/web-audio-api#1283]
We are using Web Audio API on latest Chrome to create sounds and playing it to output devices.

This [fiddle](https://fiddle.jshell.net/itamarsh/yr6pc20h/4/), let you connect to two output devices, and play a tone on each one.

This is working fine with both default output and USB outputs.

The problem starts when using two USB outputs connected to a PC with USB Hub (no external power).

After playing a while (and using the PC for other tasks, thus creating some workload) the sound breaks in one or both of the outputs

I am looking for a way to understand why its happening.
Any help would be appreciated.

(Also tried [this](https://fiddle.jshell.net/itamarsh/yr6pc20h/2/) approach, it was worse)

**Comment by rtoy** [comment]
Is this an issue with the spec?  It seems more like an implementation issue and if so, you should file a bug against the implementation.  For chrome, go to http://crbug.com/new.

**Comment by padenot** [comment]
Yep, sounds like a Chrome bug.

**Comment by ItamarShDev** [comment]
Thanks!
