### ISSUE TITLE
youtube.com/tv app navigation keeps consuming CPU when idle

### ISSUE THREAD

**Issue by ImDreamWalker** [WebAudio/web-audio-api#1289]
Reproduce it.
Step 1. Open youtube.com/tv and navigate. Check CPU utilization. 
Step 2. Stop navigation for a while. Check CPU utilization again.

My question is why it keeps consuming cpu when app navigation is idle. Is this the expected behaviour? 

Below are CPU usages using top utility:

%CPU %MEM TIME+    COMMAND                                                                                                                           
 12  16.1 0:10.39 webaudioSrc0:sr 
 7   16.1 0:10.48 webaudioSrc1:sr

**Comment by padenot** [comment]
This is not a bug tracker for Chrome or youtube or whatnot, this is an issue tracker for the Web Audio API specification.

Please file an issue at https://crbug.com, people there will be able to help you.

Thanks.

**Comment by ImDreamWalker** [comment]
Hi @padenot ,

Regarding Web Audio API. I need to understand webaudio silence/null data continuous feed to pipeline logic. As when we are not navigating on youtube tv app but still webaudio keep processing silent data which intern consumes CPU. I tried throwing these null data and process only actual buffer on navigation. But what I observe that navigation click is heard with lot of delay i.e. 20sec, 30sec or even more. And then it works correctly for subsequent navigation. The problem continues as we give delay and navigate on titles. 

I found this function 'webKitWebAudioSrcLoop(WebKitWebAudioSrc* src)' in  ../Source/WebCore/platform/audio/gstreamer/WebKitWebAudioSourceGStreamer.cpp. find this here 'https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/audio/gstreamer/WebKitWebAudioSourceGStreamer.cpp#L361'. 

Let me know if you need more information.

**Comment by padenot** [comment]
This is also not a support channel. Please refrain to comment on this bug tracker if you are not discussing spec related matters.
