### ISSUE TITLE
spatial coords should just be in metres

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#129]
> Originally reported on W3C Bugzilla [ISSUE-20681](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20681) Wed, 16 Jan 2013 01:41:27 GMT
> Reported by Ralph Giles
> Assigned to 

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#Spatialization-background Says,

"The units used in the coordinate system are not defined, and do not need to be because the effects calculated with these coordinates are independent/invariant of any particular units such as meters or feet."

This is true as far as the subsequent example goes, but is in conflict with the doppler algorithm, which compares velocities against AudioListener.speedOfSound, which is explicitly in metres per second.

I suggest the quoted sentence about unit independence just be removed, and that the spacial fields be clarified to always use metres for length.

**Comment by joeberkovitz** [comment]
This is blocked by #372 which has a pull request that hasn't progressed.

**Comment by rtoy** [comment]
#372 is closed after adding automations to the panner (aka spatial panner).

Closing this issue now because Doppler is not allowed, which is the only thing that really needed some kind of unit
