### ISSUE TITLE
How does AudioWorklet work?

### ISSUE THREAD

**Issue by andremichelle** [WebAudio/web-audio-api#1293]
Hey all,

I am trying to play with AudioWorklets. I installed Chrome Dev and started it with "--enable-blink-features=Worklet,AudioWorklet" and enabled the "Experimental Web Platform feature" flag. However the 'AudioWorkletNode' is not defined but the window.audioWorklet exists and seems to work. https://pastebin.com/VVNDdv8E

Any help is appreciated.

**Comment by hoch** [comment]
Hi Andre,

This is not Chrome's support forum. I think the right venue for this question is [the crbug.com issue](https://bugs.chromium.org/p/chromium/issues/detail?id=469639).

By the way, the feature is not completely shipped so the IDL is not exposed yet. If you have more questions, please post them in the crbug issue above.

Closing.
