### ISSUE TITLE
Tidy is failing?

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1295]
https://travis-ci.org/WebAudio/web-audio-api/builds/267632154#L257

```
$ make check
make: tidy: Command not found
Found a tidy, but with a wrong version
/home/travis/build/WebAudio/web-audio-api/.support/bin/tidy -quiet -config tidyconf.txt index.html | sed -f fixup.sed | diff -U8 index.html -
```

The check is still passing, but the log doesn't look good.

**Comment by rtoy** [comment]
The last line you show shows that the local .support/bin/tidy is running instead.  So it's probably ok.

**Comment by padenot** [comment]
Good catch: we were using tidy, but on the previous line, we're trying to check if we actually have a tidy on the machine so if there was no tidy, we would error out.

In any case, the rest of the code was working, just a cosmetic issue really.
