### ISSUE TITLE
AudioParam scheduling: no initial point and interleaved events?

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#130]
> Originally reported on W3C Bugzilla [ISSUE-17332](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17332) Tue, 05 Jun 2012 11:23:52 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-36 (linearRampToValueAtTime): AudioParam.linearRampToValueAtTime start and finish [Web Audio API]

http://www.w3.org/2011/audio/track/issues/36

Raised by: Philip Jägenstedt
On product: Web Audio API

When does the ramp start and when does it finish? There is only a single time parameter, and its meaning is not defined.

**Comment by rtoy** [comment]
I like the suggestion from @karlt.

If there's no previous event, implicitly insert setValueAtTime(<current .value>, currentTime).  I think this is what people are expecting, and certainly matches what I expect when I forget to explicitly do a setValueAtTime.

**Comment by hoch** [comment]
@rtoy You mean `setValueAtTime(lastComputedValue, currentTime)`?

How about AudioParam having the initial point of default value at the time of creation?

**Comment by rtoy** [comment]
Oops. I messed up my message.  

Since there's no previous event, it's more like setValueAtTime(attribute.value, currentTime), whatever the current value of the attribute is.

**Comment by hoch** [comment]
:+1:
