### ISSUE TITLE
MediaElementAudioSourceNode information in a funny place

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1303]
In the paragraph after https://webaudio.github.io/web-audio-api/#attributes-13, we have a description of how the node is created and its behavior.

This looks funny. First, it's in section 2.13.2 about the attributes.  That looks odd. It's also indented as if it were actually part of the main part of section 2.13.

I think this stuff should be moved above the IDL stuff, as part of the main description of the node.

**Comment by rtoy** [comment]
I think we should really fix this for V1.  I think all the needs to be done is move the attributes section down a few paragraphs.

**Comment by hoch** [comment]
Move general description in "1.22.2. Attributes" to "1.22. The MediaElementAudioSourceNode Interface", which is the node introduction.
