### ISSUE TITLE
(setValueCurveAtTime): AudioParam.setValueCurveAtTime

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#131]
> Originally reported on W3C Bugzilla [ISSUE-17335](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17335) Tue, 05 Jun 2012 11:26:17 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-39 (setValueCurveAtTime): AudioParam.setValueCurveAtTime [Web Audio API]

http://www.w3.org/2011/audio/track/issues/39

Raised by: Philip Jägenstedt
On product: Web Audio API

The interpolation of values is undefined, the spec only says "will be scaled to fit into the desired duration." The duration parameter is also completely wrong, apparently copy-pasted from setTargetValueAtTime: "time-constant value of first-order filter (exponential) approach to the target value."

**Comment by rtoy** [comment]
Oops. This issue was the same as #547.  Except in #547, we decided to use nearest instead of linear.

What should we do? I am fine with either nearest or linear interpolation.

**Comment by padenot** [comment]
Doing an interpolation seems more useful. You can do an array with step functions is you want steps.
