### ISSUE TITLE
Acquiring the contents in AudioBufferSourceNode start?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1315]
https://webaudio.github.io/web-audio-api/#acquire-the-content describes how to acquire the contents of the AudioBuffer when `AudioBufferSourceNode.start()` is called.

However, it's perfectly valid to do, say, `start(currentTime + 100)` and then sometime later set the `buffer` attribute of the source node.

Should this be updated to say that the contents are also acquired when the buffer is set if `start()` has already been called but hasn't actually stopped? Are there other corner cases to consider?

**Comment by joeberkovitz** [comment]
Decisions for V1:
- acquire buffer when its set and node is in started state
- amend ABSN algorithm to handle a null buffer properly
