### ISSUE TITLE
ScriptProcessor section is non-normative?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1318]
Why is the ScriptProcessorNode section marked as non-normative?  This is how script processors are supposed to work, even if it is deprecated.  I don't seem ScriptProcessorNode's going away any time soon in browsers.

**Comment by joeberkovitz** [comment]
@mdjp 'n' me: It's marked as non-normative to avoid getting embroiled in discussions about how to make it normative, which can't really be done. As per the existing spec: "this text is only here for informative purposes until implementations remove this node type"

**Comment by padenot** [comment]
I don't think it's possible to remove `ScriptProcessorNode` at this point.

**Comment by joeberkovitz** [comment]
That doesn't change the fact that's its near impossible to provide a normative description of it.

**Comment by padenot** [comment]
I don't agree with that. Certainly less complicated than the compressor.

**Comment by joeberkovitz** [comment]
No problem - let's discuss this tomorrow! Adding a label.

**Comment by joeberkovitz** [comment]
Removing Editorial/Doc label since this may involve making the SPN description normative.

**Comment by joeberkovitz** [comment]
Decided to close this as node is deprecated and not worth more effort
