### ISSUE TITLE
[audioworklet] Transferring MessagePort object in AWN/AWP

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1320]
Consider the following:

```js
SomeProcessor extends AudioWorkletProcessor {
  constructor () {
    super();
  }

  doThing() {
    this.port.postMessage({message: 'getThis'}, [this.port]);
  }
}
```

Nothing prevents `.port` from being passed to the other scope, possibly running on a different thread. Not sure what this actually means, but doesn't seem to be a nice thing to do. The same thing can happen for AudioWorkletNode as well.

Perhaps it would be more sane to inherit MessagePort directly into AudioWorkletProcessor. That is:

```webidl
interface AudioWorkletNode : MessagePort { ... }
interface AudioWorkletProcessor : MessagePort { ... }
```

I am neutral on this, but I thought at least we should talk about it.

**Comment by joeberkovitz** [comment]
Decided this is a feature, not a problem
