### ISSUE TITLE
[audioworklet] Using `sequence<AudioBuffer>` in `AudioWorkletProcessor.process()`

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1321]
Currently `process()` callback in AudioWorkletProcessor takes two sets of `sequence<sequence<Float32Array>>`. Perhaps we can make it easier to handle by changing it to `sequence<AudioBuffer>`. For example,

```js
process(inputBuffers, outputBuffers) {
  for (let i = 0; i < inputs.length; ++i) {
    let inputBuffer = inputBuffers[i];
    let outputBuffer = outputBuffers[i];
    // Do something with these AudioBuffers.
  }
}
```

This is better because:
- Easy to reason about. Each AudioBuffer corresponds to each input in AudioWorkletNode.
- Reusing AudioBuffer interface where we can.

One minor nit is `parameters` argument still a plain JS object. Perhaps ES6 Map might be better in terms of the consistency with AudioWorkletNode.parameters map object.

**Comment by rtoy** [comment]
Having each input port (and output port) being represented as one `AudioBuffer` is really nice.  It nicely encapsulates the input(output) port with the right number of channels and length.

**Comment by joeberkovitz** [comment]
Decided not needed in audio thread; too much main-thread-driven complexity
