### ISSUE TITLE
Specify what are the conditions for push mode streaming synthesis to be guaranteed glitch free

### ISSUE THREAD

**Issue by juj** [WebAudio/web-audio-api#1323]
In push mode streaming audio synthesis, audio program is generating fixed length audio buffers, to be seamlessly joined after each other "back to back" to produce a continuous sound stream.

This kind of audio synthesis is only softly real-time sensitive, since one can buffer up several seconds worth of audio to account for GC pauses and other stuttering effects. An example of this would be a MP3 music player application, which can generally decode much faster than real time, and can queue up 5-10seconds of audio, but does not want to queue up the whole clip as to save memory.

Currently in Web Audio this kind of push mode streaming audio synthesis strategy is not feasible, because the spec does not guarantee that manually aligning up AudioBufferSourceNodes back to back would also be played back seamlessly. For example, if the sampling rate of the buffers is not the same as the sampling rate of the AudioContext, then resampling will occur, but the resampler does not take into account that it would have to resample across adjoining buffer boundaries.

I raised this question way back in 2013 on the mailing list, in thread [How to play back synthesized 22kHz audio in a glitch-free manner?](https://lists.w3.org/Archives/Public/public-audio/2013AprJun/0546.html). That thread never had consensus.

Since then, Firefox developers spend a considerable amount of effort to ensure that this kind of joining is possible: https://bugzilla.mozilla.org/show_bug.cgi?id=913854. The trouble with that however is that the Web Audio spec itself does not state such a guarantee, so that will only provide great push mode audio streaming in Firefox.

Would it be possible to mandate such push mode streaming synthesis to be a supported use case in Web Audio spec? If not in arbitrary sampling rate case, then at least in the case that the sampling rate matches the context?

**Comment by joeberkovitz** [comment]
If context sample rate equals the buffer sample rate, I believe the spec definitely guarantees seamless back-to-back playback of ABSNs.  And in the case where these rates differ, one is now free to request a special AudioContext that uses the buffer's exact sample rate (see https://webaudio.github.io/web-audio-api/#idl-def-AudioContextOptions), eliminating the need for the resampler to infer that successive ABSNs are intended to be spliced. Note that the ability to adjust the context sample rate wasn't formerly available back in 2013 -- we added it partially to address this use case.

If you feel the spec does not provide the guarantee that we're talking about (for equal sample rates), where specifically is it falling down? The exact algorithm is documented in JS at https://webaudio.github.io/web-audio-api/#playback-AudioBufferSourceNode and it looks to me as though the first sample is guaranteed to be played at the exact start time.

**Comment by padenot** [comment]
What Joe said, this is now supported because you can have an `AudioContext` with a specific sample-rate, and the AudioBufferSourceNode algorithm is now specced.

I don't have an answer for when the sample-rates differ.

I feel we can continue talking about this in #1322, closing this one.
