### ISSUE TITLE
[audioworklet] Moving AudioContextInfo to AudioWorkletGlobalScope

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1326]
Currently `AudioContextInfo` is located at `AudioWorkletProcessor`, but it seems wasteful considering `sampleRate` and `currentTime` are identical to all instances in an `AudioWorkletGlobalScope`.

So I am proposing moving individual attributes of `AudioContextInfo` to `AudioWorkletGlobalScope`:
```webidl
interface AudioWorkletGlobalScope : WorkletGlobalScope {
  void registerProcessor (DOMString name, VoidFunction processorCtor);
  readonly attribute double currentTime;
  readonly attribute float sampleRate;
}
```

Calling `AudioContextInfo()` creates a dictionary, so accessing the primitive values directly should be more efficient and less wasteful. (in terms of GC)

**Comment by joeberkovitz** [comment]
When fixing this, be sure to update the code examples.
