### ISSUE TITLE
Can't load Mathjax fonts from www.w3.org

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1329]
There are console errors when loading the spec from github:

> Access to Font at 'https://www.w3.org/scripts/MathJax/2.6.1/fonts/HTML-CSS/TeX/otf/MathJax_Size1-Regular.otf?rev=2.6.1' from origin 'https://webaudio.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://webaudio.github.io' is therefore not allowed access.

**Comment by svgeesus** [comment]
I can have the W3C systems team add CORS-happiness for that

**Comment by svgeesus** [comment]
https://lists.w3.org/Archives/Public/public-audio/2017JulSep/0064.html

**Comment by rtoy** [comment]
I verified that the errors are gone.  Closing
