### ISSUE TITLE
ambiguous description of the stop() method

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1351]
After reading the first paragraph of the specification of the [`stop()` method of the AudioBufferSourceNode](https://webaudio.github.io/web-audio-api/#dom-audiobuffersourcenode-stop) I would expect the following code to run without throwing an error.

```javascript
const audioContext = new AudioContext();
const audioBuffer = new AudioBuffer({ length: audioContext.sampleRate, sampleRate: audioContext.sampleRate });
const audioBufferSourceNode = new AudioBufferSourceNode(audioContext, { buffer: audioBuffer } );

audioBufferSourceNode.start(0);
audioBufferSourceNode.stop(1);
audioBufferSourceNode.stop(0.5);
```

Since the `stop()` method was called twice and the second call wins, I would expect the audioBufferSourceNode to get stopped at 0.5.

However if I continue reading the first step of the algorithm described in the specification ("If stop has been called on this node, or if an earlier ...") I would expect the second call to `stop()` to throw an `InvalidStateError`.

Currently Safari is the only browser which throws an `InvalidStateError` which makes me believe that it is probably not the intended behavior. :-)

**Comment by rtoy** [comment]
Oops.  The algorithm steps are wrong.

Thanks for pointing this out!

**Comment by chrisguttandin** [comment]
The description of the AudioScheduledSourceNode is also quite similar.

**Comment by rtoy** [comment]
The current text says:

1. If stop has been called on this node, or if an earlier call to start has not already occurred, an InvalidStateError exception must be thrown.

I think it's enough to remove the first part, resulting in:

1. If an earlier call to start has not already occurred, an InvalidStateError exception must be thrown.

In terms of algorithm, I don't think we need to say anything else.  The case that the last call to stop wins is handled by the text.  If we need to say more, then we might have to really expand the section on queueing a control message to handle this.
