### ISSUE TITLE
ScriptProcessorNode has no mention of tail-time

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1356]
Even though ScriptProcessorNode is deprecated, it's not gone, so we should say something about any tail-time reference, as we do for all other nodes.

In this case, I think we should say it depends on the audio process, and any tail-time references must be handled by the user (by not dropping references to the node until any tail is done).

**Comment by joeberkovitz** [comment]
One of the problems with ScriptProcessorNode is its ill defined behavior and @matt and I don't think we should spend time tryng to patch this up.

**Comment by mdjp** [comment]
Deprecated node
