### ISSUE TITLE
ChannelMerger diagram example incorrect?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1357]
In https://webaudio.github.io/web-audio-api/#the-channelmergernode-interface, the first diagram in the examples section shows that for a 6-input merger with only two inputs connected produces a stereo output.  This is incorrect.  The output has 6 channels, of which the last 4 are silent.  Perhaps that's the intent of the diagram, but that's not how I interpret the diagram.

**Comment by JohnWeisz** [comment]
I agree, 3 diagrams could perhaps better visualize what's happening:

- 2 channels, 2 connected inputs, stereo output
- 6 channels, 2 connected inputs, 5.1 output
- 6 channels, 6 connected inputs, 5.1 output

**Comment by rtoy** [comment]
I was only thinking of updating the existing diagram to say (somehow) there are 6 channels in the output, with the last 4 channels being silent.

**Comment by rtoy** [comment]
The preview and diff don't show what the new diagram looks like.  Here it is:
![channel-merger](https://user-images.githubusercontent.com/663356/31193706-ba427840-a8f9-11e7-9d9c-a2049b2a9550.png)
