### ISSUE TITLE
Down-mixing behavior when connecting to an AudioParam?

### ISSUE THREAD

**Issue by JohnWeisz** [WebAudio/web-audio-api#1360]
From 2.4.3 in the spec, under connect/AudioParam:

 > An AudioParam will take the rendered audio data from any AudioNode output connected to it and convert it to mono by down-mixing if it is not already mono, then mix it together with other such outputs [...]

It seems it is not specced _how_ the conversion is done. It does not specify _discrete_ or _speakers_, and seems to completely ignore the `channelInterpretation` setting of the AudioParam's host AudioNode in Chrome (untested in other browsers). It also seems to use the _discrete_ down-mixing model in Chrome.

**Comment by rtoy** [comment]
Yeah, this needs to be defined better.

**Comment by rtoy** [comment]
How did you determine that discrete down-mixing was used?  My reading of [Chrome's code](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/webaudio/AudioParam.cpp?rcl=8602777b3300b617e315412bab24ef625ec5f843&l=276) says it's speaker.

(Easy enough to write a test to see what's happening, though....)

**Comment by rtoy** [comment]
Here's a quick test (that you can use in [canopy](https://hoch.github.io/canopy/))
```
// @channels 1
// @duration 1.0
// @sampleRate 44100

var osc0 = new OscillatorNode(context, {frequency: 440});
var osc1 = new OscillatorNode(context, {frequency: 4400});

osc0.start();
osc1.start();

var merge = new ChannelMergerNode(context, {numberOfInputs: 2});

osc0.connect(merge, 0, 0);
osc1.connect(merge, 0, 1);

var src = new ConstantSourceNode(context, {offset: 0});

src.connect(context.destination);

merge.connect(src.offset);

src.start();
```
In both Chrome and Firefox, the output is a sine wave on top of a sine wave.  Hence, it looks like it summed the two oscillators together.

So, proposal is that the input to an AudioParam is treated as if it were an AudioNode with `channelCount` = 1, `channelCountMode` = "explicit", and `channelInterpretation` = "speakers".

**Comment by JohnWeisz** [comment]
@rtoy 
Indeed my observation about a _discrete_ channelInterpretation being used for AudioParams was incorrect. For what it's worth, I agree with the proposal of defining _speakers_ as the down-mixing model in this case.
