### ISSUE TITLE
[audioworklets] Define "no input connection" in AudioWorkletProcessor.process()

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1377]
@rtoy suggested how to indicate "no input connect" state in `AudioWorkletProcessor.process()` is not defined. If I am not mistaken, this is rather simple and easy:

```js
process(inputs, outputs, parameters) {
  if (inputs.length === 0)
    console.log('No input connection.');
}
```

We need to add some texts in the `process()` description.

**Comment by joeberkovitz** [comment]
There's already language for this.
