### ISSUE TITLE
AudioParam rate for AudioListener

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1379]
The [forwardX](https://webaudio.github.io/web-audio-api/#dom-audiolistener-forwardx) AudioParam says that it is `a-rate` if the `PannerNode`s `panningModel` is "equalpower", and `k-rate` otherwise.

Let's say I have a source0 connected to panner0 with "equalpower".  Let source1 be connected to panner1 with "HRTF" panning.  What is the AudioListener supposed to do now?

**Comment by mdjp** [comment]
if any panner is a-rate the listener should also be a-rate and k-rate otherwise.

**Comment by rtoy** [comment]
Probably best to fix this after #1299 is fixed.  Fewer merge conflicts and potentially easier.
