### ISSUE TITLE
AnalyserNode.channelCount should probably be 2

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1385]
Currently, the spec says the `channelCount` is 1 with a `channelCountMode` of "max".  Since the mode is "max", the count has no bearing on the computed number of channels.

In addition, the default value for `channelCount` is 2 for an AudioNode.

Changing the spec to say 2 instead of 1 would be better; there's no real reason for the value to be 1. But perhaps it's too late for that.

**Comment by rtoy** [comment]
This should be done before #1304.  If not, then let #1304 fix this issue as well.

**Comment by mdjp** [comment]
Does changing the channel count conflict with this text
"Down-mix all channels of the time domain input data to mono assuming a channelCount of 1, channelCountMode of "max" and channelInterpretation of "speakers"."

**Comment by rtoy** [comment]
You mean in https://webaudio.github.io/web-audio-api/#fft-windowing-and-smoothing-over-time ?  That's for explaining how to get the FFT data.  It's independent of what the analyser node does, as stated in the next sentence:

> This is independent of the settings for the AnalyserNode itself.

**Comment by rtoy** [comment]
Hmm. This also points out a deficiency in the analyser spec for `getByteTimeDomainData` and `getFloatTimeDomainData`.  The description for each says "down-mix time-domain data".  But we don't say how.

We need to be more explicit here and say it's down-mixed to mono in the same way as the FFT data is done. I'll file an issue on this.
