### ISSUE TITLE
Meaning of 8192-length PeriodicWave arrays?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1415]
In https://webaudio.github.io/web-audio-api/#the-periodicwave-interface, the minimum supported length of the coefficients for a `PeriodicWave is specified.`

But what does that really mean?  What happens if I pass in an array of length 8193?

Assuming longer arrays are allowed, does it also imply that if I do
```
let c0 = new Float32Array(16384);
c0[8191] = 1;
let c1 = new Float32Array(16384);
c1[8192] = 1;

let w0 = new  PeriodicWave(context, {imag: c0});
let w1 = new  PeriodicWave(context, {imag: c1});

let osc0 = new OscillatorNode(context, {frequency: 1, periodicWave: w0});
let osc1 = new OscillatorNode(context, {frequency: 1, periodicWave: w1});
```
then `osc0` MUST be an 8191-Hz sine wave, but `osc1` could be 0 in a
conforming implementation?

What happens if, say, the context sampleRate is only 8000 Hz?  These coefficients are then well above Nyquist.  Presumably, they are ignored, but it's conceivable you could alias those frequencies back within Nyquist frequency.

**Comment by rtoy** [comment]
Paste the following into hoch.github.io/canopy, and look at the output from channel 2:
```
// @channels 3
// @duration 1
// @sampleRate 48000

let c2048 = new Float32Array(2048);
let c4096 = new Float32Array(4096);
let freq = 880;

// Sawtooth Fourier coefficients.
let sign = 1;
for (let k = 1; k < c4096.length; ++k) {
    c4096[k] = sign * 2/Math.PI/k;
    if (k < c2048.length) {
        c2048[k] = c4096[k];
    }
    sign *= -1;
}

let w2048 = new PeriodicWave(context, {imag: c2048});
let w4096 = new PeriodicWave(context, {imag: c4096});

let o2048 = new OscillatorNode(context, {frequency: freq, periodicWave: w2048});
let o4096 = new OscillatorNode(context, {frequency: freq, periodicWave: w4096});

let merger = new ChannelMergerNode(context, {numberOfInputs: context.destination.channelCount});
merger.connect(context.destination);
let neg = new GainNode(context, {gain: -1});
neg.connect(merger, 0, 2);

o2048.connect(merger, 0, 0);
o4096.connect(merger, 0, 1);

o2048.connect(merger, 0, 2);
o4096.connect(neg);

o2048.start();
o4096.start();
```

On chrome, which supports a max of 4096 coefficients, the difference between using 2048 and 4096 coefficients is exactly 0.  Firefox also produces 0, but I don't know how many coefficients it supports.

**Comment by joeberkovitz** [comment]
Closing - decided to leave as is since overkill here is good.
