### ISSUE TITLE
`setValueCurveAtTime` new behaviour breaks existing behaviour

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1434]
```js
    var context = new AudioContext();
    var gain = context.createGain();
    var duration = 3.0;
    var T0 = 1.0;
    gain.gain.setValueCurveAtTime([1,2,3], T0, duration/2);
    gain.gain.setValueCurveAtTime([4,5,6], T0, duration);
```

This didn't throw before we added the implicit `setValueAtTime`, it does now.

**Comment by rtoy** [comment]
I'm sorry, but I don't understand.  Where is the implicit `setValueAtTime` in your example?  There's no value setter getting called here, and we've spec'ed that overlapping `setValueCurveAtTime` automations throw errors for quite a while.

**Comment by padenot** [comment]
Huh, I didn't remember #573. This issue isn't valid, closing.
