### ISSUE TITLE
[audioworklet] Text of processor registration steps is corrupted

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#1441]
The text of step 9 of the `registerProcessor()` algorithm (see https://webaudio.github.io/web-audio-api/#methods-13) is corrupted. It's not clear how to read this.

**Comment by hoch** [comment]
Hmm. I don't know how or when this happened. I'll fix it today.

**Comment by joeberkovitz** [comment]
@hoch I already made this fix in #1445
