### ISSUE TITLE
[audioworklet] worklet.addModule() and user gesture gating logic

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1446]
Related: https://github.com/WebAudio/web-audio-api/issues/836

Without user gesture initiation, the context stays in the `suspended` state. No rendering callback fired, and all fine. The question is: does WorkletGlobalScope still have to do fetching and evaluation of the code? Even if there is a possibility that the loaded code won't be used at all?

If the answer is "no - we should defer the module loading until any gesture is registered", then we need additional step to suspend the evaluation of the worklet script.

**Comment by joeberkovitz** [comment]
@hoch The answer in the Worklet spec (and from @bfgeek) was very clear that at least one WorkletGlobalScope exists and always does fetch/eval of the scripts, even if the loaded code won't be used. So I think we can close this.

**Comment by hoch** [comment]
In other words, nothing prevents the module script from being loaded. I raised this issue because we often overlook the user gesture aspect in our discussion. Not sure if this is well-defined somewhere in the spec? Chrome and Safari mobile blocks WebAudio rendering until a valid gesture is registered.

**Comment by hoch** [comment]
> Worklets spec is currently silent on user gestures.

That's simply because there is no gating logic for the graphics rendering. Since several browsers started implementing this gating to prevent the audio 'auto play', perhaps we should start talk about this within WG.

For the future reference, this is where gating logic is: https://webaudio.github.io/web-audio-api/#dfn-allowed-to-start

**Comment by joeberkovitz** [comment]
WG agreed today that this is a non-issue, given that construction of native nodes on a `suspended` AudioContext is perfectly legal. There isn't any reason we'd delay the loading of worklet scripts for a suspended node, which makes the user gesture issue and worklets orthogonal.

We should still come back to the question of user gesture gatekeeping, which is an overall web platform question.
