### ISSUE TITLE
[audioworklet] Constructor of AudioWorkletProcessor

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1447]
Here's the current interface of AWP. It does not have `[Constructor]` IDL attribute because its construction is done by UA upon the construction of AWN.

```webidl
[Exposed=AudioWorklet]
interface AudioWorkletProcessor {
  readonly attribute MessagePort port;
}
```

It is also supposed to be extended to take advantage of it.

```js
class MyProcessor extends AudioWorkletProcessor {
  constructor () {
    super();
  }
}
```

Two problems here:
1. When AWP constructor's not exposed, subclassing it with "extends" is not possible.
2. User must call `super()` call to access `this` in the constructor and `super()` is the constructor that is not exposed.

This may be resolved by adding `[Constructor]` to AWP's IDL. Subclassing it and calling `super()` within the constructor shouldn't be a problem. However, now it leads to a different issue.  The AWP's constructor can be invoked by user.

```js
let processor = new AudioWorkletProcessor();
```

Implementation-wise, this doesn't do anything since there is no way to connect this processor instance to the audio graph. I also think we can prevent this from happening by adding a note in the spec, (e.g. "An exception will be thrown when user invoke the constructor directly", etc.) but I am not sure of its validity.

@domenic WDYT?

**Comment by domenic** [comment]
You can spec this similar to how is done for HTMLElement [in the HTML spec](https://html.spec.whatwg.org/multipage/dom.html#htmlconstructor):

> If NewTarget is equal to the active function object, then throw a TypeError.

"NewTarget" and "active function object" are from the ES spec; see https://github.com/tc39/ecma262/issues/529 for the former.

**Comment by hoch** [comment]
Thanks @domenic! It seems like this check what we need for AudioWorkletProcessor.

However, all these special steps are based on the attribute `[HTMLConstructor]`. Does it mean that AudioWorkletProcessor needs a same treatment like `[AudioWorkletProcessorConstructor]`? Or is it okay to add a check in its instantiation process?

Creating a new IDL attribute sounds non-trivial, but also adding an exception in the behavior of the constructor does not feel right either.

**Comment by domenic** [comment]
No, you just need a similar step inside the [Constructor] you define. [HTMLConstructor] is like a macro that says "use these constructor steps" whereas [Constructor] lets you specify your own steps.

**Comment by hoch** [comment]
@domenic Thanks again! :)

**Comment by joeberkovitz** [comment]
Note that #1445 (fixing #1442) already adds a new [Constructor] for AudioWorkletProcessor. We should merge that PR before addressing this, or allow that PR to also fix this issue for simplicity.

**Comment by hoch** [comment]
Agreed.

**Comment by joeberkovitz** [comment]
I've added this material to #1445 now, which references this issue.
