### ISSUE TITLE
Odd text in VuMeter example introduction and also incorrect text

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1450]
In https://webaudio.github.io/web-audio-api/#vu-meter-node, we have

> encapsulating the inter-thread communication (asynchronous) between AudioWorkletNode and AudioWorkletProcessor in clean method calls and attribute accesses.

Not sure what "clean method calls and attribute accesses" really mean.  Propose we just remove this.

We also have the statement:

>  This node does not use any output.

This probably intended to say the node produces no output.  Make it so.

**Comment by svgeesus** [comment]
Makes sense to me
