### ISSUE TITLE
Android devices - Bluetooth headphones connected = no sounds

### ISSUE THREAD

**Issue by Faksprod** [WebAudio/web-audio-api#1452]
I'm working on a webapp (built with Cordova 7) for both iOS and Android. I eI encountered a problem on some Android devices in this specific case:
1 - Enable Bluetooth.
2 - Connect your device to Bluetooth speakers or headphones.
3 - Launch your page or webapp using web audio API.
4 - Try to play a sound via JavaScript -> no sounds will be able to play.

I discovered each times this bug occurs, the **baseLatency** property of the AudioContext object is higher than 0.2 sec instead of being around 0.008 and 0.05.

`var context = new AudioContext();`
`console.log(context.baseLatency);// >= 0.2 when bug occurs`

The only solution found to have the sounds playing again is:
1 - Disable Bluetooth and disconnect from your headphones.
2 - Re-load your page or webapp.
3 - Enable Bluetooth and connect to your headphones again.
4 - Try to play a sound via JavaScript -> it works.

Any idea on how to fix this? Thanks!

**Comment by rtoy** [comment]
This is not a WebAudio spec issue.

If you're having problems with an implementation, file a bug with your implementation.
