### ISSUE TITLE
[audioworklet] Sniffing `audioWorklet` under BaseAudioContext

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1454]
Just found out a small issue (perhaps?) while I was implementing this.

Previously, the browser can sniff the AudioWorklet by querying `window.audioWorklet`. Now `audioWorklet` is under `BaseAudioContext` which must be constructed explicitly by user.

The most efficient way would be creating an `OfflineAudioContext` object then query `audioWorklet` under it. One extra step that comes with a redundant object just for querying.

I wish there is a way to get a "feature vector" from BaseAudioContext's prototype, but that sounds like a V2 issue. Otherwise, I don't think there is a clean solution for this.

**Comment by padenot** [comment]
This is not a blocking problem imo, but it's a bit unfortunate.

**Comment by hoch** [comment]
Yup. Just so we and developers know.

**Comment by joeberkovitz** [comment]
WG: Not a spec issue so we're closing this.
