### ISSUE TITLE
Incomplete text for handling active source flag

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1458]
In https://webaudio.github.io/web-audio-api/#defining-a-valid-audioworkletprocessor, at the paragraph before the Note, the second sentence says:

> At the conclusion of each call to the process() method, if the result of applying ToBoolean (described in [ECMASCRIPT]) to the return value is assigned to the associated AudioWorkletProcessor's active source flag.

This is incomplete or badly phrased. It basically says "if the result...is assigned".  There's no conclusion.

We need to add some kind of consequent.

**Comment by karlt** [comment]
I assume the word "if" should just be removed, because I assume the result is always assigned to the flag.

**Comment by rtoy** [comment]
Yes, that's probably the intent. But I'll wait for #1463 to resolve before doing anything about this.
