### ISSUE TITLE
[audioworklet] AudioWorkletNode/Processor IDL: incorrect constructor argument

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1461]
URL:
https://webaudio.github.io/web-audio-api/#idl-def-audioworkletnode

Revision:
```webidl
[Exposed=Window,
 SecureContext,
 Constructor(BaseAudioContext context, DOMString name, optional AudioWorkletNodeOptions options)]
interface AudioWorkletNode : AudioNode {
    readonly attribute AudioParamMap              parameters;
    readonly attribute MessagePort                port;
    readonly attribute AudioWorkletProcessorState processorState;
             attribute EventHandler               onprocessorstatechange;
};
```

Summary:
Add `DOMString name` in arguments.
AudioWorkletOptions => AudioWorkletNodeOptions

---

URL:
https://webaudio.github.io/web-audio-api/#idl-def-audioworkletprocessor

Revision:
```webidl
[Exposed=AudioWorklet,
 Constructor(optional AudioWorkletNodeOptions options)]
interface AudioWorkletProcessor {
    readonly attribute MessagePort port;
};
```

Summary:
AudioWorkletOptions => AudioWorkletNodeOptions

**Comment by rtoy** [comment]
Perhaps too late, but in some ways, it would be nice if the `AudioWorkletNode` function signature matched the function signature of all other audio node constructors:  `new FooNode(context, options)`, instead of `new AudioWorkletNode(context, 'node-name', options)`.

To make this work, `options` would be a required argument, and `AudioWorkletNodeOptions` would have to have an additional required member to specify the name.

**Comment by hoch** [comment]
Yes, perhaps it's a bit late but I like the consistency.

**Comment by joeberkovitz** [comment]
Bad omission! But I think the node name is really different from `options`, it's part of the identity of the node that's being created-- almost like a class name. So I'd favor keeping it as a ctor arg.

**Comment by rtoy** [comment]
Go with the proposed change in https://github.com/WebAudio/web-audio-api/issues/1461#issue-280222559

**Comment by rtoy** [comment]
This is also a V1 blocker because without this, we have an undefined `AudioWorkletOptions` dictionary.
