### ISSUE TITLE
[audioworklet] Optimizing AudioParams for AudioWorklet

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1464]
As currently spec'ed, an `AudioWorklet` gets a `Float32Array` of length 128 containing all of the parameter values for the current rendering quantum.  This is perfect if the `AudioParam` is actually changing during this period.

However, in many cases, the `AudioParam` value is actually fixed.

The worklet then either has to check that the AudioParam is constant
or just assume that it is changing and do the necessary computations.

For example, consider a `BiquadFitler`.  The `AudioParam`'s have a
complicated relationship between the values and the filter
coefficients, which is pretty expensive to have to compute for every
sample, even if the filter isn't changing.  Checking that the
parameter is constant isn't free either, and there are 4 `AudioParams`
for a biquad.

Proposal: If the `AudioParam` is known to be constant for the render
quantum, pass an array of length 1 containing just the one fixed
value.  Otherwise, pass a 128-element array for all values. This is a
relatively simple change and allows some potentially important
optimizations for the worklet.

**Comment by sletz** [comment]
You may have "intermediate" cases where control changes at explicit points in the rendering quantum. In this case an appropriate way to handle that would be to have a list of <timestamp-in-frame, value>. This would be less heavy to deal with, compared to check the complete Float32Array at each frame.

**Comment by rtoy** [comment]
I think that's getting to a level of complexity that I don't want to do. You can imagine some pretty complex results like constant for 2 frames, a change to a new value, constant (different value) for a couple of frames, and so on.  At what point do we stop?

**Comment by sletz** [comment]
"Float32Array of length 128 containing all of the parameter values for the current rendering quantum" : this basically means control is running at audio rate. A list of <timestamp-in-frame, value> is more like a model of asynchronous control.

**Comment by rtoy** [comment]
Let's say you are in the middle of a setTargetAtTime event.  What are you proposing should be given to the AudioWorklet?

**Comment by hoch** [comment]
> A list of <timestamp-in-frame, value> is more like a model of asynchronous control.

This is a series of setValueAtTime(). All the AudioParam automation methods are sparse/asynchronous operation from user's POV, and the WebAudio engines generates a stream of control signal out of the event list. Some native nodes are handling it as k-rate, but AudioWorklet only exposes a-rate mode.

With that said, if you want to be able to change the value in the middle of render quantum, we can't avoid a-rate. I see the point of "intermediate case" but that will exponentially complicate how AudioParam works, which is the most complicated part in WebAudio by far.

**Comment by mdjp** [comment]
We agree that this is going to be a very useful optimisation but requires more thought.  We are proposing to move this to V.next if there are no objections.

**Comment by andrewmacp** [comment]
Would it be possible to defer the decision around moving this to V.next until after Chrome's AudioWorklet Origin Trial? Trying out a working implementation of the AudioWorklet in more production-like scenarios might reveal more about how important this is.

**Comment by rtoy** [comment]
Hmm. I thought in the teleconf we moved this to v.next, but wasn't marked as such.

Should it be?

In any case, even if it were decided to do this, Chrome is required to make the change instantly. :-)

**Comment by rtoy** [comment]
Teleconf discussion:  Add this to the spec.  The audio param array has length 1 or 128.

**Comment by rtoy** [comment]
Instead of editing the the subject, maybe we should add an audioworklet label?

**Comment by hoch** [comment]
I thought using labels to mark a feature-specific issue is a bit weird. It's up to the spec editor!

**Comment by rtoy** [comment]
I think we can use labels for whatever/however we want.  One nice feature of using labels: It's very easy to add (or remove) the label from a bunch of issues.

**Comment by rtoy** [comment]
With the new silence hint proposal in https://github.com/WebAudio/web-audio-api/issues/1480#issuecomment-367783564, maybe we should revisit this too.

Instead of changing the length of the array of the audio param for when the audio param is constant, maybe leave things as is and have a fourth parameter of `process()` also include a constant hint.

So, the fourth parameter would be an array of two elements.  The first element would be an array (or something) indicating the silence hints for the inputs, and the second element would be an array (or something) indicating whether an `AudioParam` is constant or not for the current render quantum.

Since `AudioParam`s aren't ordered in any particular way, this might need to be a dictionary whose key is the name and whose value indicates whether it's constant or not.  This will generate a lot of extra garbage though.

**Comment by rtoy** [comment]
#1480 moved to v.next, so that has no impact on this.

Ping for one final review.
