### ISSUE TITLE
AudioWorklet Performance

### ISSUE THREAD

**Issue by andremichelle** [WebAudio/web-audio-api#1466]
Hi,

we included AudioWorklet for a test in https://next.audiotool.com (account required). The playback was unfortunately very glitchy, even with simpler setups. We also noticed that the fps was going down from 60 to 40 frames-per-second. We do not expect wonders from the AudioWorklet, but it does not meet our expectations in this early stage.

My questions:
1) Is it possible that the processor-script is talking too often for any reason to its main-thread counterpart (AudioWorkletNode)? That would explain the FPS dropping. We made sure in our testing that no additional messages were exchanged after all necessary resources were loaded into the worklet.
2) Is it possible to adjust the buffer-size yet from 128samples to something more reliable? I tried to test the latency-hint, but I could not make it work. Will it actually change the buffer-size or just hold more buffers to be filled?
3) Same question as #2 goes for the sample-rate.
`new AudioContext({sampleRate:44100}).sampleRate` // will always output 48000 on my machine. Lowering the sample-rate to 44100 would save performance on bigger graphs even it needs to be resampled in the end.

All tests done on `Version 65.0.3295.0 (Official Build) canary (64-bit)`

Thanks in advance.

**Comment by hoch** [comment]
This is an implementation issue. Please file a bug on crbug.com by using this [pre-populated link](https://goo.gl/XW3f44).
