### ISSUE TITLE
Decoding and playing chunks back to back. Not ok when sample rate changes!

### ISSUE THREAD

**Issue by gchad** [WebAudio/web-audio-api#1468]
Hi guys!
I am facing a weird issue with the decode audio data.
It is not easy to explain but I think I might be onto a weird bug of the decodAudioData function so hang-on.

My app allows for downloading of wav chunks (prepended with a wav header), decodes them and schedules them in the audioContext. This works wonderfully. No glitches.

Problems occurs when the browser's sample rate is different than the original wav file. Obviously... some resampling will take place.

Let's say you have a chunk of 20,000 samples which original sample rate is 44,1khz. If your browser is set at 44100 then the decoded audioBuffer will still be 20,000 samples. Now if your browser is set at 48khz, then you will get decoded audio buffers that are 20,000 / 44100 * 48000 = 21,768 sample long. Wonderful! let's schedule them accordingly! 
Except no. It doesn't work. It makes for a huge amount of glitches. I can ever hear 'gaps' in the audio.

I ran some tests a listened to the very first chunk of my file both un-resampled when playing at 44.1khz and resampled at 48khz by the decodedaudio data function and is just does not sound the same. It almost feels truncated. So it is definitely not a scheduling problem. It almost sounds like the decodedAudioData function does know how to resample properly....

Any ideas?

Thanks guys.

**Comment by rtoy** [comment]
An example URL illustrating this would be great, although not really relevant to the spec.

I'm guessing the issue is that when the sample rate matches the files, everything is nicely continuous.  But when you resample, sections that used to be continuous aren't any more (because the resampling can't take into account of the preceding and following audio that is not available).

This is probably part of the new audio decode issue that will be taken up in v2.

**Comment by gchad** [comment]
> This is probably part of the new audio decode issue that will be taken up in v2.

V2?

**Comment by rtoy** [comment]
Version 2 (or next) of the WebAudio spec.

**Comment by gchad** [comment]
Can we put in requests somewhere?

**Comment by rtoy** [comment]
File an issue (as you've done).  It will get reviewed and prioritized.

For best results, present a use case and concise proposal of what you want to be included in the spec.

**Comment by mdjp** [comment]
Likely to be taken up by webcodecs.  No response since Oct 2018
