### ISSUE TITLE
Tighten spec on ABSN output channels?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1481]
This is follow up from https://github.com/WebAudio/web-audio-api/issues/1471#issuecomment-361827095.

I think the proposal there is that ABSNs output exactly one channel of silence until the buffer starts playing and when the buffer stops playing (if ever), the node produces again a single channel of silence.

The difficulty with this is if the ABSN is scheduled to start in the middle of a render quantum.  It seems impossible to change the channel counts at that point, so the count has to happen at the render quantum before or after the the start time.  Stopping the source has exactly the same problem.

I think Chrome sets the output channel count when the AudioBuffer is assigned.

**Comment by rtoy** [comment]
Thanks for the nice test code!

Since it appears the GC observability issue is gone, perhaps there's nothing that needs to be done here.  It's an optimization for the browser to do if desired?

**Comment by karlt** [comment]
I suggest leaving this open as an option at least until the solution to
https://github.com/WebAudio/web-audio-api/issues/1471 is clear and complete.

The spec is currently clear that that ABSN always and indefinitely
has output channel count matching the buffer channel count, and so, if we are
happy with that, then there is nothing that _need_ be done here.

With this behavior, I don't see much optimization possible for multiple identical
channels to AudioWorklet, but I don't see that a problem either.

Still, this is an option to resolve some of the optimization concerns people
had with solution of https://github.com/WebAudio/web-audio-api/issues/1471,
and so let's leave it for consideration, at least until we know exactly what
that solution is.

**Comment by rtoy** [comment]
I think, as an optimization, that when `stop()` is called and the stop time has passed, the output of the ABSN is a single channel of silence.  This doesn't affect GC observability because it happens when `stop()` stops the source, not because GC occurred.

**Comment by karlt** [comment]
An ABSN that has a buffer, but for which start() has not been called, would
benefit from a single channel of silence in the same way as an ABSN that has
completed, both in terms of fewer channels to process downstream and because
it makes it easier for an implementation to garbage collect the resources
associated with the node (without any need to keep the effects of
multiple channels on downstream nodes).
