### ISSUE TITLE
PannerNode.rolloffFactor should throw on invalid values?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1483]
We currently say that `refDistance` and `maxDistance` should throw a RangeError if either is set to a negative value.  In https://webaudio.github.io/web-audio-api/#dfn-rollofffactor, we give ranges for the valid values of the rolloffFactor, and negative values are not included.

To be consistent with `refDistance` and `maxDistance`, we should probably also throw an error if `rolloffFactor` is negative.

**Comment by padenot** [comment]
Agreed.
