### ISSUE TITLE
[Privacy] access to physical audio devices?

### ISSUE THREAD

**Issue by chaals** [WebAudio/web-audio-api#1486]
In the security and privacy questionnaire answers, it says

> 10 Does this specification allow an origin access to other devices?
>
> No.

I think that is incorrect. Specifically, generating arbitrary audio offers the ability to access audio-sensitive devices within hearing range. This can be used to track the physical location of a user.

Equally, it seems to my non-expert view that this could enable so-called "Dolphin attacks" on voice-interaction assistants, and potentially on some other dumb audio-sensitive IoT sensors.

(Since I am late to the party I haven't checked carefully yet. There may be explanation and proposed mitigation of this in the spec, in which case I apologise for the redundancy).

**Comment by mdjp** [comment]
We discussed this today.  We do not think that we are adding a new risk here.  It would already be possible to play audio intended to trigger interaction assistants with existing web technologies.  The web audio api does not necessarily create a new risk.

**Comment by chaals** [comment]
Yes, it is true there is no new risk. I wonder if it is worth mentioning the risk that is there anyway.

It occurs to me that it should be mentioned in HTML too, and I suspect it isn't. I'll raise an issue there.

**Comment by mdjp** [comment]
We will bring this up on tomorrows call.  Thanks Chaals.

**Comment by svgeesus** [comment]
The spec now says:

>It typically does not allow access to other networked devices (an exception in a high-end recording studio might be Dante networked devices, although these typically use a separate, dedicated network). It does of necessity allow access to the users audio output device or devices, which are sometimes separate units to the computer.

> For voice or sound-actuated devices, Web Audio API might be used to control other devices. In addition, if the sound-operated device is sensitive to near ultrasonic frequencies, such control might not be audible. This possibility also exists with HTML, through the &lt;audio> element. At common audio sampling rates, there is (by design) insufficient headroom for much ultrasonic information.
 https://webaudio.github.io/web-audio-api/#priv-sec

**Comment by svgeesus** [comment]
@chaals Does that wording satisfy your concern?

**Comment by chaals** [comment]
I would prefer something that suggested more strongly not to leave the headroom - the current text seems to say ¨don´t worry, it´s all taken care of already¨, which seems a bit more dismissive that I find comfortable.

That said, I can live with the current text if the WG confirms that there really is no practical way to use this.

**Comment by svgeesus** [comment]
The limit of human hearing is usually stated as 20kHz. For a 44.1kHz sampling rate, the Nyquist limit is 22.05kHz. Given that a true brickwall filter cannot be physically realized, the space between 20kHz and 22.05kHz is used for a rapid rolloff filter to strongly attenuate all frequencies above Nyquist. That is what is meant by "insufficient headroom".
At 48kHz sampling rate, there is still rapid attenuation in the 20kHz to 24kHz band (but it is easier to avoid phase ripple errors in the passband).
That is what is meant by the phrase "by design". These common sampling rates are designed to capture the range of audible frequencies, and nothing more.

**Comment by chaals** [comment]
Thank you for this clarification. It would be helpful if some of that detail were in the spec text, for the benefit of people like me who know relatively little about audio, and for people who understand audio to be clearly alerted to the specifics that address the potential privacy concern - e.g. so they don't "fix the attenuation problem" for some other purpose, like specifically providing headroom to enable messaging like GSM does for SMS without noticing its potential impact.

The limit of human hearing **in general** is a range far wider than that for individuals.

Where it is possible (e.g. statistically viable to guess, or worth the effort of an audio that improves the guess, based on the expected value of an attack) that a given user has a lower range there is potentially more headroom. Given that the concern is related to "ambient" devices, an individual might not be a user but could reasonably be in an environment (office, home, etc) where others do have and use such devices.

**Comment by svgeesus** [comment]
OK, looks like some edits needed to add this explanation to the spec.
