### ISSUE TITLE
[Privacy] control over native UI

### ISSUE THREAD

**Issue by chaals** [WebAudio/web-audio-api#1487]
In the Privacy and Security appendix it says

> 11 Does this specification allow an origin some measure of control over a user agent’s native UI?
>
> No?. _Though it could be used to emulate system sounds to make an attack seem more like a local system event?_

In the case where the UI is actually sound-based, such as a voice assistant or screenreader, the potential effect of this seems more significant. This would be particularly worrying given the ability to determine enough about the UI to effectively emulate it, or to guess in a way that is accurate often enough to make a mass attack statistically worthwhile.

**Comment by mdjp** [comment]
After reading this again I think we need to revisit this one.  We discussed the fact that it was already possible to play "fake" system sounds in the browser and the web audio api does not really increase that risk.  however This is actually referring to the emulation of voice assistants or screenreaders - so I guess duping users into thinking that they are interacting with the screen reader when actually they are interacting with a page using the api. @chaals please shout if I have not understood this correctly.

**Comment by svgeesus** [comment]
The spec now says

> If the UI has audio components, such as a voice assistant or screenreader, Web Audio API might be used to emulate emulate aspects of the native UI to make an attack seem more like a local system event. This possibility also exists with HTML, through the &lt;audio> element.
https://webaudio.github.io/web-audio-api/#priv-sec

**Comment by svgeesus** [comment]
@chaals  Does that wording satisfy your concern?

**Comment by chaals** [comment]
Yep. (Note to self, file the issue on HTML...)

**Comment by svgeesus** [comment]
Thanks, @chaals (thanks too for the html issue)
