### ISSUE TITLE
Add currentFrame to AudioWorkletGlobalScope

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1491]
The `AudioWorkletGlobalScope` has `currentTime` to let the processor know the current time.  It would also be very nice to have `currentFrame` that is the frame counter where `currentTime = currentFrame/sampleRate`.

For algorithms that need precise timing and complex computations wrt to time, using frames reduces round-off errors.

In Chrome, currentTime used to be accumulated each render quantum, causing a small round-off each time.  This slight drift was noticeable after even a short time.  Switching Chrome's internal implementation to count frames got rid a huge class of round-off errors.  

Doing the same in Chrome's AudioParam implementation greatly reduced the small, but subtle issues in timing.  Before fixing this, @hoch  had an example where his synthesizer would suddenly stop producing output because of round-off in the audio param implementation.  Changing the implementation to work with frames instead of time fixed this and a bunch of other issues.

**Comment by padenot** [comment]
Agreed. Gecko does everything in frames internally, exactly for this reason.
