### ISSUE TITLE
Flesh out security and privacy considerations

### ISSUE THREAD

**Issue by samuelweiler** [WebAudio/web-audio-api#1495]
As discussed on the Privacy IG call today, this section needs to discuss known issues and potential mitigations including the out-of-hearing-range/ultrasonic issues, the fingerprinting issues identified by Princeton's WebTAP team, and any other issues you've identified.  

This might include https://github.com/WebAudio/web-audio-api/issues/1487, https://github.com/WebAudio/web-audio-api/issues/1486, https://github.com/WebAudio/web-audio-api/issues/1457

**Comment by jasonanovak** [comment]
May also include #1498 #1499 #1500.

**Comment by svgeesus** [comment]
PR at https://github.com/WebAudio/web-audio-api/pull/1529

**Comment by svgeesus** [comment]
Now live at https://webaudio.github.io/web-audio-api/#priv-sec

**Comment by svgeesus** [comment]
Further reminder sent out [8 August 2018](https://lists.w3.org/Archives/Public/public-privacy/2018JulSep/0015.html)

No further input, commentors assumed satisfied. Closing this meta-issue.
