### ISSUE TITLE
[Privacy] Fingerprinting Based on DynamicsCompressor and OscillatorNode

### ISSUE THREAD

**Issue by jasonanovak** [WebAudio/web-audio-api#1500]
[Research by Princeton CITP's Web Transparency and Accountability Project](https://audiofingerprint.openwpm.com/) has shown that DynamicsCompressor and OscillatorNode can be used to gather entropy from a client to fingerprint a device.  The spec should acknowledge this risk in its Security/Privacy section if it cannot be mitigated.

**Comment by rtoy** [comment]
Any major differences in the `OscillatorNode` are probably bugs.  

I don't really understand why the `DynamicsCompressor` should be so different.  AFAIK, everyone uses exactly the same code to implement this node.

We should probably look into these differences and file bugs against browsers if the outputs are inconsistent or wrong.

**Comment by svgeesus** [comment]
This seems to depend on the output buffer size on the output device. Also small DSP differences and rounding between Arm and x86, Firefox and Chrome. Compiler flags.

**Comment by svgeesus** [comment]
Differences in oscillator wavetable interpolation.

**Comment by svgeesus** [comment]
Tor browser has a resistFingerprinting mode, reduces precision of getCurrentTime, reduces the fingerprinting vector.

**Comment by svgeesus** [comment]
The spec now says:

> When giving various information on available AudioNodes, the Web Audio API potentially exposes information on characteristic features of the client (such as audio hardware sample-rate) to any page that makes use of the AudioNode interface. Additionally, timing information can be collected through the AnalyserNode or ScriptProcessorNode interface. The information could subsequently be used to create a fingerprint of the client.

> Research by Princeton CITP’s Web Transparency and Accountability Project has shown that DynamicsCompressor and OscillatorNode can be used to gather entropy from a client to fingerprint a device. This is due to small, and normally inaudible, differences in DSP architecture, resampling strategies and rounding trade-offs between differing implementations. The precise comiler flags used and also the CPU architecture (Arm vs. x86) also contribute to this entropy.

> In practice however, this merely allows deduction of information already readilly available by easier means (User Agent string), such as "this is Chrome running on an x86".
https://webaudio.github.io/web-audio-api/#priv-sec

**Comment by svgeesus** [comment]
@jasonanovak Does that wording satisfy your concern?

**Comment by jasonanovak** [comment]
@svgeesus Thanks for the addition to the spec. One question: I'm not sure what the data was that drove to the conclusion that:

> this merely allows deduction of information already readilly available by easier means (User Agent string), such as "this is Chrome running on an x86".

Is there a citation for this?

**Comment by svgeesus** [comment]
When we looked at the fingerprints, there was some commonality by compiler and platform, which comes down to the build tools used by a particular browser on a given platform.
