### ISSUE TITLE
Not able to stream from internet radio website

### ISSUE THREAD

**Issue by benravin** [WebAudio/web-audio-api#1501]
Please find the attached html code which I used to stream internet radio station.

The main url for the website is as below[1], which displays different radio stations,
when click on one internet radio station it streams from the second url [2] given here,
which has an audio format .m3u8

[1]  http://allindiaradio.gov.in/Default.aspx
[2] http://airraagam-lh.akamaihd.net/i/airraagam_1@507820/master.m3u8
[internet_radio.zip](https://github.com/WebAudio/web-audio-api/files/1741261/internet_radio.zip)

**Comment by rtoy** [comment]
Is this an issue with the WebAudio spec? It doesn't appear to be so.  If it is, please be more specific on why you think this is a problem with the spec.

This isn't a general WebAudio issue tracker;  this is for issues with the spec.
