### ISSUE TITLE
attack and release not used in DynamicsCompressor algorithm.

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1502]
In section https://webaudio.github.io/web-audio-api/#processing look at the algorithm for the reduction gain (below the figure).  In step 3 we talk about the variables `attack` and `release` which are assigned the values of the attributes.  But no where in the algorithm do we use these again.

Thus, we don't describe what these attributes actually do in the `DynamicsCompressorNode`

**Comment by rtoy** [comment]
As mentioned in #1504, final gain, threshold, and knee are also defined but not used in the DynamicsCompressor algorithm.

**Comment by hoch** [comment]
The correct link to the comp processing: https://webaudio.github.io/web-audio-api/#DynamicsCompressorOptions-processing

**Comment by padenot** [comment]
We probably want to use those in the detector curve part of the algorithm: <https://webaudio.github.io/web-audio-api/#detector-curve>

**Comment by rtoy** [comment]
Proposal for at least some of the changes:

- Remove `threshold`, `knee`, and `ratio` from the reduction gain algorithm.
- Use `threshold`, knee`, and `ratio` in the compression curve algorithm, making the link between the attributes and these variables.

This fixes  things (I think), except for the attack and release attributes/vars
