### ISSUE TITLE
CORS cross origin link is broken

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1507]
In the last paragraph of section https://webaudio.github.io/web-audio-api/#security-with-mediaelementaudiosourcenode-and-cross-origin-resources, there's a link for CORS-cross-origin that points to http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#cors-cross-origin, but this link doesn't seem to exist anymore.  It just loads up chapter 2 of the html spec.

Where is this link really supposed to go? (bikeshed complains about this broken link and I want to fix it for bikeshed.)

I think @padenot wrote this section.  Do you know where it's supposed to go?

**Comment by rtoy** [comment]
Oh, no need to create a PR for this. I think we can just fix it in the bikeshed version, which is almost done.

**Comment by padenot** [comment]
<https://html.spec.whatwg.org/#cors-cross-origin> is the right link.
