### ISSUE TITLE
Functionality other than audioBuffer for longer audio?

### ISSUE THREAD

**Issue by wmodes** [WebAudio/web-audio-api#1524]
I am using web-audio-api with the node-speaker module to combine longer and shorter sounds at the same time. However, I was experiencing long encode times.

According to https://www.w3.org/TR/webaudio/#AudioBuffer:

> This interface represents a memory-resident audio asset (for one-shot sounds and other short audio clips). Its format is non-interleaved IEEE 32-bit linear PCM with a nominal range of -1 -> +1. It can contain one or more channels. Typically, it would be expected that the length of the PCM data would be fairly short (usually somewhat less than a minute). For longer sounds, such as music soundtracks, streaming should be used with the audio element and MediaElementAudioSourceNode.

So my use of the audioBuffer to encode longer sounds/music is an abuse of the spec (and takes a long time to encode). Is there a suggested functionality in web-audio-api for longer sounds? Or if not, can you suggest another module that would be a good choice to use side-by-side with web-audio-api for longer sounds?

The specs suggest [MediaElementAudioSourceNode](https://webaudio.github.io/web-audio-api/#mediaelementaudiosourcenode), but can that be used without an actual HTML doc?

**Comment by padenot** [comment]
This issue tracker is to track issues on the Web Audio API spec. Please refrain from asking about non-spec issues, in particular, implementation issues.
