### ISSUE TITLE
AudioWorkletNode's processorState after AudioContext got closed

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1526]
After reading the spec, I'm not really sure what the `processorState` of an `AudioWorkletNode` should be when the AudioContext which it belongs to gets closed. I created a little example:

```js
// Let's assume this is the body of an async function.
// There is variable called audioContext which is referencing an AudioContext.
// An AudioWorkletProcessor called 'my-processor' was registered and added to that audioContext.

const myNode = new AudioWorkletNode(audioContext, 'my-processor');

await audioContext.close();

const processorState = myNode.processorState;
```

What will be the value of `processorState`?

I assume it should be 'stopped' but I'm not sure.

**Comment by hoch** [comment]
https://github.com/WebAudio/web-audio-api/issues/1451#issuecomment-350042936

`processorState` is removed from the spec. There is a [PR](https://github.com/WebAudio/web-audio-api/pull/1517) under the review and it is not merged yet.

**Comment by chrisguttandin** [comment]
Okay, thanks for pointing me to that other issue. I don't know how I could have missed it.

Please, feel free to close the issue.

**Comment by hoch** [comment]
Closing! :)
