### ISSUE TITLE
Gap between playback when using context.currentTime

### ISSUE THREAD

**Issue by OrbitalJeffL** [WebAudio/web-audio-api#1543]
Environment:
Windows 10 and MacOS High Seirra
Chrome and Safari

Use case:
We want to play N number of audio files one at a time. Looping a given audio file on itself with seamlessly until the user toggles another track via UI interaction. Currently we are using a linear fade between the tracks. Because the user can change at what point the track will loop we need to be able to detect the track position via loop markers and transition between the tracks on the fly. We schedule a fade out of the current gain node and fade in a new gain node of the same track immediately once we hit the end of the loop.

Expected Result:
Using a 110hz cosine signal audio file we loop infinity fading between playback of the sources. Given a perfectly aligned transition between two cosine wave forms of the same frequency we would expect a no amplitude change over the course of the transition between tracks. The two linear ramps of the same duration and starting time should cancel each other out perfectly in this scenario. 

Observed Result:
Even though we set the start time of the second source to be the same as the beginning of the fade out of the first, we end up with random amplitude drops in our playback. Occasionally playback will align and we will see the expected result of an aligned waveform.  

What could be causing this behavior? Is context.currentTime unreliable to schedule events based on?  

This Code is a bastardized version but replicates the issue:
```
function Crossfade() {
  console.log('crossfade function');
  var request = new XMLHttpRequest();

  request.open('GET', 'http://localhost:8080/cosine_110hz.wav', true);
  request.responseType = 'arraybuffer';
  request.onload = function() {
    context.decodeAudioData(request.response, function(buffer) {

      console.log("track received.");
      let trackStart = context.currentTime + .1;
      let fadeDuration = .25;
      let fadeOutStart = trackStart;
      var gainNode2 = context.createGain();
      var source2 = context.createBufferSource();

      source2.buffer = buffer;
      source2.connect(gainNode2);
      gainNode2.connect(context.destination);

      gainNode.gain.setValueAtTime(1, trackStart);
      gainNode.gain.linearRampToValueAtTime(0, trackStart + fadeDuration);
      source.stop(trackStart + fadeDuration);

      gainNode2.gain.setValueAtTime(0, trackStart);
      gainNode2.gain.linearRampToValueAtTime(1, trackStart + fadeDuration);
      source2.start(trackStart, 0);

      gainNode = gainNode2;
      source = source2;
      setTimeout(Crossfade, 1000);
    })
  }
  request.send();
}
```

Actual waveform:
![actualresult](https://user-images.githubusercontent.com/30414516/38058722-aefbff8c-3298-11e8-89e8-fe8fdc726389.png)

Expected waveform:
![expectedresult](https://user-images.githubusercontent.com/30414516/38058723-af11c376-3298-11e8-9189-de46fe18106c.png)

https://github.com/JeffreyLangston/WebAudioApiTest

**Comment by rtoy** [comment]
From the test code, there doesn't appear to be anything wrong with the spec.  Are you saying the spec is incorrect in some way?

If not, you should file a bug with the browser you are using.  

This is not a general bug reporting list.  It is for reporting issues with the spec itself.

**Comment by OrbitalJeffL** [comment]
I've tested on every browser and see the same behavior.

From what I understand of the spec scheduling two linear ramp events at the same future point in time should produce a reasonably accurate crossfade. Even if the event scheduling is slightly inaccurate I would assume they would would still be near simultaneous. However what I'm seeing is the two events happening at different points in time causing this large misalignment (The worst case above is about 100ms).

**Comment by rtoy** [comment]
You believe your example should work. I also believe it should work.  I don't see anything in the code that points to a deficiency or error in the spec.

Maybe every browser has the same bug?

I still would encourage you to file a bug with each browser in any case.

And point out why you think the spec is incorrect or at least missing some important information that makes your example not work.

**Comment by rtoy** [comment]
Closing. This is not an issue with the spec.

If this is incorrect, please re-open or file a new issue.
