### ISSUE TITLE
Make decodeAudioData more precise

### ISSUE THREAD

**Issue by annevk** [WebAudio/web-audio-api#1563]
It would be nice if https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata invoked an algorithm in MIME Sniffing rather than just referencing the whole standard. It would also be good to say which return values are accepted/rejected.

Are there tests for this method?

**Comment by padenot** [comment]
We're in the process of upstreaming tests from the various UAs into web-platform-tests, I don't now where we're at right now, but there certainly will be tests.

**Comment by rtoy** [comment]
Chrome has basically skipped upstreaming the decoder tests.  I think the only thing that might really be cross-platform would be decoding 16-bit PCM WAV files.  We could probably move the couple of tests that we have for this.

**Comment by rtoy** [comment]
Do you mean we should probably reference https://mimesniff.spec.whatwg.org/#audio-or-video-type-pattern-matching-algorithm ?

**Comment by agnivade** [comment]
@rtoy - Does that mean a web server cannot reliably sniff audio content without calling into ffmpeg ?

Because without any algorithm it is not possible to reliably do mime sniffing.

Context:
I would like to implement mime sniffing for mp3s in Go's http server. But that is blocked on https://github.com/whatwg/mimesniff/issues/70. Which is blocked on this issue. Would appreciate any leads on this.

**Comment by rtoy** [comment]
@agnivade: Don't have anything really to add.  Mime sniffing is just a heuristic anyway, right?

**Comment by agnivade** [comment]
Sure, that maybe. But there are major differences between the mime sniffing algorithm in https://mimesniff.spec.whatwg.org/#signature-for-mp3-without-id3 and the actual algorithm used by mozilla 
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/mediasniffer/mp3sniff.c.

We should fix that. I tried to implement what was in mimesniff and it failed for every possible mp3 out there. I don't believe that should be the case.

**Comment by annevk** [comment]
It's not exactly a heuristic. It determines whether or not a byte stream can be played back and needs to be interoperable across implementations.

**Comment by guest271314** [comment]
> Chrome has basically skipped upstreaming the decoder tests. I think the only thing that might really be cross-platform would be decoding 16-bit PCM WAV files. We could probably move the couple of tests that we have for this.

Can you elaborate on this?

Have input as hexadecimal PCM. The output `Float32Array`s for the same input from Chromium 81 and Nightly 74 are different. How is that possible?

(first 8 elements of `Float32Array` from `decodeAudioData()`)


Chromium 81 
`0, 0, 0, 0, 0, 0, 0, 0` 

Nightly 74
`2.927284564656668e-35, 5.943748283744958e-35, 8.134226905204596e-35, 1.023114237523477e-34, 1.177507614486811e-34, 1.3241581111803245e-34, 1.433346383514849e-34, 1.5352300604849667e-34`

**Comment by GPHemsley** [comment]
I'm not sure that #1781 sufficiently addressed this.

For starters, it's pointing to the wrong mimesniff algorithm. The [rules for sniffing audio and video specifically](https://mimesniff.spec.whatwg.org/#rules-for-sniffing-audio-and-video-specifically) are what is intended to be used for sniffing in an audio or video context (such as `<audio>` or `<video>`). This is distinct from the algorithm identifying audio or video in a browsing context, which is meant to be much more restrictive and geared towards balancing security and legacy content.

Secondly, the [spec for decodeAudioData()](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata) still contains:
> The buffer passed to decodeAudioData() has its content-type determined by sniffing, as described in [mimesniff].

Which I believe is what @annevk was referring to as vague.

**Comment by guest271314** [comment]
FYI re MIME sniffing on Firefox for Matroska files with Opus (similar for video with VP8, or VP9 codecs, which both Chromium and Firefox can play - in WebM container that is derived directly from Matroska container) the result of `decodeAudioData()` in


```
      input.onchange = async ({
        target: {
          files: [file],
        },
      }) => {
        // or await ac.decodeAudioData(await new Blob([file], {type:'audio/webm;codecs=opus'}).arrayBuffer())
        console.log(await ac.decodeAudioData(
          await new Response(file, {headers:{'Content-Type':'audio/webm;codecs=opus'}}).arrayBuffer())
       );
      }
```

will be 

```
DOMException: The buffer passed to decodeAudioData contains an unknown content type.
```

We know Firefox can decode and play the content at `HTMLAudioElement` when content type of `Response` or `type` of `Blob` or `File` is set to `audio/webm`, yet for an unknown reason `decodeAudioData()` throws.
```
$ mkvmerge -J test_matroska_audio.mkv
{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 17,
      "date_local": "2021-08-31T19:02:08-07:00",
      "date_utc": "2021-09-01T02:02:08Z",
      "duration": 1576366000,
      "is_providing_timestamps": true,
      "muxing_application": "libebml v1.4.2 + libmatroska v1.6.4",
      "segment_uid": "ca43ba11aa2c341b485157613d6db376",
      "writing_application": "mkvmerge v60.0.0 ('Are We Copies?') 64-bit"
    },
    "recognized": true,
    "supported": true,
    "type": "Matroska"
  },
  "errors": [],
  "file_name": "test_matroska_audio.mkv",
  "global_tags": [],
  "identification_format_version": 14,
  "track_tags": [
    {
      "num_entries": 1,
      "track_id": 0
    }
  ],
  "tracks": [
    {
      "codec": "Opus",
      "id": 0,
      "properties": {
        "audio_channels": 1,
        "audio_sampling_frequency": 22050,
        "codec_delay": 6500000,
        "codec_id": "A_OPUS",
        "codec_private_data": "4f707573486561640101380122560000000000",
        "codec_private_length": 19,
        "default_track": true,
        "enabled_track": true,
        "forced_track": false,
        "language": "und",
        "language_ietf": "und",
        "minimum_timestamp": 0,
        "number": 1,
        "tag_encoder": "opusenc from opus-tools 0.1.10",
        "uid": 8497742985796830241
      },
      "type": "audio"
    }
  ],
  "warnings": []
}
```

```
      input.onchange = async ({
        target: {
          files: [file],
        },
      }) => {
        let blob;
        if ('mozCaptureStream' in audio && 'CanvasCaptureMediaStream' in globalThis) {
          blob = new Blob([file], {type:'audio/webm;codecs=opus'});
        }
        console.log(blob || file);
        audio.src = URL.createObjectURL(blob || file);
      };
      fetch('test_matroska_audio.mkv')
      .then((response) => response.arrayBuffer())
      .then((ab) => audio.src = URL.createObjectURL(new Blob([ab], {type:'audio/webm;codecs=opus'})))
    </script>
  </body>
</html>
```

```
  fetch('./video.mkv')
  .then((response) => {
    console.log(response.headers.get('Content-Type'));
    if (response.headers.get('Content-Type') === 'video/x-matroska') {
      return new Response(response.body, {headers:{'Content-Type':'video/webm;codecs=vp9'}}).blob()
    }
    return response.blob();
  })
  .then((blob) => {
     console.log(blob.type);
     video.src = URL.createObjectURL(blob)
  });
```

[test_mkv.zip](https://github.com/WebAudio/web-audio-api/files/7140642/test_mkv.zip)


`decodeAudioData()` should be able to decode the file, the WebM demuxer and Opus decoder can decode the Opus track contained in the Matroska file, yet evidently "MIME sniffing" is short-circuiting even trying to do so. See https://bugzilla.mozilla.org/show_bug.cgi?id=1422891#c53, https://bugzilla.mozilla.org/show_bug.cgi?id=1422891#c54 at [[Rethink] Support mkv|matroska|video/x-matroska in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1422891).

Interesting inconsistencies in plain sight. Technically capable of decoding and playing the track(s) in Matroska container, yet for unknown internal reasons, exception is thrown.

**Comment by padenot** [comment]
> I'm not sure that #1781 sufficiently addressed this.

I agree, it's not enough. I've filed #2378 as a follow-up and will address the issues you describe there. Thanks for reporting!
