### ISSUE TITLE
More cross-origin state exposed to the web

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1566]
In https://webaudio.github.io/web-audio-api/#priv-sec, item 4 says:

> Does this specification expose persistent, cross-origin state to the web?
Yes, the supported audio sample rate(s) are exposed.

We also expose the number of output channels of the output device has via [maxChannelCount](https://webaudio.github.io/web-audio-api/#dom-audiodestinationnode-maxchannelcount).

**Comment by svgeesus** [comment]
OK, needs edits to mention maxChannelCount.

**Comment by mdjp** [comment]
was fixed by #1579
