### ISSUE TITLE
AudioWorklet on Webkit-based browsers?

### ISSUE THREAD

**Issue by josh83abc** [WebAudio/web-audio-api#1570]
Hi everybody,

Thanks to the AudioWorklets, I can finally use WebAudio for my music app. Well done guys! :)

While browsing the WebAudio source code of Chromium, I do see that everything is under the folder "webkit". Does this mean that the WebAudio implementation between Webkit and Blink are and will be the same?

And therefore, will the AudioWorklets be soon available on Safari for Mac and iOS (since they use webkit)? 

Thanks for your replies :)

**Comment by hoch** [comment]
Chromium's Blink and Safari's WebKit are not identical anymore. They were separated around 2013 and have diverged significantly.

You can ask questions in WebKit's [tracking bug](https://bugs.webkit.org/show_bug.cgi?id=182506) if needed.
