### ISSUE TITLE
Inconsistency in ScriptProcessorNode, AudioProcessingEvent, and AudioBuffer

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1578]
In https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-createscriptprocessor, we can create a node with 0 input channels or 0 output channels (but not both).  This is fine.

But in https://webaudio.github.io/web-audio-api/#audioprocessingevent,
the `inputBuffer`, and `outputBuffer` attributes are specifed to be an
`AudioBuffer` with the specified number of channels.  So it's possible
for that the event has an `AudioBuffer` with 0 channels.

But
https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-createbuffer
says that the number of channels *cannot* be 0.

So one of these is incorrectly specified.

Yes, I know `ScriptProcessorNode` is deprecated, but that doesn't mean
it doesn't exist.

A perfectly valid response to this issue is that we're not going to
fix `ScriptProcessorNode` or `AudioProcessingEvent`.  `AudioBuffer`
should not, however, be modified.

Just wanted a record of this inconsistency.

**Comment by mdjp** [comment]
Closing this, the ScriptProcessor is deprecated and has a direct replacement.  We would not expect the node to be used for new projects.
