### ISSUE TITLE
[audioworklet] Worklets should signal AudioWorkletProcessorState transitions

### ISSUE THREAD

**Issue by cristiano-belloni** [WebAudio/web-audio-api#1584]
The discussion in https://github.com/WebAudio/web-audio-api/issues/1451 led to the removal of `processorState`. I briefly discussed with @hoch and @rtoy about that and I have a couple of questions:

- `running` and `stopped` states have a well-defined, non arbitrary meaning with "real" effects that a developer might want to listen to. It would not be uncommon for an application developer wanting to know when a node has stopped (= ie, it stopped processing samples), in order, for example, to present an error to the user, or to change the graph.

- It is true that a developer can use the `messagePort` to signal a `stopped` state, but does it make sense to re-invent the square wheel and re-do the signalling of a state defined in the specs, only in a custom way? For example, are we sure that third-party libraries of custom nodes will signal the transition to a `stopped` state in the same way? In any case, why should developers re-invent a custom way of signalling something that's univocally defined and could be automatically sent to the main js thread?

My proposal would be signalling the transitions that *have a well-defined effect*, like `running` -> stopped. It could be a simple `onprocessorstopped` callback, in case (since going from stopped to running is theoretically possible, but impossible in practice, since `process` is not called anymore).

I agree that we shouldn't 'invent' additional states, but I believe we should signal states that indicate a precise behaviour that a developer might want to listen to.

**Comment by karlt** [comment]
> `running` and `stopped` states have a well-defined, non arbitrary meaning with "real" effects that a developer might want to listen to. It would not be uncommon for an application developer wanting to know when a node has stopped (= ie, it stopped processing samples), in order, for example, to present an error to the user, or to change the graph.

Before #1451, `stopped` meant that the active source flag was false, but did not necessarily mean that
the node had stopped processing samples.

Neither the active source flag nor the transition to no longer processing are in general associated with errors.  If there is an error, then I assume that more information is required to usefully report the error, and so the messagePort would be more useful.

AFAIK though there is no way for the processor to send a message when it is
(perhaps temporarily) no longer processing samples, because `process()` will
not be called in that situation.  I guess the client could keep track of the
`disconnect()` calls on nodes connected to AudioWorkletNode, but the API does
not help much here.

If there is a need to know when the processor has transitioned to not
processing samples, then I wonder whether it is better to provide this
notification on the node or the processor.

> going from stopped to running is theoretically possible, but impossible in practice, since process is not called anymore

`process()` will be called again if/after inputs are later connected.  This transition would be reasonably easy for the processor to detect, if it knew when process() calls were temporarily suspended.

**Comment by cristiano-belloni** [comment]
> Neither the active source flag nor the transition to no longer processing are in general associated with errors. If there is an error, then I assume that more information is required to usefully report the error, and so the messagePort would be more useful.

There is already a way to get errors (`onprocesserror`) and an issue open here: https://github.com/WebAudio/web-audio-api/issues/1282

I also believe getting errors is *much* more important than getting state transitions.

That said, I don't agree with using `messagePort` to report errors; if the worklet (involountarily) throws, by definition it doesn't know when to send a message through the `messagePort`.

> I wonder whether it is better to provide this notification on the node or the processor

Well, the processor would have signalled its intention no stop processing samples by returning `false` from the `process` method in the first place, so I imagine it "knows" already.

By the way, small digression: there's this tendency to see the node and the processor as "owned" by the same developer, a tendency which, in my eyes, is not necessarily accurate.

When I think of the future, I think of large libraries of third-party worklets and developers using them, not necessarily controlling the code inside them or knowing the internals. Having a well-defined interface, in this case, is essential. Processor and node are not the same thing and do not necessarily stay on the same "side" - having mechanisms in one or the other is *not* the same.

**Comment by cristiano-belloni** [comment]
@hoch: I agree with 4 - having the states emerge organically is a wise idea.

Should I close or do we want to leave this open for further discussions?

**Comment by hoch** [comment]
@cristiano-belloni I wish I could capture the chat we had in the slack channel yesterday. It is also fine to leave this open because we all agreed to address this in the future.

**Comment by cristiano-belloni** [comment]
@hoch if you want to paste the chat here or anywhere else, please go ahead. If you can't access it for any reason, I'll do that as soon as I get home (I'm on my mobile phone right now)

**Comment by mdjp** [comment]
Closing this based on conversation, we will revisit if another "state" issue is raised.
