### ISSUE TITLE
Errors on creating AudioBuffer and other nodes?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1599]
The spec doesn't say anything about `createBuffer()` or `new AudioBuffer()` failing.  So it seems as if you could say `context.createBuffer(32, 1e9, 96000)`.  This needs to allocate 32 `Float32Array`s of length 1e9 each.  That's about 128 GB of memory.  That seems unlikely.  On chrome and firefox `new Float32Array(1e9)` throws an error because both can't allocate arrays of that size. (FWIW, firefox allows you to create such an audio buffer, but getChannelData fails.  That's weird.  Chrome throws an error.)

Do we need to say that createBuffer can fail in this way? I think other nodes can fail in this way too, but none of the memory that would be needed is exposed to Javascript, so that would probably a normal out-of-memory condition.

**Comment by mdjp** [comment]
Agreed that we need to state that an error will be thrown if the buffer cannot be created, need to discuss with @padenot to ensure consistency.

**Comment by rtoy** [comment]
Just a quick clarification.  An error should be thrown if the underlying channel data wasn't created successfully.  Firefox does create the `AudioBuffer`; you just use the arrays for the channels in any way.

**Comment by rtoy** [comment]
Oh.  Filed a FF issue on this a little while ago  https://bugzilla.mozilla.org/show_bug.cgi?id=1458982

**Comment by rtoy** [comment]
Every node occupies some memory so there's a potential that we run out.  I'd rather not say anything in general.  I definitely don't want to constrain optimizations that the browser might want to do.  I also don't want to get in a situation where you can create something successfully, but can't use it like other instances of the object.

`AudioBuffer`, and, possibly, `PeriodicWave` can use significant memory.  If they can't be created, then it's useful to throw an error.

As I understand it, Firefox has a neat optimization where `AudioBuffer` only uses 16 bits per sample to optimize memory usage. And only if you do `getChannelData` or `copyToChannel` do you then change the memory to use a full 32-bit float array.  Not sure what to do this this case if you can't allocate memory for it.

**Comment by rtoy** [comment]
Hmm. I don't think we need to say anything about `new AudioBuffer(...)` failing, because construction of any new node (via constructor or factory method) can fail from lack of memory.

I think we only need to say `getChannelData`, 'copyToChannel`, and `copyFromChannel` can fail.

`decodeAudioData` is already specified to reject or call the error callback if decoding fails.  A loose interpretation for "fail" could include being unable to allocate memory. Not sure if we need to make that distinction.

`startRendering()` already has a step where the promise is rejected if the `AudioBuffer` fails to be created from some reason.

So, I think only the `AudioBuffer` methods need a little extra text about throwing errors.

**Comment by rtoy** [comment]
Actually, `copyFromChannel` should need to signal anything because we're copying internal data out, so the internal representation doesn't need to change.  So no new errors should be signaled here.
