### ISSUE TITLE
createMediaStream{track}Source needs to be on BaseAudioContext

### ISSUE THREAD

**Issue by alvestrand** [WebAudio/web-audio-api#1605]
A need has been identiifed to create a MediaStreamSource on OfflineAudioContext.
This is OK if it is created by invoking its constructor (it takes a BaseAudioContext), but the helper create function is attached to AudioContext, not BaseAudioContext.

This usage will lead to an OfflineAudioContext that can't operate faster than real time (since MediaStreamTracks are real-time), but it avoids the issues around autoplay that affect AudioContext.

Tagging @mounirlamouri

**Comment by mounirlamouri** [comment]
If we want to have an OfflineAudioContext operating at real time, why not having it return a Stream of some sort instead of a buffer? @padenot WDYT?

**Comment by rtoy** [comment]
I think that the constructor for MediaStreamSource allowing a BaseAudioContext is a mistake in the spec.  If you can't create one using the factory method, the constructor shouldn't allow that either.

I'm guessing at the use case but presumably this is something to do with WebRTC.  Don't you already have a user gesture to allow access to camera and video?  I would think that would allow count as a user gesture for WebAudio.

**Comment by rtoy** [comment]
Oh, for @mounirlamouri question, the offline context is really meant for faster than real-time processing.  We are considering for the next version of updating the offline context to allow some kind of incremental offline processing where you can get partial results.  No design work has been done, and very likely won't happen until after V1.

**Comment by hoch** [comment]
@alvestrand I am curious. What kind of use case does need this? Using a realtime source within the OAC doesn't really fit its processing model.

**Comment by stringparts** [comment]
Previously discussed and proposed to be removed in https://github.com/WebAudio/web-audio-api/issues/308 .

**Comment by rtoy** [comment]
Today's teleconf:

MediaStreamSource implies a real-time situation and OfflineAudioContext is very specifically not real-time and is actually intended to be faster than real-time.  The concepts are not compatible, so we'll leave it as is: MediaStreamSource (and friends) are only available for an AudioContext.

And we've already fixed the issue where the constructor allowed a BaseAudioContext; this is clearly a mistake and should only be allowed for an AudioContext.
