### ISSUE TITLE
Copy AudioNodes across contexts

### ISSUE THREAD

**Issue by braden-m** [WebAudio/web-audio-api#1608]
I'm currently involved in a project where signal data is filtered from a node created by `createIIRFilter()`, and then filtered data is processed via an `OfflineAudioContext`. On completion of rendering, the context closes (and so the filter node is cleared).

Since the data processing is done in a loop, we have to create a new audio context, and basically identical filter nodes multiple times - the latter of which has a large processing cost.

Is there some way in the spec for nodes to be duplicated across contexts with the same options, or to be reused across contexts? Is this a feature anticipated in the future?

**Comment by karlt** [comment]
Would having a way to restart the OfflineAudioContext address this?
I think that is covered by https://github.com/WebAudio/web-audio-api/issues/21

**Comment by rtoy** [comment]
I don't think we'd allow such nodes working across different contexts.  But as @karlt says, a restartable `OfflineAudioContext` is something we'd probably look into for the next version.  Related to #302 as well.

**Comment by braden-m** [comment]
Okay, thank you. A restartable `OfflineAudioContext` seems to address this issue. I'll continue to follow developments of this API.

**Comment by rtoy** [comment]
Hmm.  Can someone remind me why this is v.next?  I don't think we're going to allow moving nodes across contexts.  Restartable offline contexts, however, are under consideration (as mentioned in https://github.com/WebAudio/web-audio-api/issues/1608#issuecomment-388286588 and https://github.com/WebAudio/web-audio-api/issues/1608#issuecomment-388407366)

**Comment by rtoy** [comment]
I'm going to close this.  Restartable offline contexts will solve this actual problem so there's nothing we need to do for this issue; it is covered by #21 and #302.
