### ISSUE TITLE
[Exposed=Window] for Web IDL dicionary or enum doesn't do anything

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#1614]
https://webaudio.github.io/web-audio-api/#enumdef-channelcountmode has:
```webidl
[Exposed=Window]
enum ChannelCountMode {
  "max",
  "clamped-max",
  "explicit"
};
```
The `[Exposed=Window]` bit doesn't do anything for enums. It's also used for some other enums and dictionaries.

**Comment by rtoy** [comment]
I'll remove `[Exposed=Window]` from the enums and dictionaries.
