### ISSUE TITLE
process output buffer values?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1631]
In an `AudioWorkletNode`, if the `process()` methods returns but fails to write any values into the `output` argument, what happens?  That is, what are the values that are output from the node?

Couldn't find anything in the spec that says this, but I think the output arrays should be initialized to 0 so that if `process()` doesn't actually write anything, the output of the node is silence.  Perhaps it's implied by the fact that the channels are `Float32Array` objects, but I think we should say so.

**Comment by hoch** [comment]
After some thoughts, I think we have few things to discuss.

We agreed that an exception should be thrown on the configuration of data containers does not match. (i.e. length of array or sequence)

1. If an exception is thrown within AWGS, all the subsequence operation in AWGS will be halted. Thus, all the other worklet operation stops. Of course, you can catch/try this exception, but I am not sure what that means.
2. Or we can fire an "onprocessorerror" event on the associated AWN and make the processor inactive. The output of the node will be silence afterwards.

**Comment by rtoy** [comment]
I think you confused this issue with #1515 which talks about changing configuration of the `outputs` parameter.

This is just about what is the output of the node if `process()` doesn't actually write anything to `outputs`.

**Comment by hoch** [comment]
Hah, I guess I need to copy the comment above to #1515.

For this issue, the output will simply be silence. We can say something like "Float32Arrays in the given `outputs` argument are zero-filled". Then it implies the output will be silence.
