### ISSUE TITLE
Ill-defined steps and algorithms in rendering loop

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1632]
In https://webaudio.github.io/web-audio-api/#rendering-loop, step 3.2.2 says `nodes` is the all nodes in the context that are still alive.  Then 3.2.8 says reverse the order of `nodes`.  But there was no order in the original set, so reversing is meaningless.

Perhaps 3.2.8 is supposed to reverse the order of `ordered`, since these have a definite order as given in 3.2.7.  But the next step is reversal, so that's not clear either.  Perhaps 3.2.7 should be indented one level and really be 3.2.6.3 instead.  That makes ordering and reversing sensible.

**Comment by rtoy** [comment]
Also in step 3.5:

> For each AudioNode, in the order determined previously:

this should probably say something like

> For each AudioNode `n` in `ordered`

This would require some small changes in the following steps to refer to `n` instead of `AudioNode`.

**Comment by rtoy** [comment]
And step 3.2.6.1 says to choose an AudioNode in `nodes`.  Choose how?  The first one? last one? randomly?

**Comment by rtoy** [comment]
And step 1.1 says to swap Qrendering and Q, but doesn't say what Q is.  Presumably Q represents the current control message queue.  If so, we should say so.

**Comment by padenot** [comment]
Fixed by #1782.
