### ISSUE TITLE
Wavetable synthesis

### ISSUE THREAD

**Issue by mr21** [WebAudio/web-audio-api#1647]
Hi :)

What is the development status of the wavetables in webaudio? For example, how could we make a smooth transition between a sine wave sound to a triangle wave sound with only ONE oscillator node?

We can pass a specific unique periodic wave to an oscillatorNode, but should not we be able to pass an array of periodic waves + a time duration (like setValueCurveAtTime)?

Here, 6 wavetable examples :
![screenshot](http://www.lazlowmusic.com/wp-content/uploads/2017/01/wavetables-serum.jpg)

**Comment by rtoy** [comment]
Nothing is planned that I know of.

At this point, the best approach is to prototype what you want in an `AudioWorkletNode`, and if it is defined well enough, and if it seems appropriate to have such a node built in, it will get added.

**Comment by Mr21** [comment]
Ok understood thanks :)

**Comment by mdjp** [comment]
Closed, should be prototyped in worklet.
