### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#1658]
Broken fragments (these are blocking publication, otherwise [spec is ready](https://www.w3.org/TR/2018/WD-webaudio-20180605/) )

>    https://html.spec.whatwg.org/multipage/infrastructure.html#structuredserializewithtransfer (line 11301)
>    https://html.spec.whatwg.org/multipage/infrastructure.html#structuredserialize (line 11304)
>    https://html.spec.whatwg.org/multipage/infrastructure.html#structureddeserializewithtransfer (lines 11356, 11359)

Looking through WHATWG HTML infrastructure, structured serialization no longer seems to be defined there.

> https://w3c.github.io/mediacapture-fromelement/#dom-htmlmediaelement-capturestream() (line 3384)

Perhaps https://w3c.github.io/mediacapture-fromelement/#dfn-mediastream or https://w3c.github.io/mediacapture-fromelement/#idl-def-htmlmediaelement-capturestream ?

_> https://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia (line 12423)_

Link checker complains on that one, but it exists just fine 👍 
https://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia

> https://html.spec.whatwg.org/multipage/comms.html#message-ports (line 11024)

Should be
https://html.spec.whatwg.org/multipage/comms.html#dom-messageevent-ports

_> https://html.spec.whatwg.org/multipage/#message-channels (line 11295)_

Again this one looks fine, [link checker complains](https://validator.w3.org/checklink?uri=https://www.w3.org/TR/2018/WD-webaudio-20180605/&recursive=on#results1), not sure why.

**Comment by svgeesus** [comment]
The two false-positive broken links are because these are ReSpec documents so the fragments are added by script after page load. Thus our checker does not find them.

**Comment by rtoy** [comment]
I clicked on the first three links about structured serialize.  They go to pages that look correct.  What am I missing there?

Don't understand what's wrong with [https://w3c.github.io/mediacapture-fromelement/#dom-htmlmediaelement-capturestream()](https://w3c.github.io/mediacapture-fromelement/#dom-htmlmediaelement-capturestream()). It goes to the `captureStream()` method which seems right.

**Comment by rtoy** [comment]
The current MessagePort link appears to be correct to me.  And besides, bikeshed created the link. (Well, the one for `AudioWorkletProcessor`.  We should fix the other in `AudioWorkletNodeq to use the same style.

**Comment by svgeesus** [comment]
Ah, the structured serialize links get redirected (but not by some method that the link checker recognizes, perhaps by script?)
Notice the final url is not the one shown.
We should update these in place. Or did bikeshed add them?

**Comment by rtoy** [comment]
I'll have to check.  We've been trying to use bikeshed-style links so that bikeshed can keep them up-to-date instead of us.

**Comment by rtoy** [comment]
Ok, the structured serialize links are implemented using hrefs. If possible we should use bikeshed for these links.

**Comment by rtoy** [comment]
Is there really anything that needs to be here?

**Comment by svgeesus** [comment]
```
Importing a script via the <a href="https://drafts.css-houdini.org/worklets/#dom-worklet-import">import(moduleUrl)</a> method registers class definitions of <code class="idl"><a data-link-type="idl" href="#audioworkletprocessor" id="ref-for-audioworkletprocessor④">AudioWorkletProcessor</a></code> under the <code class="idl"><a data-link-type="idl" href="#audioworkletglobalscope" id="ref-for-audioworkletglobalscope③">AudioWorkletGlobalScope</a></code>.
```

The concept of worklet import does not seem to exist anymore in the worklet spec.

**Comment by svgeesus** [comment]
```
Importing a script via the <a href="https://drafts.css-houdini.org/worklets/#dom-worklet-import">import(moduleUrl)</a> method
```
Concept of worklet import does not seem to exist anymore.

**Comment by rtoy** [comment]
Any more broken links?

**Comment by rtoy** [comment]
AFAICT, there are no broken links.  Can we close this now, @svgeesus ?

**Comment by rtoy** [comment]
I'm going to close this out.  Please reopen or file a new issue if there are still broken links.
