### ISSUE TITLE
Autoplay logic should only be applied to AudioContext

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#1669]
See BaseAudioContext.resume() algorithm:
https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-resume

Including the notion of `allowed to start`, all the autoplay logic must be moved to AudioContext. OfflineAudioContext does not have to deal with any restriction, because it is invoked by user with `.startRendering()`. IMO we should not pollute the OAC with any autoplay behavior.

Editorial note: The definition of `allowed to start` is a part of the AudioContext interface, but it is referred in the algorithm of BaseAudioContext.resume(). Not sure how to resolve this cleanly though.

**Comment by rtoy** [comment]
Maybe the simplest way is to modify step 4 and break it into two cases, one each for an AudioContext and OfflienAudioContext?

**Comment by hoch** [comment]
Not sure. My personal preference is to get rid of autoplay stuff completely out of BaseAudioContext. The autoplay policy should be a UA-specific behavior and its presence on the spec should be minimized as possible.

**Comment by rtoy** [comment]
Not sure how you can do that either since `resume()` is in the `BaseAudioContext`.  Unless you're proposing to have two `resume()` methods, on for `AudioContext` and one for `OfflineAudioContext`.  I suppose that's possible.  Their behaviors are different due to autoplay.

**Comment by rtoy** [comment]
Teleconf:  Remove resume() from BAC and add one each for AC and OAC.

**Comment by rtoy** [comment]
Teleconf:  @hoch to ask for guidance on whether this split makes sense.

**Comment by domenic** [comment]
That IDL is totally reasonable, and makes a lot of sense for this case.

**Comment by hoch** [comment]
Thanks for the quick response, sir. :)
