### ISSUE TITLE
Can I merge channels in a single output buffer file

### ISSUE THREAD

**Issue by matheus-pereira** [WebAudio/web-audio-api#1672]
Can I convert a local audio file (mp3, wav) in mono channel before uploading to my server? I have no idea how to do it, it's possible?

**Comment by rtoy** [comment]
This is for issues with the spec.  If this is not about an error in the spec, please use some other forum for help.  Perhaps consider stackoverflow.com among others.

If this really is a spec issue, please re-open this issue.
