### ISSUE TITLE
Re-ordering of suspend and resume

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#1674]
```
  console.log("new AudioContext");
  var context = new AudioContext();
  console.log("initial state: " + context.state);
  context.onstatechange =
    () => {
      context.onstatechange = null;
      console.log("state change to " + context.state);
      console.log("suspend");
      context.suspend().then(() => console.log("suspend resolved"));
      console.log("resume");
      context.resume().then(() => console.log("resume resolved"));
    };
```

Expected:

```
new AudioContext
initial state: suspended
state change to running
suspend
resume
suspend resolved
resume resolved
```

As currently specified:

```
new AudioContext
initial state: suspended
state change to running
suspend
resume
resume resolved
suspend resolved
```

**Comment by karlt** [comment]
The simplest solution, I expect, would be to remove 

"If the state attribute of the BaseAudioContext is already "running", resolve promise, return it, and abort these steps."

https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-resume

Perhaps "Start rendering the audio graph" could also be conditional on
whether already started.

**Comment by rtoy** [comment]
Interesting.  

I have a question.  Let's say it takes 1 sec for your audio device to stop, and `suspend()` resolves when the audio device has actually stopped.  Let's also say it takes 1 microsecond to start the audio device. and `resume()` resolves when the audio device is running.  Does the output (expected or actual) change?

**Comment by rtoy** [comment]
These are my expectations as well.  So basically, if you suspend(), the promise is resolved after 1 sec, and the resume will then resolve() afterwards.  So basically it will take 1 sec to resume. 

Well, unless the implementation keeps track of these things and notices suspend has been called but isn't resolved so calling resume could force suspend to resolved right away and resume can "restart" the audio, which wasn't actually suspended.  But we're not requiring this behavior.  But we're also not allowing it?

**Comment by karlt** [comment]
> Well, unless the implementation keeps track of these things and notices suspend has been called but isn't resolved so calling resume could force suspend to resolved right away and resume can "restart" the audio, which wasn't actually suspended. But we're not requiring this behavior. But we're also not allowing it?

Good question.

I don't think we need to require this behavior.

The exact length of time that a suspend will take is not going to be
specified, and so, whether explicitly allowed or not, an implementation
will be free to implement some kind of shortcut provided the behavior is not
observably different from a quick suspend and resume.

Resolving the suspend and resume promise "right away" during the resume()
call, however, would be observably different, in some circumstances, due to
potentially changing the order of microtasks for promise callbacks, if there
are other (neither suspend nor resume) promises resolved later in the same
event.  My preference would be not to allow this.

**Comment by rtoy** [comment]
From today's teleconf:  @karlt's suggestion works; remove that line.
