### ISSUE TITLE
Example 12 misses required parameterDescriptors static property

### ISSUE THREAD

**Issue by saschanaz** [WebAudio/web-audio-api#1679]
**Describe the issue**

[1.33.4.3](https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-methods) requires `parameterDescriptors` static property for subclasses but [the example 12](https://webaudio.github.io/web-audio-api/#AudioWorklet-concepts) lacks it.

>The subclass MUST define a method named process() that implements the audio processing algorithm and have a valid static property named parameterDescriptors which is an iterable of AudioParamDescriptor that is looked up by the AudioWorkletProcessor constructor to create instances of AudioParam in the parameters maplike storage in the node.

>```webidl
>// bypass-processor.js script file, runs on AudioWorkletGlobalScope
>class BypassProcessor extends AudioWorkletProcessor {
>  process (inputs, outputs) {
>    // Single input, single channel.
>    let input = inputs[0];
>    let output = outputs[0];
>    output[0].set(input[0]);
>
>    // Process only while there are inputs.
>    return false;
>  }
>});
>
>registerProcessor('bypass-processor', BypassProcessor);
>```

(0af0f3dadbc0ed9dbee867328b69bff21dd01d4c somehow removed the MyProcessor example so the BypassProcessor is the only subclassing example)

**Comment by saschanaz** [comment]
(Sorry for accidental early incomplete post)

**Comment by rtoy** [comment]
@hoch will look into fixing this example (or adding a new one?)

**Comment by hoch** [comment]
The section 1.33.4.3. is not tied to the example 12. I believe the example 12 looks okay as it is. The issue here is "MyProcessor" example got deleted somehow. I'll add it back.
