### ISSUE TITLE
[Question] Get started with AudioWorkletNode

### ISSUE THREAD

**Issue by mikael-onsilva** [WebAudio/web-audio-api#1685]
Hello!

I'm starting with javascript programming and I'm currently developing kind of a audio player for Android using Cordova.
I'm struggling with memory issues when I've loaded some amount of audio files.

I've read in [this document](https://developer.mozilla.org/pt-BR/docs/Web/API/AudioBufferSourceNode) that it's posible to play audio files directly from  disk, without loading them into the memory. I believe this might be a solution for me, considering that I need the accuracy of web audio.

But as I'm new at programming, I'm not being able to change my `AudioBufferSourceNode ` to a `AudioWorkletNode`.

Do you guys have any documents I could read about how to do this (load, play, stop, gain control)?

Sorry if this wasn't the right place to post it.
Thanks in advance.

**Comment by hoch** [comment]
> I've read in this document that it's posible to play audio files directly from disk

This is not true. The AudioBufferSourceNode has to load the entire PCM data to the memory. I think what you're referring is actually HTMLAudioElement + MediaElementSourceNode. It is a completely different playback model - allowing you to stream data without loading up the entire file.

For your purpose, I don't think you need AudioWorkletNode. The MESN would be good enough.

With that said, this is the first result of Google search on AudioWorklet: [the intro article](https://developers.google.com/web/updates/2017/12/audio-worklet).
