### ISSUE TITLE
Configuring AudioWorklet output channels under-specified

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1686]
In https://webaudio.github.io/web-audio-api/#configuring-channels-with-audioworkletnodeoptions, an algorithm is specified for the number of output channels.

Consider the scenario where `numberOfInputs` = `numberOfOutputs` = 1 and `outputChannelCount` is given.  From the algorithm, the second item is true.  However, we only say what happens when `outputChannelCount` is not given; we don't say what happens if it is given.  (The last item isn't applicable in this case.)

What is the expected behavior here?

**Comment by padenot** [comment]
My expectation is that when specified, the outputs will all have `outputChannelCount` channels.

**Comment by hoch** [comment]
Yes. If user explicitly asks, it should be honored. So we need something like this in the [section](https://webaudio.github.io/web-audio-api/#configuring-channels-with-audioworkletnodeoptions):

"The output channel count is configured by `outputChannelCount`. Redundant items in the `outputChannelCount` will be ignored and the unspecified channel count will be configured as shown below:"

**Comment by karlt** [comment]
From the section above for outputChannelCount, "IndexSizeError MUST be thrown
if the length of sequence does not match numberOfOutputs", and so there will
not be any redundant or unspecified items in outputChannelCount, unless the
outputChannelCount is not specified at all.

Interesting to note that numberOfOutputs does not need to exist as the
information could be provided by the length of the outputChannelCount.
It does, however, provide a simple way of configuring multiple mono outputs
without explicitly specifying outputChannelCount.  Perhaps the default for
numberOfOutputs could be removed and outputChannelCount length used if
numberOfOutputs is not provided, but outputChannelCount is.

**Comment by karlt** [comment]
> The numberOfOutput and the length of outputChannelCount both specified:
> 
>     If they match, honor them.
>     If they do not match, throw an exception.
> 
> If numberOfOutput is omitted, thus it defaults to single output:
> 
>     If outputChannelCount not specified, use the adaptive channel count.
>     If outputChannelCount specified with a single value, honor the given channel count.
>     If outputChannelCount specified with more than 2 values, throw an exception.

That matches my interpretation of the current state of the spec.
Making that clearer sounds helpful.

My optional numberOfOutputs suggestion was a bikeshed.

Considering the needs of DelayNode, for example, outputChannelCount may end up
being the one that is unnecessary. https://github.com/WebAudio/web-audio-api/issues/1515#issuecomment-406173462

**Comment by hoch** [comment]
> Considering the needs of DelayNode, for example, outputChannelCount may end up
being the one that is unnecessary.

Would this be a V1 issue? I am not sure about getting rid of `outputChannelCount` from the spect at this point.

**Comment by karlt** [comment]
Providing a way for AudioWorkletProcessor.process() to change the number of
output channels does not need to be V1 issue.  I'd like to keep that in mind
so that nothing we do will make adding that later difficult.  Clarifying
outputChannelCount here does not make that more difficult, thanks.
