### ISSUE TITLE
Smoothing over time is under-specified

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1687]
In https://webaudio.github.io/web-audio-api/#smoothing-over-time, there's an implicit assumption that the FFT size isn't changing. If the FFT size does change, it's not clear what smoothing should do.

For example, let `fftSize = 256`.  Get the frequency data.  Set `fftSize = 2048`.  Wait a bit and get the frequency data again.  How are these two blocks supposed to be smoothed together?

**Comment by padenot** [comment]
AudioWG call resolution: the internal state of the AnalyserNode will be reset to silence in the buffers used for smoothing (i.e. the past audio data).

**Comment by rtoy** [comment]
Heh.  There's actually nothing to do here. See [fftSize](https://webaudio.github.io/web-audio-api/#dom-analysernode-fftsize).  Changing the `fftSize` resets memory.
