### ISSUE TITLE
Allowed range for OscillatorNode.detune

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1698]
According to https://webaudio.github.io/web-audio-api/#OscillatorNode-attributes, the valid range for `detune` is all finite values.  But the `frequency` attribute is limited to Nyquist frequency.  This seems odd  because you can specify a `detune` value that results in a frequency well beyond Nyquist.  

Perhaps we should make the nominal range something like 1200 * log2(2 * Nyquist) so that the detuned frequency stays within Nyquist.  (The extra factor of 2 so that if `frequency` = -Nyquist, we can detune it to produce +Nyquist.)  But also, detune forms a compound parameter whose nominal range is +/- Nyquist anyway.  Still, it's nice to have a limited range for `detune` when it would cause clipping anyway.

**Comment by padenot** [comment]
Agreed.

**Comment by rtoy** [comment]
Hmm.  From [section 1.6.3](https://webaudio.github.io/web-audio-api/#computation-of-value), I'm now not sure what's supposed to happen.  If I set `detune` to 1e20, is `detune` then clamped to 1200 * log2(2 * Nyquist)?  But since `detune` forms a compound parameter with `frequency`, the clamping to the nominal range is supposed to happen after computing the value of the compound parameter from its constituent parameters.

I think `detune` is a bit different because it's pretty easy to cause infinity to result from converting cents to frequency.

These are implementation details. I nevertheless think having a smaller range for detune is a nice hint to developers on what values they should be using.

**Comment by rtoy** [comment]
My computations are not quite right.  The [computedOscFrequency](https://webaudio.github.io/web-audio-api/#computedoscfrequency) is 

```
computed = f * 2^(d/1200)
```

where `f` is the oscillator frequency and `d` is the detune value.  If we let the computed frequency be the Nyquist frequency, we get

```
d = 1200*log2(Nyquist / f)
```

So for arbitrarily small `f`, we need arbitaritly large `d` to get a computed frequency equal to Nyquist.

However, if we restrict everything to be a finite float, the largest value for Nyquist / f is about 3.4028235e38 which implies the largest value for `d` is 153600.0.

So in practice this is the largest value of `d` that can be used.  But using this value basically causes the computed frequency to overflow for any non-zero oscillator frequency.

**Comment by rtoy** [comment]
Reopening.  The PR #1703 has a reasonable limit, but I think it's too restrictive, per https://github.com/WebAudio/web-audio-api/issues/1698#issuecomment-406426007

I think it needs to be wider and probably closer to 153600.

**Comment by rtoy** [comment]
On the other hand, the current limits allow you to detune a 1 Hz base frequency up to the sample rate, well beyond Nyquist.  Maybe that's ok, and we don't care about detuning sub 1-Hz frequencies up to Nyquist.  That seems unneeded for the use cases for WebAudio.

**Comment by padenot** [comment]
Maybe for LFOs, though.

**Comment by rtoy** [comment]
Maybe.  So, should we just leave the limit as is or make if 153600 as mentioned in https://github.com/WebAudio/web-audio-api/issues/1698#issuecomment-407131286

**Comment by svgeesus** [comment]
Is it maybe easier to say that both `frequency` and `detune` are unbounded but the computed, detuned frequency is clamped to Nyquist frequency?

**Comment by rtoy** [comment]
Teleconf result:  Change limit to 153600 (largest possible because anything larger will overflow).
