### ISSUE TITLE
Override the system mixer volume

### ISSUE THREAD

**Issue by reda-alaoui** [WebAudio/web-audio-api#1699]
**Describe the feature**
Override the system mixer volume

**Is there a prototype?**
Not yet

**Describe the feature in more detail**
Some audio applications need to be able to emit pure sound at accurate frequency and volume.

The frequency part is already handled by the OscillatorNode.

But, currently, the application can't make sure that the sound is emitted at a precise volume level.
The GainNode is subject to the OS volume setting. Therefore GainNode is only half the solution, the application needs to be at least aware of the system/application global volume, at best to be able to control it.

Ideally:
- each browser tab would be associated to a "tab gain"
- each tab could control this tab gain
- this tab gain would not be subject to system volume, meaning, the user could not impact it from the OS sound mixer
- the GainNode would be subject to this tab gain

Of course, this would require the user to accept the implied full sound control on the browser tab.
The notion of tab gain could be merged with the current GainNode.
The GainNode would then have two behaviours, depending on the user given authorization.

I didn't build a prototype for that, I wanted to crash test the idea here

**Comment by rtoy** [comment]
Why not just ask the user to turn the OS volume up to max?  

Having a browser be able to bypass the OS volume settings seems like a bad idea. It's bad enough that there are autoplaying videos and now you're giving them a way to blast audio at full volume at the same time?

**Comment by reda-alaoui** [comment]
Because some users have no idea how to turn the volume to max or won’t do it.

It would require a user autorization so I don’t see the harm.

**Comment by reda-alaoui** [comment]
The authorization could be asked once per tab lifecycle, therefere never stored

**Comment by rtoy** [comment]
Yet another popup asking for authorization is not a great idea either.  And if you never store the authorization, users get asked every time they visit a site, and that could be really annoying too.

**Comment by reda-alaoui** [comment]
The application that we are building is one that allows an audiologist to check the hearing threshold of his patient. Today we must rely on external software or hardware modules (without any sandboxing, nor authorization system) to do that.
In this kind of app, setting/locking the master volume is a one time operation.

So yes, yet another popup, but to make the user life easier and its software usage a little bit safer.

Isn't the ultimate goal being able to create any kind of application using only the web platform?
If yes, that seems to me another step toward this goal.

**Comment by rtoy** [comment]
Also, even if the OS volume setting were bypassed, how do you get precise volume and what does that really mean?  The output could be to internal speakers, external speakers, headphones, TVs, receivers, etc.  And they all have different "volumes".  What does precise volume mean here?

**Comment by reda-alaoui** [comment]
In our case, the value that we are interested in is the decibel sound pressure level (dB SPL).

The prerequisites:
- a calibrated transducer (headphone or speaker)
- a known sound card

To produce the correct sound level, we need to be sure that the master volume is set to 100%.

**Comment by reda-alaoui** [comment]
What would be great, but maybe not part of this issue, would be to be able to list the available outputs and select the desired one. The same way we can select the preferred camera using webrtc.

**Comment by rtoy** [comment]
It seems that you have custom HW for testing and you'll be sitting next to the patient.  Why would the volume not be set to 100% already?  

As for selecting the output, that is already an important issue we want to take on in V2. See #445.

**Comment by reda-alaoui** [comment]
The HW is not that custom.

Suppose we want to perform the hearing test on a Microsoft Surface.

The calibrated transducer could be any headphone of the market, only specially calibrated.
The Surface integrated sound card is known without being custom.
The Surface would not only allow to test the hearing, but also to display videos, produce quotations, etc ... It would be manipulated by people having different roles (audiologist, seller, hostess).

The used HW will be multipurpose, thus there is no guarantee that the master volume stays at 100%.

**Comment by rtoy** [comment]
Ok.  But if you're an audiologist, isn't it your responsibility to make sure things are set up correctly to do a test?  I mean, microphones and headphones do get damaged so you have to make sure they're working before doing a test.

**Comment by reda-alaoui** [comment]
One of the test is a light screening test. It just acts as a sensibilization tool. This test can be performed by a non audiologist professional. 
The customer himself could use a free access computer having the application and the headphone plugged on it to check his hearing.

Beside that, even an audiologist professionnal will prefer an auto setup to something that should be manually set.

**Comment by reda-alaoui** [comment]
> I mean, microphones and headphones do get damaged so you have to make sure they're working before doing a test.

That could be another part of the application, a calibration checker. 
If we can override the master volume, we can add a feature that allows to verify that the transducers are still correctly calibrated thanks to a special microphone that could be plugged inside the headphone ears. We could then emit a sound from the application while listening to the microphone to automatically evaluate the received sound pressure level and conclude to a correctness of the transducer.

**Comment by padenot** [comment]
This is bound to be OS and hardware specific and we won't be able to make it work properly. Two cases where this cannot work (as examples):
- On Android, the volume can be fixed and can't be changed: https://developer.android.com/reference/android/media/AudioManager.html#isVolumeFixed()
- The volume can be impossible to change in software (for example, my Focusrite Scarlett 6i6 grays out the volume slider in OSX, and I have to use the physical dial to change it)

In addition, I don't this this is really the responsibility of the Web Audio API itself (which is more about processing than outputing sound), but it's true that there is no spec _for now_ that is better. However, I'd like this to change in the future, and I'm not comfortable adding hardware control to the Web Audio API

Also I'm thinking that maybe this is too niche to warrant something in the standard. Something like a browser extension that communicates with a little piece of software installed on the machine could  achieve the result wanted here:
- When the testing page is opened, the extension communicates with a daemon on the machine (using for example [NativeMessenging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging), which is available, 
- The deamon set the master volume to the maximum (or any other pre-established value for this specific setup)
- The deamon notifies the extension that the volume has been set
- The page proceeds and the normal testing using normal Web Audio API code continues

**Comment by padenot** [comment]
AudioWG resolution (2018-07-19 call): this does not really belong in the Web Audio API spec.
