### ISSUE TITLE
Specify exactly what should happen when createScriptProcessor is passed invalid arguments

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#17]
> Originally reported on W3C Bugzilla [ISSUE-20750](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20750) Thu, 24 Jan 2013 02:07:38 GMT
> Reported by Ehsan Akhgari [:ehsan]
> Assigned to 

We should probably raise an exception and the exception type should be specified.  This applies both to the bufferSize argument and when both numberOfInputChannels and numberOfOutputChannels passed are zero.

**Comment by billhofmann** [comment]
Is this still relevant, if we've deprecated ScriptProcessorNode?

**Comment by rtoy** [comment]
I think it's still relevant. It's deprecated, but still exists and will for some time.
