### ISSUE TITLE
parameterDescriptors of an AudioWorkletProcessor should be optional

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1702]
**Describe the issue**
The [paragraph which describes how to implement an `AudioWorkletProcessor`](https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-methods) mentions that an `AudioWorkletProcessor` *may* have a valid static property named parameterDescriptors. On the other hand the algorithm which describes the inner workings of the [`registerProcessor()`](https://webaudio.github.io/web-audio-api/#AudioWorkletGlobalScope-methods) method says a TypeError should be thrown if the parameterDescriptors property is undefined.

**Where Is It**
https://webaudio.github.io/web-audio-api/#AudioWorkletGlobalScope-methods (bullet point 7 & 8)

**Additional Information**
I guess the algorithm should be changed to handle a missing (aka undefined) parameterDescriptors property.

**Comment by karlt** [comment]
I wonder whether "If descriptors is not an array or undefined, throw a TypeError and abort these steps." was intended to mean "neither an array nor undefined".

**Comment by chrisguttandin** [comment]
@karlt yes that could be the case. Should I create a pull request to change that?

**Comment by rtoy** [comment]
@chrisguttandin If you have the time and desire to do a pull request, we won't say no. :-)

However, be sure to checkout the master branch for your work.  The gh-pages branch is now only for the auto-generated HTML spec.  (This recently changed so that Travis CI can deploy the HTML spec automatically when the master branch is updated.)

**Comment by hoch** [comment]
I think the simple fix would be what @karlt said above. @chrisguttandin, you're welcome to fix this one or I could do it as well. (I guess I made a lot of mistakes here and there...)
