### ISSUE TITLE
WebAudio + User Gestures

### ISSUE THREAD

**Issue by jasonanovak** [WebAudio/web-audio-api#1715]
In addition to the fingerprinting mitigations added as part of #1498, #1499, and #1500, another approach worth considering and including would be requiring a user gesture to initialize an AudioContext.

**Comment by rtoy** [comment]
This is already currently allowed.  See the third paragraph in https://webaudio.github.io/web-audio-api/#AudioContext.  

Chrome did this recently, reverted it, and will re-enable it in the near future so that a user gesture is required under some conditions.

**Comment by jasonanovak** [comment]
Ah.  Maybe it would make sense to move the text that is currently in that note into the security / privacy considerations section in that case or somehow cross reference the note there?

**Comment by rtoy** [comment]
I can add a link to item 4 of the security section. (I think that's the best place for it.)

**Comment by rtoy** [comment]
As currently spec'ed this user gesture doesn't prevent an `AudioContext` from being created.  Rather, the spec says the `AudioContext` starts in a suspended state. You will be able to see the sample rate and output channel count.

This needs further discussion in the WG.
