### ISSUE TITLE
iOS 11 Safari, non-functioning stream from createMediaStreamDestination/MediaElementAudioDestinationNode 

### ISSUE THREAD

**Issue by sirius0xff** [WebAudio/web-audio-api#1722]
**Describe the issue**

I am working on a project that need to process an audio stream using Web Audio. The only way I found to get the output as stream is using AudioContext.createMediaStreamDestination() and the stream property.

However, on iOS 11 Safari, the stream from MediaElementAudioDestinationNode does not play, in any ways I have tried.

I have checked the properties of both the stream and the embedded track and everything looks normal.

I understand that the problem may be on Apple's side, but I would like to check if it is really the case. 

And if so, are there any workaround?

### **A simplified demonstration:**

**init:**
```
var context = new AudioContext()
// call context.resume() on touch event
function augmentStream(stream){
    var src= context.createMediaStreamSource(stream)
    var gain=context.createGain()
    gain.gain=1
    var dst= context.createMediaStreamDestination()
    src.connect(gain)
    gain.connect(dst)
    return dst.stream
}
var rtcOrGumStream=......// rtc Or Gum
var dstStream = augmentStream(rtcOrGumStream)
```

all the following cases works in android/chrome-on-pc, but not in IOS 11 safari.
**example 1:**
```
var src=context.createMediaStreamSource(dstStream )
src.connect(context.destination)// no sound
```
**example 2:**
```
var audioEl= document.querySelector('audio')
audioEl.srcObject=dstStream
audioEl.play() // no sound
```

**example 3:**
```
var audioEl = document.querySelector('audio')
var ana = context.createAnalyser()
var src=context.createMediaStreamSource(dstStream )
src.connect(ana)

ana.getByteTimeDomainData(dataArray) // always result in zero filled array anytime afterwards
```

**Where Is It**
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioDestinationNode

**More of it**
Also the sample **Web Audio input** does not work on the mobile Safari. There is sound output if and only if "Add local audio to output" is checked.
https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/

**Comment by rtoy** [comment]
Did you not read the bug template?  Your issue is not about the spec itself but about an implementation.  File a bug with Safari.  Or ask on stackoverflow or the webaudio slack channel, as mentioned in the bug template.

**Comment by davedoesdev** [comment]
@sirius0xff did you file a bug with Safari?

**Comment by davedoesdev** [comment]
For reference, these cover it:

https://bugs.webkit.org/show_bug.cgi?id=173863
https://bugs.webkit.org/show_bug.cgi?id=198284
