### ISSUE TITLE
some typo and missing description

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#1727]
https://webaudio.github.io/web-audio-api/#AudioContext-methods
   typo:HTMLEMediaElement.captureStream()

https://webaudio.github.io/web-audio-api/#AudioNode-methods
  in the Arguments for connect() / disconnect() method tables,
  "Type - Nullable - Optional" items are blank for some "destinationNode" or "input".
  And missing "Return type:"

https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-methods
  in the table "Arguments for the AudioWorkletProcessor.process(inputs, outputs, parameters)) method."
    input and output :   " It has type <sequence<sequence<Float32Array>>"
    unmatched brackets, probably the first &lt; is unnecessary?

https://webaudio.github.io/web-audio-api/#AudioWorklet-Sequence
  in the description of step 3.
  typo : "context’sThis is the global scope"

**Comment by rtoy** [comment]
Thanks for the report; I'll fix them soon.

**Comment by g200kg** [comment]
Thank you, can I add some more even it is not a simple typo?

https://webaudio.github.io/web-audio-api/#OfflineAudioContext-methods
step 1. and step 2. is reverse ordered?

https://webaudio.github.io/web-audio-api/#AudioNode-methods
"Arguments for the AudioNode.connect(destinationNode, output, input) method." - destination
  InvalidAccessError has no synchronous mark ?

**Comment by rtoy** [comment]
Ok, the "Type - Nullable - Optional" are issues with bikeshed that we haven't been able to figure out.  We think it's a bug in bikeshed, but we're not sure.

The order does look reversed in the startRendering algorithm. (I wish we could expose links to the algorithms.)

**Comment by g200kg** [comment]
Thank you. I also found some more : 

https://webaudio.github.io/web-audio-api/#AudioParam-attributes
1.6.1 Attributes
  DynamicsCompressorNode
    missing comma between "threshold knee"

https://webaudio.github.io/web-audio-api/#BiquadFilterNode-methods
1.13.3. Method
  getFrequencyResponse(frequencyHz, magResponse, phaseResponse)
    at the beginning,
      typo: "sychronous" in the tag. synchronous mark is not displayed.

https://webaudio.github.io/web-audio-api/#Convolution-channel-configurations
1.17.4. Channel Configurations for Input, Impulse Reponse and Output
  "The first image in the diagram...."
     missing corresponding diagram.

https://webaudio.github.io/web-audio-api/#MediaElementAudioSourceOptions-security
1.22.4. Security with MediaElementAudioSourceNode and Cross-Origin Resources
  "using a MediaElementAUdioSourceNode, and a ScriptProcessorNode ...."
     AudioWorkletNode is better for explanation now?

https://webaudio.github.io/web-audio-api/#Spatialization-background
7.1. Background
  "AudioListener objects (representing a person’s ears) have an orientation and up vector ..."
     AudioListener's vector is 'forward' instead of 'orientation' ?

https://webaudio.github.io/web-audio-api/#priv-sec
9. Security and Privacy Considerations
  "6. Does this specification enable new script execution/loading mechanisms?
     No. It does use the worker script... "
   may be a worklet ?

  "9.Does this specification allow an origin access to aspects of user's local...."
  The paragraph of question and answer is not divided.

<hr/>
Although it is assumed that some explanation is to use AudioContext.createXXX (), 
it may be better to mention that also it may be specified as an options when using the constructor?

https://webaudio.github.io/web-audio-api/#channelsplitternode
1.15. The ChannelSplitterNode Interface
 "determined by the numberOfOutputs parameter to the AudioContext method createChannelSplitter()..."

https://webaudio.github.io/web-audio-api/#DelayNode-attributes
1.18.2. Attributes
  delayTime, of type AudioParam, readonly
    "..maximum value is determined by the maxDelayTime argument to the AudioContext method createDelay()."

https://webaudio.github.io/web-audio-api/#IIRFilterNode-filter-definition
1.21.4. Filter Definition
  "Let bm be the feedforward coefficients and an be the feedback coefficients specified by createIIRFilter()."

https://webaudio.github.io/web-audio-api/#MediaElementAudioSourceNode-attributes
1.22.2. Attributes
  "A MediaElementAudioSourceNode is created given an HTMLMediaElement using the AudioContext createMediaElementSource() method."
  " HTMLMediaElement passed in as the argument to createMediaElementSource(), ..."

**Comment by rtoy** [comment]
Thanks for pointing these out. (And awesome [translation of the spec to Japanese](https://g200kg.github.io/web-audio-api-ja/)! I can't read it, but Google translate does a pretty good job of producing readable English from it.)

**Comment by rtoy** [comment]
I think all of the above-mentioned typos have been fixed.  Thanks for pointing them out.  If you find any more, please open a new issue for them.
