### ISSUE TITLE
Funny Chrome version numbers in impl report

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1740]
In the [implementation report](https://webaudio.github.io/web-audio-api/implementation-report.html) near the bottom about the syntax-level DOM test, the versions numbers for Chrome are 949.0.2623.112 and 949.0.2623.105. Latest stable build is 69.  Pretty nice time machine there, @svgeesus!

**Comment by hoch** [comment]
In the version 949, we'll be playing with networked DAWs in VR headsets.

**Comment by rtoy** [comment]
Headsets in 949?  You lack imagination.  You'll be controlling it directly with your mind and everything will be streamed directly to your brain so it won't even be virtual reality anymore.

**Comment by svgeesus** [comment]
Hopefully fixed by https://github.com/WebAudio/web-audio-api/commit/234e44356b3e6ba0a8e718d911af334d4e2ec2e4

I re-ran in Edge 17, Canary 71, Nightly 64a1
Still need to grab other devices to re-run iOS Safari, OSX Safari, Android Chrome.

**Comment by rtoy** [comment]
Looks good to me.  Closing this bug as fixed as by the commit mentioned in https://github.com/WebAudio/web-audio-api/issues/1740#issuecomment-420085897
