### ISSUE TITLE
AnalyserNode: Clarify how much time domain data we're supposed to keep around

### ISSUE THREAD

**Issue by Manishearth** [WebAudio/web-audio-api#1746]
Currently, according to the spec, changing fftSize resets the smoothing data.

However, nothing is mentioned of the [time domain data](https://webaudio.github.io/web-audio-api/#current-time-domain-data).

We can do one of three things here:

 - Reset the time domain data whenever fftSize is changed. This does mean that we'll have a sharp discontinuity which will take some time to subside. This is pretty efficient, however.
 - Only store `fftSize` sample frames of time domain data. If `fftSize` is increased, fill with silence. This also has a discontinuity problem, but less of one -- if we jump from 1024 to 2048, we still get to keep most of our history
 - Store 32768 (the max value of `fftSize`) sample frames of time domain data. This means we never have a discontinuity problem, but it also means that each analyser node compulsorily to allocate a megabyte of memory. This is what Firefox currently does (but it would be nice to change it)

cc @rtoy @padenot

**Comment by Manishearth** [comment]
The spec specifically says

> all state associated with smoothing of the frequency data

but it's not clear if the time domain data is associated with the smoothing data.

**Comment by rtoy** [comment]
Good questions.  Chrome allocates enough space to store 32768 elements too.  And Chrome double-buffers, but this is only 256K (8*32768).  How do you get a megabyte of data? I don't think this is terrible, but I'm assuming in typical uses, there's just one or two analyser nodes so the memory consumption isn't horrible. I could be wrong.

About the state for the frequency data, the following sentence says it's the previous block used for smoothing that is reset to all zeros.  I don't see that all state needs to be reset; wouldn't that mean if you ask for the frequency data right after changing fftSize would produce all 0s.  That's probably not what is desired.

**Comment by Manishearth** [comment]
Oops, I counted bits instead of bytes :smile: 

I guess this is fine.

For the frequency data we just want it to be invalidated, presumably (i.e. you need to recompute it even if currentTime hasn't changed)

**Comment by rtoy** [comment]
But since you asked, I think we should add sentence or something that implies that the changing fftSize doesn't cause zeroes or anything like that for the time domain data.  Not sure how to phrase that right now though.

**Comment by Manishearth** [comment]
We should also clarify that changing fftSize means you must immediately have that many frames available, so you should always store the last max-fft-size frames.

**Comment by rtoy** [comment]
Doesn't this basically mean you MUST have 32k samples available just in case you change fftSize to 32K?

**Comment by Manishearth** [comment]
Right, that's the impetus for this question. How much should we keep
around? Just fftSize? That should be specced :)

**Comment by rtoy** [comment]
Teleconf:  Leave it as is, implying 32K buffers needed.

**Comment by Manishearth** [comment]
Does that mean the text won't be changed at all? IMO we should at least add
a note (I can make a PR)

**Comment by rtoy** [comment]
A note would be excellent.  Thanks!

A bit more context from the teleconf.  It's not a huge amount of memory (assuming there's probably only one analyser).  For visualization, it's probably not a big deal if you had zeroes in the output, but some people are actually using the node for analysis, so zeroes would be a problem.  And since Chrome, Firefox, and Safari (and probably Edge?) already keep 32K of history anyway, and no one has complained about excessive memory use from this node, it's probably best to keep things as they are.
