### ISSUE TITLE
Have a single `AudioWorkletGlobalScope` per `BaseAudioContext`

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1753]
I think this was forgotten when writing a PR for #1511 (no wonder, it was so big).

The resolution seem to be https://github.com/WebAudio/web-audio-api/issues/1511#issuecomment-373391203. It's also a resolution in https://github.com/WebAudio/web-audio-api/issues/966#issuecomment-250212008.

It's rather critical for interop and is what Chrome implements (and we'll implement). Authors need to reliably be able to share data between instances (wave tables, audio buffers, other precomputed data, etc.).

**Comment by hoch** [comment]
Yes, this is an oversight and the fix should be trivial. So you think the following text in the spec is problematic? (From [here](https://webaudio.github.io/web-audio-api/#audioworkletglobalscope))

> __At least one__ AudioWorkletGlobalScope exists for each AudioContext that contains one or more AudioWorkletNodes.

**Comment by padenot** [comment]
Yes, it means you can't really count on the fact that you can read the expandos you set in one `process` in another `process`.

**Comment by hoch** [comment]
Also Worklet's `addModule` method and the construction process of `WorkletGlobalScope` do not seem to be compatible with the notion of parallelism. In fact, there is a bit of history on this sentence - @joeberkovitz wanted to have some room for the future so we can support multi-threading support by having multiple `AudioWorkletGlobalScope`s.

Here's the relevant discussion: https://github.com/WebAudio/web-audio-api/pull/1020/files#r88695255

But I think it might need a completely different approach to support the multi-threading without violating many assumptions that are already in place. Hence, SGTM.
