### ISSUE TITLE
AudioWorkletProcessor parameters

### ISSUE THREAD

**Issue by lonce** [WebAudio/web-audio-api#1755]
**Describe the issue**
The AudioWorkletProcessor parameters are set only for the 1st element in the buffer.

An example of this issue can be seen in the "Walkthrough: building a GainNode" at
https://developers.google.com/web/updates/2017/12/audio-worklet
It is broken because in the 
`process(inputs, outputs, parameters) `
 function of gain-processor.js,
gain[0] is set to the default value (1, established in parameterDescriptors), but gain[1...127] are undefined.

- lonce

**Comment by padenot** [comment]
Please refrain from using this issue tracker for problems that apply to implementations, this issue tracker is for spec related matters.

That said, if the value is constant for the duration of a rendering block, the array can have only a single element, which is the value of the `AudioParam` for the duration of this block. In all your example, this is the case.
