### ISSUE TITLE
Allow UA to resume AudioContext as a side effect of start()

### ISSUE THREAD

**Issue by mounirlamouri** [WebAudio/web-audio-api#1771]
**Describe the feature**
As part of the changes coming from https://github.com/WebAudio/web-audio-api/issues/836 Web Audio received a notion of autoplay. An AudioContext may not switch to `running` state if the UA decides so. During the F2F discussions at TPAC 2 years ago the WG decided to not allow the UA to resume the AudioContext as a side effect of calling `start()` (which Safari iOS does). Chrome has now decided to launch this and it may make sense to integrate this option in the specification to avoid future implementer to run into the same problems.

**Is there a prototype?**
Safari iOS implements this. Chrome has this implemented behind a flag.

**Describe the feature in more detail**
When `start()` is called, if the AudioContext is allowed to run and was prevented from running by the UA previously, the UA could decide to resume it.

**Comment by padenot** [comment]
This was agreed upon during TPAC 2018 in Lyon. I'll have a look at the PR shortly.

**Comment by svgeesus** [comment]
ping @mounirlamouri we are waiting for your response before landing the PR

**Comment by mounirlamouri** [comment]
Thanks for the ping. I have replied.

**Comment by rtoy** [comment]
Is there anything that still needs to be done here?  The PR for this was closed and the current draft says `start()` can resume the context: https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-start

**Comment by mounirlamouri** [comment]
I guess not

**Comment by rtoy** [comment]
Thanks for the update!

Closing.
