### ISSUE TITLE
Specification is incomplete for AudioNode.connect()

### ISSUE THREAD

**Issue by realh** [WebAudio/web-audio-api#1797]
**Describe the issue**
The spec is explicit about what happens if you connect the same output to multiple different inputs or the same output to the same input multiple times, but it doesn't say what happens if you try to connect multiple different outputs to the same input.

**Where Is It**
https://www.w3.org/TR/webaudio/#dom-audionode-connect

**Additional Information**
I would like to know if this could provide a simple way to mix multiple stereo signals into one stereo destination. Otherwise it doesn't seem possible to perform such a simple function in WebAudio without a potentially complex chain of splitters, mergers and gain nodes, or by using a custom processor, where the API is currently in an awkward state of transition from ScriptProcessorNode to AudioWorkletNode.

**Comment by realh** [comment]
Thanks for the quick answer, that's really helped me out. Perhaps you could change this to a feature request for adding a link to section 5 in the documentation for AudioNode.connect()?

**Comment by rtoy** [comment]
Yes, we should make it easier to find these things.  I'm leaving this bug open (and not a feature request) for further review.

**Comment by mdjp** [comment]
Resolve to add a link to section 5 as suggested.
