### ISSUE TITLE
clarify tail-time of DynamicsCompressorNode

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1799]
**Describe the issue**

The [property table](https://webaudio.github.io/web-audio-api/#dynamicscompressornode) and the [algorithm of the DynamicsCompressorNode](https://webaudio.github.io/web-audio-api/#DynamicsCompressorOptions-processing) mention that it has a fixed look-ahead. However it is not really mentioned how large that look-ahead is. The explanation which describes the internal graph shows a DelayNode with a delayTime of 0.006 seconds but the look-ahead seems to be 264 samples instead which is nearly 0.006 seconds, but only at 44100 Hz.

**Where Is It**

https://webaudio.github.io/web-audio-api/#dynamicscompressornode
https://webaudio.github.io/web-audio-api/#DynamicsCompressorOptions-processing

**Additional Information**

I made some quick tests to see what the look-ahead of the current implementations is. At 44100 Hz the look-ahead seems to be 264 samples which is more or less 0.006 seconds and is conforming to the spec. However when I change the sampleRate (by using an OfflineAudioContext) both Chrome and Firefox do still have a look-ahead of 264 samples no matter how many seconds that would be. I'm not sure if that means that the current implementations in Chrome and Firefox are incorrect or if the description of the internal graph just shows the processing of an AudioContext at 44100 Hz. If that's the case, I think adding a sentence which clarifies that could be helpful.

**Comment by hoch** [comment]
So it's "fixed" in terms of the number of sample frames (264 sample-frames). Would that be good enough for the fix?

**Comment by chrisguttandin** [comment]
Hi @hoch, thanks for having a look at this.

If you're asking for my opinion, then I would say that it would be helpful to mention the number of samples used for the look ahead.

Out of curiosity, do you know why the look ahead is 264 samples long and not 256? I don't think that one is better than the other. I just wonder because everything else is a multiple of the render quantum.

**Comment by hoch** [comment]
This is tricky.

1. I don't think it's a good idea to specify the number of samples that seems arbitrary.
2. However, not specifying the exact number will lead to the interop issue (and UA sniffing)
3. This is the number somehow the initial implementor ended up with, so this arbitrary number can be a burden when others try to implement the feature based on the spec.

Given the controversial history of the compressor spec work, it will be hard to justify why it should (must) be 264 sample-frames. I suggest WG needs to talk about this.

**Comment by padenot** [comment]
@chrisguttandin, can you share your code? The code clearly uses 0.006 seconds, there is no hard coding.

**Comment by chrisguttandin** [comment]
Hi @padenot,

I'm sorry I should have included the code in the first place.

I can't reproduce it and therefore I think I probably made a mistake which lead to the wrong conclusion. Please feel free to close the issue.

**Comment by hoch** [comment]
Then perhaps specifying 6ms of look-ahead on the spec is necessary?

**Comment by chrisguttandin** [comment]
Just for reference, this is the code I used to determine the delay. It always produces a value close to 0.006 seconds in Chrome and Firefox.

```javascript
const analyzeDelay = async (sampleRate) => {
    const length = 500;
    const offlineAudioContext = new OfflineAudioContext({ length, sampleRate });
    const audioBuffer = new AudioBuffer({ length, sampleRate });
    const channelData = new Float32Array(length);

    channelData.fill(1);

    audioBuffer.copyToChannel(channelData, 0);

    const audioBufferSourceNode = new AudioBufferSourceNode(offlineAudioContext, { buffer: audioBuffer });
    const dynamicsCompressorNode = new DynamicsCompressorNode(offlineAudioContext);

    audioBufferSourceNode
        .connect(dynamicsCompressorNode)
        .connect(offlineAudioContext.destination);

    audioBufferSourceNode.start(0);

    const renderedBuffer = await offlineAudioContext.startRendering();
    
    renderedBuffer.copyFromChannel(channelData, 0);

    for (i = 0; i < length; i += 1) {
        if (channelData[i] !== 0) {
            console.log(`delay ${ i / sampleRate }`);

            break;
        }
    }
};
```

**Comment by padenot** [comment]
I'm running it like this:

```js
for (var i = 16000; i < 96000; i++) {
  analyzeDelay(i);
}
```

in Firefox and Chrome, and I see that it's always very close to 0.006s.

I'm closing this, but thanks for the report

**Comment by hoch** [comment]
We have not resolved this yet. Do we need to put 0.006s in the spec? I think it's not ideal, but necessary.

**Comment by padenot** [comment]
It's been in the spec since I specced `DynamicsCompressorNode`.

I think searching for 0.006 is the easiest way to find it.
