### ISSUE TITLE
View-taking methods on AnalyserNode need to obtain a reference to the bytes

### ISSUE THREAD

**Issue by annevk** [WebAudio/web-audio-api#1804]
Getting a reference to the bytes might fail and throw (e.g., if the buffer is detached). Not defining this (and perhaps not testing this) might lead to security issues.

https://webaudio.github.io/web-audio-api/#analysernode
https://heycam.github.io/webidl/#dfn-get-buffer-source-reference

(Somewhat unfortunate it's not AnalyzerNode, but I guess that was noticed too late somehow?)

**Comment by annevk** [comment]
Note that the throwing is likely purely theoretical, due to ECMAScript not aligning with reality in implementations. So I probably stated the issue too strongly, but it's still worth being explicit how the bytes are obtained by referencing IDL.

https://github.com/heycam/webidl/pull/604 and https://github.com/heycam/webidl/pull/605 will likely land and remove all throwing and instead result in the empty byte sequence for detached buffers.

**Comment by hoch** [comment]
By "getting a reference", you mean these methods?

```webidl
void getFloatFrequencyData (Float32Array array);
void getByteFrequencyData (Uint8Array array);
void getFloatTimeDomainData (Float32Array array);
void getByteTimeDomainData (Uint8Array array);
```

The reference array must be created before you can pass it to them. Perhaps I am confused, but these functions do not give out the reference. It must be created by user.

Could you elaborate a bit more?

**Comment by annevk** [comment]
You need to use the algorithms defined by IDL (linked in OP) to get a reference to (or copy of) the actual bytes provided by the views that are passed as arguments to those methods.
