### ISSUE TITLE
Exception ordering on error

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1805]
This was found by @pehrsons when he was reviewing the patches for `MediaStreamTrackAudioSourceNode` in Gecko.

A instantiation of this `AudioNode` can fail for two reasons: either it's being created on an `OfflineAudioContext`, or the `MediaStreamTrack` passed in is not an audio track.

We should define the order in which we check both requirements.

I propose checking the context type first, and then the track type, to follow the order of the formal parameter.

Surely there are other occurrences of this pattern. Sometimes, we use an algorithm, which makes things very clear,  though, maybe we should do that more often.

**Comment by hoch** [comment]
Agreed. The context type first and then node-specific options. At least for all the "media" nodes.
