### ISSUE TITLE
Typos in audioWorklet examples

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#1809]
example12   BypassProcessor
  class BypassProcessor
  There is an extra closing parenthesis

example 16   BitCrusher
  need definition @ line 30:
  const bitDepth = parameters.bitDepth;
  const frequencyReduction = parameters.frequencyReduction;

example 19   VU Meter
  line 4 Oscillator => OscillatorNode

**Comment by padenot** [comment]
Fixed in https://github.com/WebAudio/web-audio-api/commit/615bbec0811f4bc05ba18b8618d895ca29cde64f, directly pushed to master as it was non-controversial.

Thanks for the report!
