### ISSUE TITLE
Multiple events at the same time

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1815]
In https://webaudio.github.io/web-audio-api/#AudioParam, paragraph 9 (after the list of events), we describe how events are inserted.

Compare that with https://www.w3.org/TR/2013/WD-webaudio-20131010/#methodsandparams-AudioParam.  We've lost this text:

- If one of these events is added at a time where there is already an event of the exact same type, then the new event will replace the old one.
- If one of these events is added at a time where there is already one or more events of a different type, then it will be placed in the list after them, but before events whose times are after the event.

I think this is how browsers currently handle this.  We should put this text back.

**Comment by rtoy** [comment]
Noticed this when reviewing #1796.  This implies there may be more than one "current" event.

**Comment by rtoy** [comment]
Hmm. Chrome (beta) and Firefox (nightly) behave differently.  Visit hoch.github.io/canopy and run this snippet:
```
// @channels 1
// @duration 1.0
// @sampleRate 44100

var osc = new ConstantSourceNode(context);
var gain = context.createGain();

osc.offset.setValueAtTime(0.1, 0);
osc.offset.linearRampToValueAtTime(1, .1)
osc.offset.linearRampToValueAtTime(10, .1)
gain.gain.value = 1;

osc.connect(gain).connect(context.destination);

osc.start();
```

Chrome produces a linear ramp up to 10 at time 0.1.  Firefox does a linear ramp up to 1 and then jumps instantly to 10 at time 0.1.

I don't recall any issue where we explicitly removed this sentence, so I'm restoring it.  But maybe some one remembers why?

**Comment by padenot** [comment]
> I think this is how browsers currently handle this. We should put this text back.

This is unfortunate, we've updated Gecko already in [bug 1308436](https://bugzilla.mozilla.org/show_bug.cgi?id=1308436).

**Comment by padenot** [comment]
I can probably restore the old behaviour though, but I might have updated some WPTs, I'll need to check.

**Comment by rtoy** [comment]
Not sure what to do, but I don't remember any issue or any other reason why we removed this.  Do you recall anything?

If not, then I'm inclined to say it was accidentally removed during the bikeshed conversion (total guess).

**Comment by padenot** [comment]
That'd be my guess as well.

iirc, when I did some fixes to `AudioParam` insertion in Gecko this summer, I double checked and it was not what I was expecting, so I ended up fixing the insertion algorithm. I think Karl found that during the code review even.

Can we find out which commit changed the behaviour? I remember trying to do this, and it got complicated because the history was not too clean, full of merge commits somehow, caused by the bikeshed changes.

In any case I'm open to revert Gecko's behaviour.

**Comment by rtoy** [comment]
`git bisect` says [f24afd21973bde3cafc3b9edd621eb767379aecb] removed this text.

I don't know what caused that to be applied; there's no reference to an issue or what.

**Comment by karlt** [comment]
Thank you @rtoy for finding the changeset.  (The github UI displaying the commit links to the pull request, just below the summary, though I recall not being able to find the link in some other commits for some reason).

The WG resolution to remove the special case for events of "the exact same type" was recorded at https://github.com/WebAudio/web-audio-api/issues/573#issuecomment-151032325

If restoring the special case, which seems unnecessary to me, then some care may be required regarding setValueCurveAtTime's "implicit call to setValueAtTime()" with time T_0+T_D, as the durations may differ.

**Comment by rtoy** [comment]
Ah, thanks for finding the resolution!  So chrome is wrong here and we need to fix it.

And this is a reminder to everyone:  Please, please, please make sure every pull request has an associated issue to go with it.  And reviewers, please make sure there's an associated issue!  Of course silly little typos don't need this, but any kind of change in behavior really should.

I'm satisfied with this, and am closing this bug as working as intended.
