### ISSUE TITLE
Minor typos in code snippet titled Example 18

### ISSUE THREAD

**Issue by dorontal** [WebAudio/web-audio-api#1819]
**Minor typos in code snippet titled Example 18**

Hello,

I haven't run the code in Example 18 of the document https://www.w3.org/TR/webaudio/, but it seems to have two minor typos there that, if fixed, could prevent some programmer frustrations:

1) In example 18, line 8 - the line that goes:
   ```
   this._nextUpdateFrames = this.interval;
   ```
   I think you meant
   ```
   this._nextUpdateFrames = this._updatingInterval;
   ```
   right? Because there is no reference to any `this.interval` anywhere else in the code but 
   `this._updatingInterval` is all over the place and that correction also makes sense functionally.

2) Similarly, in example 18, I think
   ```
   this._volume
   ```
   should be used (in two places) instead of
   ```
   this.volume 
   ```

**Where Is It**
Example 18 - code snippet in the document

**Additional Information**
#1809 is not a duplicate despite the similar title.

**Comment by padenot** [comment]
I fixed this in 499c01016be117e, thanks a lot for the report!
