### ISSUE TITLE
How to ignore Iphone mute switch

### ISSUE THREAD

**Issue by MarsCaiWORD** [WebAudio/web-audio-api#1820]
I want when the iphone mute switch is turned on keep music play
Is there any solution? btw i use web audio api play music

iphone 6
QQ browser

 for example[ like this website use web audio api play music ](https://www.createjs.com/tutorials/SoundJS%20and%20PreloadJS/internalPreloading.html)
when i use QQ browser open this website and turn on iphone mute switch , is mute , but i want unmute , btw other browser is working ex. chrome , native browser

**Comment by padenot** [comment]
This is not a support forum, but the repository for the specification. Please ask you question on [StackOverflow](https://stackoverflow.com/questions/tagged/web-audio).
