### ISSUE TITLE
MediaStreamAudioSourceNode can't have no valid audio track

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1824]
**Describe the issue**
I noticed that there is a little conflict in the description of the MediaStreamAudioSourceNode.

The general description says: "If there is no valid audio track, then the number of channels output will be one silent channel."

But the algorithm of the constructor says "If the mediaStream member of options does not reference a MediaStream that has at least one MediaStramTrack whose kind attribute has the value "audio", throw an InvalidStateError and abort these steps."

I think the fact that the constructor throws an error when there is no valid track in the given MediaStream eliminates the necessity to describe what happens in there is no valid track.

Is it possible to modify the MediaStream (add/remove tracks) while it is the input of an MediaStreamAudioSourceNode? I think in that case the first sentence makes sense again as a valid track could be present at construction time but might be removed later.

The [MediaStream Recording spec](https://w3c.github.io/mediacapture-record/MediaRecorder.html) does for example explicitly forbid to modify the MediaStream while it is used for recording. Maybe that needs to be added here as well if that's the case. (5.3 of that algorithm https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-start)

There is also a little typo: "MediaStramTrack" should probably be "MediaStreamTrack".

**Where Is It**
https://webaudio.github.io/web-audio-api/#mediastreamaudiosourcenode
https://webaudio.github.io/web-audio-api/#dom-mediastreamaudiosourcenode-mediastreamaudiosourcenode

**Comment by mdjp** [comment]
We will fix the typo but stick with the current behaviour

**Comment by chrisguttandin** [comment]
Hi @mdjp, thanks for having a look at this.

It might be a stupid question but I'm a little lost. What is the current behavior? Am I right that the StreamTracks should only be checked when constructing a MediaStreamAudioSourceNode. Later on the number of channels will adapt if the number StreamTracks of kind 'audio' changes?

If you like, I can create a pull request to fix the typo to save you some time.

**Comment by rtoy** [comment]
From what I remember from the call, we're keeping things as is.  If you construct the node with a MediaStream without any audio tracks, an error is thrown.  If, later on, the track is removed, the output is a single channel of silence.  I believe adding more tracks won't change anything because the node only uses the first track, so all added tracks are ignored.

I guess there's an issue if you add more tracks, then remove the first track.  Is the output now silence? Or is it the output from the "new" "first" track?

**Comment by padenot** [comment]
I'll spec what happens in those cases.
