### ISSUE TITLE
Is there a way to stop Web Audio API decodeAudioData method memory leak?

### ISSUE THREAD

**Issue by sdoherty0** [WebAudio/web-audio-api#1826]
**Describe the issue**
When creating audio buffers using the Web Audio API, there are buffers created by the decodeAudioData method, which reside in memory and are apparently not accessible through JavaScript. They seem to hang around for the entire life of a browser tab, and never get garbage collected. On memory limited devices like Chromecast, this causes huge amounts of memory to accumulate and Chromecast crashes.

I have posted a question about this on SO https://stackoverflow.com/questions/54464571/is-there-a-way-to-stop-web-audio-api-decodeaudiodata-method-memory-leak .

**Where Is It**
https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata 
Once the decodeAudioData (browser implementation dependent) makes its own copy of the input audioData, it never releases it to garbage collection, and is not exposed to Javascript.

**Additional Information**
With the WAA as the only way to play simultaneous audio files on Chromecast, this is a critical issue as all of these smart devices are becoming the mainstream way for people to cast audio from their phones to larger speaker systems and tvs.
Since the decodeAudioData method returns the decoded buffer to the promise or onsucess callback, why is it necessary for a system to maintain any audiobuffers? As you can see in the below code snippet, I don't even make a reference to the returned buffer or ever use it, yet memory fills up with audiobuffers and they are never released until the tab is closed.
```javascript
    function loadBuffer() {
        // create an audio context
        var context = new (window.AudioContext || window.webkitAudioContext)();
    
        // fetch mp3 as an arraybuffer async
        var url = "beep.mp3";
        var request = new XMLHttpRequest();
        request.open("GET", url, true);
        request.responseType = "arraybuffer";
    
        request.onload = function () {
    
            context.decodeAudioData(
                    request.response,
                    function () {// not even passing buffer into this function as a parameter
                        console.log("just got tiny beep file and did nothing with it, and yet there are audio buffers in memory that never seem to be released or gc'd");
                    },
                    function (error) {
                        console.error('decodeAudioData error', error);
                    }
            );
        };

    request.onerror = function () {
        console.log('error loading mp3');
    }
    request.send();
    }
```

**Comment by rtoy** [comment]
This doesn't really appear to be a bug in the spec but in the implementation.  You should file a bug report with the repro case.

**Comment by sdoherty0** [comment]
One reason it could be related to a legacy approach in an older version of the spec, which I'm sorry I can't find the link to, is that decodeAudioData was not allowed to decode the same request.response twice. Therefore implementations would have to keep some copy or hash of that request.response around. The spec does require detachment from the main thread and that it be made unreachable by JS. Since many of the implementers of WAA hang out on this forum, I hoped to also get their attention on this as it seems to be true across most browsers and Chromecast. I have also seen discussions in both chromium and mozilla browser dev forums that the requirement to neuter the input buffer before decoding and copy the buffer to a sub JS browser memory location may lose those buffers in an non gc'd space. In any case this is a big problem across most implementations.

**Comment by sdoherty0** [comment]
For those who may land here with similar audiobuffer problems, I have posted a workaround [here](https://stackoverflow.com/questions/54464571/is-there-a-way-to-stop-web-audio-api-decodeaudiodata-method-memory-leak/54496280#54496280).

**Comment by rtoy** [comment]
Thanks for the additional detail.  I still think it's an issue with the implementations and not the spec. Seems pretty clear that once decoding is done, there's no reason to hang on to the encoded data.  It's up to the implementation to make sure these can be collected.

**Comment by padenot** [comment]
Closing, but make sure to open a bug on the implementation tracker if this is something that shoudn't be needed, thanks!
