### ISSUE TITLE
Scheduled source onended events for OfflineAudioContext?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1828]
Consier this bit of code:
```
c = new OfflineAudioContext(1, 44100, 44100);
s = new OscillatorNode(c);
s.connect(c.destination);
s.start();
s.onended = () => {console.log("Done");}
c.startRendering();
```

Does the onended event for ths oscillator ever get fired?

Didn't find anything about this in AudioScheduledSourceNode.

I guess the event is only fired if there's an explict stop().  For
ABSNs, I guess the event is fired only for an explicit stop, or
grain duration exceeded, or playback of the buffer is finished.

If so, perhaps we should make it a bit more explicit in the spec.

**Comment by padenot** [comment]
If it's not written that it should fire `"ended"`, it should not fire `"ended"`, right?

**Comment by rtoy** [comment]
Fair enough.  But it's always hard to tell if something is not written on  purpose or forgotten by accident.

**Comment by rtoy** [comment]
Teleconf:  Don't need to do anything about this; leave spec as is.
