### ISSUE TITLE
Allowed sample rates for AudioBuffer

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1835]
**Describe the issue**
A clear and concise description of what the problem is in the spec.

If you need help on how to use WebAudio, ask on your favorite forum or consider visiting
the [WebAudio Slack Channel](https://web-audio.slack.com/) (register [here](https://web-audio-slackin.herokuapp.com/)) or
[StackOverflow](https://stackoverflow.com/).

**Where Is It**
Provide a link to where the problem is in the spec

**Additional Information**
Provide any additional information

**Comment by hoch** [comment]
Perhaps a mistake? Closing.
