### ISSUE TITLE
StereoPannerNode can't pan "hard" left/right

### ISSUE THREAD

**Issue by gridsol** [WebAudio/web-audio-api#1840]
**Describe the issue**
With my headphones, I noticed some "bleed" coming through on my right/left ear when I had panned my input left/right, respectively. In other words, even when I hold the hard-panned earphone far away from my head, I am hearing something coming through the other earphone that should be fully panned away from.

I would expect the gain of a channel full panned away from to be 0. I believe the API uses constant-power panning but in any case, the result of hard-panning should be a 0 on the other ear. See:
http://www.cs.cmu.edu/~music/icm-online/readings/panlaws/

The stereo panner example on MDN also exhibits this behavior.
https://mdn.github.io/webaudio-examples/stereo-panner-node/

(Note that, due to the web audio autoplay policies, you may have to go into the console and type "audioCtx.resume()" to actually make the media element work here)

I see this behavior on Opera and Chrome.

**Where Is It**
https://mdn.github.io/webaudio-examples/stereo-panner-node/

**Additional Information**
Windows 7. Sennheiser HD 280 pro headphones.

**Comment by mr21** [comment]
StereoPannerNode moves an audio source around the listener, so when you put the audio source at your right then you will hear the left and right channels comming from the right.

I had the same problem and after asking on the webaudio slack i ended up doing a little encapsulation around a channelSplitterNode

**Comment by gridsol** [comment]
Then I'll mark it as closed if working as intended. Mind sharing any resources on that second case, however? That happens to also be what I'm after.

**Comment by mr21** [comment]
Yes, here:
https://github.com/gridsound/gs-webaudio-library/blob/master/gswaStereoPanner/gswaStereoPanner.js

**Comment by gridsol** [comment]
Thank you.

**Comment by rtoy** [comment]
Firstly, thanks for the excellent and detailed report!

I'm pretty sure the `StereoPannerNode` implements the constant power panning as mentioned in http://www.cs.cmu.edu/~music/icm-online/readings/panlaws/

If you pan full left, you should only get sounds from the left.  If this is not the case for you, you should file a bug against the browser you're using.

**Comment by rtoy** [comment]
Oops.  That's true for mono sources.  Stereo sources do something different.  And the referenced doc seems to be just talking about panning a mono source to a stereo output.  It doesn't discuss panning stereo sources.
