### ISSUE TITLE
Parameter values used for BiquadFilterNode::getFrequencyResponse

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1851]
[getFrequencyResponse](https://webaudio.github.io/web-audio-api/#dom-biquadfilternode-getfrequencyresponse) says:

> Given the current filter parameter settings, synchronously calculates the frequency response for the specified frequencies

What exactly are the "current filter parameter settings"?  Is this just the intrinsic value of the associated `AudioParam`s?  Or should it be the [computedValue](https://webaudio.github.io/web-audio-api/#computedvalue)?

I think to be useful it should be the computed value.  Consider feeding an oscillator to the `detune` parameter.  This could have a very large effect on the response which wouldn't be reflected if we just used the intrinsic value.

**Comment by padenot** [comment]
I think this should be in line with the value getter for the `AudioParam`, it's essentially an fancy version of that, as in, use the intrinsic value of the `AudioParam`.

**Comment by rtoy** [comment]
Yeah. I think it should be the intrinsic value(s) that should be used for computing the response. I see the man (only?) use-case is for graphing the response for information purposes (equalizers) and not for anything else.

Just need to add a few words to say it's the intrinsic value, I think.
