### ISSUE TITLE
Fix error condition of AudioNode.disconnect(destinationNode, output, input)

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1852]
**Describe the issue**
The disconnect() method of an AudioNode usually should throw an error when it gets asked to disconnect something which is not connected. But I think the error condition for the `destinationNode` parameter in the `AudioNode.disconnect(destinationNode, output, input)` signature is a bit too unspecific. It currently says: "If there is no connection to the destinationNode from the given output, an InvalidAccessError exception MUST be thrown." With that in mind the following would not throw an error.

```javascript
const audioContext = new AudioContext();
const channelMergeNode = new ChannelMergerNode(audioContext, { numberOfInputs: 10 })
const channelSplitterNode = new ChannelSplitterNode(audioContext, { numberOfOutputs: 10 })

channelSplitterNode.connect(channelMergeNode, 3, 6);
channelSplitterNode.disconnect(channelMergeNode, 3, 8);
```
There is a connection from the destinationNode (the channelMergeNode in this case) from the given output. This connection is a connection to a different input but this is not part of the error condition. I think this is an oversight.

**Where Is It**
https://webaudio.github.io/web-audio-api/#dom-audionode-disconnect-destinationnode-output-input

**Additional Information**
Chrome is throwing an error when executing the code above. `DOMException: Failed to execute 'disconnect' on 'AudioNode': output (3) is not connected to the input (8) of the destination.`. Firefox is throwing an error as well, although it is a little cryptic: `InvalidAccessError: A parameter or an operation is not supported by the underlying object`

I would suggest to extend the description of the error case by mentioning the input: "If there is no connection to the destinationNode from the given output to the given input, an InvalidAccessError exception MUST be thrown."

**Comment by rtoy** [comment]
Makes sense to me.
