### ISSUE TITLE
Inconsistent use of node name to processor definition map

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#1854]
The second algorithm of
https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor has:

> 3. Let processorConstructor be the result of looking up nodeName on the AudioWorkletGlobalScope's node name to processor definition map.
>
> 4. If processorConstructor is undefined, throw a NotSupportedError DOMException.

The the result of the lookup is an "AudioWorkletProcessor definition", from https://webaudio.github.io/web-audio-api/#dom-audioworkletglobalscope-registerprocessor

> 9. Let definition be a new AudioWorkletProcessor definition with:
>    * node name being name
>    * processor class constructor being processorCtor

It seems that step 3 wants to select the "processor class constructor" field.

However, the "node name" field is not used, and so I suggest removing step 9 and replacing other mentions of "definition" with "processorCtr" in a "node name to processor constructor map".

I don't know what might see a NotSupportedError DOMException if thrown, but
processorConstructor will not be undefined at step 4, as provided by the 
first algorithm of https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor

> 2. If nodeName does not exists [sic] as a key in the BaseAudioContext’s node name to parameter descriptor map, throw a NotSupportedError exception and abort these steps.

and https://webaudio.github.io/web-audio-api/#dom-audioworkletglobalscope-registerprocessor

> 3. If the result of IsConstructor(argument=processorCtor) is false, throw a TypeError and abort these steps.

This has also been observed by the authors of Chrome's implementation:
https://chromium.googlesource.com/chromium/src/+/5e0ddb247eb5ed5f358a9d5cace2b8bf75e68b2e/third_party/blink/renderer/modules/webaudio/audio_worklet_global_scope.cc#131

I suggest removing step 4.

**Comment by rtoy** [comment]
@hoch, can you take a look?  Assigning to you for now.
