### ISSUE TITLE
createScriptProcessor parameter requirements

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1855]
There's an issue with the parameter descriptions in [createScriptProcessor](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-createscriptprocessor).

Both `numberOfInputChannels` and `numberOfOutputChannels` are optional, but the description doesn't say what the default value would be.  It should be specified.  I think the default is 1, but I couldn't find that anywhere in the spec.

**Comment by rtoy** [comment]
Oops.  The default counts are 2 in Chrome.  The default channel counts are almost always stereo.

**Comment by karlt** [comment]
2 is consistent with the webidl at https://webaudio.github.io/web-audio-api/#BaseAudioContext thanks.

**Comment by hoch** [comment]
Sort of irrelevant, but a question: should ScriptProcessorNode still be a part of the spec when it goes to REC?

**Comment by rtoy** [comment]
Yes. It's deprecated, not removed.  If you remove it, then every browser that implements it is wrong.
