### ISSUE TITLE
out-of-bound(s) spelling

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1860]
**Describe the issue**
It noticed a little disparity in the spelling of out-of-bound(s) throughout the spec. But I'm not sure which is the correct version.

In various places the spec says "If this parameter is out-of-bound, ..." and "If the parameter is out-of-bound, ..." but it also sometimes uses the same phrase with an extra "s" like this "If this parameter is out-of-bounds, ...".

As I already said I don't know which version is the correct one or if there is actually a right or wrong way of spelling out-of-bound(s) at all. Maybe both are correct.

**Where Is It**
https://webaudio.github.io/web-audio-api/#dom-audionode-connect
https://webaudio.github.io/web-audio-api/#dom-audionode-connect-destinationparam-output

https://webaudio.github.io/web-audio-api/#dom-audionode-disconnect-output
https://webaudio.github.io/web-audio-api/#dom-audionode-disconnect-destinationnode-output
https://webaudio.github.io/web-audio-api/#dom-audionode-disconnect-destinationnode-output-input
https://webaudio.github.io/web-audio-api/#dom-audionode-disconnect-destinationparam-output

**Additional Information**
I know that this is only a minor issue (if it is an issue at all). Please feel free to ignore it.

In case anyone wonders why I spotted this at all, I wanted to use the phrase and wasn't sure about the spelling. I knew that it is used in the Web Audio spec and that's why I looked it up here. I was surprised to find two different spellings.

**Comment by rtoy** [comment]
Any and all typos, grammatical errors, inconsistencies should be fixed.  It's embarrassing to have such obvious mistakes.

According to https://www.merriam-webster.com and https://dictionary.cambridge.org, it is "out-of-bounds" or possibly without the hypens.

**Comment by hoch** [comment]
Simple typos; any volunteers? :)

**Comment by chrisguttandin** [comment]
Since I was the one who reported this I would of course be happy to create a PR, but I guess that's not possible anymore, right?

**Comment by rtoy** [comment]
Over the last week, we've been fixing typos and phrasing issues.  I personally think typos can be fixed at any time since they don't change the meaning of the spec (usually). Fixing these misspellings will only make the spec better and won't change the meaning.
