### ISSUE TITLE
Add tests for ArrayBuffer detaching that throws and account for it in prose

### ISSUE THREAD

**Issue by annevk** [WebAudio/web-audio-api#1861]
As per https://github.com/whatwg/html/issues/4601 DetachArrayBuffer can throw. There should be tests that this is handled adequately for all affected APIs (seem to be at least two from super quick skimming) and prose might need to be adjusted to indicate this is a thing. You might want to look at HTML for how this is handled.

Or perhaps IDL should be updated to handle this better somehow, not sure, but if so, comment at https://github.com/heycam/webidl/issues/724.

**Comment by padenot** [comment]
I've done related work in the past, taking this.

**Comment by rtoy** [comment]
Text needs to be updated for v1.  Setting milestone to v1 for that.

**Comment by hoch** [comment]
For example, the step 2 of the algorithm for `decodeAudioData(audioData, successCallback, errorCallback)` we can capture the internal exception for an undetachable array and throw an error in the step 3.

**Comment by hoch** [comment]
For the `acquiring the content` procedure, we don't need to do anything because AudioBuffer's back-end ArrayBuffer is guaranteed to be detachable.

**Comment by annevk** [comment]
Guaranteed **not** to be detachable I take it?

**Comment by padenot** [comment]
No, this was correct:
- an AudioBuffer can _only_ be instantiated using `new AudioBuffer(...);` or `AudioContext.createBuffer(...);`, this _always_ allocate a normal ArrayBuffer ;
- This means that detaching cannot throw: either it's been detached already, and the operation returns false, or it worked, and it returns true.

**Comment by padenot** [comment]
Fixed by #1961.
