### ISSUE TITLE
Confusion on the algorithm for AudioContext.close()?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1864]
In the algorithm for [close](https://webaudio.github.io/web-audio-api/#dom-audiocontext-close), step 2 says abort if the control thread state is closed.  Step 3 says if the AudioContext.state is already "closed", resolve promise and return it.

But step 4 says to set the control thread state to closed.  So for the first call to `close`, step 3 does nothing.  The second call to `close` never reaches step 3 because step 2 sees that control thread state flag is closed.

Also, step 5 says to queue a control message to the AudioContext. Prsumably, this is referring to running a control message to close the context.  Step 5 should probably say that, otherwise, the following algorithm seems to be just dangling.

**Comment by hoch** [comment]
The current algorithm look okay as is. Closing.
