### ISSUE TITLE
Context "control thread state" and "rendering thread state"

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1865]
In many of the algorithms related to creating/suspending/resuming a BaseAudioContext, references are made to "control thread state" and "rendering thread state".  Perhaps instead of write `<code>control thread state</code>`, we should make these internal slots of the context?

But perhaps it's too late to do this for V1?

**Comment by hoch** [comment]
Define control thread state and rendering thread state as internal slots in the BaseAudioContext.

**Comment by hoch** [comment]
I think it is better to put in 2.2. It's a bit later in the spec, but this is a technical/implementation detail and not exposed via JS API.
