### ISSUE TITLE
References to garbage collection

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1866]
In [OfflineAudioContext.startRendering](https://webaudio.github.io/web-audio-api/#dom-offlineaudiocontext-startrendering), the first sentence says something about garbage collection.  Maybe this should be removed?  It's up to the system to make sure everything happens so that GC is not observable.

[decodeAudioData](https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata) mentions GC too.

**Comment by hoch** [comment]
Let's remove everything!
