### ISSUE TITLE
OfflineAudioContext.startRendering algorithm should reference suspend algorithm?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1867]
In [OfflineAudioContext.startRendering()](https://webaudio.github.io/web-audio-api/#begin-offline-rendering) algorithm step 2 says to suspend rendering if necessary.  This should probably link to the some kind of suspend algorithm. `OfflineAudioContext.suspend()` doesn't have an algorithm but the algorithm for `AudioContext.suspend()` isn't quite right because this method doesn't take an time argument.

Maybe we need to write a slightly updated algorithm for this?

**Comment by hoch** [comment]
I think startRendering() algorithm pointing to suspend() method is okay. The question here is whether we need to specify an algorithm suspend() or not.

**Comment by hoch** [comment]
Add a link to the suspend method.
