### ISSUE TITLE
OfflineAudioContext.resume algorithm looks funny

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1868]
The algorithm for [OfflineAudioContext.resume()](https://webaudio.github.io/web-audio-api/#dom-offlineaudiocontext-resume) looks kind of funny.  There are steps 1-5, but in between step 2 and 3 is a separate paragraph that reads as if it should be part of the algorithm---basically as step 2.5.

**Comment by hoch** [comment]
If we specify the algorithm of suspend(), like based on Chrome's impl, then we also need to fully specify the algorithm of resume() as a counterpart.

I am just pointing out the work to be done. Also I am curious how FireFox will address the lack of these features. I feel like OAC's suspend and resume are in limbo now.

**Comment by rtoy** [comment]
What? I'm only saying the existing algorithm for oac resume() looks funny.  That oac suspend has no algorithm is a different issue (roughly captured in #1867).

**Comment by rtoy** [comment]
For the record commit [eb612fab7cf54] introduced this to fix #1738. I think it's just a typo.  I think that paragraph just needs to be deleted. It's basically covered in step 2.
