### ISSUE TITLE
AudioBuffer interface comments

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1869]
The intro paragraph for [AudioBuffer](https://webaudio.github.io/web-audio-api/#AudioBuffer) says

> memory-resident audio asset (for one-shot sounds and other short
> audio clips).

I don't think we say anything about one-shot sounds or short audio
clips.  We're only constrained by how much memory you want to use.

**Comment by hoch** [comment]
we "should" say, you mean?

**Comment by rtoy** [comment]
Basically, just remove the parenthetical part about one-shot sounds and short clips.

**Comment by hoch** [comment]
Let's remove the text in the parentheses.
