### ISSUE TITLE
AudioNode "block-size" should probably be "render quantum"

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1870]
Section [AudioNode Interface](https://webaudio.github.io/web-audio-api/#audionode) paragraph 7 mentions "block-size":

> processing a fixed number of sample-frames of size block-size. In
> order to get uniform behavior across implementations, we will define
> this value explicitly. block-size is defined to be 128 sample-frames

Instead of "block-size", this should probably refer to "render quantum size", which is defined in https://webaudio.github.io/web-audio-api/#render-quantum-size.

**Comment by hoch** [comment]
FWIW, we've been using "render quantum" a lot, but actually the term "block size" is much more common in the similar area or project.

**Comment by rtoy** [comment]
I don't really care if it's block-size or render quantum.  But we should be consistent, especially here because we say we process in size block-size.  We should make the connection between the two explicit.  Otherwise, it's hard to tell when "block-size" is used and when "render quantum size" is used, even if they have the same value.  (Important if we ever remove the constraint of 128 frames.)

**Comment by hoch** [comment]
Let's delete the paragraph. ("For performance reasons, ...") It doesn't add any value and we have a dedicated section for render quantum.
