### ISSUE TITLE
ABSN playback algorithm offset 

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1879]
In the [ABSN playback section](https://webaudio.github.io/web-audio-api/#playback-AudioBufferSourceNode), the first paragraph says

> the following factors working in combination, which can vary dynamically during playback:

>    * A starting offset, which can expressed with sub-sample precision.

It's not really clear, but I think this "offset" is the offset parameter in `start(when, offset, duration)`.  So it's not dynamically varying.  Perhaps the paragraph should be rephrased and just mention that loop points and the playback rate are (obviously) dynamically changeable during playback.

**Comment by hoch** [comment]
Move "which can vary dynamically during playback" part to the second bullet point.
