### ISSUE TITLE
Internal slot [[input track]] defined but not used

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1889]
In the MediaStreamAudioSourceNode [constructor](https://webaudio.github.io/web-audio-api/#MediaStreamAudioSourceNode-constructors), in step 6, `[[input track]]` is defined.  But as far as I can tell it's never used.

We should either use it somewhere or remove any mention of this internal slot.

**Comment by hoch** [comment]
I believe @padenot wrote this part. Can you look at this, @padenot?

**Comment by padenot** [comment]
Closed by #1958.
