### ISSUE TITLE
Missing synchronous markers

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1899]
In many parts of the spec, we use a synchrnous marker (looks kind of like an hour glass) when we say an error must be thrown.  However, there are parts in the spec where we throw errors, but don't include this.

We should probably update all the places to use this.  Or remove them everywhere.  We should be consistent.

One such place is https://webaudio.github.io/web-audio-api/#dom-audioworkletnodeoptions-outputchannelcount

**Comment by padenot** [comment]
This is now fixed and merged. Thanks @scottlow!
