### ISSUE TITLE
AudioWorkletProcessor NewTarget undefined

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1900]
In [AudioWorkletProcessor constructor](https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-audioworkletprocessor), the first step of the algorithm mentions `NewTarget`.  This isn't defined, and I assume it comes from things related to an active function object.

Perhaps we should link to the appropriate part of ecmascript for this?

**Comment by hoch** [comment]
The closest section from ECMAScript spec is: https://www.ecma-international.org/ecma-262/6.0/#sec-built-in-function-objects
