### ISSUE TITLE
AudioWorkletNode state property?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1901]
In [process()](https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-process), the third paragraph says:

> ...update the corresponding AudioWorkletNode's state property accordingly.

I couldn't find the state property.  So we either need to add one, or add a link to this property so that it can be easily found.

**Comment by hoch** [comment]
Nice catch! `state` doesn't exist anymore so we can remove the sentence.
