### ISSUE TITLE
Funny sentence about priority and latency

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1903]
The last sentence of the first paragraph in [processing model background](https://webaudio.github.io/web-audio-api/#processing-model-background) says

> This means that a program that deals with audio only executes code from this callback, as any buffering between a rendering thread and the callback would naturally add latency or make the system less resilient to glitches.

The first part of the sentence talks about the callback, but the second part suddenly talks about buffering and latency.  I don't see the connection here.

I also don't quite see how this should be rephrased.

**Comment by padenot** [comment]
`2.1` will be marked as non-normative, as it is "just" background info.

**Comment by padenot** [comment]
Closed by #1952.
