### ISSUE TITLE
Strange Note in algorithm for swapping a control message queue

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1904]
In the algorithm for swapping a control message queues in [Section 2.2](https://webaudio.github.io/web-audio-api/#control-thread-and-rendering-thread) at the end of the section has a note adding a control message to the queue from starting an ABSN.

Not sure how that is related to swapping message queues.

If nothing else, the note needs to be moved outside of the algorithm box.

**Comment by rtoy** [comment]
Move note to Queueing a control message.

**Comment by padenot** [comment]
Closed by #1952.
