### ISSUE TITLE
Steps in rendering algorithm

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1906]
Let's look at the [rendering algorithm](https://webaudio.github.io/web-audio-api/#rendering-loop).

Step 3.2.1 says `ordered node list` is an empty list (that will have stuff).

Step 3.2.8 says that `ordered node list` is an empty list.  This is rundandant.

Step 3.2.9 mentions "unmarked" elements.  This isn't really defined and only becomes clear when you read substeps of 3.2.9 about visiting and marking a node.  Not sure what to do here, if anything.

**Comment by rtoy** [comment]
Leave this to @padenot's discretion.

**Comment by padenot** [comment]
Addressed by @scottlow in #1950, thanks!
