### ISSUE TITLE
More AudioWorklet editorial items

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1907]
In the note at the end of [BitCrusher example](https://webaudio.github.io/web-audio-api/#the-bitcrusher-node) there's the phrase:

> ...uses JavaScript’s return-override feature,

Maybe link to this "return-override" feature somewhere? (Or not?)

In the [instantion algorithm](https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor) step 9.3 uses this arrow notation.  Without context, it's a little hard to know that it's really saying to look at the key-value pair in the options dictionary.  May be add "key value pair" or something?

Also, the `option` variable in the algorithm is "defined" in step 7. I believe it really refers to the `options` paraemeter for the AudioWorkletNode constructor.  So maybe have a step 1.5 (or 0.5) that says something like

```
  1.5 Let `<var>options</var>` be the `<bs-link-to>options</bs-link-to>` parameter of the constructor.
```

**Comment by hoch** [comment]
1.  "return-override" feature

This means the user-supplied constructor has an explicit return value that is not `this`. We can use the expanded description like this if needed. But I am on the fence because this is more of ES6 class's story.

2. The arrow notation for key-value pair

> For each paramNameInOption → value of options:

We can re-write this to "For each key-value pair of `paramNameInOption` to `value` in `options`".

3. I am not sure what you're  referring to. `options` in the step 7 is from the constructor parameter of AudioWorkletNode. I think this is fine as is.

**Comment by rtoy** [comment]
We don't have to change anything, but for 1) it would be nice just to point to something relevant in ES6 if possible.

For 2) I think your proposal is nice since we don't use that key-value arrow notation anywhere else.

For 3), if you click on "options" in the algorithm, it highlights two uses.  None of the relate to the options parameter of the constructor.  This can be fixed by just writing an extra sentence like:

```
Let <var>options</var> be {{AudioWorkletNode/AudioWorkletNode()/options!argument}}
```
(Not sure about the bs link, I think you get the idea.

**Comment by hoch** [comment]
Then we have the same issue with `nodeName`. It's properly defined in the algorithm, but Bikeshed does not recognize this as a defined argument. I really rather not touch this from our side.

**Comment by rtoy** [comment]
I don't think bikeshed should magically do that because it will surely get it wrong.  It's up to us to link all the things appropriately.  (There are other areas where bikeshed could correctly link things but doesn't.)

**Comment by rtoy** [comment]
I think it's nice to make the connection explicit rather than implied, but I'm not going to require it.
