### ISSUE TITLE
AudioBuffer.copyToChannel/copyFromChannel() off-by-one error

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#1914]
**Describe the issue**
I think the error condition for the `copyToChannel()` and `copyFromChannel()` methods of an AudioBuffer contains a subtle error. The description of the the `startInChannel` parameter says: "If startInChannel is greater than the length of the AudioBuffer, an IndexSizeError MUST be thrown." But I think it should say "If startInChannel is greater than ***or equal to*** the length of the AudioBuffer, an IndexSizeError MUST be thrown."

Interestingly Chrome already implements it that way. Whereas the Developer Edition of Firefox (currently v68) implements it as the spec describes it.

```js
const audioBuffer = new AudioBuffer({ length: 10, sampleRate: 44100 });
const channelData = new Float32Array(10);

// This will work in both browsers.
audioBuffer.copyToChannel(channelData, 0, 9);
// This will only work in Firefox v68
audioBuffer.copyToChannel(channelData, 0, 10);
// This will not work in both browsers.
audioBuffer.copyToChannel(channelData, 0, 11);
```

**Where Is It**
https://webaudio.github.io/web-audio-api/#dom-audiobuffer-copyfromchannel-startinchannel
https://webaudio.github.io/web-audio-api/#dom-audiobuffer-copytochannel-startinchannel

**Comment by karlt** [comment]
See https://github.com/WebAudio/web-audio-api/issues/1884 for recent discussion on the same issue.

I'm curious why you think the spec is in error?

**Comment by chrisguttandin** [comment]
Sorry @karlt, I somehow overlooked the other issue. I think this is a duplicate. I will therefore close it. Thanks for letting me know.
