### ISSUE TITLE
MediaStreamAudioSourceNode vs. ended tracks

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#1927]
@pehrsons noted during the review of a new WPT:

> Can you add a case for a MediaStream containing a single ended audio track? The spec says this is fine but I'd like to question that. It could probably reference an Audible MediaStream [1] for simplicity.
> 
> Similarly a MediaStream with an ended audio track and a live audio track, where the ended audio track comes first, would be interesting to test the audio output on.
> 
> https://w3c.github.io/mediacapture-main/#stream-audible

A good point I think. It's something we could consider doing. It does not seem to be particularly helpful to allow passing in an ended track, even if it's an audio track.

**Comment by padenot** [comment]
It might be a bit late. Neither Firefox nor Chrome did anything w.r.t. ended tracks. Adding a note and a browser warning in the console would be a good solution maybe ?

**Comment by rtoy** [comment]
So what is the conclusion here?  Nothing needs to be done for the spec?

**Comment by rtoy** [comment]
No special handing for ended tracks.  You always get the first (sorted) track.
