### ISSUE TITLE
length of AudioWorkletProcessor.process() parameter sequences with inactive inputs

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#1935]
https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-process-inputs-outputs-parameters-inputs currently says
> If no connections exist to the nth input of the node during the current render quantum, then the content of inputs[n] is an empty array, indicating that zero channels of input are available. This is the only circumstance under which the number of elements of inputs[n] can be zero."

I assume the intention is the following?
> If there are no actively processing AudioNodes connected to the nth input of the AudioWorkletNode for the current render quantum [...]

Otherwise ended AudioScheduledSourceNodes would obstruct the optimization if not explicitly disconnected.

**Comment by rtoy** [comment]
I think that's the intent.

**Comment by hoch** [comment]
So this is answered? Can we close the issue?

**Comment by karlt** [comment]
The spec text doesn't quite match the intent right now.  I suspect it predates resolution of https://github.com/WebAudio/web-audio-api/issues/1471.

This issue should remain open until the spec text is adjusted.

**Comment by padenot** [comment]
I'll update the text with prose using the concepts introduced in #1471.
