### ISSUE TITLE
Section 1.1.6  (introspection) not needed

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#1937]
[Section 1.1.6](https://webaudio.github.io/web-audio-api/#lack-of-introspection-or-serialization-primitives) doesn't seem necessary.  It just explains why the API doesn't have introspection or serialization, but we don't really need explain it since there is no API for it.

I think it could be removed without changing the spec in any way.

Plus the last paragraph talks about GC, so that should go away regardless of what we do with this section.

**Comment by padenot** [comment]
This was requested by the TAG.
