### ISSUE TITLE
Spec is inconsistent about whether parameterDescriptors is an array or an iterable

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1947]
https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-methods says:

> may have a valid static property named parameterDescriptors which is an iterable of AudioParamDescriptor ...

but https://webaudio.github.io/web-audio-api/#dom-audioworkletglobalscope-registerprocessor step 8 has:

>  If descriptors is neither an array nor undefined, throw a TypeError and abort these steps. 

Though it does not define what "an array" means; is it in the sense of https://tc39.es/ecma262/#sec-isarray or something else?  That would allow Proxy to Array; at least Gecko's impletation at the moment does not, as far as I can tell.

**Comment by hoch** [comment]
We really don't care about the order of descriptors. It is more of a Set, but Array was simple so we used that. Not sure how "Proxy" applies to our use case here.

**Comment by bzbarsky** [comment]
The order matters in terms of observables, because getting properties from descriptors can have side-effects.  So in practice the order needs to be specified.  Note that `Set` in JS is an ordered set.

If you want to allow both `Set` and `Array`, just allow arbitrary iterables.

> Not sure how "Proxy" applies to our use case here.

If you allow all iterables, it will Just Work as needed.  If you are trying to restrict to `Array`, you need to define what you mean by "Array".  Right now that's not defined.

**Comment by hoch** [comment]
It looks like Map is also iterable and I don't think `registerProcessor` should support an iterable with a pair iterator. It only supports an iterable with a value iterator. Does it make sense?

**Comment by bzbarsky** [comment]
In practice, you would iterate the thing and try to convert the things the iterator produces into `AudioParamDescriptor`s.  In the case of a `Map` that would generally fail, because the two-element arrays would not have a `name` property, which `AudioParamDescriptor` requires.

The concept of "value iterator" or "pair iterator" doesn't really apply to general JS iterables: they can just produce any list of values from their iterator.  As long as they're producing things that are ok as `AudioParamDescriptor` (that is, objects with a `name` property), fine.  Otherwise you would get an exception.

**Comment by hoch** [comment]
I believe this issue can be resolved by specifying an algorithm of AudioParamDescriptor extraction, which is being discussed in [here](https://github.com/WebAudio/web-audio-api/issues/1946#issuecomment-501786870).

**Comment by hoch** [comment]
I will create a PR based on https://github.com/WebAudio/web-audio-api/issues/1947#issuecomment-501873293.

**Comment by bzbarsky** [comment]
@hoch You can make things a bit simpler by just invoking https://heycam.github.io/webidl/#es-to-sequence which handles all that "check for an iterable" stuff for you.
