### ISSUE TITLE
DC Offset is ignored when calling AudioContext.createPeriodicWave()

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [WebAudio/web-audio-api#1959]
Hello everyone!

I was experimenting with AM/FM modulation using sine waves and had a bit of trouble with waves ranging from `-1.0` to `+1.0`, where I needed to have waves, that go from `0` to `+1.0`, similarly to what is described in this other ticket: https://github.com/WebAudio/web-audio-api/issues/321

I saw, that createPeriodicWave() takes 2 coefficients of a Fourier transformation and the cosine one's first argument is for setting a DC Offset. The MDN page mentions this briefly, referring to an example with Float32Arrays of length 2:

> Here, we create a PeriodicWave with two values. The first value is the DC offset, which is the value at which the oscillator starts. 0 is good here, because we want to start the curve at the middle of the [-1.0; 1.0] range.

( [source](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createPeriodicWave) )

I experimented with this a bit, rendering the periodic wave using OfflineAudioContext, but it seemed like this value is ignored. I've also tried setting the disableNormalization option to true.

This behaviour is actually correct based on the spec:

> The real parameter represents an array of cosine terms. The first element (index 0) is the DC-offset of the periodic waveform. Implementations MUST set it to zero when computing the waveform.

( [source](https://webaudio.github.io/web-audio-api/#dom-periodicwaveoptions-real) )

My questions would be:

1. **why is the dc offset ignored?**
  It is a very useful feature for audio effects.

2. **can I generate a wave with dc offset in any other way?**
  Preferably not by rendering a wave to a Buffer and manipulating that, since I would like to use it in an oscillator and change it's value over time.

**Comment by rtoy** [comment]
I do not know  the history of why the DC component is ignored, but there it is.

If you want a DC offset, you can do:
```
o = new OscillatorNode(c);
c = new ConstantSourceNode(c, {offset: offset})
o.connect(g);
c.connect(g);
```
where `g` could be a gain node or some other node to sum up the two nodes.

This is not an issue with the spec.

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you very much, It does solve the issue, since the signals will sum up. For the record, here is an example, where I managed to get a sine wave with custom phase shift and dc offset:

```javascript
const ctx = new OfflineAudioContext(1, 44100 * 2, 44100)

const OFFSET = 0.7
const PHASE = 0.35

// https://medium.com/web-audio/phase-offsets-with-web-audio-wavetables-c7dc85ac3218
const real = new Float32Array(2)
const imag = new Float32Array(2)
const shift = 2 * Math.PI * PHASE

real[0] = 0
real[1] = 0 * Math.cos(shift) - 1 * Math.sin(shift)
imag[0] = 0
imag[1] = 0 * Math.sin(shift) + 1 * Math.cos(shift)

const wave = ctx.createPeriodicWave(real, imag, { disableNormalization: true })

const oscillator = ctx.createOscillator()
oscillator.frequency.value = 400
oscillator.setPeriodicWave(wave)

const offset = ctx.createConstantSource()
offset.offset.value = OFFSET

oscillator.connect(ctx.destination)
offset.connect(ctx.destination)

ctx
  .startRendering()
  .then(buffer => {
    // https://github.com/audiojs/audio
    audio(buffer).save('demo.wav')
  })
  .catch(e => {
    console.error(e)
  })

oscillator.start()
offset.start()
```

The generated wave file has the shifted waveform as expected:
<img width="1236" alt="Képernyőfotó 2019-06-28 - 10 56 25" src="https://user-images.githubusercontent.com/2386064/60330958-df78f800-9993-11e9-85f3-3cc3d470c0b2.png">
