### ISSUE TITLE
options handling in AudioWorkletProcessor constructor is a bit confusing

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1965]
https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-audioworkletprocessor step 2 says that the `AudioWorkletProcessor` is initialized using _options_.  At the moment this is a no-op, as the following note says.  That's fine, but in that case why have this step listed at all?

If I understand the setup here correctly, the expectation is that consumers of this API will define `AudioWorkletProcessor` subclasses.  The constructors of those subclasses will be invoked (by the UA) with an `AudioWorkletNodeOptions` argument, converted to an ES value.  Presumably the expectation is that those subclasses can choose to pass that argument on to the superclass constructor like so:
```
   super(options);
```
though nothing actually forces them to, since the argument is optional, right?  And at the moment the superclass (and indeed UA code in general) does nothing with the object, as far as I can tell.

Given that, is this argument actually needed?  Is this meant to be an extension point for some time when `AudioWorkletProcessor` _might_ have some configuration options?  But why not just add the argument at that point, if it ever comes?

Separately, it's not clear to me whether this wording:
> The contents of this dictionary will have been serialized and deserialized according to the algorithm for instantiating an AudioWorkletProcessor.

is meant to be informative or normative.  But in either case I don't think it's a true statement: the contents of this dictionary will be whatever the api-consumer-defined constructor passes to `super()`, which may have absolutely nothing to do with the things the "instantiating an AudioWorkletProcessor" algorithm works with.

**Comment by padenot** [comment]
This is a bit unclear, but the idea is to be able to set things like `numberOfInputs`, etc., from user code, like what is done for native (non-audioworklet) nodes. It seems that a bit of the initialization that made it clear isn't here.

**Comment by hoch** [comment]
After some thoughts, the consumption of `numberOfInputs` and `numberOfOutputs` should happen when the node is created. Also the `parameterData` is also used when AudioParams are created in the node constructor. (i.e. on the control thread)

The only utility of `options` here is `processorOptions` for the user code. On that note, `super()` of AWP does not need it and it only needs to be passed to AWP subclass constructor.

**Comment by hoch** [comment]
> step 2 says that the AudioWorkletProcessor is initialized using options. At the moment this is a no-op, as the following note says. That's fine, but in that case why have this step listed at all?

This is not relevant anymore.

> though nothing actually forces them to, since the argument is optional, right? And at the moment the superclass (and indeed UA code in general) does nothing with the object, as far as I can tell.

This is also changed. Now the construction relies on "processor construction data", so the user code does not need to use "super(options)" to initialize the internals correctly. The more work to be done on this construction data, and it is tracked by #2027.

> meant to be informative or normative. But in either case I don't think it's a true statement: the contents of this dictionary will be whatever the api-consumer-defined constructor..

The text has been changed and we removed non-normative notes and built an algorithm for this:
https://webaudio.github.io/web-audio-api/#processor-construction-data
