### ISSUE TITLE
parameterDescriptors is not looked up by the AudioWorkletProcessor constructor

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1966]
https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-methods says:

> may have a valid static property named parameterDescriptors which is an iterable of AudioParamDescriptor that is looked up by the AudioWorkletProcessor constructor

but that's not what happens, as far as I can tell.  The property is consulted once, at `registerProcessor` time, then the resulting value is looked up by the `AudioWorkletNode` constructor.  The `AudioWorkletProcessor` constructor has nothing to do with any of this, and in fact has no access to this data as far as I can tell.

**Comment by hoch** [comment]
Yes. The later part is not really relevant to the AWP's method description. I think we should just remove it.

**Comment by hoch** [comment]
Closing via #2024.
