### ISSUE TITLE
It would be clearer if the various validation of AudioWorkletNodeOptions were an explicit step or set of steps

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1969]
https://webaudio.github.io/web-audio-api/#dictionary-audioworkletnodeoptions-members defines various validity constraints on `AudioWorkletNodeOptions` members that are supposed to lead to exceptions.

https://webaudio.github.io/web-audio-api/#configuring-channels-with-audioworkletnodeoptions defines some more validity constraints.

It's not 100% clear to me whether these constraints should be enforced in just the `AudioWorkletNode` constructor, or also in the `AudioWorkletProcessor` constructor (even though that claims to ignore its options arg), or something else.

It would be much clearer if there were a "validate a `AudioWorkletNodeOptions`" algorithm defined that does the relevant checks and if that algorithm were invoked in the relevant places explicitly.

**Comment by hoch** [comment]
The option-level validation is:
- IndexSizeError MUST be thrown if the length of outputChannelCount does not match numberOfOutputs.

The other validation should be a part of AudioWorkletNode construction:
- outputChannelCount: A NotSupportedError exception MUST be thrown if a channel count is not in the valid range of an AudioNode's channelCount.
- parameterData: If the string key of an entry in the list does not match the name of any AudioParam objects in the node, it is ignored.
- numberOfInputs = 0, numberOfOutputs = 0: NotSupportedError MUST be thrown by the constructor.

I'll try to come up with a plan to clarify this.

**Comment by hoch** [comment]
> parameterData: If the string key of an entry in the list does not match the name of any AudioParam objects in the node, it is ignored.

This is fixed by #2005.
