### ISSUE TITLE
parameterDescriptors handling during AudioWorkletNode initialization is probably wrong

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1972]
https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor step 9.3 says:

> For each key-value pair (paramNameInOption to value) of options:

At this point _options_ is a `AudioWorkletNodeOptions` instance, so the only possible keys here are "numberOfInputs", "numberOfOutputs", "outputChannelCount", "parameterData", and "processorOptions", right?  But the various spec examples use all sorts of custom param names like "myParam".  Do those just not affect AudioParam values here?   Am I totally misreading what's going on?

Also, what does the "value is not a type of Number" bit even mean if the values are IDL types?

An informative note about what this is really trying to do would maybe help.... I can't shake the feeling that this is not working with the object it means to be working with.

**Comment by karlt** [comment]
I assume the intention was that the key-value pairs should come from the value of the `parameterData` member on _options_.

"not a type of Number" can be dropped, I assume, because _value_ is of IDL type `double`.

**Comment by hoch** [comment]
I'll update the example code based on the updated spec text.

**Comment by hoch** [comment]
> But the various spec examples use all sorts of custom param names like "myParam". 

The incorrect usage in code example will be fixed by #1994.

> Do those just not affect AudioParam values here?

Yes, by passing |options| to `super()` in the constructor of AudioWorkletProcessor.

> Also, what does the "value is not a type of Number" bit even mean if the values are IDL types?

If the user-code does something like this, it will be ignored even if `myParam` is a valid entry in the retrieved `AudioParamMap` in the step 9.1. ([algorithm](https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor))
```js
parameterData: {
  myParam: 'hey'
}
```

I think we can drop the second bullet point about "not a type of Number" in the step.

**Comment by bzbarsky** [comment]
> Yes, by passing |options| to super() in the constructor of AudioWorkletProcessor.

I don't understand this part, especially as it relates to the changes in <https://github.com/WebAudio/web-audio-api/pull/1994>.

I suspect that the real key here is https://github.com/WebAudio/web-audio-api/issues/1972#issuecomment-509137611 paragraph 1...

>   myParam: 'hey'

If `parameterData` is a `record<DOMString, double>` then `myParam: 'hey'` in the object will throw when converting to the record type (because `ToNumber('hey')` is `NaN` and the value type is `double`, not `unrestricted double`).  It will most definitely not just be ignored!  There should be tests for this to make sure browsers are actually following the spec.

**Comment by hoch** [comment]
That's why I left this part alone in the second bullet point: `_value_ is out of the range specified in AudioParamDescriptor` An entry with a NaN value will be ignored by the range check.

**Comment by bzbarsky** [comment]
No, you don't understand.   `NaN` will throw when converting to IDL `double` at the IDL layer, so you won't even reach this code in the `myParam: 'hey'` case.

I did just test, and Chrome seems to do it right: this testcase throws an exception about a non-finite double without ever reaching the "bar" getter:
```
  var c = new AudioContext();
  new AudioWorkletNode(c, "b", { 
    parameterData: { 
      foo: 'hey', 
      get bar() { throw new Error("HELLO!") } 
    }
  });
```

**Comment by hoch** [comment]
That's why I am saying that we don't need to check 'number type' here in this algorithm because a non-number value will be invalidated by IDL layer. That's exactly what I meant as you showed in the code example above.

We still need to have the range check because we don't want values like NaN if infinity sneaking into the AudioParam.

Am I still missing something?

**Comment by hoch** [comment]
(a button mistake! sorry!)

**Comment by bzbarsky** [comment]
> That's why I am saying that we don't need to check 'number type' here in this algorithm

Yes, we all agree on that.

> We still need to have the range check

Right, if it's meant to catch finite values of some sort that are out of range.  You can't have `NaN` or `Infinity` at this point, because IDL will catch that.

Again, the main thing to fix here is https://github.com/WebAudio/web-audio-api/issues/1972#issuecomment-509137611 paragraph 1.

**Comment by karlt** [comment]
@hoch, I assume this was closed unintentionally?

**Comment by hoch** [comment]
Yeap, we still need to deal with the paragraph 1.

**Comment by hoch** [comment]
@karlt WDYT? The IDL/ECMA language should be refined a little, but I think it covers what we discussed.

The step 10.2 can be:
1. For each _descriptor_ of _parameterDescriptors_:
    1. Let _paramName_ be the value of _name_ member in _descriptor_.
    1. Let _audioParam_ be a new **AudioParam** instance.
    1. Configure _audioParam_ with _descriptor_.
    1. Perform _audioParamMap_.set(_paramName_, _audioParam_).

And the step 10.3 can be:
1. If _options_ has a dictionary member _parameterData_, performs the following steps:
    1. For each _paramName_ → _userValue_ of _parameterData_:
        1. If _audioParamMap_.has(_paramName_) is `true`:
            1. Let _audioParamInMap_ be _audioParamMap_.get(_paramName_).
            1. Set _audioParamInMap_.`value` property to _userValue_.

What we're still missing, but will be addressed in a different issue:
1. The validation on _parameterDescriptor_ on the AWP registration:
    1. Throw when duplicate _paramName_ found in _parameterDescriptors_.
    1. Throw when _userValue_ is out of the _descriptor_'s acceptable range.

**Comment by karlt** [comment]
The change to 10.2 to apply descriptor configuration to parameters addresses a separate real issue, thanks.  I wonder whether 10.2.iii "Configure audioParam with descriptor" could be more specific.  I don't see an AudioParam constructor defined.  Perhaps something like

> 10.2.ii Let _audioParam_ be a new `AudioParam` instance with `automationRate`, `defaultValue`, `minValue`, and `maxValue` having values equal to the values of corresponding members on _descriptor_.

**Comment by karlt** [comment]
For 10.3, `parameterData` is not a dictionary, but there is no need to mention the type. e.g.

> 10.3. If `parameterData` is present on _options_, perform the following steps:
> 10.3.1. Let _parameterData_ be the value of `parameterData` on _options_.

**Comment by karlt** [comment]
I wonder whether the change from "append (paramName, audioParam) to `audioParamMap`’s entries" to `audioParamMap.set(paramName, audioParam)` in 10.2 is not necessary and may not be appropriate.

`interface AudioParamMap` has a `readonly maplike<>` declaration, which provides "API for querying the map entries appropriate for the language binding".  IIUC that means there are methods available in the ECMAScript language binding, but not necessarily on the WebIDL types themselves.  Even so, there is no `set` method when `readonly`.

"Prose accompanying the interface can describe how the map entries of an object change."  Given there are no duplicate keys, "append" seems fine here.

There are similar questions around _audioParamMap_`.has()` and _audioParamMap_`.get()`.  I wonder whether prose would be more appropriate for these. e.g.

> 10.3.a If there exists a map entry on _audioParamMap_ with key _paramName_:

**Comment by karlt** [comment]
> Throw when userValue is out of the descriptor's acceptable range.

`AudioParam.value` does not throw when set outside the nominal range.
Is there a reason why _userValue_ should be treated differently?

**Comment by hoch** [comment]
> For 10.3, `parameterData` is not a dictionary

Just to clarify, it means `_options_` is a "dictionary", and `_parameterData_` is a "dictionary member". I was following WebIDL's convention.

**Comment by hoch** [comment]
@karlt Thanks for your input. I'll revise and try to create a PR based on the discussion here.

**Comment by hoch** [comment]
> `AudioParam.value` does not throw when set outside the nominal range.
> Is there a reason why _userValue_ should be treated differently?

After offline discussion @rtoy, we believe throwing an exception on a value outside of the nominal range is acceptable. This is an obvious user error, so notifying can be helpful. But also I agree with the idea that we should be consistent with the AudioNode's param value initialization. (which doesn't throw an exception)

**Comment by hoch** [comment]
Also the current spec text already throws an exception:
https://webaudio.github.io/web-audio-api/#dictionary-audioparamdescriptor-members

> Represents the default value of the parameter. If this value is out of the range of float data type or the range defined by minValue and maxValue, a NotSupportedError exception MUST be thrown.

**Comment by rtoy** [comment]
To be clear, in https://github.com/WebAudio/web-audio-api/issues/1972#issuecomment-515159603, we mean the `defaultValue` must be in the nominal range.  And you can't really compare this to how `AudioParam`s are constructed for other nodes because they're not user-constructable.  And the default value for these AudioParam's are always within the nominal range.

**Comment by karlt** [comment]
> > For 10.3, `parameterData` is not a dictionary
> 
> Just to clarify, it means `_options_` is a "dictionary", and `_parameterData_` is a "dictionary member". I was following WebIDL's convention.

Ah, thanks.  Apologies for my misunderstanding.  You are correct that WebIDL frequently uses the term "dictionary member".

(Still, WebIDL seems to use ["is present in _V_"](https://heycam.github.io/webidl/#es-dictionary) rather than "_V_ has" to test whether or not a dictionary member value exists. )

**Comment by karlt** [comment]
> To be clear, in #1972 (comment), we mean the defaultValue must be in the nominal range.

Thanks for clarifying.  I'm OK with throwing when `AudioParamDescriptor.defaultValue` is outside the nominal range, as indicated in the quoted text describing the member.

My point was for _userValue_ deriving from https://webaudio.github.io/web-audio-api/#dom-audioworkletnodeoptions-parameterdata.
Currently the spec is aiming to ignore the value when ["out of the range specified in AudioParamDescriptor."](https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor).

I suggest dropping that clause altogether for consistency with built-in AudioNode param value initialization.

**Comment by hoch** [comment]
> I suggest dropping that clause altogether for consistency with built-in AudioNode param value initialization.

Not sure what you mean by "that clause". Does it mean that throwing an exception when UA instantiates an AudioParam with a paramDescriptor? As rtoy@ mentioned, the built-in AudioParam doesn't throw on a value outside of nominal range. What we want with the AudioParamDescriptor is the opposite of that.

**Comment by karlt** [comment]
I'm not sure I completely understand the question.

`AudioParamDescriptor.defaultValue` behavior is independent from `AudioWorkletNodeOptions.parameterData` behavior.

@rtoy has commented on `AudioParamDescriptor.defaultValue` behavior, which has no comparable client-facing feature in built-in AudioParams.

The clause ["paramNameInOption will be ignored when:" "out of the range specified in AudioParamDescriptor"](https://webaudio.github.io/web-audio-api/#instantiation-of-AudioWorkletNode-and-AudioWorkletProcessor) should be dropped for consistency of `AudioWorkletNodeOptions.parameterData` with initialization of built-in parameters from node constructor options.

That clause is already dropped in the proposal for [step 10.3](https://github.com/WebAudio/web-audio-api/issues/1972#issuecomment-514745432).
The suggested addition "Throw when _userValue_ is out of the _descriptor_'s acceptable range" should not be added.

**Comment by hoch** [comment]
Now I understood. Thanks for pointing that out. I'll remove "value is out of the range specified in AudioParamDescriptor" in the step 10.3 (the current spec) should be removed.

I do think we still need to "throw when userValue is out of the descriptor's acceptable range" in the descriptor validation algorithm.
