### ISSUE TITLE
What happens if the constructor registered for an AudioWorkletProcessor subclass throws?

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#1975]
The "process a control message for the construction of an AudioWorkletProcessor" algorithm (really wish I could link to it directly!) does:

> Let processor be the result of Construct(processorCtor, « options »).

What happens if this throws?  The algorithm seems to assume this can't throw, but it obviously can...  If it throws, is there a way to detect the failure from the `AudioWorkletNode`?  

The processing model at https://webaudio.github.io/web-audio-api/#rendering-a-graph step 3.4.4.2 assumes  that every `AudioWorkletNode` in fact has an associated `AudioWorkletProcessor`, which can't be true in the "constructor threw" case.

**Comment by bzbarsky** [comment]
I guess https://webaudio.github.io/web-audio-api/#dom-audioworkletnode-onprocessorerror has some comefrom language that assumes the constructor can in fact throw.  It would be better if that behavior were actually expicitly referenced at the relevant callsites too...

**Comment by hoch** [comment]
Firstly, now the constructor is properly performed by "Construct a callback function":
https://webaudio.github.io/web-audio-api/#processor-construction-data (step 8)

Secondly, the AWP constructor is now able to route ErrorEvent when the construction goes wrong:
https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-audioworkletprocessor

I think now we can close this one.
