### ISSUE TITLE
Add event interfaces for `AudioParam` scheduling methods

### ISSUE THREAD

**Issue by Korilakkuma** [WebAudio/web-audio-api#1985]
**Describe the feature**

I think that some developers know when scheduling has done.

**Is there a prototype?**

For example (Envelope Generator) ...

```JavaScript
// Attack -> Decay -> Sustain
const t0 = audiocontext.currentTime;
const t1 = t0 + attack;
const t2 = decay;
const t2Value = sustain;

envelopegenerator.gain.cancelScheduledValues(t0);
envelopegenerator.gain.setValueAtTime(0, t0); 
envelopegenerator.gain.linearRampToValueAtTime(1, t1);  // Fire `onattack` event at `t1`
envelopegenerator.gain.setTargetAtTime(t2Value, t1, t2);  // Fire `ondecay` event at `t2`

envelopegenerator.gain.onattack = (event) => {
  // do something ....
};

envelopegenerator.gain.ondecay = (event) => {
  // do something ....
};

// ---------------------------------------------------

// Sustain -> Release
const t3 = audiocontext.currentTime;
const t4 = release;

envelopegenerator.gain.cancelScheduledValues(t3);  // Fire `onsustain` event at `t3`
envelopegenerator.gain.setTargetAtTime(0, t3, t4);  // Fire `onrelease` event at `t4`

envelopegenerator.gain.onsustain = (event) => {
  // do something ....
};

envelopegenerator.gain.onrelease = (event) => {
  // do something ...
};
```

**Describe the feature in more detail**

Fire event when scheduling has done. Then, for example, developers enable to update UI. But, event is not fired in v1. So, timer keeps watching gain.

##### Example from [XSound](https://github.com/Korilakkuma/XSound)

- https://github.com/Korilakkuma/XSound/blob/master/src/OscillatorModule/index.js#L170
- https://github.com/Korilakkuma/XSound/blob/master/src/SoundModule/Effectors/EnvelopeGenerator.js#L220

**Comment by rtoy** [comment]
I'm a bit confused on this.  You know when the automations end because you specified the time.  The events are asynchronous and would happen some time after the actual end, so you could achieve the same effect with a `setTimeout((t1-t0*1000)`.

I also don't understand the difference between the ondecay and onrelease events for `setTargetAtTime`.  How are they different, and why do you need both? (And why is it the time constant that triggers the event?)

Why does `cancelScheduledValues` fire an onsustain event but `setValueAtTime` does not?

**Comment by Korilakkuma** [comment]
Sorry to confuse you. I fixed prototype ...

```JavaScript
// Attack -> Decay -> Sustain
const t0 = audiocontext.currentTime;
const t1 = t0 + attack;
const t2 = decay;
const t2Value = sustain;

envelopegenerator.gain.cancelScheduledValues(t0);
envelopegenerator.gain.setValueAtTime(0, t0); 
envelopegenerator.gain.linearRampToValueAtTime(1, t1);  // Fire `onattack` event at `t1`
envelopegenerator.gain.setTargetAtTime(t2Value, t1, t2);  // Fire `ondecay` event at `t2`

// ---------------------------------------------------

// Sustain -> Release
const t3 = audiocontext.currentTime;
const t4 = release;

envelopegenerator.gain.cancelScheduledValues(t3);  // Fire `onsustain` event at `t3`
envelopegenerator.gain.setTargetAtTime(0, t3, t4);  // Fire `onrelease` event at `t4`

// event interface is provisional
envelopegenerator.gain.onended = (event) => {
  switch (event.scheduledTime) {
    case t0:
      // do something ...
      break;
    case t1:
      // do something ...
      break;
    case t2:
      // do something ...
      break;
    case t3:
      // do something ...
      break;
    case t4:
      // do something ...
      break;
    default:
      break;
  }
};
```

**Comment by Korilakkuma** [comment]
And ...

> The events are asynchronous and would happen some time after the actual end, so you could achieve the same effect with a setTimeout((t1-t0*1000).

I think this implementation is not simple for application developers  (compared to event interfaces). For example, calculation of timeout, clear timer ... etc

**Comment by hoch** [comment]
This is very similar (or identical) idea with https://github.com/WebAudio/web-audio-api/issues/1756. WG decided to punt it to V.next.
