### ISSUE TITLE
`webrtc-integration.html` uses lagacy APIs

### ISSUE THREAD

**Issue by Korilakkuma** [WebAudio/web-audio-api#1990]
**Describe the issue**

- `createJavaScriptNode` -> `createScriptProcessor`
- `navigator.getUserMedia` -> `navigator.mediaDevices.getUserMedia`
- `onaddstream` -> `ontrack`
- `noteOn` -> `start`

**Comment by padenot** [comment]
AudioWG telcon resolution: remove `webrtc-integration.html`, it's not really useful.

Thanks for noticing this an opening an issue about it!
