### ISSUE TITLE
MediaStreamAudioSourceNode with no audio tracks?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2009]
In https://webaudio.github.io/web-audio-api/#MediaStreamAudioSourceNode-constructors, step 2 of the algorithm says:

> 3. Let tracks be the list of all MediaStreamTracks of inputStream that have a kind of "audio"

and

> 6. Set an internal slot [[input track]] on this MediaStreamAudioSourceNode to be the first element of tracks.

But what if there are no tracks with a kind of 'audio'?

See also the related issue #1824.  It seems something has changed because comments there indicate that we used to throw an error if there were no audio tracks. [MediaStreamTrackAudioSourceNode](https://webaudio.github.io/web-audio-api/#MediaStreamTrackAudioSourceNode-constructors) does throw an error if the track is not an audio track.

**Comment by mdjp** [comment]
Requires discussion with @padenot

**Comment by padenot** [comment]
We did resolve this during a call: this was a mistake and we need to restore the old behaviour.

**Comment by padenot** [comment]
And it seems we overlooked the fact that step 2 already does the right thing in case there are no audio track: throw and abort.
