### ISSUE TITLE
AudioWorkletNodeOptions.processorOptions should not default to null.

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#2011]
**Describe the issue**
Because it is defaulting to `null`, the processor always get `null` for the field even the main scope option object is undefined. We should make it a plain object.
```webidl
object processorOptions;
```

**Where Is It**
https://webaudio.github.io/web-audio-api/#dictdef-audioworkletnodeoptions

**Comment by guest271314** [comment]
Not gathering what the expected result is. Can you include short snippets of code detailing what the expected output is for each input where options are passed or not passed?

**Comment by hoch** [comment]
The setup code:

```js
const node = new AudioWorkletNode(context, 'processor', nodeOptions);
```

```js
class extends AudioWorkletProcessor {
  constructor(options){
    console.log(options);
  }
}
```

When `nodeOptions = {}`:
```js
{numberOfInputs: 1, numberOfOutputs:1}
```

When `nodeOptions = {foo: 'bar'}`:
```js
{numberOfInputs: 1, numberOfOutputs:1}
```

When `nodeOptions = {foo:bar, processorOptions: {foo:'bar'}}`:
```js
{numberOfInputs: 1, numberOfOutputs:1, processorOptions: {foo:'bar'}}
```

**Comment by hoch** [comment]
From WG Telecon:
Remove the `nullable` type and the default value from `processorOptions`.

**Comment by karlt** [comment]
I'm not aware of any value in `processorOptions` being nullable.

If the value could default to the empty object, then that would permit clients to test for members without throwing a TypeError when `processorOptions` is not specified, but I don't think it is possible to specify an empty object default in WebIDL.

So, yes, the proposed change seems the best option available.
