### ISSUE TITLE
There are still issues with the setup of an AudioWorkletNode's parameters

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#2018]
I am looking at https://webaudio.github.io/web-audio-api/#ref-for-node-name-to-parameter-descriptor-map%E2%91%A2 (AudioWorkletNode constructor step 10).

There are three issues I see here:

1) The first bullet point in step 10.3.2 seems to be informative, not normative, since it just restates the conditional from step 10.3.1.  Why is it there at all?  If it needs to be there, it should be clearly marked as an informative note.

2) The second bullet point in step 10.3.2 says:

    > value is out of the range specified in AudioParamDescriptor.

    but `AudioParamDescriptor` is just a dictionary type that can be used to specify ranges... to actually specify a range you need a specific `AudioParamDescriptor` instance, and this step does not say which instance should be used.

3) In step 10.3.1 it's talking about "an entry with name member equal to paramNameInOption inside audioParamMap" but _audioParamMap_ is an instance of `AudioParamMap`, which is a `maplike<DOMString, AudioParam>`.  The entries of such a thing do not have a "name member"; what they have are keys and values.  so presumably this should be talking about "an entry with a key equal to paramNameInOption".  But even better would be to explicitly write out what needs to happen here:
    1. Look up the value for key _paramNameInOption_ in _audioParamMap_.  But see more on this below!
    2. If there is no value, continue to the next key-value pair.
    3. Assert that the value is an `AudioParam` instance.
    4. Set the value's value to _value_.  (This step could use some better naming for the result of the lookup in the first step, clearly!)

There's one major complication here, which is that in IDL a maplike has a `[[BackingMap]]` that is the source of truth as far as I can tell, in the sense that `.get` goes through that `[[BackingMap]]`, etc.  Unfortunately, the way IDL defines things right now there is no way to access that backing map in a reliable or side-effect-free way.  See <https://github.com/heycam/webidl/issues/254>.  It's possible that implementing option 3 from that issue would be enough to make things OK here; I haven't thought through the implications carefully but I suggest doing so.

**Comment by hoch** [comment]
@bzbarsky Too many issues were opened in a short period time, and the speed of PR review couldn't catch up. I am going to revisit all the issues you raised once more after #2005 is merged since it has a fundamental restructure.

**Comment by bzbarsky** [comment]
Ah, OK.  I was looking at this bit again because #1946 got resolved and I wanted to see what the outcome was.  If there are more things in flight, great.

**Comment by hoch** [comment]
> The first bullet point in step 10.3.2 seems to be informative, not normative, since it just restates the conditional from step 10.3.1. Why is it there at all? If it needs to be there, it should be clearly marked as an informative note.

I think the algorithm was revised, so this is pointing a wrong place.

> but AudioParamDescriptor is just a dictionary type that can be used to specify ranges... to actually specify a range you need a specific AudioParamDescriptor instance, and this step does not say which instance should be used.

Now this validation is handled by registerProcess() (step 10) so I think we should remove all the mention of exceptions from 1.32.4.4.1.

> In step 10.3.1 it's talking about "an entry with name member equal to paramNameInOption inside audioParamMap" but audioParamMap is an instance...

This step should be removed because now the step 11.3 already handles it.

> It's possible that implementing option 3 from that issue would be enough to make things OK here

I believe the current step 11.3 handles things correctly.

Let me know we still have issues around the usage of "AudioParamDescriptor" in the AWN constructor.
