### ISSUE TITLE
channelCount and channelCountMode constraints for AudioWorkletNode

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2025]
In [Configuring Channels With AudioWorkletNodeOptions](https://webaudio.github.io/web-audio-api/#configuring-channels-with-audioworkletnodeoptions), an algorithm is given for how the output channel count is determined.  I think there are constraints here, like the channel count of an output is pretty much fixed, independent of the `channelCount` and `channelCountMode` attributes of the node.  (Except for the case listed in algorithm step 4.1.)

We might want to make a note of the constraints and add  them to the section of constraints in [channelCount constraints](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcount) and [channelCountMode constraints](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcountmode).

**Comment by karlt** [comment]
`channelCount` and `channelCountMode` directly affect the inputs to nodes.
The constraints sections describe constraints on those attributes.
I expect introduction of discussion of node-specific effects on outputs could unnecessarily confuse the constraints sections.

**Comment by rtoy** [comment]
Teleconf: @hoch to look into adding a simple entry if possible.
