### ISSUE TITLE
AudioBufferSourceNode: Clarify if playhead truncation should happen when changing loop endpoints

### ISSUE THREAD

**Issue by collares** [WebAudio/web-audio-api#2033]
**Describe the issue**
Suppose looping is enabled, and we update loopEnd so that the playhead is now past the new loop end. Should we immediately truncate the playhead to loopEnd (and immediately loop back to loopStart, as when handling Start()'s offset argument)? Or should we jump back in `loopEnd - loopStart` increments?

**Where Is It**
https://webaudio.github.io/web-audio-api/#looping-AudioBufferSourceNode

**Additional Information**
If this concern is valid, then there is the analogous concern for negative playbackRates. See https://github.com/WebAudio/web-audio-api/issues/2031 for example.

**Comment by padenot** [comment]
AudioWG calls:
- jumping back in `loopEnd - loopStart` increments seem like a good behaviour to adopt.

**Comment by padenot** [comment]
It looks like this is already handled in the normative section of the description of the `AudioBufferSourceNode`:

```js
      // Wrap loop iterations as needed. Note that enteredLoop      
     // may become true inside the preceding conditional.
      if (enteredLoop) {
        while (bufferTime >= actualLoopEnd) {
          bufferTime -= actualLoopEnd - actualLoopStart;
        }
        while (bufferTime < actualLoopStart) {
          bufferTime += actualLoopEnd - actualLoopStart;
        }
      }
```

The link in the description for this issue was linking a non-normative textual description.
