### ISSUE TITLE
De-duplicate initial value setting on AudioWorkletNode AudioParams

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2035]
https://github.com/WebAudio/web-audio-api/issues/2018#issuecomment-522747997 says
> > In step 10.3.1 it's talking about "an entry with name member equal to paramNameInOption inside audioParamMap" but audioParamMap is an instance...
> 
> This step should be removed because now the step 11.3 already handles it.

https://webaudio.github.io/web-audio-api/#AudioWorkletNode-constructors currently has this step in 11.4.

**Comment by hoch** [comment]
The step 11.4 is not needed anymore.
