### ISSUE TITLE
Remove unnecessary cycle check.

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#2038]
**Describe the issue**
The algorithm for [rendering a graph](https://webaudio.github.io/web-audio-api/#rendering-a-graph) describes how to handle cycles. It requires every DelayNode which forms a cycle to be removed from the list. Afterwards (3.2.7) it says that remaining cycles should be muted.

To my understanding each cycle has to have a DelayNode which means there cannot be any cycles in the graph when all the DelayNodes are splitted up.

**Where Is It**
https://webaudio.github.io/web-audio-api/#rendering-a-graph 3.2.7.

**Additional Information**
As always there is a good chance that I got something wrong and for whatever reason this step might still be unnecessary.

**Comment by padenot** [comment]
Their is no synchronous check that a new connection forms a cycle (that would allow us to throw, for example). It's perfectly possible to create cycles. When this happens, we mute the cycle during the rendering. Cycles that contain a `DelayNode` however are allowed

Does this make sense ?

**Comment by chrisguttandin** [comment]
Thanks for taking a look at this.

The [description of the input parameter of AudioNode.connect()](https://webaudio.github.io/web-audio-api/#dom-audionode-connect-destinationnode-output-input-input) says a NotSupportedError should be thrown for all cycles without DelayNodes which is why I believe there can't be any cycle left after filtering those with DelayNodes.

Sorry I should have referenced that description in the first place.

**Comment by padenot** [comment]
Yes this one should have been removed ages ago, good catch.

**Comment by chrisguttandin** [comment]
By looking at the pull request I guess my assumption was wrong. It's not the cycle check in the algorithm, it's instead the cycle check in the `connect()` function  that is obsolete. Am I right now when I assume that this graph should render silence no matter what the output of the `ConstantSourceNode` is? Firefox seems to be the only browser that does this so far.

```txt
┌─────┐    ┌──────┐    ┌─────┐
│ CSN │ ─> │      │ ─> │ DST │
└─────┘    │ GAIN │    └─────┘
   ┌─>─>─> │      │ ─>─>─>─┐
   │       └──────┘        │
   │                       │
   └ 0 or more other nodes ┘ 
```

**Comment by rtoy** [comment]
@chrisguttandin I think you're correct on all counts.  Chrome doesn't mute cycles because Chrome doesn't search for cycles.  We don't have any immediate plans to fix this, even though we should.
