### ISSUE TITLE
Remove `options` parameter from `AudioWorkletProcessor` constructor WebIDL

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2044]
This is a follow-up to https://github.com/WebAudio/web-audio-api/issues/2036.
The parameter has been removed from the description at https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-audioworkletprocessor but not from the IDL at https://webaudio.github.io/web-audio-api/#ref-for-dom-audioworkletprocessor-audioworkletprocessor%E2%91%A0

**Comment by hoch** [comment]
TODO:
https://webaudio.github.io/web-audio-api/#callbackdef-audioworkletprocessorconstructor

**Comment by karlt** [comment]
> TODO:
> https://webaudio.github.io/web-audio-api/#callbackdef-audioworkletprocessorconstructor

I assume we don't want to change that one.  We want the AudioWorkletProcessorConstructor callback to receive the option.

**Comment by hoch** [comment]
Closed by #2102.
