### ISSUE TITLE
Disable normalization for OscillatorNode?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2046]
Currently, construction of a PeriodicWave allows you to disable the normailzation of the waveform.  This is fine.  But when you use the builtin types for the OscillatorNode, you can't.  Perhaps it should be allowed (by adding a disableNormalization member to the options dictionary)?  This would not apply when the type is "custom", of course.

Granted, you can do this using an appropriate PeriodicWave object, but you don't know how many coefficients are used in the OscillatorNode so it's not possible to match exactly without trial and error.

**Comment by karlt** [comment]
> Granted, you can do this using an appropriate PeriodicWave object, but you don't know how many coefficients are used in the OscillatorNode so it's not possible to match exactly without trial and error.

Perhaps I don't understand the problem with using PeriodicWave.  It will truncate appropriately for the frequency and Nyquist, but the builtin oscillators are spec'd and so could be reproduced exactly if desired.  But I don't know that that is the issue anyway.  The key is that PeriodicWave (I assume) allows the client to generate the waveform that they want?

**Comment by karlt** [comment]
I fear there may be some confusion if there is a `disableNormalization` option on both `OscillatorNode` and `PeriodicWave` and the option on `OscillatorNode` does not affect a `PeriodicWave` used with the `OscillatorNode`.

I guess it could be spec'd that setting disableNormalization on either of the objects would be sufficient to disable the normalization.  That may be the behavior of least surprise, if there is a genuine need for two options.
