### ISSUE TITLE
Restore ConvolverNode channel mixing configurability (up to 2 channels)

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2050]
https://www.w3.org/TR/2015/WD-webaudio-20151208/#ConvolverNode has the desired behavior:
>  The input of this node is either mono (1 channel) or stereo (2 channels) and cannot be increased. Connections from nodes with fewer or more channels will be up-mixed or down-mixed appropriately, but a NotSupportedError MUST be thrown if an attempt is made to set channelCount to a value great than 2 or if channelCountMode is set to "max".

This was reworded while maintaining the same behavior in https://github.com/WebAudio/web-audio-api/pull/999/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR2783 and https://github.com/WebAudio/web-audio-api/pull/999/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR2858

https://github.com/WebAudio/web-audio-api/commit/7a504211bb8152d3935c32eb4a4618bf4e242415 changed the text to say
> These constraints ensure that the input to the node is always stereo.

IIUC the reasoning was lack of clarity around the processing of mono input.
This text was not changed:
> The input of this node is either mono (1 channel) or stereo (2 channels) and cannot be increased."

https://github.com/WebAudio/web-audio-api/pull/1176/files restored the mono input case, so that input could be either mono or stereo, but didn't restore the ability for the client to set `channelCountMode` and/or `channelCount` in a way that fixed the input channel count to a single value.  Only the `clamped-max`, `2` case was restored, in which input channel count depends on the nodes connected.

Permitting `channelCount = 1` allowed clients to down-mix to one channel when desired, without the need for a separate upstream node to do this.

Permitting `channelCountMode = explicit` allowed clients to up-mix to two-channels, if desired, which can be useful to maintain stereo output even though inputs may be mono or stereo at different times.

**Comment by padenot** [comment]
The last two paragraphs are sensible, should this be V1 or V.next is the question.
