### ISSUE TITLE
Rationalize and update Milestones, Labels, and Projects

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2052]
Something to consider for TPAC.  We need to rationalize our milestones and projects. We currently have milestones for V1, which makes sense, but there's also v.next and "out of scope for v.next".

Maybe we need a V2 milestone?

But maybe all of this is subsumed by having a Project V2 that can hold everything we want to do for V2.

May also want to clean up the labels. I think there are too many and it's not really clear what they mean anymore.

**Comment by rtoy** [comment]
Maybe dump all this info in to a wiki page so we can remember?

**Comment by mdjp** [comment]
TPAC F2F - V2 is now in a clean repo. v.next milestone will be removed from v1.
