### ISSUE TITLE
Question -  Play AudioWorkletNode from disk

### ISSUE THREAD

**Issue by mikael-onsilva** [WebAudio/web-audio-api#2053]
Hello guys,

At the [AudioBufferSourceNode ](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode) page is mentioned:

> To play sounds which require accurate timing but must be streamed from the network or played from disk, use a AudioWorkletNode to implement its playback.

but I'm not shure how do I do that.

Any good hearted person could give me a hint? 😊

Thanks.

**Comment by rtoy** [comment]
This is not a spec issue.  You might want to ask on stackoverflow or some other forum for WebAudio questions.
