### ISSUE TITLE
High Priority V2 issues should probably not be v.next milestone

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2058]
All the issues that have the label "High Priority V2" should probably not also have a milestone of "v.next".

This is related to #2052.

**Comment by rtoy** [comment]
For reference these issues:  https://github.com/WebAudio/web-audio-api/issues?q=is%3Aopen+is%3Aissue+label%3A"High+Priority+V2"

**Comment by mdjp** [comment]
This has been dealt with during the TPAC F2F. V2 issues are now in a separate repository.
