### ISSUE TITLE
Does the process() function of a muted AudioWorkletNode get called?

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#2064]
**Describe the issue**
It is possible to create cycles by connecting AudioNodes. If such a cycle contains no DelayNode it should be [muted](https://webaudio.github.io/web-audio-api/#mute).

What happens if a cycle contains no DelayNode but an AudioWorkletNode? Does that mean process() gets called anyway and the output is just ignored?

The spec currently doesn't say anything about that edge case and maybe that's fine. Please feel free to close this issue if you think it's not necessary to specify it.

**Where Is It**
https://webaudio.github.io/web-audio-api/#mute

**Comment by padenot** [comment]
> Does that mean process() gets called anyway and the output is just ignored?

Yes, if nothing is said about not calling process, then process has to be called.

In general, specs tell you only what to do exactly, and what is not written must not be done.
