### ISSUE TITLE
Inconsistencies in constructor descriptions and factory method initialization

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2073]
The Web Audio API specifies an algorithm [to create an AudioNode of a particular type using its constructor](https://webaudio.github.io/web-audio-api/#AudioNode-creation).

Many descriptions of constructors more or less repeat that algorithm, but without explicitly passing arguments to the algorithm for [Initializing an object that inherits from AudioNode](https://webaudio.github.io/web-audio-api/#audionode-constructor-init).
e.g. [the AudioBufferSourceNode constructor](https://webaudio.github.io/web-audio-api/#dom-audiobuffersourcenode-audiobuffersourcenode).

Some descriptions of constructors use a similar algorithm, but extended to perform additional initialization (e.g. [the MediaStreamAudioSourceNode ](https://webaudio.github.io/web-audio-api/#dom-audiobuffersourcenode-audiobuffersourcenode)).

The [AudioWorkletNode constructor description](https://webaudio.github.io/web-audio-api/#AudioWorkletNode-constructors) is a little different in that the algorithm initializes `this` instead of creating and returning a new object.

The approach for AudioWorkletNode seems more consistent with the WebIDL spec which says that
[The prose definition of a constructor operation must either initialize the value passed as `this`, or throw an exception.](https://heycam.github.io/webidl/#idl-constructors)
[The WebIDL algorithm for creation of an interface object with the ECMAScript binding](https://heycam.github.io/webidl/#create-an-interface-object) will "Perform the actions listed in the description of constructor with values as the argument values and object as this" and so it would not seem appropriate for the description of the constructor to return a new object.

Given that each particular type describes the steps for the constructor and WebIDL describes the steps for creation from ECMAScript and that the generic algorithm is not complete for all "particular type"s, I guess it would be best to remove the generic algorithm "to create an `AudioNode` of a particular type _n_ using its constructor".

Also, the algorithm "to create a new `AudioNode` of a particular type _n_ using its factory method" does not invoke the constructor, and so does not contain any type-specific additional initialization steps, such as those in the `MediaStreamAudioSourceNode` constructor.  Perhaps this should invoke the constructor instead of the "Intialize" algorithm.

**Comment by rtoy** [comment]
I believe this is an artifact of when we added the node constructors in addition to the factory methods, and we wanted to use a generic algorithm to describe the construction since they are all very similar.  And because we didn't want to duplicate much of the algorithm across every single node.

**Comment by padenot** [comment]
Taking this:
1. Remove the generic ctor algorithm in favour of one for each type that calls the "initialize" algorithm, and pass the arguments appropriately.
1. Change the generic factory method algorithm to call the ctor underneath, so that the "initialize" algorithm is called and the specific initialization is performed
