### ISSUE TITLE
Should the AudioWorkletNode constructor invoke the algorithm for initializing an object that inherits from AudioNode?

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2074]
https://github.com/WebAudio/web-audio-api/issues/2073 gives an overview of the current specification for AudioNode creation/construction.

The [AudioWorkletNode constructor description](https://webaudio.github.io/web-audio-api/#AudioWorkletNode-constructors) also differs in that it does not invoke the algorithm for [Initializing an object that inherits from AudioNode](https://webaudio.github.io/web-audio-api/#audionode-constructor-init). Invoking this algorithm would set `channelCount`, `numberOfInputs`, etc. appropriately for the `AudioWorkletNodeOptions` provided.

I assume the appropriate place to do this would be between "Let _node_ be `this` value" and "Configure input, output and output channels of _node_ with _options_".  That would provide the usual order of processing `AudioNodeOptions` members before the members on the derived dictionary.

**Comment by padenot** [comment]
This makes sense. I'm fixing this in #2092 along with with the other fixes for #2073
