### ISSUE TITLE
NaN inputs to AudioParam?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2077]
The `AudioParam` value attribute is a `float`, so you can't use the value setter to set it to NaN.  The automation methods take `float`s too, so you can't use NaN there either.

However, the curve for `setValueCurveAtTime` could contain NaN.  And a subgraph could be connected to the input to the `AudioParam` where the subgraph produces NaN.

What is supposed to happen in these cases? 

`AudioParam`s have a min and max value, so presumably NaN could be replaced by one of these values.  But which one?

Or maybe just garbage in/garbage out so we leave the behavior undefined?

**Comment by padenot** [comment]
Implementation will probably flush `NaN` to zero, we might as well spec it.

**Comment by rtoy** [comment]
Heh. Can't say for other nodes, but in Chrome's DelayNode, we set the delay to the max delay.  I don't know why that is, but I happened to be looking there for something else when I noticed this issue.

**Comment by padenot** [comment]
Call resolution: the default value for the `AudioParam` is used in the presence of `NaN`.
