### ISSUE TITLE
OscillatorNode channelCount should be 1

### ISSUE THREAD

**Issue by AdenFlorian** [WebAudio/web-audio-api#2079]
**Describe the issue**
The spec says the OscillatorNode channelCount is 2, but I think it should be 1.

**Where Is It**
https://webaudio.github.io/web-audio-api/#oscillatornode
In the property table.

**Additional Information**
@padenot asked me to file this issue on slack where I brought it up.

**Comment by padenot** [comment]
As Raymond pointed out, this is for input, and the node has no inputs, so this is invalid.

**Comment by rtoy** [comment]
People (including experienced people like me and you) get confused about this all the time.  Maybe we can add a note somewhere that this has no effect for AudioScheduledSourceNodes?

**Comment by padenot** [comment]
Yep that would be helpful.

**Comment by rtoy** [comment]
I'll open a new issue on this.
