### ISSUE TITLE
Specify how often Analyser smoothing is done

### ISSUE THREAD

**Issue by akaltar** [WebAudio/web-audio-api#2101]
**Describe the issue**
Currently it is not clear how often the audioAnalyser performs the FFT and smoothing steps. Is it once per quantum(128 samples) using the latest fftSize samples? Is it once every fftSize samples? Is it only if get*FrequencyData is called?

Here it was mentioned that it could be every 128 frames, but with a modified smoothing factor to account for the added smoothing introduced by more overlap, but there is no sign of either in the spec.
https://github.com/WebAudio/web-audio-api/issues/375#issuecomment-60193494

The description for get*FrequencyData also mentions that if called twice within the same quantum the same data will be returned. This hints that processing may be done once per quantum, but this isn't really stated.

**Where Is It**
https://webaudio.github.io/web-audio-api/#fft-windowing-and-smoothing-over-time

**Comment by padenot** [comment]
`getFloatFrequencyData` and `getByteFrequencyData` are the only two bits in the spec uses the [current frequency data](https://webaudio.github.io/web-audio-api/#current-frequency-data), that is the series of steps, including an FFT, windowing, smoothing, etc., that does the actual computation.

It also states that if it is requested more than once per quantum, the first call computes the FFT, and the subsequent calls merely copy the previous result:

> If another call to getFloatFrequencyData() or getByteFrequencyData() occurs within the same render quantum as a previous call, the current frequency data is not updated with the same data. Instead, the previously computed data is returned.

The spec doesn't tell how how to do this: it's valid to always compute the frequency data on the rendering thread, or also on demand on the control thread. The spec tells you what should be returned when those functions are called.
