### ISSUE TITLE
Lifetime of pending processor construction data and exceptions in instantiation of AudioWorkletProcessor when AudioWorkletProcessor() constructor is not invoked

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2119]
[The instantiation of AudioWorkletProcessor algorithm](https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-instantiation) sets the node reference and transferred port of the AudioWorkletGlobalScope's pending processor construction data.

Only the [AudioWorkletProcessor() constructor](https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-audioworkletprocessor) arranges for this data to be cleared, but "Construct a callback function" in the [instantiation of AudioWorkletProcessor](https://webaudio.github.io/web-audio-api/#AudioWorkletProcessor-instantiation) does not necessarily invoke the [AudioWorkletProcessor() constructor](https://webaudio.github.io/web-audio-api/#dom-audioworkletprocessor-audioworkletprocessor).

I assume that steps to "Empty the pending processor construction data slot" and "queue a task to the control thread to fire an event named processorerror" should be moved from the AudioWorkletProcessor() constructor to the instantiation of AudioWorkletProcessor algorithm?

Some more details are in https://github.com/WebAudio/web-audio-api/issues/2096, but perhaps all the details there occluded the core of the issue.

**Comment by guest271314** [comment]
If gather this issue correctly this means there is a significant difference in processing between

```
constructor() {
  this.port.onmessage = e => {
    // messages, data transferred immediately upon AudioWorkletNode()
  }
}
```

and 

```
constructor() {
  this.port.onmessage = this.handMessage.bind(this);
}
handleMessage(e) {
  // do stuff
}
```

as to when `process()` is contructed begins processing inputs, outputs?
