### ISSUE TITLE
AudioScheduledSourceNode.start does weird checks that don't match browsers

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#2142]
https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-start step 1 says:

> If stop() has been called on this node, or if an earlier call to start() has already occurred, an InvalidStateError exception MUST be thrown.

I don't think any browsers implement this as written.  Consider this testcase:
```
var ctx = new AudioContext;
var node = new ConstantSourceNode(ctx);
try { node.stop(); } catch (e) {}
node.start();
```
Per spec as written, the `start` call should throw, since `stop` has been called.  In practice, browsers do not seem to do it.

Similarly, consider this testcase:
```
var ctx = new AudioContext;
var node = new ConstantSourceNode(ctx);
try { node.start(-5); } catch (e) {}
node.start();
```
Again, per spec as written this should clearly throw.  It does not throw in browsers.

I suspect that what the spec really aims to do here is to have some internal flag that is initially unset and gets set between the current step 2 and step 3 of the `start` steps.  And then throw in step 1 if that flag is set.

Similarly, the steps for `stop` should probably check this flag.  That's certainly how browsers seem to behave: if there was only a _failed_ call to `start`, then `stop` is not allowed.  But that's not what https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-stop step 1 says to do.

**Comment by guest271314** [comment]
Both of the test cases throw an error at Chromium 81 and Nightly 74

```
var ctx = new AudioContext;
var node = new ConstantSourceNode(ctx);
try { node.stop(); } catch (e) { console.error(e); }
try { node.start(); } catch (e) {console.error(e); }
```
Chromium 81
```
DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
```
Nightly 74
```
DOMException: "An attempt was made to use an object that is not, or is no longer, usable"
```

```
var ctx = new AudioContext;
var node = new ConstantSourceNode(ctx);
try { node.start(-5); } catch (e) { console.error(e); }
try { node.start(); } catch (e) { console.error(e); }
```

Chromium 81 
```
RangeError: Failed to execute 'start' on 'AudioScheduledSourceNode': The start time provided (-5) is less than the minimum bound (0).
```

Nightly 74
```
RangeError: "The value for the start time is outside the valid range."
```

```
var ctx = new AudioContext;
var node = new ConstantSourceNode(ctx);
try { node.start(0); } catch (e) { console.error(e); }
try { node.start(); } catch (e) { console.error(e); }
```
Chromium 81
```
DOMException: Failed to execute 'start' on 'AudioScheduledSourceNode': cannot call start more than once.
```

Nightly 74 
```
DOMException: "An attempt was made to use an object that is not, or is no longer, usable"
```

**Comment by bzbarsky** [comment]
> Both of the test cases throw an error at Chromium 81 and Nightly 74

Yes, but do they throw _two_ errors like the spec requires?

> DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.

Sure.  But the spec currently requires that the _start_ call also throw.  Please do see the testcase I wrote, which is carefully testing the thing I was filing this issue on.

> RangeError: Failed to execute 'start' on 'AudioScheduledSourceNode': The start time provided (-5) is less than the minimum bound (0).

Again, the issue is that per current spec the _second_ call to `start`, without an arg should throw, and does not in browsers.

> DOMException: Failed to execute 'start' on 'AudioScheduledSourceNode': cannot call start more than once.

Yes, this part makes sense and is not what this issue is about.

**Comment by guest271314** [comment]
> Again, the issue is that per current spec the second call to start, without an arg, should throw, and does not in browsers.

The second case does throw on second `call to start()`, without an arg, at Chromium 81 and Nightly 74.

```
var ctx = new AudioContext;
var node = new ConstantSourceNode(ctx);
try { node.start(); } catch (e) { console.error(e); }
try { node.start(); } catch (e) { console.error("second call", e); }
```

The first case, executing `start()` after `stop()` does not throw.

**Comment by guest271314** [comment]
> Again, the issue is that per current spec the _second_ call to `start`, without an arg, should throw, and does not in browsers.

Why should the second call to `start` throw in that case, after the `RangeError` has been handled?

**Comment by bzbarsky** [comment]
> Why should the second call to start throw in that case

Again, because the spec clearly says:

> if an earlier call to start() has already occurred, an InvalidStateError exception MUST be thrown

as I said in the original issue.  In this case an earlier call to `start` has occurred; it just happened to throw.  Again, I suspect this is not what the spec _means_, but it's what it _says_.  That's the issue.

**Comment by rtoy** [comment]
Not sure what the right behavior is.  It's possible implementors overlooked the case where start or stop threw an error and didn't record the fact that the call had been made.

**Comment by bzbarsky** [comment]
Well, either behavior is sensible, depending on what the goals are.  But basically, we either need to change the spec to match implementations or change implemenations to match the spec and make the spec clearer so implementations don't mess up like this in the future.  And in either case, add web platform tests...

**Comment by rtoy** [comment]
Teleconf:  Failed calls to start/stop don't affect subsequent calls.  Thus the second test case in https://github.com/WebAudio/web-audio-api/issues/2142#issue-557838439 is the behavior we want.
