### ISSUE TITLE
IIRFilterOptions description makes impossible demands

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#2148]
https://webaudio.github.io/web-audio-api/#dom-iirfilteroptions-feedforward says:

> If not specifed, a NotFoundError MUST be thrown

But the IDL for that member says `required`.  That means that if it's not specified https://heycam.github.io/webidl/#es-to-dictionary step 4.1.5 will throw a TypeError before anythiing involving the Web Audio spec happens.  So it's not clear to me what this NotFoundError requirement is about and how it can be complied with.

https://webaudio.github.io/web-audio-api/#dom-iirfilteroptions-feedback has the same issue.

**Comment by padenot** [comment]
Telconf decision: Remove this check and exception throwing and let WebIDL do its thing.
