### ISSUE TITLE
AudioBufferOptions requires throwing NotFoundError in cases that can't happen

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#2150]
https://webaudio.github.io/web-audio-api/#AudioBufferOptions says:

> A NotFoundError exception MUST be thrown if any of the required members are not specified.

but those members are `required` in the IDL, so this can't happen.

**Comment by padenot** [comment]
Telconf decision: this will be remove and the check will be handled by WebIDL.
