### ISSUE TITLE
close() steps don't make sense

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#2152]
https://webaudio.github.io/web-audio-api/#dom-audiocontext-close step 2 says:

> If the control thread state flag on the AudioContext is closed reject the promise with InvalidStateError, abort these steps, returning promise.

and then step 3 says:

> If the state attribute of the AudioContext is already "closed", resolve promise, return it, and abort these steps.

But https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-state says:

> Its value is identical to control thread state

so those checks are checking the same value but describing different behavior for that value.

If I call `close()` twice on the same `AudioContext` Chrome rejects with an `InvalidStateError` for the second call.  Firefox resolves the promise with an InvalidStateError (!); I think that's just a typo and will fix it.  So it seems like step 2 is the right one and step 3 should just be removed.

**Comment by padenot** [comment]
Telconf decision: we'll keep step 2 and remove step 3.
