### ISSUE TITLE
Exception for changing channelCountMode on ScriptProcessorNode does not match browsers

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#2154]
https://webaudio.github.io/web-audio-api/#dom-audionode-channelcountmode says:

>ScriptProcessorNode
>    The channel count mode cannot be changed from "explicit" and an InvalidStateError exception MUST be thrown for any attempt to change the value.

Testcase:
```
var ctx = new AudioContext
var n = ctx.createScriptProcessor(2048, 3)
try { n.channelCountMode = "max"  } catch (e) { console.log(e.name) }
```
logs "NotSupportedError" in both Chrome and Firefox.

**Comment by padenot** [comment]
Telconf decision: align this node on all the others, and make it throw "NotSupportedError", which makes more sense.
