### ISSUE TITLE
Restore changes accidentally reverted in bikeshed conversion

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2155]
One such change is the ["Spec document unloading" PR](https://github.com/WebAudio/web-audio-api/pull/1425), which was merged to index.html November 2017, for issue https://github.com/WebAudio/web-audio-api/issues/1139

Mention of unload was removed from index.html in the [Bikeshed conversion commit](https://github.com/WebAudio/web-audio-api/pull/1514/commits/e8f64d4ee1621f986c88a4b85b43de6b84ef646d), which was [merged](https://github.com/WebAudio/web-audio-api/pull/1514) March 2018, and there was no mention in the new index.bs.

**Comment by padenot** [comment]
Telconf decision: put this one back, and try to find a way to find what else has been missed.

**Comment by padenot** [comment]
I'm going to rebase my old PR on the current text, and find paths that create promises that have been added since then, to add then to the `[[pending promises]]` array.

This must have been missed when re-basing in-flight PRs in between starting and merging the Bikeshed conversion work.

**Comment by padenot** [comment]
This has been sorted out in #2166. Hopefully it was the only one.

**Comment by karlt** [comment]
Thank you for fixing that.

I used w3m to convert to text the versions of index.html before and after the bikeshed and then ran `patdiff -html <(sed s/’/\'/g index.c70964.w3m) <(sed s/’/\'/g index.e8f64d.w3m)`.

The key changes that came with the bikeshed conversion are listed below.
I didn't find anything major that has been missed.

I assume these changes were intended:
* AudioContextOptions parameter to AudioContext constructor is no longer nullable.
* OfflineAudioContext oncomplete attribute is no longer readonly.
* OfflineAudioCompletionEventInit renderedBuffer attribute is no longer readonly.

These changes have since been corrected:
* Removal of default values for input and output parameters to AudioNode.connect() methods.
* ChannelSplitterNode constructor parameter type changed from ChannelSplitterOptions to ChannelSplitterNode.
* Removal of "The use of a curve that produces a non-zero output value for zero input value will cause this node to produce a DC signal even if there are no inputs connected to this node. This will persist until the node is disconnected from downstream nodes."
* Addition of extra AudioContext in BitCrusher Node and VU Meter Node.
* Removal of document unloading.

These have not been corrected, but don't seem significant:
* "Single input and output with single channel." > "Single input, single channel." in BypassProcessor.
* Deletion of "'s audio rendering thread" after "new AudioWorkletGlobalScope is created in association with the context" in AudioWorklet Sequence.
* "produce" -> "use" output in VU Meter Node.

This is now irrelevant because the state property no longer exists:
```
-|the node. The flag change is propagated by queueing a task on the control
-|thread to update the corresponding AudioWorkletNode's state property
-|accordingly.
+|the node. To propagate the flag change queue a task on the control thread to
+|update the corresponding AudioWorkletNode's state property accordingly.
```
