### ISSUE TITLE
AudioWorkletProcessor definition without `get ParameterDescriptor`

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#2171]
Should this be allowed? Per spec, it shouldn't:

https://heycam.github.io/webidl/#es-sequence throws if the input is not iterable, and there is particular handling for when there is no `get parameterDescriptors`.

I see WPTs and examples in the spec that don't have `get parameterDescriptors`.

@hoch, I believe your intent there was to allow it, is that right?

**Comment by rtoy** [comment]
Teleconf:  Allow not having parameterDescriptors.  Makes sense if there are no AudioParams defined for the worklet.
