### ISSUE TITLE
getting blank channelData of audioContext on safari

### ISSUE THREAD

**Issue by jainketan** [WebAudio/web-audio-api#2180]
hey,

want to check mic is mute or not on button click. I am using audioContext to achieve this, it works fine on chrome and firefox but on **safari** it is not working fine

Safari - on first click it works fine, but when i click second time it always give me blank inputData.

can anyone help me with audioContext or is there any alternate way to do this ?

window.AudioContext = window.AudioContext || window.webkitAudioContext;
var audioContext = new AudioContext();

function checkForMicMute() {
        if(audioContext.state === "suspended" && countmeter > 0) {
            audioContext.resume();
        }

        var mediaStreamSource = audioContext.createMediaStreamSource(localMediaStream);
        var processor = audioContext.createScriptProcessor(4096, 1, 1);
        mediaStreamSource.connect(processor);
         processor.connect(audioContext.destination);
        processor.onaudioprocess = function (e) {
              var inputData = e.inputBuffer.getChannelData(0);
              var inputDataLength = inputData.length;
              var total = 0;
        
               for (var i = 0; i < inputDataLength; i++) {
                        total += Math.abs(inputData[i++]);
                }
        
                var rms = Math.sqrt(total / inputDataLength);

                 if(rms <= 0) {
                        console.log("Microphone is muted.")
                        audioContext.suspend();
                } else {
                        console.log("Microphone is working.")
                         audioContext.suspend();
                }
        };
    }

    checkForMicMute();

**Comment by padenot** [comment]
This sounds like an implementation bug, please file a bug in the vendor's bug tracker:

- WebKit (Safari): https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Web%20Audio (WebKit bugzilla account needed).
- Blink (Chrome): https://new.crbug.com/ (Google account needed).
- Gecko (Firefox): https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Web%20Audio (GitHub or Mozilla Bugzilla account needed).
