### ISSUE TITLE
Bikeshed won't render spec

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2183]
**Describe the Issue**
The latest version of bikeshed crashes when rendering the spec.  We'll have to wait for tabatkins/bikeshed#1625 to be fixed.

This is closely related to #2182 because we need python 3.7 to run the latest bikeshed, which doesn't work right now.

**Comment by sideshowbarker** [comment]
https://github.com/tabatkins/bikeshed/issues/1625 has been merged, so Bikeshed is no longer crashing at least. But as I reported in https://github.com/WebAudio/web-audio-api/issues/2185, there seem to some IDL errors that need to be fixed.

**Comment by rtoy** [comment]
tabatkins/bikeshed#1625 has been fixed.

Closing this issue.
