### ISSUE TITLE
PannerNode refDistance description unclear

### ISSUE THREAD

**Issue by tim-we** [WebAudio/web-audio-api#2184]
The current description for the `refDistance` attribute [1]  is

> A reference distance for reducing volume as source moves further from the listener. The default value is 1. A RangeError exception MUST be thrown if this is set to a negative value.

From the formulas for each `DistanceModelType` [2] one can deduce that it is the distance at which there is no reduction in volume (gain=1). To me this is not clear from the description above.
For further clarification I suggest adding at least a sentence like

> For distances greater than this the volume will be reduced.

If it is just me or you think the formulas in the specification are enough to describe this, feel free to just close & dismiss this issue.

[1] https://webaudio.github.io/web-audio-api/#dom-pannernode-refdistance
[2] https://webaudio.github.io/web-audio-api/#dom-distancemodeltype-linear

**Comment by rtoy** [comment]
Teleconf:  This makes sense and clarifies the behavior.  We'll add this.

**Comment by rtoy** [comment]
But instead of saying
> For distances greater than this the volume will be reduced.

I think it's better to say something like
> For distances less than this, the volume is not reduced.

because the current spec already says the volume is being reduced.

Thanks for bringing this to our attention.

**Comment by tim-we** [comment]
Yes that sounds good to me. Sorry I was a bit quick about closing this issue, I did not notice this commit was on a fork.

**Comment by rtoy** [comment]
No problem.  When the PR lands, this issue will get closed automatically.
