### ISSUE TITLE
Incorrect azimuth comparison in spatialization algorithm

### ISSUE THREAD

**Issue by koalefant** [WebAudio/web-audio-api#2193]
Change 73726d16d9dd1a9b17ca0e494449be678164bca2 (Replace HTML entities in code algorithms) has broke comparison in azimuth spatialization algorithm code:

It became
```
// Make azimuth relative to "forward" and not "right" listener vector.
if ((azimuth <= 0) && (azimuth <= 270))
```
(note double less less-equal)
While previously it was:
```
if ((azimuth >= 0) && (azimuth <= 270))
```

**Comment by rtoy** [comment]
Thanks for the report and a link to the offending change!
