### ISSUE TITLE
Destination of request created by `addModule`

### ISSUE THREAD

**Issue by jugglinmike** [WebAudio/web-audio-api#2203]
[A non-normative table in Fetch](https://fetch.spec.whatwg.org/#requests) describes the "destination" of requests generated by the `addModule` method to be `"audioworklet"`. Currently, the normative text of the specification doesn't support this, so the property value is "script."

Should the table in Fetch be updated? Or should this specification be changed to set the destination?

/cc @mikewest @annevk

**Comment by jugglinmike** [comment]
Also cc @bfgeek who added the "audioworklet" destination to Fetch's examples via https://github.com/whatwg/fetch/pull/527

**Comment by annevk** [comment]
See https://github.com/w3c/css-houdini-drafts/issues/378.

**Comment by jugglinmike** [comment]
Thanks, Anne. It's too bad there's been silence about that issue for three years. [Mozilla's leading the pack on this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1402784), so I've reached out to see if they'd be interested in standardizing the behavior.

**Comment by padenot** [comment]
I've been talking with @annevk about this and will fix in the spec(s).

**Comment by padenot** [comment]
This is blocked on https://github.com/w3c/css-houdini-drafts/issues/378 being merged. It seems ready, and our side of the fix is #2212.
