### ISSUE TITLE
Missing self-link in some sections

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#2205]
There are missing self-links ( with '§' ) that should be at the beginning in some sections.
For example, 1.1.3 1.1.4 1.5 1.5.6 ....

**Comment by padenot** [comment]
We investigated with @rtoy during the weekly call. By doing this:

```diff
diff --git a/index.bs b/index.bs
index 03538147..31c029bc 100644
--- a/index.bs
+++ b/index.bs
@@ -2570,7 +2570,7 @@ The allowed values for the members of this dictionary are constrained.  See {{Ba
 -->
 
 
-<h3 interface lt=AudioNode>
+<h3 id="AudioNode">
 The {{AudioNode}} Interface</h3>
 
 {{AudioNode}}s are the building blocks of an {{AudioContext}}. This interface
@@ -3265,7 +3265,7 @@ Dictionary {{AudioNodeOptions}} Members</h5>
 -->
 
-<h3 id="AudioParam" interface lt="AudioParam">
+<h3 id="AudioParam">
 The {{AudioParam}} Interface</h3>
 
 {{AudioParam}} controls an individual aspect of an
(END)
```

then the `§` appear. It seems that the `id` needs to be the only attribute, and the value needs to be quoted.

**Comment by rtoy** [comment]
We also need to ask Tab about this.  I'm pretty sure this used to work without the changes @padenot mentions above.

**Comment by rtoy** [comment]
See tabatkins/bikeshed#1734.

**Comment by rtoy** [comment]
Here's a list of all the sections missing markers:

- 1.1.3
- 1.1.4
- 1.5
- 1.5.6
- 1.6
- 1.7
- 1.8
- 1.84
- 1.9
- 1.10
- 1.11
- 1.12
- 1.12.2
- 1.13
- 1.13.4
- 1.14
- 1.14.2
- 1.15
- 1.15.2
- 1.16
- 1.16.3
- 1.17
- 1.17.3
- 1.18
- 1.18.3
- 1.19
- 1.19.3
- 1.20
- 1.20.3
- 1.21
- 1.21.3
- 1.22
- 1.22.3
- 1.23
- 1.24
- 1.24.3
- 1.25
- 1.25.2
- 1.26
- 1.26.4
- 1.27
- 1.27.4
- 1.28
- 1.28.2
- 1.28.3
- 1.29
- 1.30
- 1.30.3
- 1.31
- 1.31.3
- 1.32
- 1.32.2
- 1.32.3
- 1.32.3.3
- 1.32.4
- 1.32.4.4

**Comment by rtoy** [comment]
It appears the that common theme is that the tags have stuff after them.  Just a bare tag appears to work with bikeshed automatically adding an id based on the section name, but all lower-case.  Bikeshed also warns that we need to add an id manually so the MDN can refer to it.

I think @padenot's idea in https://github.com/WebAudio/web-audio-api/issues/2205#issuecomment-649673964 will work.

Would still like some clarification from @tabatkins on the issue, though.

**Comment by rtoy** [comment]
I just checked the current draft at https://webaudio.github.io/web-audio-api/.  All of the sections that were missing links as listed in https://github.com/WebAudio/web-audio-api/issues/2205#issuecomment-665156442 have links now.

I didn't look through the spec to see if there are other missing links.

I'm going to close this out as fixed, but note that https://github.com/tabatkins/bikeshed/issues/1734 is still open.

Thanks for bringing this to our attention.
