### ISSUE TITLE
PannerNode.rollOffFactor with "linear" distance model is not clamped to [0, 1] in main browser engines

### ISSUE THREAD

**Issue by cdumez** [WebAudio/web-audio-api#2206]
**Describe the issue**

PannerNode.rollOffFactor with "linear" distance model is not clamped to [0, 1] in main browser engines. The spec says it should be here:
https://www.w3.org/TR/webaudio/#dom-pannernode-rollofffactor

However, if you set it to 2, in Chrome / Firefox / WebKit, it will return 2 after, not 1. We noticed this when trying to implement the specification behavior in WebKit.

**Comment by padenot** [comment]
This was discussed in the AudioWG weekly call:
- This is intended: you can set any value, and it's clamped as part of the processing, on the render thread. This allows setting a value and then changing the mode and the value set might lie outside the range in the first more but be in the range in the second mode.
- Resolution: add a sentence that says explicitly that the clamping happens as part of the processing, and the attribute on the control thread side reflects the value set. This is in line with most APIs and, more importantly, with `AudioParam` clamping.
