### ISSUE TITLE
Chrome: AudioContext Will Not Resume, even on User Gesture

### ISSUE THREAD

**Issue by ryanmchenry2** [WebAudio/web-audio-api#2207]
I have a React (v16 w/ Hooks) application that fetches and plays back audio files. In Chrome (v83), the AudioContext constructor inconsistently starts in a `running` state and a `suspended` state. I understand that expected behavior should be `suspended`, which should later be resumed with `audioContext.resume()`, triggered by user gesture.

Note: initializing the context on page load is crucial for decoding audio.

In the case (~20% of page loads) where the `AudioContext()` constructor initializes in a 'suspended' state, Chrome will not allow the context to resume, regardless of where/how I call `audioContext.resume()`. I have tried using the React `onClick` handler, as well as examples directly from Chrome FAQ docs:

```
document.querySelector('#PlayPauseButton').addEventListener('click', () => {
    audioContext.resume().then(() => {
      console.log('Playback resumed successfully')
    })
  })
```

In all cases, the AudioContext remains suspended, and will not playback audio. The only thing that fixes the bug is a reload, and again this is inconsistent, as about ~20% of page loads have the bug.

I'm not sure where I'm going wrong, but am immensely frustrated by the lack of predictability and consistency of the behavior. Looking for any ideas on how to handle properly.

**Comment by hoch** [comment]
Please file an issue at https://crbug.com. You can cc me in the issue so I can take a look. (hongchan@chromium)

**Comment by eoikonomou** [comment]
Anything related with this? This also happens to me. Also it would be helpful if we could somehow retry resuming if it gets stuck but from what I've experienced so far if it gets stuck it never finishes up. No promise.then or promise.catch is fired.
