### ISSUE TITLE
Creating tags when we do a CR

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2243]
**Describe the Issue**
When CRs are created, we don't know exactly what version of the spec was used.  Sometimes the date isn't enough since changes could have happened on the same date that aren't reflected.

Proposal:  Create a tag whenever we submit a CR (or other checkpoint).

Maybe name the tags cr-yyyy-mm-dd for when the CR was created?

We should also do the same when we send out the recommendations.

**Comment by svgeesus** [comment]
Yes, this would help.

I notice that the ED is missing the two most recent Previous Versions:

https://www.w3.org/TR/2020/CR-webaudio-20200611/
https://www.w3.org/TR/2018/CR-webaudio-20180918/

Also the changes section is for the 2018 publication
https://webaudio.github.io/web-audio-api/#changestart1

and a "since 2020" changes section should be added

**Comment by rtoy** [comment]
Oops.  I'll update the ED with that info.  I'll update the changes section soon too.

Once I get #2274 fixed; that's going to block landing the fixes.

**Comment by rtoy** [comment]
Since the last two PR/CRs used branches, perhaps the way forward is to create branches for the PR/CR work.  Then when all the changes are done and it is published, we can add branch [protection rules](https://docs.github.com/en/github/administering-a-repository/about-protected-branches). At the very least, we can prevent the branch from being deleted.  It would be ideal if we could restrict further pushes, but it seems the best that can be done is to restrict pushes to certain people.  It seems good enough if only editors or chairs (or W3C rep) can do pushes (after the PR/CR is published.)

I guess tags can still be applied, but having a protected branch is probably good enough.  We can't ever really merge the branch to the main branch if we continue to do development.

**Comment by rtoy** [comment]
Oh.  https://github.com/WebAudio/web-audio-api/wiki/Creating-a-CR-manually says to create a tag.

**Comment by rtoy** [comment]
With the decision to go forward with a living standard, perhaps the way forward is to create a permanent branch that has the recommendation.  This branch will get updated as needed from the draft version.

Or maybe continue doing the same thing and creating new branches as needed when the recommendation is updated.

Not sure what the best approach would be.

**Comment by padenot** [comment]
I've created a pushed a tag named `1.0`, that corresponds to https://github.com/WebAudio/web-audio-api/commit/b53d3d7df84c9c0797bf1ba6d80a8f337ea54ead, which is the correct base modulo a typo fix.

**Comment by hoch** [comment]
Closing per https://github.com/WebAudio/web-audio-api/issues/2243#issuecomment-908493137.
