### ISSUE TITLE
When are promises in "[[pending resume promises]]" resolved?

### ISSUE THREAD

**Issue by tidoust** [WebAudio/web-audio-api#2252]
The [`[[pending resume promises]]` slot](https://webaudio.github.io/web-audio-api/#dom-audiocontext-pending-resume-promises-slot) gets filled with promises from early calls to `resume` (before context is allowed to start).

However, as far as I can tell, the spec never says when these promises are resolved.

The steps for [running a control message to resume an AudioContext](https://webaudio.github.io/web-audio-api/#dom-audiocontext-resume) either reject the promises or "clear" the list (why aren't the promises resolved first?). On top of that, I suspect that these promises need to be resolved when the context becomes [allowed to start](https://webaudio.github.io/web-audio-api/#allowed-to-start). In which case, this issue is similar to the comment I added to #2251: the spec does not explain what happens when context becomes allowed to start.

**Comment by rtoy** [comment]
Teleconf:  Yes we should fix this in V1.  Rejecting pending resume promises when we're resuming is odd.

**Comment by skratchdot** [comment]
I wrote a test for this, but I can convert it to wpt (and submit it to that repo if you agree this makes sense):

```
(async () => {
    const ctx = new AudioContext();
    const promises = [];
    const triggerResume = () => {
        const p = ctx.resume();
        p.isResolved = false;
        p.isRejected = false;
        p.then(() => p.isResolved = true).catch(() => p.isRejected = true);
        promises.push(p);
    };
    let runningCalled = false;
    ctx.onstatechange = () => {
        runningCalled = true;
        console.assert(ctx.state === 'running');
        console.assert(promises[0].isResolved === true);
        console.assert(promises[0].isRejected === false);
        console.assert(promises[1].isResolved === true);
        console.assert(promises[1].isRejected === false);
        console.log('done3', ctx.state);
    };
    // firefox ctx.state==='suspended', chrome ctx.state==='running'
    triggerResume();
    console.assert(promises[0].isResolved === false);
    console.assert(promises[0].isRejected === false);
    // firefox ctx.state==='suspended', chrome ctx.state==='running'
    triggerResume();
    console.assert(promises[1].isResolved === false);
    console.assert(promises[1].isRejected === false);
    console.log('done1', ctx.state);
    await Promise.all(promises);
    // firefox ctx.state==='running', chrome ctx.state==='running'
    console.assert(runningCalled === false);
    console.assert(promises[0].isResolved === true);
    console.assert(promises[0].isRejected === false);
    console.assert(promises[1].isResolved === true);
    console.assert(promises[1].isRejected === false);
    console.log('done2', ctx.state);
})().catch(console.error);
```

If you run the above test in latest Firefox and Chrome, all the assertions pass, and the console logs: done1, done2, done3

If you try running in Safari preview, it will error on the `new AudioContext()` so you have to change to `new webkitAudioContext()`. After you do that, you will only see the console log: done1.  It never resolves or rejects the `await Promise.all(promises);` line.

The test could definitely be cleaned up to make it easier to read. I also need to review all the existing tests, b/c I feel like we could just update one of the existing "allowed to start" tests:
https://github.com/web-platform-tests/wpt/tree/master/webaudio/the-audio-api/the-audiocontext-interface

Or just have a new one (perhaps `pending-resume-promises.html`).

**Comment by rtoy** [comment]
Thanks for writing the test.  Yes, ideally, it needs to use the WPT testing framework.  I would prefer a new file for this, but I think that's mostly up to whoever reviews the PR.

**Comment by padenot** [comment]
I agree that a new file is better. It should be fairly straightforward to convert this to a WPT, and this would be greatly appreciated (we can help with any problem of course just ping us).
