### ISSUE TITLE
Security review for Web Audio API 1.0

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2254]
The [Security and Privacy appendix](https://webaudio.github.io/web-audio-api/#priv-sec)

[Review requested 29 Sept 2020](https://lists.w3.org/Archives/Public/public-web-security/2020Sep/0003.html)

**Comment by hafixo** [comment]
Merge pull requested

**Comment by svgeesus** [comment]
No security issues raised, so far.

**Comment by svgeesus** [comment]
Lack of any substantive security review, six months after it was requested, was mentioned on the [Proposed Recommendation transition](https://github.com/w3c/transitions/issues/328#issuecomment-830187380) and transition was approved.

The difficulty in getting security review on complex, lengthy specifications in general was noted.
