### ISSUE TITLE
New bikeshed failures

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2262]
**Describe the issue**
When merging PR #2253 to the main branch, there are new bikeshed errors that didn't how up in the PR itself.  I think the PR CI used bikeshed 2.0.0, but the main branch has pulled in the latest version 2.1.0 (to fix dark mode).

**Where Is It**

See https://travis-ci.com/github/WebAudio/web-audio-api/builds/189506052

It seems bikeshed doesn't understand our links to `{{MediaStream}}`, `{{MediaStreamTrack}}`, and `{{undefined}}`.  This wasn't a problem in 2.0.0.

**Comment by tabatkins** [comment]
That's because there was nothing relevant to that regression. Those links are all in the current db, and it looks like you're running `bikeshed update`. So, uh, dunno. Is it just a transient failure?

**Comment by rtoy** [comment]
I'm not really sure what's going on.  (I also have a really confused local system with some random mix of just plain pip3 install, but also from a git clone.  I need to remove everything and start over.)

But Travis does just a plain pip3 install + bikeshed update, not a git clone.

I'll let you know when I've wiped bikeshed off and reinstalled using pip3 install.

**Comment by rtoy** [comment]
Not sure what's going on.  I think I cleaned out all existing bikeshed stuff.  pip3 install gives the media errors. But if I install from a git clone, the errors are gone.

For now I think I'll try changing Travis to clone the bikeshed repo and install it.
