### ISSUE TITLE
AudioWorkletProcessor makes false assumptions that have to be worked around.

### ISSUE THREAD

**Issue by carlsmith** [WebAudio/web-audio-api#2271]
The API begins calling the `process` method of a subclass of `AudioWorkletProcessor` as soon as the instance is instantiated, on the assumption that is is ready. This is often not the case.

For example, instantiating a Wasm module instance is asynchronous. We cannot create `async` constructors, so must use a callback. Either way, this creates a race condition, where the `process` method can (and does) call functions exported by the Wasm module before they are exported:

``` js
class Node extends AudioWorkletProcessor {

    constructor(args) {

        super();
        this.exportedFunction = null;
        const wasmBuffer = args.processorOptions.wasmBuffer;
        WebAssembly.instantiate(wasmBuffer).then(wasm => {
            this.exportedFunction = wasm.instance.exports.exportedFunction;
        });
    }

    process(inputs, outputs, params) {

        this.exportedFunction();
        outputs[0][0].set(this.memory.slice(0, 128));
        outputs[0][1].set(this.memory.slice(128, 256));
        return true;
    }
}
```

The work around is obvious: You initialize an instance attribute with a name like `isReady` to `false`, set it to `true` in the `WebAssembly.instantiate` callback, then check it in the `process` method, returning `true` immediately if `this.isReady` is still falsey.

This adds an `if` branch to the `process` method that is only ever taken while the instance is readying up. Once the instance is (properly) ready, the branch is never taken.

Another problem, when using Wasm, is that the Wasm code will often have to repeatedly loop to generate blocks of zeroes, when the node is inactive. Unlike a JS implementation, the Wasm module cannot just return `true` and leave the `output` argument full of zeroes, as the samples are copied from the Wasm memory (which is not cleared automatically).

**Edit**: *Ignore the previous paragraph. The entry-point to the Wasm module can return a bool to indicate whether the `process` method should copy from memory, or just return `true`.*

Neither issue (or their variants) are showstoppers. They only make code less efficient, but it would be nice if the API provided a way to suspend and resume processing on a specific node.

**Comment by skratchdot** [comment]
If you are concerned about the useless conditional after your async code in the constructor is loaded, can't you just set `this.process = () => {}` in your callback right below where you set `this.exportedFunction = wasm.instance.exports.exportedFunction;`?

For instance, code like this is ugly, but works:
```
class Foo {
    constructor() {
        this.process = () => console.log('loading');
        setTimeout(() => {
            this.process = () => console.log('loaded');
        }, 1000);
    }
    process() {
        console.log('never called');
    }
}

let foo = new Foo();
foo.process(); // loading
foo.process(); // loading
setTimeout(() => {
    foo.process(); // loaded
}, 2000);
```

**Comment by rtoy** [comment]
Teleconf:

- Yes, you're right about having to have an if statement to handle the case where it's not ready yet.
- Yes, for WASM you have to copy the data out.  This is basically https://github.com/WebAudio/web-audio-api-v2/issues/4 and https://github.com/WebAudio/web-audio-api-v2/issues/5
- It's too late in the V1 spec cycle to add a new API to suspend/resume a node.

**Comment by carlsmith** [comment]
@skratchdot - Thank you. I hadn't thought of that. It's a useful option to have.

@rtoy - I hadn't seen #4 and #5. Issue #4 covers coping the samples to the output arrays, but the main issue here (delaying processing until the instance is ready, and possibly allowing developers to suspend and resume processing arbitrarily) is not addressed anywhere else.

I accept that this cannot change within the V1 cycle, but don't know what that implies, in terms of whether this issue should be closed. I'll leave it up to you.

**Comment by rtoy** [comment]
We're trying to finish the spec, so we're really reluctant to add new APIs unless really necessary.  Adding suspend/resume even for just AudioWorklet is a significant undertaking because all the corner cases need to be considered.

In Chrome, IIRC, `process()` won't get called until you connect the worklet to the destination node (in most cases).  This is a long-standing issue on how node processing happens in Chrome, but it has its uses. ;-)

I'll leave this open for now.

**Comment by guest271314** [comment]
If context is running, call `suspend()` before initiating `AudioWorklet`, the constructor will still be called. When ready message to main thread then call `resume()`. I use that pattern when waiting for a minimal amount of data to be accumulated (1-3 seconds worth of raw PCM) or written to a `WebAssembly.Memory` instance that dynamically grows, https://github.com/guest271314/quictransport/tree/main/audioworklet-webassembly-memory-grow.

**Comment by guest271314** [comment]
The code requires minimal adjustment. 

```
const aw = /* AudioWorklet instance */
ac.suspend().then(_ => {
  aw.port.onmessage => {
     ac.resume()
     .then(_ => { // process called
        // process called
     })
  }
})
```

```
class Node extends AudioWorkletProcessor {
    constructor(args) {
        super();
        console.log(this); // currentTime: 0
        this.exportedFunction = null;
        const wasmBuffer = args.processorOptions.wasmBuffer;
        WebAssembly.instantiate(wasmBuffer).then(wasm => {
            return this.exportedFunction = wasm.instance.exports.exportedFunction;
        })
        .then(_ => {
           this.port.postMessage('start');
        })
    }
    process(inputs, outputs, params) {
      // called when context state is running
    }
}
```

An alternative approach is utilizing `export` and `import` before constructor.

**Comment by carlsmith** [comment]
> Unlike a JS implementation, the Wasm module cannot just return `true` and leave the output argument full of zeroes, as the samples are copied from the Wasm memory (which is not cleared automatically).

After posting that, I found a simple solution: The Wasm function can just return a bool that lets the `process` method know whether to copy the data or not:

``` js
process(inputs, outputs, params) {

    if (this.interpolate(params.param[0])) {

        const [L, R] = outputs[0];
        L.set(this.memory.slice(0, 128));
        R.set(this.memory.slice(128, 256));
        }
        return true;
    }
```

**Comment by rtoy** [comment]
Teleconf:  Are you happy with the solutions in https://github.com/WebAudio/web-audio-api/issues/2271#issuecomment-725732820 and https://github.com/WebAudio/web-audio-api/issues/2271#issuecomment-722774247?

If not, this is out-of-scope for V1.  A suspend/resume API for a worklet will have to wait for V2.

**Comment by carlsmith** [comment]
@rtoy - I think this can easily wait till later.

The original issue was that `process` can be called before functions exported by a Wasm module are ready, but you can do (per @skratchdot)...

``` js
this._process = this.process;
this.process = () => true;
```

...in the constructor, and then restore the proper `process` method in the callback that handles the exports (from the Wasm module).

Node-specific suspend and resume is not as useful as I first thought, as the Wasm function can exit early and return a bool that tells the `process` method whether to copy the memory or not.

**Comment by guest271314** [comment]
@carlsmith Re `WebAssembly.instantiate()` see https://github.com/WebAudio/web-audio-api/discussions/2482. If you do something like the following on Chromium 101

```
await WebAssembly.instantiate(buffer, {
    js: { mem: memory },
  }).then((obj) => {
  const i32 = new Uint32Array(memory.buffer);
  for (let i = 0; i < 10; i++) {
    i32[i] = i;
  }
  const sum = obj.instance.exports.accumulate(0, 10);
  return sum;
  });
class AudioWorkletStream extends AudioWorkletProcessor {
  constructor(options) {
    super();
    console.log(this, options);
  }
  process(inputs, outputs) {
    return true;
  }
}
registerProcessor('audio-worklet-stream', AudioWorkletStream);
```

The correponding `AudioWorkletNode` will not be constructed. A `DOMException` will be thrown. Clearly the node name is defined in `AudioWorkletGlobalScope`
