### ISSUE TITLE
Is MediaStream from MediaStreamAudioDestinationNode expected to playback when set as srcObject of HTMLAudioElement?

### ISSUE THREAD

**Issue by guest271314** [WebAudio/web-audio-api#2293]
**Describe the issue**

Consider the following code

```
      <audio controls autoplay id="input"></audio>
      <script>
        const ac = new AudioContext();
        const msd = new MediaStreamAudioDestinationNode(ac);
        const {stream} = msd;
        const [track] = stream.getAudioTracks();
        const input = document.querySelector('audio');
        [
          'loadedmetadata',
          'loadeddata',
          'canplay',
          'canplaythrough',
          'play',
          'playing',
          'pause',
          'ended',
          'stalled',
          'waiting',
          'durationchange',
          'suspend',
          'abort',
          'emptied',
          ].forEach((event) =>
            input.addEventListener(event, (e) => {
            console.log(e.type, input.currentTime);
            })
        );
        input.srcObject = stream;
      </script>
```

The `MediaStream` is `active`.

The `MediaStreamTrack` `readyState` is `"live"`.

At Chromium 90 `HTMLAudioElement` `durationchange`, `loadedmetadata`, `loadeddata`, `canplay`, `play`, `playing`, `canplaythrough` events are fired at `currentTime` `0`, afterward `currentTime` does does not advance

```
durationchange 0
loadedmetadata 0
loadeddata 0
canplay 0
play 0
playing 0
canplaythrough 0

```
At Firefox 84 `suspend` event is fired before the same events that are fired at Chromium 90, at `currentTime` `0.058049886621315196`, `currentTime` advances

```
suspend 0.058049886621315196
durationchange 0.058049886621315196
loadedmetadata 0.058049886621315196
loadeddata 0.058049886621315196
canplay 0.058049886621315196
play 0.058049886621315196
playing 0.058049886621315196
canplaythrough 0.058049886621315196

```

**If it's really an implementation bug, considering filing an issue for your browser at**

I do not know if this is an implementation bug. Chromium and Firefox exhibit different behaviour. 

The specification does states that `MediaStreamAudioDestinationNode` has `0` outputs. 

The specification does not state that when `MediaStreamAudioDestinationNode` `stream` is set at `srcObject` `HTMLMediaElement` playback of the live `MediaStreamTrack` must commence and `currentTime` of the media element must advance, or conversely, if the _live_ track should not advance `currentTime` at `HTMLMediaElement`.

**Where Is It**

https://webaudio.github.io/web-audio-api/#mediastreamaudiodestinationnode

**Additional Information**

I am experimenting with using `MediaStreamAudioDestinationNode` as source for an _infinite_ audio stream where the browser (Firefox; Chromium) is the server. I tested the same code at Chromium 90 and Firefox 84 on Linux and observed the different implementations of the audio node.

**Comment by padenot** [comment]
Firefox is correct, `currentTime` should advance: https://w3c.github.io/mediacapture-main/getusermedia.html#mediastreams-in-media-elements clearly states that the `currentTime` should be increasing "whenever the stream is playing".

**Comment by guest271314** [comment]
Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1170680
