### ISSUE TITLE
AnalyserNode.getFloatTimeDomainData should specify the output range

### ISSUE THREAD

**Issue by tambien** [WebAudio/web-audio-api#2296]
Currently WAA implementations handle the range of AnalyserNode.getFloatTimeDomainData differently. Safari clamps the output to between [-1, 1] while Chrome and Firefox seem to allow any range output. The spec does not specify the range of the output. I'm curious if this should be made explicit, if it's not implied elsewhere in the spec

If this is already explicitly in the spec, i will file a bug with Safari.

**Comment by tambien** [comment]
Whoops! turns out the clamping issue was because i was using [standardized-audio-context](https://github.com/chrisguttandin/standardized-audio-context) and not actually in Safari's implementation (since they haven't implemented it yet and the workaround is to just use `getByteTimeDomainData`). 🤦🏻‍♂️ 

Not sure if it's still worth specifying the range in the spec since it seems obvious that it shouldn't be clamped to [-1,1] but should use the full range of float32 values.

**Comment by rtoy** [comment]
Odd that Safari doesn't have getFloatTimeDomainData.  I vaguely remember that being added before the split of webkit and blink.

Anyway, I think we could, but as you say, it's pretty clear that no clamping should be done because the full range is supported everywhere.
