### ISSUE TITLE
Normative references, and stability criteria

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2297]
From [how to go to Proposed Recommendation](https://www.w3.org/Guide/transitions?profile=PR):

> In general, documents do not advance to Proposed Recommendation with normative references to other specifications that are considered unstable. See also [Normative References Guidelines](https://www.w3.org/2013/09/normative-references).
>  Documents must not include normative references to a Rescinded/Obsolete/Superseded Recommendation.

In the [CR snapshot](https://www.w3.org/TR/webaudio/#normative):

- [WebRTC 1.0 was a CR, is now a Rec](https://www.w3.org/TR/2021/REC-webrtc-20210126/). Bikeshed should pick up that change automatically.
- [Media Capture and Streams is still a CR](https://www.w3.org/TR/mediacapture-streams/) so we need to argue that it meets the stability criteria
- [WebIDL is still a draft](https://heycam.github.io/webidl/) but [that didn't stop WebRTC referencing it in their Rec](https://www.w3.org/TR/webrtc/#normative-references) so there is evidence it already meets the stability criteria.

**Comment by svgeesus** [comment]
I contacted the staff contacts for the [Web Real-Time Communications Working Group](https://www.w3.org/groups/wg/webrtc) asking about stability for the [28 Jan 2021 CR of Media Capture and Streams](https://www.w3.org/TR/2021/CRD-mediacapture-streams-20210128/).

**Comment by rtoy** [comment]
Are those the only ones you found?

I'm also curious why WebIDL isn't automatically allowed.

**Comment by svgeesus** [comment]
Yes, those are the only ones I found.

WebIDL is in practice automatically allowed, I checked with some recent specifications that reference it.

**Comment by rtoy** [comment]
The media capture and streams spec appears to be referenced only from the privacy section.  (Searching for "media capture" shows only 3 instances.)  If so, we're not using media capture in any way within the spec, so perhaps it's ok that it's not a recommendation.

That leaves only WebIDL.  (The spec already links to the WebRTC recommendation).

I think we're fine here?  Is there more to do?  If not can we close this?

**Comment by svgeesus** [comment]
We can close this.
