### ISSUE TITLE
behavior not defined when AudioParam setting invalid value

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#23]
> Originally reported on W3C Bugzilla [ISSUE-21344](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21344) Wed, 20 Mar 2013 06:00:18 GMT
> Reported by Wei James
> Assigned to 

should it be the same with setting attribute of value? or just ignore if the value is invalid.

**Comment by billhofmann** [comment]
Handled by webidl, won't fix - values like "Dave" would be rejected in any case - http://heycam.github.io/webidl/#idl-float, "set of finite IEEE-754 numbers"
