### ISSUE TITLE
A way to destroy an AudioContext instance

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#230]
> Originally reported on W3C Bugzilla [ISSUE-17423](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17423) Tue, 05 Jun 2012 15:52:37 GMT
> Reported by olivier Thereaux
> Assigned to 

Closed per http://www.w3.org/2011/audio/track/issues/3

Raised by Jussi as “There should be a way to destroy an Audio Context. This is especially important because the number of AudioContexts is limited, and if the end developer is using multiple libraries that create these contexts, this will be a problem unless the libraries have a way to get rid of the AudioContext instance. The ideal solution would be that AudioContexts would follow basic garbage collection rules and would be destroyed if there were no references to it, and currently the spec doesn't actually say anything about the garbage collection, so this is the expected behavior.”

Resolved at 16 Apr teleconference:

Resolution: close ISSUE-3 as satisfying as is, make sure we document limits in the number of contexts - not necessarily in the spec but in some developer doc.

http://lists.w3.org/Archives/Public/public-audio/2012AprJun/0060.html

**Comment by gunar** [comment]
If you've reached this point, you should go here next =>> [GO](https://stackoverflow.com/a/35564886/1456173)

**Comment by rtoy** [comment]
Or better yet, see [AudioContext.close()](https://webaudio.github.io/web-audio-api/#dom-audiocontext-close)
