### ISSUE TITLE
Implementation and test reports needs updating

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#2300]
**Describe the Issue**

The [test report](https://webaudio.github.io/web-audio-api/test-report.html) and [implementation report](https://webaudio.github.io/web-audio-api/implementation-report.html) should probably be updated one last time before CR/Recommendation to include the latest results from [wpt.fyi](https://wpt.fyi).

**Comment by svgeesus** [comment]
I [updated the implementation report](https://github.com/WebAudio/web-audio-api/commit/29dba0afd6654830538b9dfdd60d81a1497089ab) most recently on 4 Feb

The test report though could use some update, and more info on the Firefox implementation.

**Comment by svgeesus** [comment]
Updated again for Safari 120 preview

**Comment by rtoy** [comment]
It's up to Firefox and Safari to update the test report.  I don't have any plans to update these further. (I was mostly guessing atwhat I put in for Firefox.)  I will update Chrome soon, but I don't think much has changed.

**Comment by rtoy** [comment]
Per last weeks teleconf, there will probably be one more update to the implementation and test reports before May, so leave this open until then.  After that, we can close this issue.
