### ISSUE TITLE
Improve definition of regular tasks processing.

### ISSUE THREAD

**Issue by gterzian** [WebAudio/web-audio-api#2302]
Follow-up on https://github.com/WebAudio/web-audio-api/pull/2301/files#diff-5e793325cd2bfc452e268a4aa2f02b4024dd9584bd1db3c2595f61f1ecf7b985R11164 which is currently in the spec over at https://webaudio.github.io/web-audio-api/#ref-for-baseaudiocontext-associated-task-queue%E2%91%A0.

Have you considered that "spin the event-loop" might be confusing here, since there is a HTML concept of  [spinning the event-loop](https://html.spec.whatwg.org/multipage/#spin-the-event-loop), which I think doesn't match what you are trying to do here. 

The current wording could be read as if you are taking the task count from the queue, and then waiting for that number of tasks to be executed somewhere else(say on another event-loop somewhere). 

I assume you actually want the tasks in the queue to be executed, right then and there on the rendering thread, until the queue is empty?

If that is the case, you could consider wording like this:

Process the BaseAudioContext's associated task queue:

1. Let taskQueue be the BaseAudioContext's associated task queue.
2. Let oldestTask be the first runnable task in taskQueue, and remove it from taskQueue.
3. If there is no such runnable task, then jump to Process a render quantum.
3. Set the rendering loop's currently running task to oldestTask.
4. Perform oldestTask's steps.
5. Set the rendering loop currently running task back to null.
6. Microtasks: Perform a microtask checkpoint.
7. Go back to 1. 

(this is based on https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model)

**Comment by rtoy** [comment]
Teleconf: We should look into improving the text as suggested.

**Comment by padenot** [comment]
Yeah it looks like I missed the `in parallel` bit. Doing it manually like you said was indeed the intent.
