### ISSUE TITLE
Up-to-date changes list

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2314]
For the Proposed Recommendation transition.

**Comment by svgeesus** [comment]
The current changes list is "Since Candidate Recommendation of 11 June 2020 " but we also need the, hopefully much shorter, "Since [W3C Candidate Recommendation Snapshot of 14 January 2021](https://www.w3.org/TR/2021/CR-webaudio-20210114/)

**Comment by rtoy** [comment]
this [search](https://github.com/WebAudio/web-audio-api/search?q=merged%3A%3E2020-11-12&type=issues) says there were 18 merge requests sine 2020-11-13, which was the last time the change list was updated.

**Comment by svgeesus** [comment]
The changes are [not showing up](https://webaudio.github.io/web-audio-api/#changes) on the preview

**Comment by rtoy** [comment]
They show up now.  Can we close this issue?  Or maybe wait in case there are some last minute things, like PR #2318 which wasn't added.
