### ISSUE TITLE
Living Standard?

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#2320]
**Describe the Issue**

We have two options for Web Audio post-1.0. Which we pick _affects the Proposed Recommendation for Web Audio 1.0_ which is why I am raising the issue here.

Firstly, the traditional route where Web Audio 1.0 Recommendation is essentially frozen, it can list errata in a separate document and can be updated every few years to roll in the errata but can't have **substantive changes** or **new features**. All new work goes into a separate specification, like Web Audio 2.0

Secondly, and this is new, [the Proposed Rec and the Rec can allow new features](https://www.w3.org/2020/Process-20200915/#allow-new-features). (Even if we do this, we don't have to use this capability. But if we don't allow this, we cannot ever add substantive changes or new features. So we need to decide now).

The second option means that Web Audio becomes a living standard. It is _always at Recommendation_, but it can be [revised](https://www.w3.org/2020/Process-20200915/#revised-rec-substantive) to add [candidate **corrections** and candidate **additions**](https://www.w3.org/2020/Process-20200915/#candidate-correction) - changes to existing features, and brand new features.

I recommend this second, new option because there is then only one Web Audio API specification and it keeps moving forward, always reflecting the current state of the work.

**Comment by hoch** [comment]
+1 on "the Proposed Recommendation".

It sounds great for everyone, but then why does "Recommendation" exists? What's the downside of the proposed rec?

**Comment by mdjp** [comment]
+1 for the new approach from me also. It sounds very positive.  Is there a downside to going down this route, will it delay the process for v1 at all?

**Comment by rtoy** [comment]
Teleconf:  People were generally supportive of a living standard, especially since there we don't have to use this ability if we don't want to. But we had questions on exactly how this would work and how we manage getting appropriate review for new additions.

**Comment by svgeesus** [comment]
> It sounds great for everyone, but then why does "Recommendation" exists? What's the downside of the proposed rec?

Proposed Recommendation is a temporary state that only exists for 4 weeks while the W3C Advisory Committee does a review (not a technical review, at this stage). It then becomes a W3C Recommendation. 

> Is there a downside to going down this route, will it delay the process for v1 at all?

No delay.

**Comment by svgeesus** [comment]
Some useful details on the required HTML classes for candidate additions in [this specberus issue](https://github.com/w3c/specberus/issues/1077)
