### ISSUE TITLE
Speaker output enter Microphone input

### ISSUE THREAD

**Issue by ajay960singh** [WebAudio/web-audio-api#2372]
Hey guys,

We are using Web Audio API to capture Microphone of the user. 

The problem is that the microphone input also contains the speaker output when the speaker volume is high enough. We only want to get audio that a user speaks into the mic and not from the speaker. 

Our hypothesis is that since we are using earphones, the mic and speaker are close to each other so that's why mic is reading from speaker volume as well.

How can we filter this speaker output in mic input?

**Comment by hoch** [comment]
Sorry, but this is not a forum for the audio Q/A.

Perhaps googling "echo cancellation" might be helpful - Web Audio API does not have such functionality built in, but WebRTC does.
