### ISSUE TITLE
The audio track to use in `decodeAudioData` isn't specified

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#2375]
At least Firefox and Chrome both pick the first track, respectively:

https://searchfox.org/mozilla-central/source/dom/media/webaudio/MediaBufferDecoder.cpp#257
https://source.chromium.org/chromium/chromium/src/+/main:media/filters/audio_file_reader.cc;l=71;drc=570d2d089d1d822d8b29111ea92d7e2e12cce67b;bpv=1;bpt=1

**Comment by hoch** [comment]
Closed per #2376.
