### ISSUE TITLE
Access to a different output device: AudioContext.setSinkId()

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#2400]
Should be able to specify different audio devices, using media device selectors.

**Comment by hoch** [comment]
So the consensus so far:
- This API only applies to AudioContext (real-time).
- The channel count heuristics will be handled by the destination node.
- How to handle an invalid device ID:
  - AudioContext(): use the default audio device.
  - AudioContext.setSinkId(): reject the promise.
  - 'null': AudioContext will use the "muted" mode, driven by a synthetic clock on a non-realtime priority worker thread.

**Comment by hoch** [comment]
To get the API design discussion started, here's the initial WebIDL:

```webidl
enum AudioContextSinkCategory {
  "none"
}

partial interface AudioContext : BaseAudioContext {
  [SecureContext] Promise<undefined> setSinkId((DOMString or AudioContextSinkCategory) sinkId);
  readonly attribute DOMString sinkId;
  attribute EventHandler onsinkchange;
}

dictionary AudioContextOptions {
  (AudioContextLatencyCategory or double) latencyHint = "interactive";
  float sampleRate;
  (DOMString or AudioContextSinkCategory) sinkId;
}
```

Questions:
- What if the sample rate of the current device is different from the newly selected device?

**Comment by hoch** [comment]
Teleconf 5/5:
- The overall API shape looks great. @hoch will start a draft/PR based on this proposal.
- `onsinkchange` won't be fired immediately after the construction. `onstatechange` after construction can already signal that the device is running.
- `sinkId` will be `undefined` when this field is not set by the constructor options or `setSinkId()`.

**Comment by hoch** [comment]
I believe we can reuse the text from `AudioElement.setSinkId()`, but the context construction should be different. Here's my proposal:

---

When the AudioContext constructor is executed, the user agent MUST perform the following additional steps:

**AudioContext(contextOptions)**

1. Let context have a `[[SinkId]]` internal slot, initialize to “”.
2. If contextOption is given apply the options:
    1. If contextOptions.sinkId is specified, run the following substeps:
       1. if document is not allowed to use the feature identified by `“speaker-selection”`, abort these substeps.
       2. if `contextOptions.sinkId` is not the empty string and does not match any audio output device identified by the result that would be provided by `enumerateDevices()`, set `[[SinkId]]` to `contextOptions.sinkId` and abort these substeps.
       3. if contextOptions.sinkId is `“none”`, use a worker thread provided by the user agent to drive the rendering loop and abort these substeps.
       4. Otherwise switch the audio output device for context to the audio device identified by `contextOptions.sinkId`.
   3. If `contextOptions.latencyHint` is specified...(omitted)...

**AudioContext.sinkId**

This attribute contains the ID of the current audio output device, or the empty string for the user-agent default device. The attribute MUST return the value of `[[SinkId]]` internal slot upon getting.

**AudioContext.setSinkId(sinkId)**

(As mentioned above, we can reuse the text from `AudioElement.setSinkId()` but we might need some consideration on the default audio device.)


---

**Comment by hoch** [comment]
While prototyping this with @alvinjiooo in Chromium, we found some issues:

1. The union type of `DOMString or AudioContextSinkCategory` doesn't really work because both are string: we might need to use `DOMString` and handle `"none"` string internally.
2. How do we handle a new request of `setSinkId("B")' when the previous request 'setSinkId("A")' is not resolved yet?

**Comment by hoch** [comment]
More details on a solution that doesn't seem clean or practical:

```WebIDL
setSinkId((DOMString or AudioContextOptions) sinkId);
```

Where `AudioContextOptions` has:
```WebIDL
dictionary AudioContextOptions {
  (AudioContextLatencyCategory or double) latencyHint = "interactive";
  float sampleRate;
  (DOMString or AudioContextSinkOptions) sinkId;
};

dictionary AudioContextSinkOptions {
  bool useSilentSink;
}
```

With this way, we can change the latency hint and the sample rate when we change the sink.

**Comment by chrisguttandin** [comment]
Could the following be expressed in WebIDL?

```js
new AudioContext() // uses the default device since sinkId is not defined

new AudioContext({ sinkId: null }) // uses no output device since sinkId is set to null
// or
const audioContext = new AudioContext();
audioContext.setSinkId(null);

new AudioContext({ sinkId: 'abcd' }) // uses the device with the sinkId called 'abcd'
// or
const audioContext = new AudioContext();
audioContext.setSinkId('abcd');
```

If I recall correctly any member of a dictionary is nullable by default. In that case it would just be a dictionary in WebIDL.

```markdown
dictionary AudioContextOptions {
    DOMString sinkId;
}
```

Another option could be to use `false` instead of `'none'` to select no output device.

```js
new AudioContext({ sinkId: false })
// or
const audioContext = new AudioContext();
audioContext.setSinkId(false);
```

I'm not sure though if it is possible to define a union of a DOMString with a boolean in WebIDL.

**Comment by hoch** [comment]
`(DOMString or boolean)` should be possible, but it's not descriptive enough.

Using `null` is an interesting idea, and then I believe it becomes a union of `(DOMString and object)`. It should be doable but leaving the second field wide open to `object` doesn't feel great either.

I don't have a strong opinion, but the `FooBarOptions` approach is generally considered future-proof.

**Comment by bicknellr** [comment]
Have you all considered putting this functionality on `AudioDestinationNode` instead? That way you'd be able to route different streams from the same graph to different outputs. This would be useful if you want to build something that supports separate master and monitor outputs when, for example,  preparing upcoming tracks while DJing.

**Comment by hoch** [comment]
This idea also was proposed from Chrome engineers:
```js
audioContext.setSinkId("default");
audioContext.setSinkId("device-unique-id");
audioContext.setSinkId("silent");
```

No complicated types, just plain DOMStrings. This is easy and sensible, but IIUC there's no precedences in Web Audio API. We've been using enums for this purpose.

**Comment by hoch** [comment]
To recap, here are two proposals for configurability:

A. Using `AudioSinkOptions` pattern:
```js
dictionary AudioContextOptions {
  ...
  (DOMString or AudioSinkOptions) sinkId;
};

dictionary AudioSinkOptions {
  bool useSilentSink;
}

// example
audioContext.setSinkId("");
audioContext.setSinkId("device-unique-id");
audioContext.setSinkId({useSilentSink: true});
```

B. Using plain strings:
```js
dictionary AudioContextOptions {
  ...
  DOMString sinkId;
};

// example
audioContext.setSinkId("default");
audioContext.setSinkId("device-unique-id");
audioContext.setSinkId("silent");
```

**Comment by Sheraff** [comment]
Is it a guarantee that no device (sink) will ever have an ID of `"silent"` or `"default"`?

**Comment by hoch** [comment]
See examples if typical IDs over here:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices#examples

This is what I get from my MacbookPro:
```
audioinput: Default - MacBook Pro Microphone (Built-in) id = default
audioinput: MacBook Pro Microphone (Built-in) id = 5b79a953d8fb279e717b108562f28b4d934473541367b4ae41b809fedb319a8d
audiooutput: Default - MacBook Pro Speakers (Built-in) id = default
audiooutput: MacBook Pro Speakers (Built-in) id = 94508a698f07a537453f6c37a9449817ff3321b8f0869588a94ee4661350f0a8
```

> Is it a guarantee that no device (sink) will ever have an ID of "silent" or "default"?

So I would say no and yes:
1. "No": you'll get `default` as an ID. This rather works nicely with this API. You can just throw `default` and it'll work.
2. "Yes": you won't get `silent` as an ID unless there's no future spec change on `MediaDevices.enumerateDevices()`. Also the first proposal (using `AudioSinkOptions`) will be effective for this corner case.

**Comment by guest271314** [comment]
> Is it a guarantee that no device (sink) will ever have an ID of "silent" or "default"?

No, because users can create virtual devices and name them whatever they want.

**Comment by padenot** [comment]
The identifier is generated by the browser, it cannot be controlled by authors. It's different than the device name.

**Comment by guest271314** [comment]
The default speakers can be set programmatically by the user, so that, for example, the default output can be a null sink mapped to input, a microphone. The specification cannot guarantee that a device the browser interprets as default output is actually that. Similarly, `getUserMedia()` cannot guarantee a captured audio device will be a microphone; the user can remap speakers to an input and set that device as default. Test to verify.

**Comment by guest271314** [comment]
Let's illustrate problems with selecting a media device on browsers. Chrome is by dar the worst when it comes to `getUserMedia()` - there is no list of options presented in the picker - only "Microphoe", so the user really has no idea what the default device is, nor what the underlying characteristics of the device are. No matter how many issues are filed at the specification level, implementers have not provided fine-grained device descriptions and selection methods at the browser UI, for disambiguation and abaility to select _any_ media device.

Firefox 104 has defined `navigator.mediaDevices.selectAudioOutput()`, Chrome 106 does not.

So, let's observe what Firefox 104 offers us for details about audio output devices.

First let's load the kernel module to create full-duplex loopback soundcard

```
$ sudo modprobe snd-aloop
```

Now let's see how Firefox presents the options to us, and try to figure out which device is which


![Screenshot_2022-09-10_07-47-42](https://user-images.githubusercontent.com/4174848/189488693-92d8befb-2a00-4aad-9b46-bf94b65ae7e2.png)

![Screenshot_2022-09-10_07-48-17](https://user-images.githubusercontent.com/4174848/189488690-0691b8ab-7699-493c-9103-92d786c721a7.png)

Which device named "Built-in Audio Analog Stereo" and `kind` set to `'audiooutput'` is the default ouput device, which is the kernel module that is a virtual deive?

There is no way for the user to know - based solely on the UI device picker - 1) which device labelled "Built-in Audio Analog Stereo" is the default device; 2) if the user programmatically set the kernel module virtual loopback device to default.

> Is it a guarantee that no device (sink) will ever have an ID of "silent" or "default"?

So, no, the specification cannot guarantee anything re what a device will be named; if the device named "Default" is actually the default device, or just one named that by the user; 3) On Firefox 104 UI device picker can contain duplicate entries, and there is no additional device description diplayed for disambiguity; On Chrome device descriptions are non-existent.

**Comment by hoch** [comment]
As @padenot mentioned above, the `device identifier` and the label are different.

**Comment by padenot** [comment]
Update from discussing with @hoch at TPAC, this is what we're currently thinking:

```webidl
enum AudioSinkType {
  "default",
  "none",
};

dict AudioSinkOptions {
  AudioSinkType type;
};

partial interface AudioContext {
  Promise<undefined> setSinkId(AudioSinkOptions or DOMString);
}
```

`AudioSinkType` could grow other values. Something we thought about was the notion of "default device for communication use-case" (vs., say, listening to music). This is something that Android and Windows expose, at least.

**Comment by guest271314** [comment]
> As @padenot mentioned above, the `device identifier` and the label are different.

It doesn't matter. This specification cannot _guarantee_ the device selected will be an output device.

**Comment by guest271314** [comment]
@hoch My reply was addressing this question

> Is it a guarantee that no device (sink) will ever have an ID of "silent" or "default"?

The answer is no.

**Comment by guest271314** [comment]
While vendoes _can_ apply a device identifier to a device, the point is the specification cannot guarantee said device identifier, for example `"Default"` is actually an output device nor the defualt audio output device. The reason why is demostrated above. The user can set whatever device they want as default, and I don't think browsers are going to be querying the underlying OS to make sure the device is an output device. Browsers can try, as Chrome deliberately _tries_ to prevent monitor devices (output to speakers or headphones) from being captured with `navigator.mediaDevices.getUserMedia({audio: true})`, but can't, because the user can create a remapped source

```
$ pactl load-module module-remap-source \
  master="$(pactl list | grep -A2 'Source #' | grep 'Name: .*\.monitor$' | cut -d" " -f2)" \
  source_name=speakers source_properties=device.description=Speakers
```

then

```
$ pactl set-default-source speakers

```

Voila. We have _speakers_ being remapped to _microphone_ so when we call 

```
navigator.mediaDevices.getUserMedia({audio: true})
```

the devices selected as `"Default"` is actually remapped _output_ that Chrome thinks is an input, to get around Chrome refusing to capture monitor devices on Linux. `navigator.mediaDevices.enumerateDevices()` lists the device as an _input_. So whether the OS label or browser label is in question _neither_ can be relied on exclusively as reflecting what the device is. Of course the specification authors are free to _guarantee_ anything, that doesn't mean said guarantees will be true and correct for every case.

**Comment by hoch** [comment]
A slight update and one more discussion topic:
```webidl
enum AudioSinkType {
  "none"
};

dict AudioSinkOptions {
  AudioSinkType type;
};

partial interface AudioContext {
  Promise<undefined> setSinkId(AudioSinkOptions or DOMString);
}
```

`audioContext.setSinkId("")` is already available for the default device, and the concept of "default device" doesn't really fall into a "type". A device being a default one is more about its identity, less of characteristics.

Question: what would be the value of `audioContext.sinkId` when the current sink type is `"none"`?

**Comment by hoch** [comment]
We agreed upon the `sinkId` getter design. The up-to-date API shape is:

```
enum AudioSinkType {
  "none"
};

dict AudioSinkOptions {
  AudioSinkType type;
};

partial interface AudioContext {
  readonly attribute (DOMString or AudioSinkOptions) sinkId;
  Promise<undefined> setSinkId(DOMString or AudioSinkOptions);
}
```

**Comment by guest271314** [comment]
> Question: what would be the value of audioContext.sinkId when the current sink type is "none"?

`"none"`, `null`, empty string.

**Comment by mjwilson-google** [comment]
hoch, would this generally mean that after a successful setSinkId we should get exactly the same argument back when we call sinkId?

guest271314,  I think you are describing using PulseAudio commands to make a microphone / other input device appear as an output device, then setting that output device as the system default output device.  I don't think this is the usual configuration, so if someone has set up their system that way it may be that they have a reason to and the browser should respect that.  Are you concerned with the meaning of "default audio output device" in the spec?  Would it make more sense to say something like the "system-reported" default audio output device?

It seems to me that if the user configures their system to have a particular default output audio device, then that is the "real" default audio output device (even if it happens to be a microphone, /dev/null, etc.).  There isn't anything special that would make one audio device the natural default for a particular system.

Or am I misunderstanding your concern?

**Comment by hoch** [comment]
Based on the algorithm, the internal slot changes only when the transition is successful. So:

```js
await context.setSinkId('some-id'); // if this was successful
console.log(context.sinkId); // then this should be 'some-id'
```

**Comment by guest271314** [comment]
> Are you concerned with the meaning of "default audio output device" in the spec? Would it make more sense to say something like the "system-reported" default audio output device?

Yes.

I was replying to this question, specifically the language _guarantee_. 

Consider the case of all of your laptops breaking for some reason. You borrow a laptop from a colleague. You use `setSinkId("default")`. The user happens to have  given you a *nix machine where they configured their PulseAudio, PipeWire or other sound manager to do as described above; both cases; where you might not be routing the output to where you think is default guaranteed by specification. That is my input: Don't _guarantee_ named, id's match all users' expectations in all cases.
