### ISSUE TITLE
Clarify behavior when DelayNode output is connected back to delayTime AudioParam, creating a cycle

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#2401]
"It is possible to connect an AudioNode to another AudioNode which creates a
cycle: an AudioNode may connect to another AudioNode, which in turn connects
back to the first AudioNode. This is allowed only if there is at least one
DelayNode in the cycle or a NotSupportedError exception MUST be thrown."

Requiring a delay of at least 128 samples for a DelayNode in a cycle involving
the delayTime AudioParam of the DelayNode does not provide a defined behavior
for the output because the output function (cf. [1]) depends on the current
(not delayed) input at the delayTime AudioParam.

[1] https://github.com/WebAudio/web-audio-api/issues/209

**Comment by hoch** [comment]
Closing because this is already specified: 
https://www.w3.org/TR/webaudio/#rendering-loop (Step 4.7.)

**Comment by chrisguttandin** [comment]
Just for anyone else looking for the existing spec text, I think it's step 4.2.7.

https://webaudio.github.io/web-audio-api/#rendering-loop:~:text=If%20nodes%20contains%20cycles%2C%20mute%20all%20the%20AudioNodes%20that%20are%20part%20of%20this%20cycle%2C%20and%20remove%20them%20from%20nodes.
