### ISSUE TITLE
Input only / muted AudioContext

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#2411]
**Describe the feature**
I think using the Web Audio API to drive some visualization or to only analyze the incoming audio is a very common use case. I therefore think it makes sense to allow creating an `AudioContext` without any output. It could reduce the energy consumption because the output device can be turned off and such an `AudioContext` could be allowed to start without any user interaction.

**Is there a prototype?**
No.

**Describe the feature in more detail**
I think of this feature as an equivalent to `<video muted/>` which allows videos to be played without requiring any user gesture.

Given that WebAudio/web-audio-api#2400 will be added to the spec which will allow to specify the output device by setting the `sinkId` the API for muting an `AudioContext` might look like this:

```js
new AudioContext({ sinkId: null });
```

This is also related to WebAudio/web-audio-api-v2#82 which proposes to add a similar thing for the `OfflineAudioContext`.

**Comment by chrisguttandin** [comment]
I think this can be almost closed as complete now that it is possible to use `new AudioContext({ sinkId: { type: "none" } })`. Or would it be necessary to mention somewhere that this allows starting an `AudioContext` without a user gesture?

It looks like Chrome v111 which is the only browser implementing this so far still enforces the autoplay policy on a muted `AudioContext`.

I created a little demo which only creates a muted AudioContext and prints it's state on the screen. https://stackblitz.com/edit/js-wncv2l?file=index.js

**Comment by hoch** [comment]
2023 TPAC Audio WG Discussion:
Closing because the described issue has been resolved. To @chrisguttandin's point, I will create a new issue to discuss and handle it.
