### ISSUE TITLE
[audioworklet] AudioWorklets integration with WebAssembly

### ISSUE THREAD

**Issue by juj** [WebAudio/web-audio-api#2427]
Reading the AudioWorklet reference at https://github.com/WebAudio/web-audio-api/wiki/AudioWorklet-Examples and https://github.com/WebAudio/web-audio-api/wiki/AudioWorklet-IDL-Proposal, it looks like code that would utilize WebAssembly to render audio in an AudioWorklet would look something like the following:

```javascript
registerAudioWorkletProcessor('WasmInAudioWorklet', class extends AudioWorkletProcessor {
  constructor (options) {
    super(options);

    // Compile and Instantiate Wasm Module here, communicate with SharedArrayBuffer with the remaining program
    this.wasmModule = ...;
    this.wasmInstance = ...;
    this.wasmHeap = new Float32Array(...);
  }

  process(inputs, outputs, parameters) {
    for(var i = 0; i < inputs.length; ++i) { // *
      var input = inputs[i]; // *
      for(var j = 0; j < input.length; ++j) this.wasmHeap[... + j] = input[j]; // *
    } // *
    this.wasmInstance.processAudio();

    for(var i = 0; i < outputs.length; ++i) {  // *
      var output = outputs[i]; // *
      for(var j = 0; j < output.length; ++j) { // *
        output[j] = this.wasmHeap[... + j]; // *
      } // *
    } // *
  }
});
```

Talking with WebAssembly developers and @lukewagner, he is suggesting that it would be made possible to register the WebAssembly heap at AudioWorklet construction time, so that one would be able to optimize away the copies on the lines marked with stars `// *`.

Would something like this be feasible?

**Comment by hoch** [comment]
At this point, I feel like this issue almost looks like https://github.com/WebAudio/web-audio-api/issues/2442. I suggest marking this as duplicate and focus on the other thread since it has a proposal by @padenot.

**Comment by hoch** [comment]
@juj Since you opened this issue years ago - the WG believes that prioritizing [registerBuffer()](https://github.com/WebAudio/web-audio-api/issues/2442#issuecomment-842512229) proposal over this issue is more sensible at this time. What do you think?

**Comment by juj** [comment]
Yes, `registerBuffer()` would directly address this need.

**Comment by hoch** [comment]
Thank you. Then I will close this issue and the WG will focus on #2442.
