### ISSUE TITLE
Add an way to request mathematically correct oscillators

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#244]
When using an OscillatorNode as an LFO, it can be useful to get rid of the ripples inherent to high frequency limiting to get precise modulation.

This issue is about designing an API to request mathematically correct oscillator, and define them using a mathematical definition (in terms of phase, waveform shape and peak amplitude).

**Comment by mdjp** [comment]
This is a niche use case which can be covered by the Audio Worklet. Closing.
