### ISSUE TITLE
AudioContext.resample(Float32Array, sampleRate)

### ISSUE THREAD

**Issue by guest271314** [WebAudio/web-audio-api#2454]
**Describe the issue**

This issue is based on the failure of WebCodecs `'opus'` codec specification and implementation on Chromum to resample `EncodedAudioChunk` back to original sample rate as `opusenc` and `opusdec` do.

- https://bugs.chromium.org/p/chromium/issues/detail?id=1254496
- https://github.com/w3c/webcodecs/issues/378 

If it's really an implementation bug, considering filing an issue for your browser at

    * Safari (WebKit): https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Web%20Audio (WebKit bugzilla account needed).
    * Chrome (Blink): https://new.crbug.com/ (Google account needed).
    * Firefox (Gecko): https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Web%20Audio (GitHub or Mozilla Bugzilla account needed).

**Where Is It**

- https://github.com/WebAudio/web-audio-api-v2/issues/133

**Additional Information**

Workarounds are to 

1) Create an `AudioContext` with expected sample rate and create a WAV file from `Float32Array` https://plnkr.co/edit/nb1O08jar2J5Y6fQ?preview;
2) Use `opusenc` and `opusdec` from the browser https://bugs.chromium.org/p/chromium/issues/detail?id=1254496#c32.

Proposal:

`AudioContext.resample(Float32Array, sampleRate) (Promise)`

**Comment by guest271314** [comment]
Why this is needed:

Preserving integrity of original input.

Let's say I am both live streaming audio, and concurrently saving the entire concerts, albums, interviews, speech synthesis, and fragments thereof and other audio in audio as serialized WebCodecs `EncodedAudioChunk` to reduce stroage size - the only reason to compress audio using a "lossy" codec. Input is S16 PCM, 1 channel, 22050 for live speech synthesis, 2 channel 44100 for streaming, for example live system audio output to multiple peers.

For fidelity and consistency, ideally we get out what we put in to an audio codec encoder and decoder. `opusenc` and `opusdec` do that. WebCodecs `AudioEncoder` and `AudioDecoder` do not do that, and the Chromium implementation refuses to resample to original input, even though the input sample rate is encoded into the header in Chromium's own source code. 

Instead, we only get back 48000 for sample rate, whether the input sample rate is 8000, 16000, 32000, 44100, 96000, or 128000 - WebCodecs will always output 48000 sample rate `AudioData` and underlying source buffer. That measn we never get back out what we put in to WebCodecs `AudioEncoder` and `AudioDecoder`.

We live stream using the proposal mediacapture-transform, "Breakout Box", "Insertable Streams". For a 1 channel, 22050 input, which is what some speech synthesis engines use that we live stream STDOUT from the browser STDIN, it is preferable to use the same sample rate for each use case throughout the code. For live streaming whatever the user is listening to on their machine to other peers, input can be 44100 2 channel PCM, again, it would be preferable to get back that so we can set appropriate frame size for `AudioData` input to `MediaStreamTrackGenerator`, which is different for each sample rate, 220, 441, 480 per `AudioData` written to `WritableStream` of `MediaStreamTrackGenerator`. However, WebCodecs outputs first `AudioData` at `2586`, next at 2880`. That means we need to slice that data to 220 typed arrys to live stream. The work does not end there, because we now have two different sample rates to handle, the input and WebCodecs's residual undecoded 48000 sample rate from 'opus' encoding, that is the opposite of how `opusdec` works, `opusdec` uses the encoded input sample rate to output original sample rate.

I have tried various ways of creating an `AudioContext` of various sample rates, then streaming through `MediaStreamAudioDestinationNode`. Additional nodes need to be created on Chromium, which has a bug where the `MediaStreamTrack` does not output silence without a source. Therefore, we are creating triple the amount of objects to resample and continue the live stream. Where there is a dedicated web platform resampler, we should be able to at least reduce 1/3 of the workload due to lack of a canonical means to resample - the most efficiently, that is, not using multiple objects that were not intended to achive the goal of resampleing expressly, as a workaround.

**Comment by guest271314** [comment]
I tried using SpeexResampler as suggested in https://github.com/w3c/webcodecs/issues/378 yet have not been able to compile and successfully run version for browser.

Given WebCodecs refuses to resmaple to original input sample rate for Opus decoding, what is the canonical web platform procedure to resample audio?

**Comment by padenot** [comment]
Closing in favour of https://github.com/w3c/webcodecs/issues/378. We can't put this on `AudioContext` like this, because resampling is a mathematically stateful operation (any resampling algorithm except linear resampling, that leads to horrible results anyway), and having it on the `AudioContext` means that this could only resample one audio stream at a time.

It needs to be a separate object with its own state. For now, compiling a resampler to WASM is what people do, and works well in production.

**Comment by guest271314** [comment]
https://github.com/w3c/webcodecs/issues/378 does not solve anything, rather tries to avoid dealing with the fact that WebCodecs does not really decode completely - leaves the residue of Opus encoding: 48000 sample rate, the exact opposite of what `opusdec` does.

> For now, compiling a resampler to WASM is what people do, and works well in production.

I have not been able to compile a resampler to WASM. 

If you are going to suggest an alternative, then post a working example.

**Comment by guest271314** [comment]
This is what I have so far using your proposed solution. Either throws `'Chunk length should be a multiple of channels * 2 bytes'` in `processChunk()` or returns `undefined` plnkr https://plnkr.co/edit/cKW9SBDpbb8MyS8R?open=lib%2Fscript.js.

**Comment by guest271314** [comment]
@padenot Unfortunately your porposed solution produces distorted output https://github.com/geekuillaume/node-speex-resampler/issues/9.
