### ISSUE TITLE
DynamicsCompressor node should enable sidechain compression

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#246]
Side-chain compression (http://en.wikipedia.org/wiki/Dynamic_range_compression#Side-chaining) is a very common and useful music production technique.  It's used for ducking (reducing music level while speaking), de-essing, removing plosives, maximizing volume in bass-heavy music, and other techniques.

There are a couple of ways that have been suggested to add this to the Web Audio API: either exposing the reduction as an AudioNode that can be connect()ed to other AudioParams, or exposing a separate input node (with the semantic, presumably, that a separate input node would disable the signal path from the "control" input).

**Comment by rtoy** [comment]
In https://github.com/WebAudio/web-audio-api/issues/246#issuecomment-60688160, the resolution seems to be to add a second input to the `DynamicsCompressorNode` that is the control signal for the compression on the first input signal.

Are we really going to do this?  In time for v1 and CR and TPAC 2016?  We don't even know how the compressor actually works.

Adding WG review label, too.

**Comment by joeberkovitz** [comment]
@rtoy yes, I thought the sense of the group was that we needed to work out the algorithm properly before ramifying the DynamicCompressorNode with more features

**Comment by cwilso** [comment]
Note that "sidechain compression" isn't a separate feature, really - it
just means you can plug a different audio input into the control than the
signal.  To put it in analog terms, you're just soldering a jack into a
cable.

Sidechain compression is an incredibly common effect, because it's heavily
used in dance music as well as pretty much any music production (my
Novation Circuit groovebox exposes it as a primary page).  Without
sidechaining, you're pretty much relegating the usefulness of
DynamicsCompressor to a limiter inserted right before the destination so
you don't clip.

**Comment by rtoy** [comment]
I'm not debating the usefulness. I'm just wondering about the timing.  We'll be adding another "undefined" thing to an already undefined black box---a box that people have wanted defined for years but no one has actually been motivated to define.

**Comment by DonKarlssonSan** [comment]
I was really surprised to see that DynamicsCompressorNode does not support side chaining. What is the latest update on this? It's still Open. What is the next step?

**Comment by hoch** [comment]
@DonKarlssonSan The prerequisite would be writing the section for the compressor itself (which currently do not exist). After that, describing how the side chaining work would not be too hard - WG already has a rough idea on how to implement.

**Comment by joeberkovitz** [comment]
From F2F meeting: The current compressor design is quite limited and being speced as far as practical for V1 as per #10. We plan to introduce a more transparent and flexible compression/expansion/side-chaining/noise-gating approach in the next rev of this spec.

**Comment by JohnWeisz** [comment]
Hold on for a second folks, can't you just connect a control signal to the `threshold` and `knee` AudioParams (with some preprocessing) and achieve sidechain-compression? (these AudioParams are _k-rate_, but that should still yield a good result, shouldn't it?)

**Comment by mdjp** [comment]
Could be added to existing compressot and be backwards compatible.
Add one input and sidechain prop. (TPAC 17)

**Comment by mdjp** [comment]
Addressed by #12 in V2
