### ISSUE TITLE
start(currentTime + baseLatency) behavior isn't strictly defined

### ISSUE THREAD

**Issue by markdascher** [WebAudio/web-audio-api#2467]
# Describe the issue

Browser differences with `baseLatency`, `currentTime`, `start`, and `stop` prevent sounds from being scheduled precisely.

https://github.com/WebAudio/web-audio-api/issues/2397#issuecomment-257100626 suggests that `start(currentTime + baseLatency)` should reliably play a sound at the indicated time, but that's not true in all browsers. If it were, playing a click sound effect would be easy:

```js
const osc = new OscillatorNode(ctx, { frequency: 1000 });
osc.connect(ctx.destination);
const t = ctx.currentTime + ctx.baseLatency;
osc.start(t);
osc.stop(t + 0.002);
```

This works in Chrome but not in Firefox. There are a few relevant bug reports ([956574](https://bugzilla.mozilla.org/show_bug.cgi?id=956574), [966585](https://bugzilla.mozilla.org/show_bug.cgi?id=966585), [1228207](https://bugzilla.mozilla.org/show_bug.cgi?id=1228207), [1248731](https://bugzilla.mozilla.org/show_bug.cgi?id=1248731)), but they've been open for nearly a decade, and it's [unclear](https://bugzilla.mozilla.org/show_bug.cgi?id=966585#c4) if they're even considered spec violations or just optional enhancements.

I consider this a spec bug because everyone seems to have a different idea of what these values are for, making it tougher to develop a reliable app. The spec describes what the fields are without clarifying what they're useful for. (Especially baseLatency.)

If we agree that `start(currentTime + baseLatency)` should be predictable under normal circumstances, then explicit language or examples could be added to the spec. This may also make issues like #2410 less visible. I considered adding a more focused comment under that issue, as the "more global scheduling latency value" mentioned in https://github.com/WebAudio/web-audio-api/issues/2410#issuecomment-846125762 sounds like it would help. But it wouldn't actually help without tightening up the existing fields first. And once that's done, baseLatency might already serve that purpose.

# Where Is It

https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-currenttime
https://webaudio.github.io/web-audio-api/#dom-audiocontext-baselatency
https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-start
https://webaudio.github.io/web-audio-api/#dom-audioscheduledsourcenode-stop

# Additional Information

**baseLatency**
* Chrome baseLatency seems to match currentTime's increment interval.
* Firefox baseLatency is [intentionally](https://blog.paul.cx/post/audio-video-synchronization-with-the-web-audio-api/#new-members-on-the-audiocontext-interface) always zero.

**currentTime**
* Chrome currentTime is always accurate.
* Firefox currentTime can be stale, updating only between every JS task.

**start(currentTime + baseLatency)**
* Chrome schedules sound immediately, playing even if the JS task is still running.
* Firefox defers scheduling until after draining the JS task and microtask queues.

**stop(currentTime + baseLatency + 0.002)**
* Chrome plays the expected click sound immediately.
* Firefox plays nothing, since `currentTime + baseLatency + 0.002` is already in the past.

Adding a constant delay (at least 20ms) helps, but isn't reliable since the actual delay depends on how long the current task has taken, how much more time it will take, and even how many other tasks are queued. The only reliable fix is to prerender sound effects using an OfflineAudioContext, then use AudioBufferSourceNode (whose start method accepts a duration) instead of OscillatorNode.

Is there a downside to Chrome's behavior? Does the structure of Firefox (or other implementations) make it particularly difficult to standardize this behavior?

**Comment by guest271314** [comment]
I would not rely on implementation timers for precision or consistency between implementations using the same code. You can `connect()`, `disconnect()` nodes using your own timing implementation.

**Comment by guest271314** [comment]
To demonstrate Chrome's implementation of `OscillatorNode` starts immediately, without `start()` being called at all, run this in `console`

```
const ac = new AudioContext();
const osc = new OscillatorNode(ac);
const msd = new MediaStreamAudioDestinationNode(ac);
const processor = new MediaStreamTrackProcessor({track: msd.stream.getAudioTracks()[0]});
osc.connect(msd);
processor.readable.pipeTo(new WritableStream({
  write(value) {console.log(value)}
}));
```

**Comment by padenot** [comment]
No, this just shows that a `MediaStreamAudioDestinationNode` outputs silence continuously, like an `AudioDestinationNode`, as it should.

```
const ac = new AudioContext();
const osc = new OscillatorNode(ac);
const msd = new MediaStreamAudioDestinationNode(ac);
const processor = new MediaStreamTrackProcessor({track: msd.stream.getAudioTracks()[0]});
osc.connect(msd);
processor.readable.pipeTo(new WritableStream({
  write(value) {
    var f = new Float32Array(1024);
    value.copyTo(f, {planeIndex:0});
    console.log(f);
}}));
```

continously logs silent buffers.

**Comment by guest271314** [comment]
@padenot 

> No, this just shows that a MediaStreamAudioDestinationNode outputs silence continuously, like an AudioDestinationNode, as it should.

No, it does not. It shows that Chrome implementation is exactly backwards re `OsciallatorNode` that starts without `start()` being called and implementation of `MediaStreamTrack` of `kind` `"audio"` does not produce silence per specification, Issue 1262796: MediaStreamTrack does not render silence https://bugs.chromium.org/p/chromium/issues/detail?id=1262796. 

Simply comment out `OsciallatorNode` to demonstrate no output, specifically no silence produced by `MediaStreamAudioDestinationNode` on Chrome. 

```
const ac = new AudioContext();
//const osc = new OscillatorNode(ac);
const msd = new MediaStreamAudioDestinationNode(ac);
const processor = new MediaStreamTrackProcessor({track: msd.stream.getAudioTracks()[0]});
//osc.connect(msd);
processor.readable.pipeTo(new WritableStream({

    write(value) {console.log(value)}
}));
```

Chrome banned me, but didn't fix their bugs.

**Comment by guest271314** [comment]
@padenot 

Given `OscillatorNode` starts rendering output on Chrome without `start()` being called it is impossible to rely on `baseLatency` or any other timing mechanism for precision. `start()` is useless on Chrome when piping the output through a `MediaStreamAudioDestinationNode`. I encountered that issue by experimenting with WebCodecs when `AudioFrame` was initially specified and shipped on Chrome and getting or creating a `timestamp` was (is) not clear, given Chrome's internal restrictions on sample rate for `'opus'` encoding/decoding. I found that I could "piggy-back" on an `OscillatorNode` producing silence connected to an `MediaStreamAudioDestinationNode` to get `timestamp` for input to `MediaStreamTrackGenerator`.

`MediaStreamAudioDestinationNode` alone does not produce silence. `OscillatorNode` produces output immediately, I don't need to call `start()` at all. Again, exactly backwards implementation. They marked the bug as `WontFix`. If you want consistency and conformance with the specifications, you will need to file your own Chrome bugs.

Note also, Web Audio API is not the only specification that suffers from Chrome implementation of `MediaStreamTrack` of `kind` `"audio"` not rendering silence, WebRTC is also affected.

On Firefox 95 both `<audio>` elements play, on Chromium 99 neither `<audio>` element plays https://plnkr.co/edit/XNwNwANBuMzaBKxj?preview. 

```
<!DOCTYPE html>

<html>
  <head>
    <title>MediaStreamTrack does not render silence on Chromium</title>
    <!-- https://bugs.chromium.org/p/chromium/issues/detail?id=1262796 -->
    <!-- https://www.w3.org/TR/mediacapture-streams/#life-cycle-and-media-flow -->
  </head>

  <body>
    <script>
      var webrtc = new RTCPeerConnection();
      var transceiver = webrtc.addTransceiver('audio');
      var { track: webrtc_track } = transceiver.receiver;
      var webrtc_audio_element = new Audio();
      webrtc_audio_element.controls = webrtc_audio_element.autoplay = true;
      document.body.appendChild(webrtc_audio_element);
      webrtc_audio_element.srcObject = new MediaStream([webrtc_track]);
      webrtc_audio_element.ontimeupdate = webrtc_audio_element.onplaying = (
        e
      ) =>
        console.assert(e.target.currentTime > 0, [
          e.target.currentTime,
          e.type,
        ]);

      var ac = new AudioContext();
      var msd = new MediaStreamAudioDestinationNode(ac);
      var { stream } = msd;
      var [webaudio_track] = stream.getAudioTracks();
      var webaudio_element = new Audio();
      webaudio_element.controls = webaudio_element.autoplay = true;
      document.body.appendChild(webaudio_element);
      webaudio_element.srcObject = new MediaStream([webaudio_track]);
      webaudio_element.ontimeupdate = webaudio_element.onplaying = (e) =>
        console.assert(e.target.currentTime > 0, [
          e.target.currentTime,
          e.type,
        ]);
    </script>
  </body>
</html>
```

**Comment by hoch** [comment]
Closing per https://github.com/WebAudio/web-audio-api/issues/2467#issuecomment-1009012693.
