### ISSUE TITLE
Filter node pops when frequency parameter is modulated below 0

### ISSUE THREAD

**Issue by joshontheweb** [WebAudio/web-audio-api#247]
When using an oscillator to modulate the frequency parameter of a filter node you get a popping sound when the modulation dips the frequency value below 0.  A common case for this is when you are modulating the filter cutoff with an LFO.  example code here http://jsfiddle.net/hyf5N/

The desired effect is a clean cutoff to silence when the frequency value is at or below 0

**Comment by padenot** [comment]
This might be solved by #391, that proposes to clamp when an AudioParam is outside is nominal range. The nominal range for the frequency of a biquad is [10; sampleRate/2] (I'm not sure why we put a 10 in there as the lower bound, this seems restrictive).

**Comment by rtoy** [comment]
Why 10? This seems rather arbitrary.  Certainly, people won't be able to hear anything that is output from such a filter, but the filter could be going into an audioparam.

**Comment by padenot** [comment]
Yeah, zero is fine.

**Comment by joeberkovitz** [comment]
@padenot Is this being addressed in #391 by #620? It seems as though it should, but the nominal range for the biquad frequency there is -Nyquist, +Nyquist

**Comment by padenot** [comment]
Yes. The biquad should be [0, Nyquist], that was a bug I just fixed.

**Comment by rtoy** [comment]
I think this can be closed. #620 has specified the appropriate ranges, and I don't hear any pops from the test case (once you change createGainNode to createGain).
