### ISSUE TITLE
Typing error identified in one of the spec examples

### ISSUE THREAD

**Issue by guiseek** [WebAudio/web-audio-api#2472]
**Describe the issue**

The Bitcrusher class is ending with braces and parentheses, like this: `})`, instead of just braces `}`.
Probably just a typo.

**Where Is It**
In example 16, line 67, use this link to make it easier to find:
https://webaudio.github.io/web-audio-api/#AudioWorklet-Examples

**Additional Information**

It should be enough to validate the problem

**Comment by chrisguttandin** [comment]
I believe this has been fixed already. https://github.com/WebAudio/web-audio-api/commit/5ac88fa9d155b86be27db63aed3e5f120ccb4129

**Comment by mjwilson-google** [comment]
> I believe this has been fixed already. [5ac88fa](https://github.com/WebAudio/web-audio-api/commit/5ac88fa9d155b86be27db63aed3e5f120ccb4129)

I think you are correct.  Closing.
