### ISSUE TITLE
AudioWG virtual F2F: AudioOutputContext

### ISSUE THREAD

**Issue by guest271314** [WebAudio/web-audio-api#2478]
AudioWG virtual F2F:
- This is desirable, and can be implemented on some systems fully (Jack on Linux for example, or using kernel extensions on other OSes), but is out of scope of the Web Audio API. This is clearly the responsibility of the  WebRTC working group, because they deal with device access and permissions. The security considerations are extremely important: without an explicit user consent, the audio of the machine could be exfiltrated to any website.
- Closing, but we'll follow up in other groups if needed.

_Originally posted by @padenot in https://github.com/WebAudio/web-audio-api-v2/issues/106#issuecomment-846093297_

**Comment by guest271314** [comment]
**Describe the feature**
Route system or specific application audio output through a dedicated audio context intended to be utilized for this purpose.

**Is there a prototype?**
Yes.  https://github.com/guest271314/captureSystemAudio/tree/master/native_messaging/capture_system_audio.

In pertinent part re `Notification`

```
async function nativeMessageStream() {
  return new Promise(async (resolve) => {
    let permission = await navigator.permissions.query({
      name: 'notifications',
    });
    if (permission.state !== 'granted') {
      permission = await Notification.requestPermission();
    }
    if (permission.state === 'granted' || permission === 'granted') {
      const captureSystemActionNotification = new Notification('Save file?', {
        body: `Click "Activate" to capture system audio.`,
      });
      captureSystemActionNotification.onclick = async (e) => {
        onmessage = (e) => {
          if (e.origin === this.src.origin) {
            if (!this.source) {
              this.source = e.source;
            }
            if (e.data === 1) {
              this.source.postMessage(
                { type: 'start', message: this.stdin },
                '*'
              );
            }
            if (e.data === 0) {
              document
                .querySelectorAll(`[src="${this.src.href}"]`)
                .forEach((iframe) => {
                  document.body.removeChild(iframe);
                });
              onmessage = null;
            }
            if (e.data instanceof ReadableStream) {
              this.stdout = e.data;
              resolve(this.captureSystemAudio());
            }
          }
        };
        this.transferableWindow = document.createElement('iframe');
        this.transferableWindow.style.display = 'none';
        this.transferableWindow.name = location.href;
        this.transferableWindow.src = this.src.href;
        document.body.appendChild(this.transferableWindow);
      };
    }
  }).catch((err) => {
    throw err;
  });
}
```

**Describe the feature in more detail**
User performs user action, e.g., clicking a `Notification` to capture system audio output. Entire system audio output is routed through a dedicated `MediaStreamAudioDestinationNode` or dedicated `AudioWorkletProcessor`. 

User calls `stop()` on `MedisStreamAudioDestinationNode` or `return false` in `process()` to stop system audio capture.

Prior feature request in we-baudio-api-v2 https://github.com/WebAudio/web-audio-api-v2/issues/106.

https://github.com/WebAudio/web-audio-api-v2/issues/106#issuecomment-904246686

> @PaulFidika
> 
> capture user-audio on this machine, then stream or record it
> let users select in their browser what audio device they want their music to play out of
> These two requests are different; the latter is being tracked by #10 and the WG's response to the former request is laid out in https://github.com/WebAudio/web-audio-api-v2/issues/106#issuecomment-846093297. However, please feel free to open a new issue if you have different thoughts.

This is implementable on Linux, Windows, and macOS https://www.buildtoconnect.com/help/how-to-record-system-audio.

No movements elsewhere to implement this. Only piecemeal issues here and there that become circular references, e.g., https://github.com/w3c/mediacapture-output/issues/125.

I added the `Notification` to the beginning of the code to demonstrate such a requirement is trivial to implement at the implementer source code level.

Thus, there should be no issue specifying and implementing an `AudioOutputContext`.

The argument that this or that implementation does not do this or that fails when we observe that `decodeAudioData()` only supports decoding codecs that the implementation supports, particularly with regard to macOS and Safari. If you are waiting around for Safari and macOS support, you might as well abandon all hope of certain functionality being implemented https://github.com/mdn/webaudio-examples/issues/5.

**Comment by hoch** [comment]
As pointed out above, the WG still believes this is out of the scope of Web Audio API.

Is there any specific reason to create a new issue instead of following up on the existing one?

**Comment by guest271314** [comment]
> As pointed out above, the WG still believes this is out of the scope of Web Audio API.

Currently this is out of scope for all W3C working groups. Nobody has specified nor implemented system audio output capture. Every group passes the buck to a different group and nothing ever gets done to realize this.

> Is there any specific reason to create a new issue instead of following up on the existing one?

There is no existing issue that I am aware of. https://github.com/WebAudio/web-audio-api-v2/ is closed and archived.

**Comment by guest271314** [comment]
> As pointed out above, the WG still believes this is out of the scope of Web Audio API.

Web Audio working group will not be stepping on the toes of Media Capture and Streams working group by specifying and implementing this. I already filed multiple issues and PR in Media Capture and Streams and nothing got done.

I am not certain what the problem is with just specifying and implementing this, here?

**Comment by guest271314** [comment]
This specification https://github.com/w3c/mediacapture-output does not capture speakers or headphones and this PR https://github.com/w3c/mediacapture-output/pull/128 does not change that fact because ['audiooutput' does not mean system audio output](https://github.com/guest271314/SpeechSynthesisRecorder/issues/18) in Media Capture Output API - and the quality of audio when capturing using WebRTC streams via `getUserMedia()` to set [Chromium does not support capture of monitor devices by default #17](https://github.com/guest271314/SpeechSynthesisRecorder/issues/17) is subpar. We need the raw PCM to get quality streams and recording.

Currently no W3C specification or recommendation, including https://github.com/w3c/mediacapture-screen-share handles capturing system audio output. That is why this answer https://stackoverflow.com/a/70665493 at [How to capture generated audio from window.speechSynthesis.speak() call?](https://stackoverflow.com/questions/45003548/how-to-capture-generated-audio-from-window-speechsynthesis-speak-call) records only silence, and the Chrome bug/feature request filed https://bugs.chromium.org/p/chromium/issues/detail?id=1291146, unbeknown to the OP of the issue, is a duplicate of existing bugs https://bugs.chromium.org/p/chromium/issues/detail?id=1185527 and specification issues https://lists.w3.org/Archives/Public/public-speech-api/2017Jun/0000.html, https://github.com/WICG/speech-api/issues/69, https://github.com/WebAudio/web-audio-api/issues/1764.

Again, I just see people and groups passing the buck to each other and years go by without anything actually getting done for the use cases of capturing speech synthesis audio output and entire system audio output to speakers and headphones.

I demonstrated how trivial it is to just use `Notification` for prompt. I see no reason to not specify this here, in the domain of web audio. The technology exists to achieve the goal, the will to do so evidently does not.

**Comment by guest271314** [comment]
A prudent step at this stage is to simply ask @jan-ivar if specifying system audio output capture here in Web Audio API would be intruding into the domains of Media Capture and Streams, Media Capture Screen Share, or Media Capture Output?

(I don't see how that could rationally be the case where none of those specifications have the clear goal of producing that deliverable).

**Comment by padenot** [comment]
Is there anything wrong with `getDisplayMedia({audio: true})` ?

https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia

**Comment by guest271314** [comment]
> Is there anything wrong with `getDisplayMedia({audio: true})` ?
> 
> https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia

Well, that alone won't work. You still need to get video then use `removeTrack()`. Even then that will not capture output of `window.speechSynthesis.speak()`, and the quality is subpar (on Chromium/Chrome 101) compared to raw PCM that is fed to `AudioWorkletProcessor.process`.

I contacted the author of this answer https://stackoverflow.com/a/70665493 at [How to capture generated audio from window.speechSynthesis.speak() call?](https://stackoverflow.com/questions/45003548/how-to-capture-generated-audio-from-window-speechsynthesis-speak-call) to let them know their code only records silence. Try for yourself.

**Comment by guest271314** [comment]
I will point out Mozilla does not have this long-standing issue https://bugs.chromium.org/p/chromium/issues/detail?id=1185527 which has several source causes. Thus for interoperabablity we need to just specify and implement system audio output capture to avoid ambiguity and finally resolve this issue.

**Comment by guest271314** [comment]
Additionally, `getDisplayMedia({video: true, audio: true})` only captures the _Tab_. When I run `mpv video.mkv` where audio and video are output, `getDisplayMedia({video: true, audio: true})` only captures the application window, on Chromium 101 the exotic `FocasableMediaStreamTrack`, on Firefox 98 a single `MediaStreamTrack` of `kind` `"audio"`. `getDisplayMedia()` doesn't meet the requirement of the use cases.

**Comment by padenot** [comment]
It only captures the tab on Linux and macOS, but captures the computer audio on Windows and Chrome OS. It's an OS limitation, there's not much spec work to do.

**Comment by guest271314** [comment]
> It only captures the tab on Linux and macOS, but captures the computer audio on Windows and Chrome OS. It's an OS limitation, there's not much spec work to do.

Can you clarify what you are talking about, `getDisplayMedia()`? There is no OS limitation for capturing entire system audio or specific audio device, e.g., `speech-dispatcher`, on Linux. Any limitation on Chrome is a self-imposed limitation by Chrome authors. Spec-wise we certainly can spell out capabilities that exist which will further expose Chrome authors just refuse to implement, right now.

**Comment by guest271314** [comment]
>  It's an OS limitation, there's not much spec work to do.

To demonstrate there is no limitation on Linux, rather a self-imposed Chrome limitation see https://github.com/guest271314/captureSystemAudio#pulseaudio-module-remap-source, https://aweirdimagination.net/2020/07/19/virtual-microphone-using-gstreamer-and-pulseaudio/

```
pactl load-module module-remap-source \
  master=@DEFAULT_MONITOR@ \
  source_name=virtmic source_properties=device.description=Virtual_Microphone
```

```
var recorder;
const devices = await navigator.mediaDevices.enumerateDevices();
const device = devices.find(({label})=>label === 'Virtual_Microphone');
const stream = await navigator.mediaDevices.getUserMedia({
          audio: {
            deviceId: {
              exact: device.deviceId
            },
            echoCancellation: false,
            noiseSupression: false,
            autoGainControl: false,
            channelCount: 2,
          },
        });
const [track] = stream.getAudioTracks();
console.log(devices, track.label, track.getSettings(), await track.getConstraints());
// do stuff with rempapped monitor device
recorder = new MediaRecorder(stream);
recorder.ondataavailable = e => console.log(URL.createObjectURL(e.data));
recorder.onstop = () => recorder.stream.getAudioTracks()[0].stop();
recorder.start();
setTimeout(()=>recorder.stop(), 10000);
```

**Comment by guest271314** [comment]
I haven't tried this on Mac, others have faced this https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux#prologue

> Screensharing with desktop audio was recently fixed on Mac OS on the official client only through a proprietary hack since getting desktop audio on Mac isn't easy and you need something like Soundflower to interact with the kernel and electron/chromium don't have such functionality.

- https://github.com/akhudek/Soundflower
- https://github.com/karaggeorge/kap-soundflower

**Comment by padenot** [comment]
Yes, it's possible on Linux desktop as well, but not possible without third-party software on macOS.

Anyway, there is nothing missing on the web platform for this feature, I'm closing this.

**Comment by padenot** [comment]
`getDisplayMedia({audio: true})` allows capturing the device's output, as you note.

**Comment by guest271314** [comment]
Not it does not. It only captures the Tab. Not entire system audio.

**Comment by guest271314** [comment]
We cannot capture, for example, Web Speech API output on that same Tab.

There is plenty third-party software in Firefox source code, and Chrome.

I have no idea why you closed this.
