### ISSUE TITLE
MediaStreamAudioSourceNode memory leak, OR no way to destroy node

### ISSUE THREAD

**Issue by vneznaikin** [WebAudio/web-audio-api#2484]
I am using MediaStreamAudioSourceNode to connect via WebRTC. Everything works fine until the moment when I need to end the call and open a new connection. What am I doing:
- when the call starts
```
this.peerConnection.ontrack = (e) => {
this.stream = e.streams[0];
...
this.source = this.context.createMediaStreamSource(this.stream);
...
```
- when the call end
```
  this.peerConnection.close()
...
  this.stream.getAudioTracks().forEach(track => {
        track.stop()
        this.stream.removeTrack(track);
   });
...
this.source.disconnect(this.destination)
this.source.disconnect()
this.source = null
```
After remove all tracks MediaStream have status "inactive"
But node MediaStreamAudioSource still EXIST.
I can see it through the Chrome app "Audion"

I tried not to recreate MediaStreamAudioSourceNode , just delete tracks and add new ones to MediaStream, but it's not working

I found a similar issue on [stackoverflow](https://stackoverflow.com/questions/64764193/mediastreamaudiosourcenode-memory-leak), without any solution

As a result I didn't find any way to destroy the MediaStreamAudioSourceNode . Maybe I'm missing something?

**Comment by hoch** [comment]
This looks like a GC issue and maybe browser-specific. Please file an issue to the bug tracker for the browser that you used.
- Chrome: [crbug.com](https://bugs.chromium.org/p/chromium/issues/entry)
- FireFox: https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla
- Safari: [webkit](https://webkit.org/reporting-bugs/)

**Comment by hoch** [comment]
Please file an issue [here](https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EWebAudio) with a small repro case.

This forum is for spec discussion, and the problem reported above is an implementation issue.
