### ISSUE TITLE
Specify what should happen when the input channel count changes for delay nodes

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#25]
> Originally reported on W3C Bugzilla [ISSUE-21426](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21426) Thu, 28 Mar 2013 17:05:04 GMT
> Reported by Ehsan Akhgari [:ehsan]
> Assigned to 

For example, when the input channel count increases, it's not clear whether we need to playback silence or an upmixed version of the delayed buffer.  The rather might not be efficient to implement because it might require a large amount of work when processing the first buffer after the input channel count change.

**Comment by padenot** [comment]
Do we think Karl's way of doing things here is what we want to do? If yes, we can start speccing.

**Comment by joeberkovitz** [comment]
Resolution: Yes, we like Karl's way of doing things. Rephrasing this: up/downmix any block of samples in the stored delay line state as soon as they are required to be mixed with freshly injected samples from the input.
