### ISSUE TITLE
maxChannelCount vs sinkId

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-audio-api#2528]
**Describe the issue**

Currently the setter of the `channelCount` property of the `AudioDestinationNode` is meant to fire an `IndexSizeError` if the "value is not within the valid range".

But now that it's possible to change the audio output device the valid range might change at any time. Let's imagine the currently used audio output device has 6 channels and all 6 of them are in use.

```js
audioContext.destination.channelCount = 6;
```

But later on the audio output device gets changed and the newly selected device only supports 2 channels.

```js
audioContext.setSinkId('id-of-a-device-with-two-channels');
```

I guess this should throw an `IndexSizeError`, too.

**Where Is It**

https://webaudio.github.io/web-audio-api/#AudioDestinationNode

**Additional Information**

I'm not sure if this case is already handled somewhere in the spec. Theoretically it was already possible before to change the audio output device without `setSinkId()` by changing the default audio output device on the OS level.

**Comment by orottier** [comment]
In similar vein: in the future we can choose a render quantum size optimized for the current sink (AudioContextRenderSizeCategory::hardware) which should remain constant for the lifetime of the BaseAudioContext. But what should happen when we change the sinkId?

**Comment by guest271314** [comment]
A tentative solution without a specification change is to use `MediaStreamAudioDestinationNode` with `applyConstraints()` to declaratively set the `channelCount`.

**Comment by mdjp** [comment]
After discussion,  we will continue to use the downmixing mechanism in the API. A new issue will be raised to ensure that an event is triggered on device change.

**Comment by padenot** [comment]
> After discussion, we will continue to use the downmixing mechanism in the API. A new issue will be raised to ensure that an event is triggered on device change.

This is https://github.com/WebAudio/web-audio-api/issues/2532.
