### ISSUE TITLE
Audio quality metrics similar to RTCAudioPlayoutStats

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#2542]
Would it be useful to have audio quality metrics in Web Audio API?

An example in WebRTC Stats Spec:
https://www.w3.org/TR/2023/CRD-webrtc-stats-20230303/#playoutstats-dict*

Although the current status of the example above seems a bit controversial (https://github.com/w3c/webrtc-stats/issues/742, https://github.com/w3c/webrtc-stats/issues/741), **on 3/9 the Audio WG members had a general consensus that we need a way to inspect buffer under/overrun at the boundary between MediaStream (push model) and Web Audio API (pull model)**. The group also agreed that the MediaStreamTrack might be a better place to have such API.

This is a reference point of the group discussion, but ultimately we might want to voice our request to the relevant spec/WG.

**Comment by hoch** [comment]
Teleconference on 4/6:
We raised issues to the relevant WG (WebRTC WG) and there is no action item for the Audio WG.

**Comment by mehagar** [comment]
Would https://github.com/w3c/mediacapture-extensions/pull/117 solve this?
