### ISSUE TITLE
TAG Issue: Explaining ("De-sugaring") the `*Node` Types

### ISSUE THREAD

**Issue by chrislo** [WebAudio/web-audio-api#255]
The following issue was raised by the W3C TAG as part of their [review of the Web Audio API](https://github.com/w3ctag/spec-reviews/blob/master/2013/07/WebAudio.md)
### Explaining ("De-sugaring") the `*Node` Types

On the back of a repaired `ScriptProcessorNode` definition, the spec should contain tight descriptions of the built-in library of the `AudioNode` subclasses; preferably in the form of script which could be executed in a `ScriptProcessorNode`.

_Obviously_ we do not recommend that implementations lean on this sort of self-hosting for production systems. It is, however, clear that without such a detailed description of the expected algorithms, compatibility between implementations cannot be guaranteed, nor can conformance with the spec be meaningfully measured. This de-sugaring-as-spec-exercise would be helpful for the testing of the system and for users who will at a later time want to know _exactly_ what the system is expected to be doing for them.

We imagine an appendix of the current spec that includes such de-sugarings and test suites built on them.

**Comment by joeberkovitz** [comment]
How far do we want to go with this for V1?

**Comment by billhofmann** [comment]
I'd propose we not hold for this.

**Comment by joeberkovitz** [comment]
I agree with @billhofmann but adding discussion label for TPAC 2015

**Comment by joeberkovitz** [comment]
TPAC: Not a V1 issue, but make progress over time on this.

**Comment by mdjp** [comment]
Going forwards, we will take this approach to developing new nodes and additional functionality in existing nodes.  
Nodes in V1 spec will be tackled retrospectively.
