### ISSUE TITLE
Use of deprecated `DomException` types.

### ISSUE THREAD

**Issue by KristofferStrube** [WebAudio/web-audio-api#2551]
**Describe the issue**

The specs [sepcifies](https://webaudio.github.io/web-audio-api/#dom-audionode-connect-destinationparam-output-destinationparam) that the [connect](https://webaudio.github.io/web-audio-api/#dom-audionode-connect-destinationparam-output) method MUST throw a [InvalidAccessError](https://webidl.spec.whatwg.org/#invalidaccesserror) DOMException if the destinationNode parameter is from another AudioContext. This error is deprecated and we should instead use [NotSupportedError](https://webidl.spec.whatwg.org/#notsupportederror).

This is the same case for the output parameter where the specs specify that the [connect](https://webaudio.github.io/web-audio-api/#dom-audionode-connect-destinationparam-output) method MUST throw a [IndexSizeError](https://webidl.spec.whatwg.org/#indexsizeerror) (which is also deprecated) if the index is outside the valid range of indices. Instead of this, we should use the ECMA Script [RangeError](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-native-error-types-used-in-this-standard-rangeerror).

**Where Is It**

This is one of the places that this is mentioned in the specs: https://webaudio.github.io/web-audio-api/#dom-audionode-connect-destinationparam-output

But there are many more places that it is used in the specs.

**Additional Information**

I'm not sure if this is something we actually want to change since many might depend on these deprecated errors being emitted.

**Comment by padenot** [comment]
Thanks for the issue. As you note, it's not worth it to change this. Those errors are deprecated but (and I quote the spec):

> are kept for legacy purposes

This is the case we are in here. This part of the Web Audio API standard dates from 2011 or so, it's fairly old.
