### ISSUE TITLE
Average AudioContext.outputLatency

### ISSUE THREAD

**Issue by henbos** [WebAudio/web-audio-api#2563]
**Describe the feature**
Output latency is an instantaneous value. Some apps might be interested in the average, minimum and maximum output latency over an app-defined interval without having to do high frequency polling. Avoiding high frequency polling when not needed should not only be convenient but also have performance benefits.

**Is there a prototype?**
No but outputLatency is shipped so shimming based on high frequency polling is possible.

**Describe the feature in more detail**
Output latency can be measured via [AudioContext.outputLatency](https://webaudio.github.io/web-audio-api/#dom-audiocontext-outputlatency), which can be useful for synchronization use cases when polling at high frequency:

> The [outputLatency](https://webaudio.github.io/web-audio-api/#dom-audiocontext-outputlatency) attribute value may change while the context is running or the associated audio output device changes. It is useful to query this value frequently when accurate synchronization is required.

In Chromium, [this](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/audio/audio_destination.cc;l=506;drc=8e78783dc1f7007bad46d657c9f332614e240fd8) can change [all the time](https://source.chromium.org/chromium/chromium/src/+/main:media/base/audio_renderer_sink.h;l=36;drc=8e78783dc1f7007bad46d657c9f332614e240fd8).

But apps may want to monitor this less frequently in which case an infrequent poll of `outputLatency` may not be as representative. In [MediaStreamTrackAudioStats](https://w3c.github.io/mediacapture-extensions/#the-mediastreamtrackaudiostats-interface), the instantaneous `latency` value is complemented with a min, max and average latency since the last time the app called `resetLatency()`, allowing the app to easily control what periods of time this should be measured over.

Should WebAudio use the same pattern for its latency? Proposal:
```
partial interface AudioContext {
   // Today
   readonly attribute double outputLatency;
   // Proposal
   readonly attribute double averageOutputLatency;
   readonly attribute double minimumOutputLatency;
   readonly attribute double maximumOutputLatency;
   undefined resetOutputLatency();
};
```

**Comment by henbos** [comment]
WDYT @o1ka @hoch @padenot ?

**Comment by chrisguttandin** [comment]
I was curious how fluctuant the values are in practice. I built a little demo to check it.

https://stackblitz.com/edit/js-jfkhex?file=index.js,index.html

When testing this on macOS with the internal speakers I get a constant `outputLatency` value for Chrome and Firefox. The demo doesn't work in Safari because it doesn't implement `outputLatency` and has a [bug](https://bugs.webkit.org/show_bug.cgi?id=264247) in its `getOutputTimestamp()` implementation.

My test is obviously very simple and not really a real life audio app. @henbos Is there anything obvious I could do to provoke a changing `outputLatency`?

**Comment by o1ka** [comment]
@henbos SG, though I'd rather call it resetOutputLatencyStats(), to not confuse with outputLatency.

**Comment by hoch** [comment]
Relatedly https://github.com/WICG/proposals/issues/142

**Comment by hoch** [comment]
Since this idea is pursued by the WICG issue link, I believe we can close this.
