### ISSUE TITLE
AudioDestinationNode numberOfOutputs=1 according to the spec, but all browsers return 0

### ISSUE THREAD

**Issue by orottier** [WebAudio/web-audio-api#2578]
**Describe the issue**

The specification lists `numberOfOutputs = 1` for the AudioDestinationNode, but Firefox, Chrome and Safari all report 0.

**Where Is It**

https://webaudio.github.io/web-audio-api/#AudioDestinationNode

Also, the WPT suite asserts the value of 0:
https://github.com/web-platform-tests/wpt/blob/master/webaudio/the-audio-api/the-audionode-interface/audionode.html#L41

**Additional Information**

I actually think it would be a nice feature to be able to put things *after* the destination node, but it is probably wisest to adjust the spec. I could write a PR for that.

The following text should also probably dropped:

> The output of a [AudioDestinationNode](https://webaudio.github.io/web-audio-api/#AudioDestinationNode) is produced by [summing its input](https://webaudio.github.io/web-audio-api/#channel-up-mixing-and-down-mixing), allowing to capture the output of an [AudioContext](https://webaudio.github.io/web-audio-api/#AudioContext) into, for example, a [MediaStreamAudioDestinationNode](https://webaudio.github.io/web-audio-api/#MediaStreamAudioDestinationNode), or a MediaRecorder (described in [[mediastream-recording]](https://webaudio.github.io/web-audio-api/#biblio-mediastream-recording)).

**Comment by chrisguttandin** [comment]
Wouldn't it be better to update the test?

FWIW standardized-audio-context supports it: https://github.com/search?q=repo%3Achrisguttandin%2Fstandardized-audio-context%20%23168&type=code.

**Comment by padenot** [comment]
This is just because we haven't implemented it. We've intentionally spec-ced it that way precisely for the reasons you describe.

I still intend to implement it in Firefox because it's very nice. Modifying the WPT is what we should do, and clearly show that the 3 main browser engines haven't implemented it.

**Comment by orottier** [comment]
Alright then! https://github.com/web-platform-tests/wpt/pull/45278
