### ISSUE TITLE
AudioContext stuck on "interrupted" in Safari

### ISSUE THREAD

**Issue by methot-ilya-3ds** [WebAudio/web-audio-api#2585]
I have a website which starts an audiocontext. This site works with all browsers on laptops, and works on Android l. However, for IOS devices the audiocontext seems to be stuck on the "interrupted" state.

Running AudioContext.resume() on user input does not seem to change the state of the context. Whenever I run resume I can see that the state has not changed via the debugger.

Is there something I am missing? Am I supposed to await the .resume function?

I've also tried to do AudioContext.resume().then(()=>) with not luck either.

**Comment by mjwilson-google** [comment]
Please see #2392 -- Web Audio still hasn't specified how to handle "interrupted" or AudioSession integration.

This repository is only for working on the Web Audio specification.  For support with the iOS Safari implementation please ask on https://bugs.webkit.org/, StackOverflow, or the WebAudio Slack Channel as appropriate.
