### ISSUE TITLE
error event uses ErrorEvent but it doesn't fill in any of its fields

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-audio-api#2590]
The new `error` event, added in https://github.com/WebAudio/web-audio-api/commit/116612c14fef9299d4dd86181a72e1a3032430c4, says to fire the event using the `ErrorEvent` interface.

However, the `ErrorEvent` interface is meant for use when there's a JavaScript exception value (`event.error`), and then you have to fill in its other properties as well. (`message`, `filename`, `lineno`, `colno`.)

From what I can gather reading the spec diff, there is no JavaScript exception value in question. This is meant to signal underlying errors from the audio hardware/software stack. So, `ErrorEvent` is not appropriate. You can just use the default `Event`.

**Comment by hoch** [comment]
Thanks for your input, @domenic!

The last paragraph makes sense to me (and it is a welcome change), but dispatching non-error event via `onerror` seems strange. What are your thoughts on this?

cc @padenot

**Comment by domenic** [comment]
That's a pretty common pattern, e.g. that's what `img` does for problems loading or decoding images.
