### ISSUE TITLE
Use consistent language and approach to document algorithms

### ISSUE THREAD

**Issue by chrislo** [WebAudio/web-audio-api#260]
The following issue was raised by the W3C TAG as part of their [review of the Web Audio API](https://github.com/w3ctag/spec-reviews/blob/master/2013/07/WebAudio.md)

----------------

What language are the examples in Section 11 written in? Can it be executed?

**Comment by joeberkovitz** [comment]
Are these examples still relevant given the changes to PannerNode?

**Comment by padenot** [comment]
We could simply unify all the codes in the spec (whether normative or informative) to be JavaScript. We may need to define the vector operations. Then, it's very possible that it could be executed.

**Comment by joeberkovitz** [comment]
Resolution: we will use JavaScript
