### ISSUE TITLE
Spatial audio stopped working

### ISSUE THREAD

**Issue by LeXXik** [WebAudio/web-audio-api#2609]
Noticed the spatial sound stopped working for me. Using latest Safari on Mac and Chrome on Win11. Trying the example given provided on MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics

https://mdn.github.io/webaudio-examples/spatialization/

Some issue with panning?

**Comment by padenot** [comment]
This sounds like an implementation bug, please file a bug in the vendor's bug tracker:

- WebKit (Safari): https://bugs.webkit.org/enter_bug.cgi?product=WebKit&component=Web%20Audio (WebKit bugzilla account needed).
- Blink (Chrome): https://new.crbug.com/ (Google account needed).
- Gecko (Firefox): https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Web%20Audio (GitHub or Mozilla Bugzilla account needed).

This works for me on at least Chrome and Firefox, and we haven't changed anything in the spec related to this, and I know I haven't changed anything in Firefox in a very long time.
