### ISSUE TITLE
Latest published version link in Editor's Draft is broken

### ISSUE THREAD

**Issue by mjwilson-google** [WebAudio/web-audio-api#2612]
The [Editor's Draft ](https://webaudio.github.io/web-audio-api/) has "Latest published version" linked as https://www.w3.org/TR/webaudio-11/ but the new FPWD is actually at https://www.w3.org/TR/webaudio-1.1/

[index.bs](https://github.com/WebAudio/web-audio-api/blob/main/index.bs#L9) seems to have the correct link so I'm not sure why this is happening.

**Comment by hoch** [comment]
@svgeesus Chris, could you take a look at this issue?

**Comment by svgeesus** [comment]
I notice the Editors Draft is dated which is before the FPWD. So I added the FPWD to the Previous Version list and hopefully that small change triggers bikeshed to regenerate it.

**Comment by svgeesus** [comment]
Ah, I also see

> Notice:  A new release of pip is available: 23.0.1 -> 24.0
Notice:  To update, run: pip install --upgrade pip
Bikeshed now requires Python 3.9; you are on 3.7.17.
    If you're seeing this message in your CI run, you are
    likely specifying an old OS; try `ubuntu-latest`.
    If you're seeing this on the command line, see the docs
    for instructions:
    https://speced.github.io/bikeshed/#installing

**Comment by hoch** [comment]
Updated the python and the Github action to fix the build failure. Also confirmed the published page has the current link now.
