### ISSUE TITLE
Need a AudioMediaStreamTrack-based StreamSourceNode factory method

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#264]
Comment from Stefan Håkansson LK:
http://lists.w3.org/Archives/Public/public-audio/2013OctDec/0078.html

In section 4.24 (_Note: probably referring to 4.25. The MediaStreamAudioSourceNode Interface_) it is said that "The first AudioMediaStreamTrack from 
the MediaStream will be used as a source of audio."

Which audio track that is the first one is undefined (in the case when 
there is more than one). I think it would make much more sense to deal 
directly with a MediaStreamTrack (of kind audio) in this API (which 
should as a consequence be renamed to "MediaStreamTrackAudioSourceNode").

And it would probably make sense to rename "MediaStreamAudioDestinationNode" to "MediaStreamTrackAudioDestinationNode", and have it produce a MediaStreamTrack.

**Comment by joeberkovitz** [comment]
This is ready for editing since it can be taken together with #132 whose resolution is well defined.

**Comment by padenot** [comment]
This issue is about speccing a way of choosing the right track in the stream.
