### ISSUE TITLE
Lack of support for continuous playback of javascript synthesized consecutive audio buffers causes audio artifacts.

### ISSUE THREAD

**Issue by ILOVEPIE** [WebAudio/web-audio-api#265]
The specification/implementations do not address this crucial aspect of modern audio apis. The reason why this is so important is that most modern game-engines require these features in order to provide varied and streaming audio, the current solution it seems is to provide pre-canned audio files which are played back when events occur but this results in games sounding horrible, you get a few pre-recorded audio pieces in a loop. The ability to continuously play back audio that has been synthesized in chunks is essential, calling a JavaScript node continuously is inefficient in a large application. The specification needs a way to schedule exact, and precise streaming playback of consecutive audio buffers. The simplest solution to this is to add a startImmediatelyAfter() function, but their are other ways as well (for instance providing a start after x number of samples method).

Explanation of the issue/test case:
https://dl.dropboxusercontent.com/u/40949268/Bugs/beep.html

Relevant emscripten Code:
https://github.com/kripken/emscripten/blob/a08253a00a0c37563ffabb3163de8088bca23933/src/library_sdl.js#L1481

Original topic:
http://lists.w3.org/Archives/Public/public-audio/2013AprJun/0546.html

**Comment by joeberkovitz** [comment]
Now that AudioContext supports arbitrary sample rates, this problem might be mitigated since the context can be requested to use the exact sample rate of the buffers being queued, meaning that interpolation between samples at buffer boundaries could be avoided.

**Comment by svgeesus** [comment]
padenot: trivially implementable with worklet and sharred array buffer
