### ISSUE TITLE
OscillatorNode's frequency attributes nominal range should be specced

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#273]
I think we should spec the acceptable range for the `frequency` parameter. In particular, what happens when the frequency is negative or null. Here is a proposal:

- If the frequency is set to a negative number, then the phase is reversed. This can potentially be useful.
- If the frequency is set to null, then the actual frequency used and reflected is the previous frequency, i.e. the new frequency is silently ignored. Not throwing an exception seems better when doing sweeps from negative to positive frequency.

**Comment by rtoy** [comment]
What is the resolution here? There are two competing proposals, but no apparent consensus.

**Comment by joeberkovitz** [comment]
This appears to be in progress via #391 and #620. Closing.
