### ISSUE TITLE
Dynamic modification of looping: (4.10.3) doesn't specify what happens when setting 'loop' to false on a playing source

### ISSUE THREAD

**Issue by Cwiiis** [WebAudio/web-audio-api#281]
It is unspecified, it would appear, what should happen to a started, looping sound source when you set the 'loop' parameter to false.

In Firefox, this is equivalent to calling stop(0), but I would suggest that it should play the source until the end of the buffer and then stop, as there is currently no trivial way of doing this.

**Comment by cwilso** [comment]
The desired behavior (according to WG accord) is that if loop changed from true to false while in the loop, the playback should continue from the current position as if loop had always been false (i.e. exiting the loopEnd and continuing to play the rest of the buffer).

**Comment by Cwiiis** [comment]
So exactly the behaviour I said would be nice in the initial comment :)
