### ISSUE TITLE
Multiple calls to stop allowed

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#297]
In issue #15, multiple calls to stop are allowed.  However the last sentence in the first paragraph of section 2.9 still says stop can only be called once.  This sentence could probably be deleted.

Also, the description of the when parameter to start says start can only be called once. I think it would be clearer if it were mentioned in the first paragraph instead of being buried in the description of the when parameter.

**Comment by billhofmann** [comment]
Addressed by pull request #576
