### ISSUE TITLE
decodeAudioData: option to disable automatic resampling to context rate

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#30]
> Originally reported on W3C Bugzilla [ISSUE-21519](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21519) Tue, 02 Apr 2013 14:41:41 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26 

Add  an optional 4th argument for decodeAudioData that disables automatic sample rate conversion.

**Comment by skratchdot** [comment]
I added a comment in #300, but I would really like to have access to the original non-resampled rate (if it's available).  I'm not sure if I can squeeze that request into this bug, or if I should log something new.  

For instance, assume I have a .wav file that has a sampling rate of 11025.  Currently, I call decodeAudioData on that file, and I get an audioBuffer with a sampling rate of 44100.  This is fine, but it would be great if there was a 2nd argument to the DecodeSuccessCallback callback that contained some additional information (originalSamplingRate at least- perhaps other info like originalNumberOfChannels, originalMimeType, etc).

I can describe my use-case if needed, but I would guess this info might be useful to other people as well.

**Comment by lonce** [comment]
Yes, the ability to get the original audio file data would be very useful.
Also, it seems inconsistent that decodeAudioData automatically resamples, but leaves the original NumberOfChannels no matter what the AudioContxt number of channels is!

**Comment by rtoy** [comment]
Leaving the number of channels as the original makes sense.  You can do all kinds of multi-channel processing and then mix the result up (or down) for the number of channels in the context.

**Comment by rtoy** [comment]
This is part of the "current sprint".  How do we want to do this? To kind of match the other things we're doing, I propose an optional fourth parameter that is a dictionary with the single option of "disableResampling", which defaults to false to preserve current behavior.

**Comment by padenot** [comment]
That makes sense. This could be used in the future to specify in-memory compression settings and things like that.

**Comment by rtoy** [comment]
Also, perhaps we can allow

    Promise<AudioBuffer> decodeAudioData(ArrayBuffer audioData, DecodeAudioDataOptions options);

I think this is more natural if want to support promise nicely.  It would be a pain to have to specify the optional callbacks if we want to disable resampling and if we were using the promise pattern to handle decode success and failure.

**Comment by rtoy** [comment]
The proposal in https://github.com/WebAudio/web-audio-api/issues/30#issuecomment-228441793 won't work.  IDL does not distinguish between a callback and a dictionary (both are objects), so it can't disambiguate the call to the two methods.

We will have to do something else, like add the optional dictionary after the error callback.  Or create a new method for this.  Or something.

**Comment by joeberkovitz** [comment]
Resolved on WG call today that we will move to v.next as part of designing a more thorough decoding API that includes progress callbacks.

**Comment by rtoy** [comment]
Closing this CL, per https://github.com/WebAudio/web-audio-api/issues/30#issuecomment-235950008

**Comment by Pomax** [comment]
As this issue is pretty high on Google's list when searching how to get the sampleRate of an audio file _before_ building a context for it, what was the result? Comment #30 mentions it got moved to the next version, but that was almost 4 years ago and as far as I can find online, no way to discover this value short of "knowing the file format, and performing a partial file-format-appropriate byte examination". 

Can this be confirmed or refuted, so that others who find this issue hoping to find a solution to their problem won't still be lost?

**Comment by padenot** [comment]
The consensus is that all this work in now in the hands of the [web codec](https://github.com/WICG/web-codecs) group, where a good solution for this is being designed.

The Web Audio API's scope in V2 explicitly excludes any audio decoding and encoding, and focuses on processing.

**Comment by guest271314** [comment]
> The consensus is that all this work in now in the hands of the [web codec](https://github.com/WICG/web-codecs) group, where a good solution for this is being designed.
> 
> The Web Audio API's scope in V2 explicitly excludes any audio decoding and encoding, and focuses on processing.

Where is WebCodecs working on this?

This concern https://github.com/WebAudio/web-audio-api/issues/30#issuecomment-60283637 

> This issue is very important as otherwise it is not possible to use the built-in codecs to acquire an unmunged version of the data in a decoded file. The desired-rate idea proposed by cwilso seems fancy but maybe is useful.

is real and ripe in WebCodecs right now, where `AudioEncoder` to `AudioDecoder` for `'opus'` codecs ignores the input sample rate, always decodes to `48000` sample rate https://bugs.chromium.org/p/chromium/issues/detail?id=1254496, unlike `opusenc` and `opusdec` https://github.com/xiph/opus-tools/issues/65.

In this issue https://github.com/w3c/webcodecs/issues/378 the work of resampling is being referred back to WebAudio, while the short coming of resampling back to original sample rate, which is what `opusdec` does, is not listed as an option.

**Comment by guest271314** [comment]
For WAV files the original sample rate can be retrieved by reading a `Uint32Array` representation of bytes 24-28, see http://soundfile.sapp.org/doc/WaveFormat/

          fetch(url).then(async (r) => {
            if (r.headers.get('content-type').includes('wav')) {
              return {
                INPUT_SAMPLE_RATE_WAV: new Uint32Array(
                  (await r.arrayBuffer()).slice(24, 28)
                )[0],
              };
            }
          }).then(console.log).catch(console.error);

plnkr https://plnkr.co/edit/4IxTb0jbsQYoMLOr?open=lib%2Fscript.js

Per https://github.com/WebAudio/web-audio-api-v2/issues/133#issuecomment-908483610 

> Opus always works in 48kHz internally

**Comment by guest271314** [comment]
To get the sample rate of any audio file `<audio>`, `HTMLMediaElement.captureStream()`, `MediaStreamTrackProcessor` can be used to get `sampleRate` from the `AudioData` of the first `read()`.
```

<!DOCTYPE html>

<html>
  <head> </head>

  <body>
    <pre></pre>
    <script>
      Promise.all(
        ['./piano3.wav', './test.wav', 'ImperialMarch60.opus'].map((url) =>
          fetch(url).then(async (r) => {
            const blob = await r.blob();
            const audio = new Audio();
            audio.autoplay = true;
            return new Promise(async (resolve) => {
              audio.onplay = async (e) => {
                audio.onplay = null;
                const stream = audio.captureStream();
                const [track] = stream.getAudioTracks();
                const processor = new MediaStreamTrackProcessor({ track });
                const { readable } = processor;
                const reader = readable.getReader();
                await reader.read().then(async ({ value: { sampleRate } }) => {
                  resolve(JSON.stringify({ sampleRate }, null, 2));
                  track.stop();
                  audio.pause();
                  URL.revokeObjectURL(audio.src);
                  try {
                    await reader.cancel();
                    await reader.closed;
                  } catch (err) {
                    console.log(err);
                  }
                });
              };
              audio.src = URL.createObjectURL(
                new Blob([blob], { type: r.headers.get('content-type') })
              );
            });
          })
        )
      )

        .then((data) => (document.querySelector('pre').textContent = data))

        .then(console.log)
        .catch(console.error);
    </script>
  </body>
</html>

```

**Comment by stevenwaterman** [comment]
Note that the above snippet uses brand new experimental APIs and is only currently available in Chrome

**Comment by MikeyZat** [comment]
@guest271314 note that sometimes the `WAVE` files might contain the `JUNK` chunk [(more)](https://www.daubnet.com/en/file-format-riff) - then the sample rate is not present in bytes `24:28`. 

Here is my code snippet that works for both cases, hopefully it's helpful for somebody:

```javascript
const getSampleRate = (
  arrayBuffer: ArrayBuffer
) => {
  const view = new DataView(arrayBuffer);
  const chunkCellSize = 4;

  const getChunkName = (newOffset: number) =>
    String.fromCharCode.apply(
      null,
      new Int8Array(arrayBuffer.slice(newOffset, newOffset + chunkCellSize))
    );

  const isWave = getChunkName(0).includes("RIFF");
  if (!isWave) return { sampleRate: 0, bitsPerSample: 0 };

  let offset = 12;
  let chunkName = getChunkName(offset);
  let chunkSize = 0;

  while (!chunkName.includes("fmt")) {
    chunkSize = view.getUint32(offset + chunkCellSize, true);
    offset += 2 * chunkCellSize + chunkSize; // name cell + data_size cell + data size
    chunkName = getChunkName(offset);

    if (offset > view.byteLength)
      throw new Error("Couldn't find sampleRate.");
  }

  const sampleRateOffset = 12;
  const bitsPerSampleOffset = 22;

  const sampleRate = view.getUint32(offset + sampleRateOffset, true);
  const bitsPerSample = view.getUint16(offset + bitsPerSampleOffset, true);

  return { sampleRate, bitsPerSample };
};
```
