### ISSUE TITLE
Configurable sample rate for AudioContext

### ISSUE THREAD

**Issue by bjornm** [WebAudio/web-audio-api#300]
1. It would be nice to be able to run the AudioContext in a predefined sample rate, which might differ from the underlying hardware. Some Windows machines default to 192k, which require a lot of processing power compared to 44.1k, especially when 192k quality is not required. Besides increased performance, it can also help optimize buffers and give more consistent output quality. Example:

new AudioContext(optional float sampleRate = _default_)

Being able to change the value at runtime would mean increased flexibility (e.g. in case of sudden performance problems). If that'd be easy to implement in a consistent way:

interface AudioContext {
  attribute float sampleRate;
  ...
}
1. Being able to query the host for default or preferred sample rate(s) would also be nice, so we can choose an optimal sample rate when the underlying hardware supports it. Not sure if this would make sense on all OS:es though. E.g.

float AudioContext.preferredSampleRate

or

float[] AudioContext.preferredSampleRates

If there is some kind of Sink interface coming up which abstracts the AudioContext.destination then I guess it would make sense to go there:

List<Sink> MediaStreamTrack.getSinks()
sink.defaultSampleRate

I might have misunderstood the proposed sink api completely so forgive me if this does not make sense.

**Comment by rtoy** [comment]
Now that we have the dictionary for the playbackCategory, let's add a sampleRate property that specifies the sample rate.  An error is thrown if it is outside the allowed range for the system.

Assuming we really do want to have this in V1, as implied in the recent comments.

**Comment by Timmmm** [comment]
This would be very useful. There should also be a way to query available inputs to see what sample rates they support. Ideally, returned in [MediaDeviceInfo](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo). That structure is really anaemic - it doesn't even list how many channels a device has.

**Comment by skratchdot** [comment]
Not directly related, but another "non-default sample rate" thing I would like to see, is knowing what the original sample rate was on files processed with decodeAudioData() (https://github.com/WebAudio/web-audio-api/issues/30).  My use-case: I'm working on a web based sample editor in which the original sample rate is important for me when saving/displaying information.

**Comment by rtoy** [comment]
If (when?) this option is added, context.sampleRate will, presumably, be the specified sample rate.  However, should we also expose the actual HW sampleRate that would have been used if the option were not given?

**Comment by padenot** [comment]
This would be better done using a device enumeration API. Something that
gives you some sort of ID for a device, that you can match with the
device the AudioContext will use or something like that.

**Comment by joeberkovitz** [comment]
This reflects the need for output device enumeration and selection which is a V.next concern.

**Comment by rtoy** [comment]
Not sure how important this use case is, but say you have a game with 8kHz audio samples. It would be convenient to run your audio graph at 8 kHz and then resampling at the destination node to the actual output rate.  Much lower CPU usage (probably, if the resampling isn't too expensive), no issues with resampling the audio samples to the context rate.

**Comment by rtoy** [comment]
I'm a bit confused on the state of this issue.  It's closed, but also marked v.next.  So does that mean it's not for v.next?

Also, the original issue was about allowing an AudioContext to have a selectable sample rate different from the actual HW sampleRate.  But the discussion devolved into one about device enumeration (https://github.com/WebAudio/web-audio-api/issues/300#issuecomment-234877471).  That seems not relevent to the actual original issue of a selectable sample rate.

**Comment by cwilso** [comment]
Yeah, I'm confused - this was a strong request from game developers, since the 48kHz rate on mobile was painful for game emulators (which frequently run at like 8kHz).  I think this should be reopened, at least.

**Comment by rtoy** [comment]
I'm re-opening this.  

Maybe not for v1, but it seems quite easy to specify. Just add another dictionary member to AudioContextOptions.  If specified, the context.sampleRate is the given value. Otherwise use whatever the HW rate is.  And it's up to the browser to resample the audio samples to the actual HW rate for actual output.  The range of valid rates should match at least the limits for an AudioBuffer.

**Comment by nybbs2003** [comment]
@rtoy I need that too!

**Comment by TobyMasonInstruments** [comment]
BUMP, this is necessary for broadcast audio production.

**Comment by ccampbell** [comment]
Will this be the ticket to follow implementation progress in chrome/blink?

https://bugs.chromium.org/p/chromium/issues/detail?id=432248

**Comment by mvattuone** [comment]
Wondering whether the above is true or not as well - I assume so.

Also, is this something an outside contributor could help implement?

**Comment by rtoy** [comment]
An outside contributor could help, but that is best discussed on the browser bug.
