### ISSUE TITLE
AnalyserNode and OfflineAudioContext

### ISSUE THREAD

**Issue by JonathanMM** [WebAudio/web-audio-api#303]
The AnalyserNode has 4 methods to get Array of time and frequency information. When we call this methods, we are the values at this moment. It's work with an AudioContext.

But, when we use an OfflineAudioContext, we can't get this value for an analyser, because this methods are out of the chain. Can you add a callback in the AnalyserNode, which call a function when a frame passed, to permit in this case to get time and frequency information ?

**Comment by mdjp** [comment]
resolved by suspend/resume on offline context.

**Comment by rtoy** [comment]
To be clear, this is the solution for the analyser node.  The scriptprocessor is a different issue.

**Comment by vlobanov** [comment]
Six years later, if anyone is googling this and can't find a clear answer, here's how you do it.

To get FFT data every 0.1 sec:
```js
const source = audioContext.createBufferSource();
source.buffer = clip; //clip is loaded with audioContext.decodeAudioData

const analysisNode = audioContext.createAnalyser();
analysisNode.fftSize = 64;
const bufferLengthAlt = analysisNode.frequencyBinCount;

const dataArray = new Uint8Array(bufferLengthAlt);

source.connect(analysisNode);
analysisNode.connect(audioContext.destination); // analysis needs to be connected to something

source.start(0);

const step = 0.1;

for (let i = 0; i < durationInSeconds; i += step) {
  const stoptime = i;
  // the trick is to call suspend at each time point you're interested in. 
  // do not await since it won't ever happen - you can only suspend a running context,
  // and we'll run it on the last line by calling startRendering. these will only start resolving as the context is rendering
  // so we're essentially scheduling stopping time points

  void audioContext.suspend(i).then((a) => {
    console.log('suspended', stoptime);
    analysisNode.getByteFrequencyData(dataArray);
    void audioContext.resume();
    console.log('and resumed', dataArray); // do whatever with the data
  });
}

await audioContext.startRendering();
```

**Comment by jixbo** [comment]
> Six years later, if anyone is googling this and can't find a clear answer, here's how you do it.
> 
> To get FFT data every 0.1 sec:
> 
> const source = audioContext.createBufferSource();
> source.buffer = clip; //clip is loaded with audioContext.decodeAudioData
> 
> const analysisNode = audioContext.createAnalyser();
> analysisNode.fftSize = 64;
> const bufferLengthAlt = analysisNode.frequencyBinCount;
> 
> const dataArray = new Uint8Array(bufferLengthAlt);
> 
> source.connect(analysisNode);
> analysisNode.connect(audioContext.destination); // analysis needs to be connected to something
> 
> source.start(0);
> 
> const step = 0.1;
> 
> for (let i = 0; i < durationInSeconds; i += step) {
>   const stoptime = i;
>   // the trick is to call suspend at each time point you're interested in. 
>   // do not await since it won't ever happen - you can only suspend a running context,
>   // and we'll run it on the last line by calling startRendering. these will only start resolving as the context is rendering
>   // so we're essentially scheduling stopping time points
> 
>   void audioContext.suspend(i).then((a) => {
>     console.log('suspended', stoptime);
>     analysisNode.getByteFrequencyData(dataArray);
>     void audioContext.resume();
>     console.log('and resumed', dataArray); // do whatever with the data
>   });
> }
> 
> await audioContext.startRendering();

This is exactly what I was looking for, took me a while to find it... thank you so much!
