### ISSUE TITLE
Difficult to address specific channel in ChannelMergerNode

### ISSUE THREAD

**Issue by tszynalski** [WebAudio/web-audio-api#304]
Suppose you want to write a function that plays a mono sample on a given channel (left, right, center, etc.). The intuitive way of doing it would be to connect a BufferSourceNode with the mono sample to the appropriate input of a ChannelMergerNode. For example:
```
//connect to input #5 = right surround
bufferSource.connect(mergerNode, 0, 5);
```
Unfortunately, a ChannelMergerNode only takes into account **connected inputs**, so the above code would ignore the unconnected inputs 0-4, take the first connected input (#5), and output a mono signal.

The current solution is to do the following:
```
var silence = audioContext.createBufferSource();
//creating a dummy AudioBufferSourceNode which is treated as one channel of silence
silence.connect(mergerNode, 0, 0);
silence.connect(mergerNode, 0, 1);
silence.connect(mergerNode, 0, 2);
silence.connect(mergerNode, 0, 3);
silence.connect(mergerNode, 0, 4);
bufferSource.connect(mergerNode, 0, 5);
```
Note that when working with 5.1-channel audio, we have to connect **5 dummy silent nodes** every time we want to play a sample on a single channel.

In addition, I believe there is nothing in the spec that prevents a browser from disconnecting and disposing of the dummy nodes as soon as the function exits and the silence variable is no longer referenced. This would cause the mergerNode to start outputting a mono signal, since it would receive only one input. So we would also have to make sure the "silence nodes" exist in a different (longer-lasting) scope than bufferSource.

It would be better to have the possibility of 1-1 mapping between ChannelMergerNode inputs and the channels in the output signal. We could tell a ChannelMergerNode what kind of output signal we want (mono, stereo, 5.1, etc.), connect a single input and the remaining inputs would be filled with silence.
It could work like this:

```
mergerNode.outputSignal = "5.1";
bufferSource.connect(mergerNode, 0, 5); //connect source to right surround channel
```
or
```
mergerNode.outputSignal = "5.1";
bufferSource.connect(mergerNode, 0, "SR");
```

The default setting of the "outputSignal" property could be "auto". This would correspond to the current way it works – automatically determine the number of channels by summing the channels on all connected inputs.
Setting outputSignal to "5.1" would have the following effects:
- take the first 6 inputs (# 0-5)
- interpret each input as mono (downmix if necessary)
- interpret unconnected inputs as one channel of silence
- mix input 0 into the left channel, input 1 into right, input 2 center, and so on.
- ignore remaining inputs

**Comment by hoch** [comment]
Here is a proposal for ChannelMergerNode:

The following properties are fixed for ChannelMergerNode and InvalidState error should be thrown when user changes them:

~~~
ChannelMergerNode.channelCount = 1
ChannelMergerNode.channelCountMode = ‘explicit’
~~~

Changed behavior: 
- Each input will be summed to mono based on the specified mixing rule.
- The summed mono channel from input will be transferred to the corresponding output channel (input_1 -> output_channel_1). If an input is not connected (inactive or disconnected), it still counts as one silent channel in output. 
- Note that the input to output channel mapping is fixed and won’t change the order of output channels dynamically.

Since this new behavior prevents ChannelMergerNode from dynamic channel reordering/resizing, any related issue can be resolved with this change. (such as #459)

**Comment by hoch** [comment]
Note that the up/downmixing rule is only applied to each input when the channel layout is canonical (mono, stereo, quad, 5.0 and 5.1). For undefined channel layout, the mixing rule automatically changes to 'discrete' mode. That means the merger will just take the first channel and drop the rest.

**Comment by cwilso** [comment]
As a side note, this means that we could drop the dynamic channel
definition requirement for audio workers.  Do we want to?

**Comment by hoch** [comment]
@cwilso I second that. The dynamic (or so-called-intelligent) channel configuration is causing problems here and there. The behavior is unpredictable and difficult to maintain the state, etc. If the proposal above is accepted, the merger node will be robust and easy to control.

I would love to hear what other WG members think.

**Comment by hoch** [comment]
@cwilso In the teleconference (2/5), @joeberkovitz agreed on this proposal but we would like to hear your opinion on this issue, especially in the regard of AudioWorker.

@padenot I was under the impression that you're not against the proposal. Please let me know if you have a different idea!

**Comment by padenot** [comment]
I'm not against this proposal, I'm going to read it again and think
about it next week, though.

**Comment by joeberkovitz** [comment]
To clarify, my concern was that the proposed removal of dynamic channel configuration from AudioWorker might have potential side effects for AWs' ability to simulate other nodes for which this behavior is in fact expected and necessary, thus creating a problem for layering.

**Comment by cwilso** [comment]
It's fine.  I'd already removed the ability for AWs to dynamically control
their number of inputs; the dynamic channel configuration is still possible
in AW (since it's necessary for other node replication, like
BufferSourceNode or Convolution).  We should be good to go with Hongchan's
proposal.

**Comment by hoch** [comment]
As @cwilso mentioned, the dynamic channel configuration between nodes (or downstream propagation) is not the problem we're trying to fix here. The problem is the unintuitive behavior of __channel stacking__ in `ChannelMergerNode`.

**Comment by mdjp** [comment]
discussed on a WG teleconf 5th March 2015 - the group agrees with the proposal and the issue has been marked ready for editing.

**Comment by cwilso** [comment]
Fixed.
