### ISSUE TITLE
Remove unsupported methods from offlineAudioContext

### ISSUE THREAD

**Issue by chrislo** [WebAudio/web-audio-api#308]
The methods 

`createMediaElementSource`
`createMediaStreamSource`
`createMediaStreamDestination`

don't make sense in an `offlineAudioContext`. They should be removed from the spec. Robert O'Callahan [suggests](http://lists.w3.org/Archives/Public/public-audio/2014JanMar/0089.html) adding a `baseAudioContext` or similar to the spec which `AudioContext` and `offlineAudioContext` can inherit from. That seems sensible to me. 

[more details](http://lists.w3.org/Archives/Public/public-audio/2014JanMar/0088.html)

**Comment by padenot** [comment]
I'm asking heycam for best WebIDL practices before merging.

**Comment by heycam** [comment]
You can just mirror that structure in IDL interfaces:

```idl
interface BaseAudioContext {
  ...
};

[Constructor(...)]
interface AudioContext : BaseAudioContext {
  ...
};

[Constructor(...)]
interface OfflineAudioContext : BaseAudioContext {
  ...
};
```

This does go against what @domenic says earlier about not having non-constructable base classes, but to be honest having the abstract base class not be constructable makes sense to me.
