### ISSUE TITLE
Un-neutering operation on an ArrayBuffer is not defined

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#319]
The [spec](http://webaudio.github.io/web-audio-api/#widl-AudioContext-decodeAudioData-Promise-AudioBuffer--ArrayBuffer-audioData-DecodeSuccessCallback-successCallback-DecodeErrorCallback-errorCallback) for `decodeAudioData`, in some cases, says something like:

> Temporarily neuter the audioData ArrayBuffer in such a way that JavaScript code may not access or modify the data.
> 
> Restore the audioData neutered state to normal.

However, neutering is defined as a non-reversible operation, as per the [HTML spec](http://www.whatwg.org/specs/web-apps/current-work/multipage/common-dom-interfaces.html#concept-transferable-neutered):

> [...] _neuter_ the original object. (This is an irreversible and non-idempotent operation; once an object has been transferred, it cannot be transferred, or indeed used, again.)

We should just remove the text about un-neutering the array, since it's not defined. This means that when a buffer is passed to `decodeAudioData`, using it somewhere else won't be possible anymore.

**Comment by kakukogou** [comment]
Hi all,
I was searching concept of "un-neutering" and found this post. I am wondering what if the `ArrayBuffer` argument of `decodeAudioData` is an asm.js application's run time heap? To my understanding, the application will then lose its heap? Have you ever discussed it?

**Comment by padenot** [comment]
This is not really a Web Audio API issue. I would expect that people who use `decodeAudioData` manage their buffers outside the asm.js heap, since it might come from an XHR or some other code that interacts with Web APIs.
