### ISSUE TITLE
Introduction: link "use cases" to the stable Use Cases document

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#32]
> Originally reported on W3C Bugzilla [ISSUE-21512](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21512) Tue, 02 Apr 2013 12:21:56 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26:

The Introduction section mentions the use cases and requirements document. The link should be pointing to http://www.w3.org/TR/webaudio-usecases/ and that spec/Note added to the list of references.

**Comment by billhofmann** [comment]
Fix with https://github.com/WebAudio/web-audio-api/pull/596

**Comment by rtoy** [comment]
I think you're closing these prematurely.  They should get closed when the pull request is merged.  If you add "fix #n" in the commit message, github will automatically close the issue when the pull request is merged.

At least that's my understanding of the process.  I could be wrong.

**Comment by billhofmann** [comment]
Thanks.  Not sure where the process is documented, so now that I know, I will follow process.  Make sense.  *Is* it documented someplace?  I’m not a github user.

**Comment by rtoy** [comment]
Found this:  https://help.github.com/articles/closing-issues-via-commit-messages/

And I see I've been doing it wrong because I normally work on a fork (so I don't trash the real repo by accident).  I need to use the correct syntax on my commit messages.

**Comment by billhofmann** [comment]
OK, the pull request is merged, I think this is done.
