### ISSUE TITLE
WaveShaperNode oversampling latency?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#322]
The WaveShaperNode allows for oversampling by 2 or 4 using some appropriate algorithm. Depending on the algorithm used for oversampling, this can introduce some latency in the output.  

Should the user be able to determine the latency that was introduced (if any)? This would be needed if you need to align some signals precisely in time.

**Comment by joeberkovitz** [comment]
F2F resolution: as per #469 and #414 capture information about WaveShaperNode's tailTime and latency being coupled to use of oversampling.

**Comment by joeberkovitz** [comment]
Currently WaveShaperNode says there is no tail-time. We need to fix this.

**Comment by padenot** [comment]
This has been fixed, closing.
