### ISSUE TITLE
Biquad: Possibility to set the filters coefficients and not just Q/freq/gain

### ISSUE THREAD

**Issue by narnau** [WebAudio/web-audio-api#323]
Currently it is only possible to design a filter by using the Q/freq/gain parameters.
It seems that the solution would be to show the setNormalizedCoefficients function of the biquad node on the API.

void Biquad::setNormalizedCoefficients(double b0, double b1, double b2, double a0, double a1, double a2) ->  http://dxr.mozilla.org/mozilla-central/source/content/media/webaudio/blink/Biquad.cpp

**Comment by rtoy** [comment]
After thinking this over a bit, I think I like Jussi's proposal https://github.com/WebAudio/web-audio-api/issues/323#issuecomment-60533393 about just making a general IIR filter node where you can specify any set of a and b coefficients. No automation allowed.

**Comment by joeberkovitz** [comment]
@rtoy Can you please explain why you want to remove the automation? We had already agreed to make a new filter node type with the general coefficients, but *with* automation.

**Comment by rtoy** [comment]
I just don't really see a use case for automating random coefficients for a general IIR filter. But if you really want automation, then ok. I find it quite messy even for a general biquad.

**Comment by joeberkovitz** [comment]
I don't care a lot about automation in this case. But others might, so I just wanted a statement on record as to why you wanted to remove it, in case they care. It sounds as though the reason is "unlikely use case" and "implementation complexity".

**Comment by rtoy** [comment]
Oh, I didn't think about implementation complexity, but that does bring up a good point in how to design such a filter.  Will there be a set of attributes like a1,a2,a3,..., b0, b1, b2,... that represent the coefficients?  Then we have to specify some arbitrary but fixed number of coefficients.  I was thinking more along the lines of createIIRFIlter(<array of a coef>, <array of b coef>). Not sure how to do automation in this case.

**Comment by joeberkovitz** [comment]
Yes, that was exactly the idea (a1, a2... with explicit and fixed number of names), except the original thought was that they would be AudioParams for consistency with the old biquad. I think it would be a more consistent API if they are AudioParams, whether that seems likely or not. If we're going to change that decision then we should run it by everyone again.

**Comment by rtoy** [comment]
I'm fine with AudioParams.

**Comment by padenot** [comment]
Since this would essentially be a custom biquad, we could just have an type that would be `"custom"` on the biquad, and the 6 new AudioParams that would only work when the type is `"custom"`, like there is for the `OscillatorNode`.

People from IRCAM told me they would also need a way to set the internal filter state, essentially `setFilterMemory(x0,x1,y0,y1)`.

**Comment by rtoy** [comment]
A BiquadFilterNode with type "custom" is acceptable to me.  Except there should be 5 audioparams, not 6: b0, b1, b2, a1, a2.  a0 is implicit and is always 1.  If I set a filter type of "lowpass", can I read the coefficient attributes to get the current filter coefficients for the lowpass filter? Kind of useful, but perhaps problematic if the filter has automation.

setFilterMemory is ok too as long as users know it won't be sample accurate and could cause glitches.

Finally, are you saying we should not support a general IIR filter node as proposed by Jussi and just support the custom BiquadFilterNode?

**Comment by padenot** [comment]
Yes, 5 AudioParam. I'd say you could read out the values, but that would mean to solve the issues about read back of AudioParams first (I don't know the issue number # offhand, sorry).

Yes, `setFilterMemory` would have a note saying that it is expected that authors call it while nothing is flowing through the BiquadFilter.

I think we can go a long way with a Biquad with custom coefficient, but I'm certainly not opposed to having a generic IIR filter node, we'd need to discuss that.

**Comment by rtoy** [comment]
This works for me.

I would prefer that if we add a generic IIR filter node, then the Biquad filter node is unchanged (no custom coefficients).  Or don't add an IIR node and the Biquad node allows custom coefficients.

**Comment by joeberkovitz** [comment]
The previously accepted proposal envisioned a new node interface with a new name and factory method, and we had agreed at the F2F to leave the existing BiquadFilter alone (without adding a new filter type of "custom").

To avoid going around on this again and possibly surprising members who previously agreed to leaving the old class alone, I'd ask if one of the following choices is acceptable:

1) [previously agreed on] Add a new biquad filter node with custom coefficients
2) Add a new IIR filter node

In both cases, the old Biquad filter would stick around unchanged.

**Comment by rtoy** [comment]
I prefer option 2.  If we're adding a new node, might as well go all the way with a fairly general IIR filter node.

**Comment by Nantonos** [comment]
I thought the reason to have a new node was to avoid the case where the coefficients are set indirectly (but cutoff frequency, Q, etc) and then read back or modified individually at the individual coefficient level.
Automation of individual coefficients is not harmful but equally is not very useful as they don't correspond to physical concepts. I could imagine code that precomputes a set of five automations though.
A more general IIR node might be be useful; is it a strict superset of FIR (he said hazily)?

**Comment by rtoy** [comment]
The general IIR node would be a (limited) strict superset of FIR.  Given Joe's suggestion on what it would look like, there would be some max limit on the number of FIR (and IIR) coefficients, so you could implement fairly short FIR with it instead of using a convolver node.

From an implementation viewpoint, it might be beneficial to have additional attributes to tell how many of the a and b coefficients are in use.

**Comment by rtoy** [comment]
From the 2015/03/19 teleconf, a general IIR filter is desired.  The coefficients will not be audioparams. Details to be worked out.

**Comment by joeberkovitz** [comment]
@rtoy Given the agreement on a general IIR node, is that proposal now ready for editing as a resolution for this issue?

**Comment by gyltefors** [comment]
Hmm, why have a biquad node in the first place if one can't set the parameters (a0,a1,a2,b1,b2), but is restricted to a few predefined filters only?

**Comment by rtoy** [comment]
First, as explained above, any biquad filter can be created using the predefined filters.  Second, the predefined filters allow you to do useful automations that aren't easily possible by automating the individual coefficients. Third, if you really want to set the coefficients, use IIRFilterNode.

Finally, this bug is closed.  Please open a new bug.

**Comment by gyltefors** [comment]
Well, what we have now is a node called "biquad" that can't implement MOST biquad filters (*). While filter sweeps are FUN, I doubt many people would need that in any serious application. So, yes, there is definitely a need to open a few new tickets to address the overall design decisions concerning Web Audio.

* Let's say I want to implement a non-resonant LPF with a cutoff of 1000Hz. That forces the frequency parameter to 1000Hz and the Q parameter to 0.707. That only leaves the gain parameter left, but I could hardly design a filter with just a gain parameter! You are forced to use text-book filters, but text-book filter are just that: intended as simple text-book examples. That is not of much use in a real-world application.

**Comment by rtoy** [comment]
Any biquad filter can decomposed into a combination of the builtin biquad filters, so you are not limited in any way.  The only difficulty is deciding how to decompose the general biquad into one of the predefined ones.

**Comment by gyltefors** [comment]
So you say that to implement ONE biquad, I have to use SEVERAL biquad nodes, using in your words "difficult" math? It doesn't sound like a good design decision to me.

**Comment by rtoy** [comment]
So, use the IIRFilterNode.

**Comment by gyltefors** [comment]
It is not available in the current version of Chrome, so I'll have to use a custom node. In the end, none of the predefined nodes, biquad, compressor etc. are useful in a real application, and you have to use custom nodes for everything. Reading through this thread, there seem to be many people with an audio engineering background giving valuable comments, that are mostly ignored with remarks like, "why would we need that?" etc. And we end up with a framework that does a lot a cool stuff, but not really the things that an audio engineer needs to be able to implement his designs.

**Comment by notthetup** [comment]
@gyltefors This is how the W3C spec process works. The discussions here are about the WebAudio specification. Whatever is discussed and decided becomes a part of the WebAudio spec. The browser (UA) manufacturers are then free to implement the spec based on their own priority and schedule.

**Comment by gyltefors** [comment]
@notthetup Thanks, I am new to this process. What is best approach to push for changes that I feel are important for WebAudio to be useful for application developers?

**Comment by notthetup** [comment]
1. Check the latest version of [WebAudio Spec](http://webaudio.github.io/web-audio-api/) for reference.

2. Search the [issues](https://github.com/WebAudio/web-audio-api/issues) to see if there already a discussion on that topic/node/aspect. People interested in certain issues would be subscribed to them so they'll get notified.

3. If there isn't one, then raise a new issue and explain what you'd want to see in the WebAudio spec. If the Audio Working Group needs more information or examples, feel free implement some tests or examples to help the discussion.

4. Once the suggestion gets accepted by the W3C Audio Working Group, it will get added to the WebAudio Specification. After that you'll have to wait for the browser vendors to implement it and for all the updates to go out so all your users can also have the new functionality. This may take time. We have to be patient. :)

5. Also, look at the various open source libraries, frameworks and tools available on top of WebAudio. Tons of great functionality is available that way, and ready to be used.

**Comment by gyltefors** [comment]
Great, thanks!

**Comment by rtoy** [comment]
Complaining that things are useless isn't helping your case.  File an issue with real-world examples of things you want to do but can't with the existing nodes.  Propose solutions for them if you know.  This is how IIRFilterNode was created.  This is how a-rate biquads got spec'ed.  Be constructive.

By the way, the IIRFilter is in Chrome canary, maybe beta.  It was implemented just a month or two ago so it takes a while to get to Chrome stable.
