### ISSUE TITLE
Degenerate azimuth/elevation calculation

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#324]
In https://webaudio.github.io/web-audio-api/#Spatialization the given algorithm says that if the source and listener are at the same position, the azimuth and elevation are both set to zero.

This seems incorrect.  If the source is moving towards the listener with an azimuth of 90, I would expect the azimuth to be continuous when it reaches the listener. If you don't do this, the azimuth suddenly changes to 0, causing a change in the sound.

This effect can be heard at http://jsfiddle.net/UxwGP/8/.

**Comment by joeberkovitz** [comment]
From F2F: @rtoy says spec so that when source and listener are at the same position, you get equal L and R signals.

**Comment by rtoy** [comment]
The algorithm as it stands today is correct.  When the source and listener positions are equal, azimuth = 0.  That implies (for a stereo source), x = 1.  Then gainL = 0 and gainR = 1.  Finally, outputL = inputL and outputR = inputR.

(I don't understand why Chrome does something weird in this case.  Probably some bug introduced long ago.)

**Comment by rtoy** [comment]
And for a mono source, x = 1/2 so gainL = gainR = 1/sqrt(2) implying outputL = input/sqrt(2) and outputR = input/sqrt(2).  Thus, there's sound on both left and right.
