### ISSUE TITLE
Synchronizing getFloatFrequencyData and getFloatTimeDomainData

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#331]
It's useful to be able to get the time domain data and the frequency data at the exact same block of data.  Currently, however, this requires two separate calls. If there's a slight delay between the calls (perhaps a GC happens), the captured frequency data may not correspond to the time domain data.  This would be especially noticeable if there is no smoothing of the frequency data (smoothingConstant = 0).

There should be some way of getting the time and frequency data at the same time.

**Comment by mdjp** [comment]
Closed after discussion with original requester
