### ISSUE TITLE
Are AudioBufferSourceNode.loopStart and .loopEnd subsample-accurate?

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#336]
The spec should say whether the loop points specified for an AudioBuffer are subsample-accurate, or whether they are rounded to the nearest sample.

Most commercial sampler applications do not support subsample-accurate loop points and require loop points to be at exact sample frames, for efficiency's sake.

**Comment by rtoy** [comment]
Curiously, the spec currently says `loopStart` and `loopEnd` are rounded to the nearest frame. I didn't look to see when this change was made.

However, I think Chrome does do subsample accurate loopStart and loopEnd.  Here's an example

    var context = new OfflineAudioContext(1, 100, 12800);
    var src = context.createBufferSource();
    var b = context.createBuffer(1, 3, context.sampleRate);
    var d = b.getChannelData(0);
    d[0] = 0;
    d[1] = 1;
    d[2] = 1;
    src.buffer = b;
    src.loop = true;
    src.loopStart = 0.5 / context.sampleRate;
    src.loopEnd = 2 / context.sampleRate;

    src.connect(context.destination);
    src.start();
    context.startRendering().then (function (buffer) {
        console.log(buffer.getChannelData(0));
    });


If there were no subsampling going on, the output should always be either 0 or 1.  In Chrome, some samples are 0.5, indicating that subsampling is being done.

Presumably this is also true with Safari (webkit), Edge, and Opera too.  I didn't test this though.

**Comment by padenot** [comment]
Gecko snaps to frames.

**Comment by joeberkovitz** [comment]
The spec was changed by me, "curiously" in the PR that is referenced by this issue: https://github.com/WebAudio/web-audio-api/issues/332.

So, sorry, I forgot to close this issue. Closing now.

**Comment by joeberkovitz** [comment]
This is a duplicate of #332, which itself was closed via #400. So, closing.

**Comment by hoch** [comment]
Note: the resolution is reverted by https://github.com/WebAudio/web-audio-api/issues/915.
