### ISSUE TITLE
decodeAudioData Prose: avoid video containers that have an audio track

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#34]
> Originally reported on W3C Bugzilla [ISSUE-21520](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21520) Tue, 02 Apr 2013 14:41:45 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26

Change:

"Audio file data can be in any of the formats supported by the audio element"

For:

"...can be accepted in formats containing only audio data (w/o video)"

This is to avoid the overhead of dealing with video containers that have an audio track.

**Comment by billhofmann** [comment]
Modified per cwilso's comment, https://github.com/WebAudio/web-audio-api/commit/971b33f1cbb013916ad65a9c6fa8ecb7910267a7

**Comment by billhofmann** [comment]
ok, taking another swing at it...
