### ISSUE TITLE
AudioParam.linearRampToValueAtTime

### ISSUE THREAD

**Issue by pendragon-andyh** [WebAudio/web-audio-api#341]
I am currently writing tests for the specification and have found linearRampToValueAtTime does not match my understanding of my spec.

If you do:

```
    param.value=0;
    param.linearRampToValueAtTime(1, 1);
```

then Chrome and Firefox both then there is no change until 1 second - when it jumps _instantaniously_ from 0 to 1.

However,

```
    param.setValueAtTime(0, 0);
    param.linearRampToValueAtTime(1, 1);
```

then you get a _smooth ramp_ between 0 and 1.

https://github.com/pendragon-andyh/WebAudio-Testing/blob/master/webaudio/the-audio-api/the-audioparam-interface/method-linearRampToValueAtTime.html

@chrislo recommended that I clarify here whether you feel this is a bug or if the specification needs to be amended.

**Comment by olsonpm** [comment]
I just ran into this exact issue now.  I appreciate your guys' explanation of the problem - and would love the docs to make this explicit.  What's further confusing is the following exmple seen on the official MDN docs:

http://mdn.github.io/audio-param/
