### ISSUE TITLE
Can OfflineAudioContext be used more than once?

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#346]
My preference is no, it should be a one-shot-deal.

Source:
http://stackoverflow.com/questions/25406474/can-i-call-offlinecontexts-startrendering-more-than-once

**Comment by rtoy** [comment]
I don't think there's anything to clarify; they can't be reused.

**Comment by rtoy** [comment]
Based on the comments https://github.com/WebAudio/web-audio-api/issues/346#issuecomment-61625457 and https://github.com/WebAudio/web-audio-api/issues/346#issuecomment-146962168, I'm closing this issue.

@zya raises a different issue in https://github.com/WebAudio/web-audio-api/issues/346#issuecomment-52894842, but that should be filed as a different issue.

**Comment by andremichelle** [comment]
I like to reopen the issue, since we now have audio-worklets. Loading the worklets each time you like to render a piece of audio is not really feasible and also has side-effects performance wise. OfflineAudioContext can be used to cache certain audio-data, which outcome is always the same. Right now this is not possible, if the OfflineAudioContext cannot be reused.

**Comment by rtoy** [comment]
Can't seem to find the issue, but we are considering changing `startRendering()` so that it can be called as many times as you want, with each result returning the new audio data.

I don't quite understand why you need to reload the worklet code everytime, though.

**Comment by rtoy** [comment]
Ah, it's #1279.  Will that work for your use-case?

**Comment by andremichelle** [comment]
@rtoy I do not think so.
> If a suspended context is resumed, continue to render the buffer.
As far as I can see, this is good to cancel the rendering or make changes to the graph and continue rendering to the same buffer (which will probably leads to discontinuities?).
Anyway, my issue is that I have to load the worklets everytime I instanciate a new OfflineRenderer. It also introduces strange behaviours when I load (even unused worklets) in the live AudioContext.

**Comment by rtoy** [comment]
Hmm. #1279 isn't quite what I thought.  We briefly discussed the idea at TPAC 2017 to allow you to call `startRendering()` as many times as you want.  Each render would continue where the previous render ended, so everything would work as if you rendered everything all at once, except you get the results in chunks.  Won't this work for you?

If you have strange behaviors now with worklets, you should file bugs against your browser with test cases.

**Comment by andremichelle** [comment]
@rtoy There should be a method to reset the clock. Then you can have whatever you like.

> If you have strange behaviors now with worklets, you should file bugs against your browser with test cases.

I will, but you see the issue, that the worklets needed to be loaded everytime you create a new OfflineRenderer?

**Comment by rtoy** [comment]
Resetting the clock won't in general work, I think.  You'd also need to reset the state of every node.  And it would only work if graph is static so that it doesn't change from beginning to end of rendering, including assuming no nodes get GCed while rendering.

I thought you could share worklet code between contexts, but that seems not the case.  @hoch would know better.

**Comment by andremichelle** [comment]
@rtoy True. Reseting the clock alone is not sufficient enough. What I am asking for is that we can reuse the OfflineRendererContext with all loaded worklets as if it was the first time (time: 0, graph: empty).

**Comment by rtoy** [comment]
I think reusing the offline context that starts at time 0 and an empty graph is weird. You've already created a bunch of nodes on the context and connected them so making them not connected is weird.

However, if you can call `startRendering()` multiple times, you can recreate your graph again and call `startRendering()`.  I think this will do what you want, except that time won't be reset to 0; you'll have to account for that, but that's relatively simple.  Slightly more work, but doable.

**Comment by sachingarg05** [comment]
Safari seems to not allow creating more than 2028 AudioContexts or OfflineAudioContexts (it crashes). If OfflineAudioContext can't be reused, how to process streaming audio buffers in Safari? Maybe there is something that needs to be done to let Safari create more than 2028 OfflineAudioContexts? I tried both stop() or close() but that didn't help. 

```
    for (let i = 0; i < 3000; i++) { // Safari will crash at i 2026 or 2028, on both iOS and Mac
      let ctx = new OfflineAudioContext(1, 16384, 44100);
      console.log(i);
    }
```
