### ISSUE TITLE
MediaElementSourceNode should have one output per track on media elements with multiple tracks

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#352]
Reported to HTML (https://www.w3.org/Bugs/Public/show_bug.cgi?id=26534), but this is really a requirement on how we create MediaElementSourceNodes.

Change MediaElementSource definition in Web Audio to create one output per track on the media element node, rather than a single output.

**Comment by padenot** [comment]
This will be implemented with `MediaStream`s in #264.

You can do `HTMLMediaElement.captureStream()`. This returns a `MediaStream` with multiple tracks (on per `AudioTrack`). You can then create route those tracks into Web Audio using the new `MediaStreamTrackAudioSourceNode`, and process the tracks as needed.

Closing this one, as #264 has a pull-request already in flight.
