### ISSUE TITLE
Unspecified behaviour of bounds exceeding offset in looped/unlooped AudioBufferSourceNode.start

### ISSUE THREAD

**Issue by mark-buer** [WebAudio/web-audio-api#353]
What is the expected behaviour of a bounds exceeding start offset,
without looping:

```
audioBufferSourceNode.loop = false;

// Case NL1
audioBufferSourceNode.start(0, -1);
// Case NL2
audioBufferSourceNode.start(0, audioBuffer.duration + 1);
```

and with looping:

```
audioBufferSourceNode.loop = true;

// Case L1
audioBufferSourceNode.start(0, -1);
// Case L2
audioBufferSourceNode.start(0, audioBuffer.duration + 1);
```

?

Edit: fixed `audioBuffer.length` typos so they now read `audioBuffer.duration`

**Comment by padenot** [comment]
These days, `AudioBufferSourceNode.buffer` cannot be assigned more than once.

In light of this, how about silently clamping to [0, `AudioBufferSourceNode.buffer.duration`] ? Or do we prefer throwing for negative value ?

**Comment by joeberkovitz** [comment]
Resolved: we'll document that the `offset` argument is clamped to the above range.

**Comment by joeberkovitz** [comment]
This issue is moot because the current behavior of `offset` as documented in the new ABSN description effectively clamps it.
