### ISSUE TITLE
Valid values for ScriptProcessor channelCount and channelCountMode?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#357]
This is a follow up of #355, comment https://github.com/WebAudio/web-audio-api/issues/355#issuecomment-56901419

The link mentions that you cannot change the channelCount from the value specified on creation of the node, and the mode cannot be changed from "explicit".  This makes sense and should be explicitly mentioned in the spec.

**Comment by rtoy** [comment]
Given that ScriptProcessorNodes are deprecated do we need to add these corrections? Perhaps yes, since the node is deprecated, not removed.

**Comment by padenot** [comment]
Might as well, yes.
