### ISSUE TITLE
Inter-app audio (Consistent request from ISVs, a la VSTs, Audio Units, Rack Effects)

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#358]
Likely a stream source/sink.

**Comment by mdjp** [comment]
A previous meeting action was to verify the use cases (http://www.w3.org/TR/webaudio-usecases/)
I believe that the following use cases could have a requirement for inter app audio.

2.3 Online Music Production Tool.
Dependency on inter app audio: High assuming the requirement is to recreate DAW functionality.
2.4 Online Radio Broadcast.
Dependency on inter app audio: Medium, routing of audio to existing effects may be a requirement.
2.5 Music Creation Environment with Sampled Instruments.
Dependency on inter app audio: High
2.7 Playful sonification of user interfaces.
Dependency on inter app audio: High
2.10 Web based guitar practice service.
Dependency on inter app audio: Medium

We can of course support these use cases without inter app audio however it would have an impact on their usefulness ( in my opinion.)

**Comment by jussi-kalliokoski** [comment]
On 9 Feb 2015 12:56, "Matthew Paradis" <notifications@github.com> wrote:
>
> A previous meeting action was to verify the use cases (
http://www.w3.org/TR/webaudio-usecases/)
> I believe that the following use cases could have a requirement for inter
app audio.
>
> 2.3 Online Music Production Tool.
> Dependency on inter app audio: High assuming the requirement is to
recreate DAW functionality.
> 2.4 Online Radio Broadcast.
> Dependency on inter app audio: Medium, routing of audio to existing
effects may be a requirement.
> 2.5 Music Creation Environment with Sampled Instruments.
> Dependency on inter app audio: High
> 2.7 Playful sonification of user interfaces.
> Dependency on inter app audio: High

Could you elaborate on how this has a high dependency? :)

> 2.10 Web based guitar practice service.
> Dependency on inter app audio: Medium
>
> We can of course support these use cases without inter app audio however
it would have an impact on their usefulness ( in my opinion.)

**Comment by mdjp** [comment]
--
Matthew Paradis
Senior Software Engineer (Audio),
BBC Research & Development
030304 09889 | matthew.paradis@bbc.co.uk | www.bbc.co.uk/rd/sound

**Comment by jussi-kalliokoski** [comment]
(edited our comments to rid of the email noise I created :)

@mdjp That's a whole different beast, though. Let's look at a few scenarios:

1. An app adding sound effects to its own UI.

In this scenario, the app itself decides what kind of sonification to apply. In here, third party synthesis such as VST __could__ be used, but there's no specific justification here that doesn't apply to pretty much any use case we can think of.

2. An app adding key-stroke/click whatnot sounds to all applications globally in the OS.

In this scenario, there's no need for inter-app __audio__ per se, but more something like global keylogging and pointer tracking capabilities (color me frightened), which is outside the scope of this WG.

3. An app adding sonification to the UI of an external device.

In this scenario, we're transmitting audio and control data across devices, so this is more in the domain of Web MIDI API and WebRTC.

**Comment by mdjp** [comment]
Completely agree with the first 2 points.  I think that the context that I was referring to is actually very different and should not be considered in the same use-case. I have made a note in the original comment to reflect that.

**Comment by mdjp** [comment]
No considered for V2, use WASM/Worklet/Audio Device Client
