### ISSUE TITLE
Clarify suspend/resume on AudioContexts

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#361]
In issue #317, there is a discussion of suspend/resume.  This needs to be spec'ed out a bit more.

In particular, I think suspend and resume can be called as many times as desired without errors.  The Promise returned by resume() is resolved when the audio context has started processing the audio graph again.

What happens to the context currentTime needs to explained, but I think currentTime stops advancing once suspend is called and starts advancing some time after resume has been called.

**Comment by cwilso** [comment]
Merged.
