### ISSUE TITLE
Constructible and connect()able AudioParams

### ISSUE THREAD

**Issue by ugur-zongur** [WebAudio/web-audio-api#367]
Binding AudioParam of another AudioNode to an AudioWorker

As far as i understand, it is impossible to change a native AudioNodes' parameter at real-time. Some use cases i can think of:
1. Changing parameters of AudioNodes with respect to audio input/output signals (e.g. side-chaining)
2. Changing parameters of AudioNodes with respect to some internal real-time algorithm.
3. Changing parameters of AudioNodes with respect to MIDI messages at minimum latency possible.
  (also resolving following issue https://github.com/WebAudio/web-midi-api/issues/99)

A solution can be achieved by making AudioParams bindable to AudioWorkers.

Possible WebIDL can be something like:
```
interface AudioWorkerNode : AudioNode {
    ...
    void  bindParameter(DOMString name, AudioParam parameter);
    ...
};
```

Example main file javascript:
```
envelope = context.createGain();
worker.bindParameter('envelopeGain', envelope.gain);
```

Example worker code:
```
onaudioprocess= function (e) {
  e.parameters.envelopeGain.value = calculateValue();
}
```

Since AudioWorkers are processed sequentially in audio processing graph, i think changing AudioParam in a AudioWorker's context won't be a problem in terms of concurrency.

**Comment by mdjp** [comment]
F2F: To be reviewed for next conference call to establish effort required to include in V1.

**Comment by rtoy** [comment]
Can't the constructible audioparam be done with a UnitSource source node whose output is 1.  This node would have one AudioParam, say, gain.  Would this not allow you to construct, in effect, an AudioParam, and allow you to connect an AudioParam to other AudioParams?

I find myself creating unit sources all the time and it's really annoying to have to create a looping 1-sample buffer source for this.

**Comment by joeberkovitz** [comment]
@rtoy That does seem elegant, and much less of a perturbation than adding new bells and whistles to either `AudioNode` or `AudioParam`.

**Comment by cwilso** [comment]
This *can* be done that way (by creating a ValueNode - that has a single
AudioParam .value, which controls its value.  I think the "elegance" in
that is elegance in having to put less in the spec, rather than elegance in
users using it (the pattern would result in this code:

var value = context.createValueNode;
value.value.value = 5;   //  <- hahahaha :)

It's okay, I suppose.  Constructible/Connectable audioparam would still be
cleaner.

**Comment by joeberkovitz** [comment]
`ValueNode` is definitely a better name.

But using `value` as the name of the AudioParam (the `node.value.value` thing) stylistically frightens me. Maybe the param could be called `output` or something else.

**Comment by rtoy** [comment]
What would a constructible AudioParam look like?  Would you have to do basically the same thing:

    var p = context.createAudioParam();  // or new AudioParam();
    p.value.value = 5;

Or is there some other approach you have in mind?

Regardless, I, personally, would love to have a constant value source node; I can of course work around this, but when using hoch.github.io/canopy to hack a test, a constant value node would be sweet.

**Comment by cwilso** [comment]
Yeah, that's exactly it.  The only real change is that AudioParam would
need to acquire a .connect().

**Comment by rtoy** [comment]
In that case, let me cast my vote for a constant source node (of some appropriate name) with an audioparam.

**Comment by rtoy** [comment]
Per teleconf:  The constant source node probably doesn't work quite right. If you connect, say, an oscillator to the audioparam, the output would be the 1 + the oscillator.  This isn't desired.  It can be worked around by having the user set the constant source node value to 0, but this might not be what we want.

**Comment by rtoy** [comment]
According to https://webaudio.github.io/web-audio-api/#computation-of-value, this is the correct behavior.  If we make the default value of the constant source node be 0, I think everything will work out as desired.  Then it's up to the developer to do the right thing with this constant source node.  But it will behave as if it were a constructible AudioParam.

**Comment by rtoy** [comment]
See #902 for a proposed `ConstantSourceNode` with one audio param named `sourceValue` defaulting to 0.

**Comment by pendragon-andyh** [comment]
Do you need to specify anything about garbage collection?

Maybe "the node will become eligible for garbage collection when there are
no javascript references to the node AND when the node is no-longer
connected to a part of the audio graph that is being kept alive by a
oscillator or buffer-source node".

What should happen if the new ConstantSourceNode is connected directly to
the destination node (with no supporting oscillator)? Should it cause a
dc-offset until it goes out of scope ... or should it be silent because no
real node is driving the graph?

**Comment by rtoy** [comment]
A `ConstantSourceNode` is a real `AudioNode`, very similar to an `OscillatorNode`. I would expect it to behave the same in terms of GC just like an `OscillatorNode`.  Thus, I wouldn't expect to need to say anything special.

Unless, of course, you're thinking of `ConstantSourceNode` as if it were a constructible `AudioParam`.  But it's not; it's an `AudioNode`, att least how I've defined it here.  The group needs to decide if this is the correct approach or not.

**Comment by pendragon-andyh** [comment]
The ConstantSourceNode differs from other source nodes because it does not
have start and stop methods.

I have not rechecked the spec, but my memory says that the audio context
holds a reference to oscillator nodes until they stop - which therefore
makes them eligible for garbage collection.

**Comment by rtoy** [comment]
Ah.  The current (updated) PR actually includes start and stop methods.  But @hongchan and I were just discussing whether this makes sense or not. For an AudioParam, this probably doesn't make sense.  But for a source node it does, along with an onended event.

**Comment by mdjp** [comment]
Keep the factory method = yes
Name of attribute = source
Default value = 1
