### ISSUE TITLE
AudioBuffer should not be tied to a context

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#370]
AudioBuffers shouldn't really be tied to an AudioContext*.  Therefore, AudioBuffers should have a constructor that works - i.e. "context.createBuffer(2, 88200, 44100);" should turn into "new AudioBuffer(2, 88200, 44100);"

*except when they're created by decodeAudioData - and even that shouldn't be "tied" to an AudioContext - i.e. I think they should be shareable - but the context currently resamples.  We should also make decodeAudioData have a flag that disables the resampling.

**Comment by cwilso** [comment]
This is actually going to happen in v1, as part of #250.

**Comment by joeberkovitz** [comment]
I am reopening, moving to V1 and marking as needing discussion because it probably didn't happen in the way that @cwilso expected: the current `AudioBuffer` constructor takes a `BaseAudioContext` as its first argument. Which seems unnecessary; perhaps this was a mistake? Or is it nullable?

**Comment by cwilso** [comment]
Yeah, not sure why AudioContext is needed at all here?

**Comment by rtoy** [comment]
Yeah, let's remove this. I think we just forgot about this issue when defining the constructor.  So, something like

```
[ Constructor(AudioBufferOptions options)]
```

but `AudioBufferOptions.sampleRate` would now be required.

**Comment by danigb** [comment]
Hi, thanks for the awesome work, and sorry for comment on a cloosed issue, but I have a question:

Does it means that in next version of WAA we will be able to create a buffer using the constructor instead of AudioContext's factory function?:

```js
var buffer = new AudioBuffer(length, 44100);
buffer.copyToChannel(myArray);
```

Thanks

**Comment by rtoy** [comment]
On Tue, Jan 10, 2017 at 8:42 AM, danigb <notifications@github.com> wrote:

> Hi, thanks for the awesome work, and sorry for comment on a cloosed issue,
> but I have a question:
>
> Does it means that in next version of WAA we will be able to create a
> buffer using the constructor instead of AudioContext's factory function?:
>

​Yes.​


> var buffer = new AudioBuffer(length, 44100);
>
>
​But it would look more like:

var buffer = new AudioBuffer({length: length, sampleRate: 44100});
​

-- 
Ray

**Comment by danigb** [comment]
Great news! Thanks for the answer @rtoy !
