### ISSUE TITLE
Add a canDecodeType utility

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-audio-api#371]
Right now decodeAudioData says

> Audio file data can be in any of the formats supported by the audio element.

From a layering perspective, this is a circular dependency: we would like to explain `<audio>` in terms of web audio, but here web audio has taken a dependency on `<audio>`.

Practically, this screws me when trying to implement `<audio>` as part of HTML as Custom Elements.

I think web audio should have something like AudioContext.prototype.canDecodeType() that returns the same `""`, `"maybe"`, `"probably"` enum. Then we could explain `HTMLMediaElement.prototype.canPlayType` in those terms.

**Comment by billhofmann** [comment]
Still marked as v1 - should this be deferred?

**Comment by padenot** [comment]
I think we should push that to v.next, since we don't have proper layering anyway.

**Comment by rtoy** [comment]
Add Needs WG review for a final decision.

**Comment by rtoy** [comment]
Per teleconf, moving to v.next, per
https://github.com/WebAudio/web-audio-api/issues/371#issuecomment-151735933

**Comment by mdjp** [comment]
This will now be handled by https://discourse.wicg.io/t/webcodecs-proposal/3662
