### ISSUE TITLE
Rework PannerNode

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#372]
This came out of the discussion of issue #368 .

I think Panner needs a rework. Conflating equalpower (a pretty simple concept) and HRTF (not a simple concept, and an effect that would not play well with other effects later in the chain) seems like a bad idea. I'd really like a SIMPLE equal-power stereo panner node - effectively just chained gain nodes, with an input from -1 to +1 for left to right, or something like that - and a spatializer effect that works more like the current one, but could be smarter about how it gets inserted in the graph, and/or when the HRTF database is loaded. cf. http://lists.w3.org/Archives/Public/public-audio/2012JulSep/0411.html.

**Comment by cwilso** [comment]
Note to self:

SpatializerNode should have a loadHRTFDatabase() that returns a promise.

**Comment by cwilso** [comment]
Yeesh, I think I just didn't commit this.  https://github.com/WebAudio/web-audio-api/compare/372-StereoPanner.

**Comment by joeberkovitz** [comment]
@cwilso and @hoch to resolve via pull request

**Comment by kickermeister** [comment]
Can you give an indication when V1 or more specifically a specification of the aimed SpatializerNode will be published?

**Comment by cwilso** [comment]
Fixed by https://github.com/WebAudio/web-audio-api/pull/639.

**Comment by juj** [comment]
Hey, I'm trying to understand the deprecation here, and the consensus on this github issue thread reads to me as

> We're deprecating the current node, and we'll remove it from the spec.

with "current node" referring to PannerNode. But then looking at Chrome deprecation notice at https://www.chromestatus.com/features/5238926818148352, it instead reads

> The methods panner.setVelocity() and listener.setVelocity() and the attributes listener.speedOfSound and listener.dopplerFactor are now no-ops 

These two things seem different, but that deprecation notice links to this github issue for reference. Did PannerNode not get deprecated after all then, or are these two separate deprecations?

**Comment by rtoy** [comment]
You are correct.  `PannerNode` was originally going to be deprecated in favor of a new `SpatialPannerNode`, but it could be implemented in a backward-compatible way with `PannerNode` so the `PannerNode` was not deprecated.

The Doppler stuff, however, is gone.

**Comment by juj** [comment]
Thanks for the clarification.

What is the new API for performing a doppler effect? I don't see a documentation or a conversation that would discuss how to do `setVelocity`-type of audio feature in the new way. It would be good to pair API refactoring with documentation on how to migrate to the new style of API.

Though re-reading, it sounds like the doppler effect feature was removed altogether? But that is odd, because @cwilso started this issue with the original comment

> Conflating equalpower [...] and HRTF [...] seems like a bad idea. I'd really like a SIMPLE equal-power stereo panner node [...]

and a later comment

> Equal-power stereo panning, with a simple L-R control, is 99% of the desired scenarios. The current PannerNode has proven to be confusing to developers [...]

which suggests that the original motivation for breaking the API was because it was confusing, and the goal to refactor it to a new cleaner version.

How did refactoring the API then turn into removing features instead? Or am I just super confused here..?

**Comment by cwilso** [comment]
Doppler effect in the previous node was a hack, plain and simple.  It
walked back upstream to the source node and changed its playback rate - and
thus, didn't work on non-AudioBufferSourceNode sources (even Oscillator,
although it could have; but it simply would never have been able to work on
a live input node, for example).

The right way to do a Dopper effect in Web Audio would essentially be like
physical modelling - put in a delay node, and animate the delayTime based
on the motion of the object (that is, make the delayTime equate to the
distance of the source from the "ears", and use AudioParams to smoothly
interpolate between values).  That would not only provide a physically
accurate Doppler effect, it would work on all nodes.
