### ISSUE TITLE
Analyser size is quite limiting

### ISSUE THREAD

**Issue by cwilso** [WebAudio/web-audio-api#375]
I've repeatedly heard feedback that the 2k max FFT size in the AnalyserNode is overly restrictive, particularly in higher-sample-rate devices.  Would suggest evaluating upping it to 4k or 8k.

**Comment by rtoy** [comment]
Commit 25f480e fixed this (from pull request #463). Closing this.

**Comment by rtoy** [comment]
Actually close this, per https://github.com/WebAudio/web-audio-api/issues/375#issuecomment-113580488.
