### ISSUE TITLE
Real-Time messaging between AudioWorkers

### ISSUE THREAD

**Issue by ugur-zongur** [WebAudio/web-audio-api#382]
Is it possible to establish messaging functionality between AudioWorkers that is guaranteed to be delivered on real-time? E.g. a MessageChannel like structure where message dispatching is done deterministically without involving main thread.

**Comment by joeberkovitz** [comment]
MessagePorts can be passed directly to AudioWorkletProcessors via serialization and the built in 
main/rendering thread message channel, so this is already allowed.
