### ISSUE TITLE
Review spec wide behavior on setting enum to invalid values.

### ISSUE THREAD

**Issue by mdjp** [WebAudio/web-audio-api#383]
after discussion of issue #105 it was decided that we should review this behavior to ensure consistency

**Comment by joeberkovitz** [comment]
If @padenot is correct, sounds like we can close this

**Comment by billhofmann** [comment]
Does this still require a review to bring language in line with WebIDL?

**Comment by padenot** [comment]
I think we're good, I just had a look at other enums, and this one, and the text is good.
