### ISSUE TITLE
Throw TypeError for out of range arguments

### ISSUE THREAD

**Issue by Ms2ger** [WebAudio/web-audio-api#385]
For example in `AudioBufferSourceNode.start`. This is consistent with how non-finite floats are handled in the rest of the platform.

**Comment by zcorpan** [comment]
When fixing this, drop the prose about non-finite numbers since that is already handled by WebIDL when using `double` or `float` types (as opposed to `unrestricted double`/`unrestricted float`).

**Comment by billhofmann** [comment]
Done

**Comment by rtoy** [comment]
Reopen. This is pending the merge of pull request #579
