### ISSUE TITLE
PeriodicWave is limited to 4096

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#386]
The size of the arrays for a PeriodicWave is limited to a max of 4096. With a fundamental frequency of 20 Hz, the maximum harmonic is 81920 Hz.  Since some audio devices support up to 192 kHz sampling rate, the number of harmonics produced by a period wave is less than the highest Nyquist frequency.

Perhaps the limit should be increased to 4800 or maybe 8192?  Increasing the size has some implications on CPU usage because a larger IFFT is needed to generate the time domain signal.

This is a pretty minor detail.

**Comment by rtoy** [comment]
Since we know the sample rate of the context, we can choose to do an appropriately sized FFT.  Thus, for typical rates around 44.1 kHz, 2048 is an appropriate size.  For those folks with ultrasonic ears running at 192 kHz, they can pay the price of larger FFTs.

Thus, I think we just need to select a new maximum size to support 192 kHz, and maybe update the spec to say that for lower sample rates not all of the values may be used because they would be beyond the Nyquist rate (for some nominal minimum fundamental frequency).  Or something.

**Comment by joeberkovitz** [comment]
If no objections to @rtoy proposal, can this be applied to the spec?

**Comment by rtoy** [comment]
Fixed by commit 9eab3d2a93872476ea95fd17df938eaffec5ab01
