### ISSUE TITLE
Proposed: recorderNode

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#39]
> Originally reported on W3C Bugzilla [ISSUE-21533](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21533) Tue, 02 Apr 2013 15:13:13 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26

Proposal for a real-time recorderNode. Already possible with scriptProcessorNode - but dedicated node would be more conveinient.

**Comment by svgeesus** [comment]
related to https://github.com/WebAudio/web-audio-api/issues/496

**Comment by mdjp** [comment]
Closed see #496 for future solution
