### ISSUE TITLE
Specify nominal ranges for AudioParam

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#391]
Some of them already have a nominal range, but some are missing. I also propose that we clamp the values to the nominal range if it happens to be outside the range.

The one that are missing, along with a proposal, are:
- GainNode.gain: `[-sampleRate/2; sampleRate/2]` (that is, the max of any other AudioParam, for AudioNode -> GainNode -> AudioParam purposes)
- AudioBufferSourceNode.playbackRate: `[0; 10000]`. The upper range is somewhat arbitrary

**Comment by mdjp** [comment]
Proposal to review parameters for suitable treatment and upper and lower limits if clamping.

**Comment by padenot** [comment]
Note to self, we need to allow negative `playbackRate`, now.

**Comment by notthetup** [comment]
:clap:
