### ISSUE TITLE
Tail-time reference should be noted for Convolver, Delay, AudioWorker

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#414]
The *Lifetime* section of the spec http://webaudio.github.io/web-audio-api/#lifetime-1 explains a **tail-time reference** that pins a node in the graph while it has pending, audible internal state. ConvolverNode is mentioned explicitly as an example of a node with a tail time, and it's stated that descriptions of nodes elsewhere in the document will mention a tail-time reference if it's applicable to that node.

1. The ConvolverNode interface makes no mention of tail-time reference. Presumably it should, since this is the one node that has it for certain.

2. The AudioWorkerNode should probably documented as having a tail-time reference as long as it has an active onaudioprocess handler, since it can act as a source and has an internal state unknown to the audio engine. It could be emitting a signal at any given time.

3. Shouldn't DelayNode have a tail-time as well?

**Comment by joeberkovitz** [comment]
Can this be marked Ready for Editing? What remains to be decided?

**Comment by hoch** [comment]
Here are some follow-up questions:
- Do implementors have to expose `node.tailTime` attribute as a read-only value?
- What about the node with the variable tail time? (i.e. delay, convolution, biquad...)
- If they can be changed dynamically, what level of accuracy do we want to have in terms of updating/getting this value?

**Comment by joeberkovitz** [comment]
- We did not discuss exposing this time in the API. Is there a good reason we must do so? It will create additional issues with determining the current tail time (as you pointed out).

- I do not think there is any issue with having variable tail times providing they are well-defined based on the node state.

**Comment by rtoy** [comment]
On Tue, May 5, 2015 at 1:01 PM, Joe Berkovitz <notifications@github.com>
wrote:

>
>    -
>
>    We did not discuss exposing this time in the API. Is there a good
>    reason we must do so? It will create additional issues with determining the
>    current tail time (as you pointed out).
>
> ​I don't see any reason to expose it.  What would the user do with it?
All I could think of is disconnecting the node after the tail time.  But
the implementation could do that itself. Or at least optimize the case
where the tail-time has passed.​


>
>    -
>
>    I do not think there is any issue with having variable tail times
>    providing they are well-defined based on the node state.
>
> ​I agree. It's a bug in the implementation if there should be non-zero
output and there isn't.​


>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/414#issuecomment-99204116>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
F2F Resolution: we're going to mention the existence of tail-time for nodes that have it but leave unquantified and unexposed via the API for V1.
