### ISSUE TITLE
Define the behaviour when disconnect called on node output wired to an AudioParam

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#43]
> Originally reported on W3C Bugzilla [ISSUE-21539](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21539) Tue, 02 Apr 2013 16:03:27 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26

When an AudioNode is connected to an AudioParam and disconnect() is called, what should the behaviour be? How will it affect the value of the AudioParam. This needs to be specified in greater detail.

**Comment by hoch** [comment]
Related to #482.
