### ISSUE TITLE
suspend/resume/close should use rejected promise for offline contexts

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#441]
Currently the spec says that suspend/resume/close on an offline context should throw an exception.  However, since these methods also return a promise, it seems more appropriate not to throw an exception but return a promise that is rejected with an InvalidStateError DOM exception.

**Comment by padenot** [comment]
Agreed.

**Comment by padenot** [comment]
I think it's a bit weird that `OfflineAudioContext.{suspend,resume,close}` use `InvalidStateError`, because this is a matter of type, not state. I'd rather use `InvalidAccessError`, which means:

> The object does not support the operation or argument.

@rtoy, any thoughts ?

(<http://w3c.github.io/dom/#error-names-0>)

**Comment by rtoy** [comment]
InvalidAccessError works for me.

On Tue, Mar 24, 2015 at 8:19 AM, Paul Adenot <notifications@github.com>
wrote:

> I think it's a bit weird that OfflineAudioContext.{suspend,resume,close}
> use InvalidStateError, because this is a matter of type, not state. I'd
> rather use InvalidAccessError, which means:
>
> The object does not support the operation or argument.
>
> @rtoy <https://github.com/rtoy>, any thoughts ?
>
> (http://w3c.github.io/dom/#error-names-0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/441#issuecomment-85548941>
> .
>



-- 
Ray

**Comment by rtoy** [comment]
Closing this.  

Based on the discussion in #302 where offline contexts get support for suspend/resume and on pull request #561, this isn't valid anymore.  The appropriate rejections should be handled in #561.

**Comment by padenot** [comment]
We still need to spec what exception is passed to the rejected promise, the last PR fixes that.

**Comment by joeberkovitz** [comment]
This has been addressed; closing.
