### ISSUE TITLE
Add a playing reference to MediaElementAudioSourceNode and MediaStreamAudioSourceNode

### ISSUE THREAD

**Issue by jdsmith3000** [WebAudio/web-audio-api#442]
http://webaudio.github.io/web-audio-api/#lifetime-1 describes AudioNode lifetime.  The spec states that only AudioBufferSourceNode and OscillatorNode use a playing reference.  We've seen implementations that add a playing reference for Media Element and Media Stream AudioNodes as well.  This will keep the Media Element and Media Stream nodes, the nodes they’re connected to, and the AudioContext alive until the document closes.  This seems the desired behavior and should be specified.

**Comment by mdjp** [comment]
Should be marked as informative. It should stay in the spec despite the fact that this should be observable.

**Comment by jdsmith3000** [comment]
I had to fix some issues with travis checks and conforming with tidy HTML.  The PR for this issue is now ready for review.
