### ISSUE TITLE
OfflineAudioContext and AudioContext decoding should complete before garbage collection

### ISSUE THREAD

**Issue by jdsmith3000** [WebAudio/web-audio-api#443]
The following code snippet illustrates this scenario:

function playOfflineAudio() {
    var context = new OfflineAudioContext(...);
    ...    
    context.oncomplete = finishAudioTest;
    context.startRendering(); 
}

If garbage collection runs before the complete event fires, the OfflineAudioContext will get garbage collected and never fire the event.  It would be consistent with the rest of our media event handling to require the OfflineAudioContext to complete before allowing this.

A similar issue can be encountered calling decodeAudioData() in AudioContext.

Proposed Solution: The OfflineAudioContext should remain alive until it finishes processing and fires the complete event.  Similarly, AudioContext should remain alive until it finishes decoding and fires the decoding complete event.

**Comment by mdjp** [comment]
Agreed that spec should note this behavior.

**Comment by billhofmann** [comment]
I'm going to read this as:
*AudioContext shall not be garbage collected after decodeAudioData until the promise is rejected and errorcallback called, or promise resolved and successcallback called (note, is that order correct)?
* OfflineAudioContext: shall not be garbage collected after startRendering before promise is resolved and  completion event called UNLESS the rendering is suspended.
