### ISSUE TITLE
OfflineAudioContext should not fire "complete" directly

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#448]
But should queue a task to do so.

See Gecko [bug 1087944], comments 9.

[bug 1087944]: https://bugzilla.mozilla.org/show_bug.cgi?id=1087944

**Comment by joeberkovitz** [comment]
@padenot Please merge https://github.com/WebAudio/web-audio-api/commit/a72bd41d67f0b5ec0abcb45afd3d69ca310fa60d and close this bug.
