### ISSUE TITLE
Record all documentation that is considered developer documentation

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#45]
> Originally reported on W3C Bugzilla [ISSUE-21548](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21548) Tue, 02 Apr 2013 16:20:21 GMT
> Reported by Olivier Thereaux
> Assigned to 

Per discussion at Audio WG f2f 2013-03-26

This is a placeholder to keep track of all the sections in the spec which are considered "developer documentation", to be split out from the spec and into a primer/developer doc type document.

**Comment by mdjp** [comment]
Will mark up developer documentation and we can review/discuss before applying to the spec

**Comment by joeberkovitz** [comment]
Seems to largely refer to Section 9 at this point.
