### ISSUE TITLE
(CircularRouting): Circular graphs should exist while observable?

### ISSUE THREAD

**Issue by mark-buer** [WebAudio/web-audio-api#452]
Should cyclic graph fragments stay alive while they are observable through *any* means?

[The spec states](http://www.w3.org/TR/webaudio/#lifetime-AudioNode):
> Any AudioNodes which are connected in a cycle and are directly or indirectly connected to the AudioDestinationNode of the AudioContext will stay alive as long as the AudioContext is alive.

But, the output of the cycle may be observable via a MediaStreamAudioDestinationNode or an AnalyserNode.

What happens in these cases?

**Comment by joeberkovitz** [comment]
Resolution: fix the spec to cite MediaStreamAudioDestinationNode as well as AudioDestinationNode (they don't share a super-interface).
