### ISSUE TITLE
ChannelMergerNode in a cycle has unspecified behaviour

### ISSUE THREAD

**Issue by mark-buer** [WebAudio/web-audio-api#459]
What happens if the output of a ChannelMergerNode is fed back into it's input (via a DelayNode)?
The specification does not state the expected runtime behaviour.

As an illustration, please consider the following JS snippet where a ChannelMergerNode has two connected inputs - an oscillator, and the ChannelMergerNode itself (via a DelayNode):
```javascript
var audioContext;
if (!audioContext) {
    if (window.AudioContext) {
        audioContext = new AudioContext();
    } else if (window.webkitAudioContext) {
        audioContext = new webkitAudioContext();  
    } else {
        throw new Error('AudioContext missing');
    }
}

var o = audioContext.createOscillator();
var m = audioContext.createChannelMerger(2);
var d = audioContext.createDelay();

o.connect(m, 0, 0);
d.connect(m, 0, 1);
m.connect(d);
m.connect(audioContext.destination);
d.delayTime.value = 0.5;
o.start(0);
```

The snippet produces silence in Blink and seems to correctly produce a tone in Mozilla.

**Comment by joeberkovitz** [comment]
Fixed by changing behavior of ChannelMergerNode #304
