### ISSUE TITLE
InvalidAccessError for WaveShaperNode.curve?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#464]
Currently the [spec for WaveShaperNode.curve](https://webaudio.github.io/web-audio-api/#widl-WaveShaperNode-curve) says an InvalidAccessError should be thrown if the curve is too short.  It seems that InvalidStateError would be more appropriate.

**Comment by hoch** [comment]
+1

**Comment by joeberkovitz** [comment]
Resolution: change error type as proposed
