### ISSUE TITLE
Make AudioParam value attribute be a double instead of float

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#465]
The AudioParam value and defaultValue attributes are defined to be floats. This seems fine for general use, but if the AudioParam represents a time value, this can cause problems due to loss of precision from converting the JS double float to an AudioParam float.  I find it annoying that if I do delayNode.value = 128/44100, the value read back is not the same as what I set it too.

This inaccuracy can be seen in https://code.google.com/p/chromium/issues/detail?id=448801.

It would be beneficial to make these attributes be doubles instead of floats.  Internally algorithms can continue to use floats, if desired, for speed reasons, so there doesn't have to be any visible change in behavior, but it is hoped that implementers will choose carefully.  Chrome would certainly like the example in 448801 work as a naive user would expect.

**Comment by padenot** [comment]
Have you thought about specifying how to round time (possibly in addition to making AudioParam doubles) ? I'm thinking that maybe rounding to the nearest integer would solve quite a lot of those issues. I don't know if this respects ES/WebIDL semantics, though.

The right way to do this would be to have a API that is in sample-frames so authors can round on their own, but I'm afraid it's a bit late for this, now (and it's possibly easier for people to understand seconds, maybe?).

**Comment by rtoy** [comment]
On Thu, Jan 15, 2015 at 3:07 AM, Paul ADENOT <notifications@github.com>
wrote:

> Have you thought about specifying how to round time (possibly in addition
> to making AudioParam doubles) ? I'm thinking that maybe rounding to the
> nearest integer would solve quite a lot of those issues. I don't know if
> this respects ES/WebIDL semantics, though.
>

​Based on the code in Chrome, it seems that time is usually not rounded to
a frame.  Instead, linear interpolation is used to get the desired value if
the time is not on a sample frame boundary.  However, in cases where it
makes sense, time is rounded (not truncated) to the nearest sample frame.

> The right way to do this would be to have a API that is in sample-frames
> so authors can round on their own, but I'm afraid it's a bit late for this,
> now (and it's possibly easier for people to understand seconds, maybe?).
>

​Yeah, I think it's way too late for an API using sample-frames.

I think the problem with sample frames is that the frame number keeps
changing depending on the sample rate.  It's easier to work in seconds in
that case, which is probably closer to what people expect. Like start
playing in 1 sec, instead of 44100 frames on that machine, but 48000 over
there, and 192000 on your machine.​


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/465#issuecomment-70070677>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
Resolution: leave typed as float in IDL, recommend to developers that if converting between integer units and real units for same quantity (e.g. sample frames vs. time) use rounding judiciously to avoid truncation errors.

**Comment by rtoy** [comment]
I did a little more investigation using the example listed in the chromium bug.  It appears that there is no way to get exactly 128 internally.  Rounding doesn't help, adding a magical fudge factor doesn't help. I think fundamentally there is no way to get 44100 * (x/44100) to produce 128 for any value x when done with single precision floating point numbers.

So, I propose there is no text that needs to be added to the spec.
