### ISSUE TITLE
Define FFT for AnalyzerNode

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#470]
The FFT is not specified for the AnalyzerNode.  There is at least the mathmatician's definition and the engineer's definition which are slightly different.  And the FFT has at least 3 different possible scalings (1, 1/N, 1/sqrt(N)), so that means at least 6 different possible implementations.

I believe all implementations use the engineering definition with a scale factor of 1:

X(k) = sum(x(n)*exp(-j*2*pi*k*n/N), n = 0, N - 1)

**Comment by hughrawlinson** [comment]
:+1:

**Comment by padenot** [comment]
Agreed, I'll take this, verify Blink/WebKit/Gecko use the same definition, and write the normative text.
