### ISSUE TITLE
PannerNode specification inconsistent

### ISSUE THREAD

**Issue by LJ1102** [WebAudio/web-audio-api#471]
In `2.15.1 Attributes` it says that the panningModel `Defaults to "HRTF"` while [a few paragraphs above](https://github.com/WebAudio/web-audio-api/blob/aa075bfd515c3d586a0fc34a6ec2cc7bcb0426c9/index.html#L2695) it says `The default is "equal-power"` followed by the specification of the `PanningModelType` enum enumerating `equalpower` without the hyphen.

I noticed that(as of #372) the PannerNode will eventually be deprecated and removed. But until then it would be beneficial to have a consistent spec here as this inconsistency seems to have already resulted in Firefox using "`HRTF`" as default while Chrome uses "`equalpower`".

**Comment by joeberkovitz** [comment]
Fix conflicting specs of default value.
