### ISSUE TITLE
Allow arraybuffers to be made immutable and shared between main and audioworkernode threads

### ISSUE THREAD

**Issue by charlieschwabacher** [WebAudio/web-audio-api#474]
It would be nice to have a way to make an audio file available both to an audio worker node and to the main thread, for example to be able to do audio processing while using canvas or svg to show an interactive representation of the waveform as part of the user interface.

Serializing and sending the file to the worker will duplicate it in memory, and transferring it will make it unavailable to the main thread.

If we can make an ArrayBuffer read only, we can share it between the worker and code in the main thread while preserving thread safety and without duplicating it in memory.

Maybe a syntax like audioWorkerNode.postMessage(message, [transfers], [shares])?

**Comment by padenot** [comment]
This is something that should not be Web Audio API specific. iirc, there is something in the works, that looks like a facility to create immutable slice of an ArrayBuffer that are transferable without neutering, but I can't remember the name, and I can't find it.

**Comment by charlieschwabacher** [comment]
Great to hear something is in the works!  This is definitely not something specific to Web Audio, I just came across the issue while using a worker thread to fill buffers for a ScriptProcessorNode, and needing to copy buffers of sample data.  The ability to share immutable data between threads seems particularly useful for web audio, so I am sort of hoping that discussion here could help move it forward in another spec?

I have not been able to find anything in a standard either, but did find this gist which seems like a strong proposal.  https://gist.github.com/dherman/5401735

**Comment by joeberkovitz** [comment]
Resolution: This issue will be handled by having Transferables behave appropriately as part of the `postMessage()` implementation that will be exposed by AudioWorkerNodes. The details of that will be very similar to the handling of array buffers for Workers.

**Comment by taisel** [comment]
We already have this ability in Firefox Nightly: https://blog.mozilla.org/javascript/2015/02/26/the-path-to-parallel-javascript/

SharedArrayBuffers are what you want to postMessage with transferable object support to share the same array between both contexts.

**Comment by joeberkovitz** [comment]
We have instead decided to replace the Transferable passing in postMessage with a simpler structured-cloning-only data transfer API, and leave it to Javascript to supply read-only array slices at some point in the future.
