### ISSUE TITLE
AudioWorkerNode should still work if not connected to destination

### ISSUE THREAD

**Issue by hughrawlinson** [WebAudio/web-audio-api#476]
ScriptProcessorNode in Chrome won't call the callback unless the SPN is connected to context.destination (either directly or via other nodes). From my reading, whether or not this is correct behaviour is not defined in the spec, nor is it defined for AudioWorkerNode. Not sure if this isn't necessary because of how it has to be implemented, but it seems like a good idea to define this.

My two cents: AudioWorkerNode should work as long as there's one or more output OR one or more input. This will facilitate signal generation from scratch, as well as signal analysis without any output.

**Comment by rtoy** [comment]
On Thu, Feb 5, 2015 at 2:24 AM, Hugh Rawlinson <notifications@github.com>
wrote:

> ScriptProcessorNode in Chrome won't call the callback unless the SPN is
> connected to context.destination (either directly or via other nodes). From
>

​I think this is a bug in Chrome's implementation. A SPN should be able to
work as a sink, like an AnalyzerNode.  Since the SPN is deprecated, the
motivation to fix this is drastically reduced.​


> my reading, whether or not this is correct behaviour is not defined in the
> spec, nor is it defined for AudioWorkerNode. Not sure if this isn't
> necessary because of how it has to be implemented, but it seems like a good
> idea to define this.
>
> My two cents: AudioWorkerNode should work as long as there's one or more
> output OR one or more input. This will facilitate signal generation from
> scratch, as well as signal analysis without any output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/476>.
>



-- 
Ray

**Comment by hughrawlinson** [comment]
Absolutely, the SPN definition doesn't matter as it's deprecated, but the behaviour should be defined in the spec for AnalyserNode, which going by @cwilso's fork it isn't (if I'm reading it correctly).

**Comment by hughrawlinson** [comment]
I meant AudioWorkerNode rather than AnalyserNode, oops. Edited the comment.

**Comment by cwilso** [comment]
Actually, it explicitly says " audioprocess events are only dispatched if the AudioWorkerNode has at least one input or one output connected."

**Comment by hughrawlinson** [comment]
Sorry, my mistake!
