### ISSUE TITLE
Clarify real array usage in createPeriodicWave

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#478]
https://webaudio.github.io/web-audio-api/#widl-AudioContext-createPeriodicWave-PeriodicWave-Float32Array-real-Float32Array-imag describes how the real and imaginary arrays are used for the PeriodicWave.

For the real array, it suggests that real[0] should be 0.  In Chrome, Firefox, and Safari, this is not a suggestion.  The internal computations make real[0] be zero.  The text should be updated to say real[0] is ignored.

**Comment by joeberkovitz** [comment]
Merged
