### ISSUE TITLE
AudioNode.channelCount = 0 throws NotSupportedError

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#480]
The spec (https://webaudio.github.io/web-audio-api/#widl-AudioNode-channelCount) says NotSupportedError is thrown. The spec doesn't say, but presumably setting channelCount to be greater than the implementation's maximum number of channels should also throw.  

In this case, IndexSizeError seems more appropriate.

**Comment by hoch** [comment]
+1

It is not like "we can't do it", it is more like "you shouldn't do it."

**Comment by padenot** [comment]
Well, admittedly, when setting it to something greater than the max for one particular implementation, `NotSupportedError` makes sense, because it possible another implementation supports more channels.

**Comment by rtoy** [comment]
Leaving it as NotSupportedError is acceptable to me.

**Comment by joeberkovitz** [comment]
Resolution: leave as NotSupportedError for zero case, setting channelCount to be greater than the implementation's maximum number of channels should also throw NotSupportedError.
