### ISSUE TITLE
Should Convolver normalisation be based on integrated energy?

### ISSUE THREAD

**Issue by chrispike-bbc** [WebAudio/web-audio-api#481]
The ConvolverNode's normalize parameter is intended to "achieve a more uniform output level from the convolver when loaded with diverse impulse responses". I have found issues with zero-padding in impulse responses giving drastically different loudness.
This simple example shows that when normalize is true a short impulse response is much quieter than a long impulse response. Both are unit impulses i.e. the first sample is 1 and the rest are 0.

http://vm-1015-user.virt.ch.bbc.co.uk/webaudio-test/convolver/index.html

I admit that this is a contrived example, but I wonder if we would get more consistent loudness by using the integrated energy in the impulse response buffer, rather than dividing by the length of the buffer?

**Comment by rtoy** [comment]
Are you saying the normalization should be based on the sum of squares of the impulse response buffer instead of the sum of squares divided by the length? The latter is what the spec currently says, I think.

**Comment by chrispike-bbc** [comment]
Yes.
My suggestion is essentially that the line in the normalisation algorithm:
<pre><code>power = sqrt(power / (numberOfChannels * length));</code></pre>
becomes:
<pre><code>power = sqrt(power / numberOfChannels);</code></pre>

**Comment by rtoy** [comment]
Don't have any real technical objections to this change.  However this will very likely break just about every single app out there that uses a convolver node.

**Comment by chrispike-bbc** [comment]
Good point. I don't have strong feelings about it. Happy to let it lie.
Chris
________________________________

**Comment by rtoy** [comment]
Fortunately, for some one that needs fine-grained control over this, there is the normalize attribute to turn off this scaling so you can do the appropriate scaling yourself.

**Comment by joeberkovitz** [comment]
Closing; see previous comment.

**Comment by karlt** [comment]
If this change were to be made, so as to make normalization useful, it would be sensible to change the GainCalibration based on the average reverb buffer length to compensate for the change in scaling.  Obviously though, there are different lengths and so making such a change would still change the volume of existing apps.
