### ISSUE TITLE
AudioWorkerNode buffer size

### ISSUE THREAD

**Issue by echo66** [WebAudio/web-audio-api#484]
Greetings!

I noticed that the specification does not consider a custom buffer size for AudioWorkerNode. Is there a reason for that?

**Comment by padenot** [comment]
Yes, the Web Audio API mandates block processing, and a fix buffer size for each block of 128 samples. One design goal of the AudioWorkerNode is to not add latency to the graph and to the output, so its size is fixed, at 128 samples as well, that is, one block.
