### ISSUE TITLE
Remove or update hardware scalability section

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#487]
There's the non-normative section http://webaudio.github.io/web-audio-api/#hardware-scalability about how to scale webaudio to hardware available.  In particular, the section talks about the cpuUsage and priority attributes for an AudioNode.  These attributes were removed from the spec several months ago, so we should consider either updating or removing this section on hardware scalability.

**Comment by padenot** [comment]
Agreed. I double-checked, there are nothing really worth keeping in here.
