### ISSUE TITLE
Define DOM exceptions for DecodeErrorCallback

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#489]
https://webaudio.github.io/web-audio-api/#callback-decodeerrorcallback-parameters says the callback should take a DOMException. However, I couldn't find anything saying what kinds of exceptions are thrown. It seems clear that the intent was for an implementation to tell the developer what happened to cause decoding to fail.

To be useful, I think some of the common errors should be defined.  Off the top of my head some useful error conditions:

 * Unsupported encoding
 * Invalid or corrupted data
 * Unsupported number of channels (too many or too few)
 * Unsupported sample rate

**Comment by padenot** [comment]
I'm not sure `DOMException` have the right level of expressiveness, here.

For example Gecko, we fire the error callback (I can't remember if we pass a parameter), and then report an (hopefully) more readable and actionable message to the developer console, but those don't map to existing `DOMException`.

Are you proposing to add new exception to the DOM spec?

**Comment by rtoy** [comment]
No, not proposing a new exception.  Chrome currently just passes null to the callback and there are no messages anywhere on why decoding failed.
