### ISSUE TITLE
Feature Request - encodeAudioData

### ISSUE THREAD

**Issue by ghost** [WebAudio/web-audio-api#496]
Hi,

I'm not sure if this has been discussed before because an issue search wasn't returning any results, so I thought I would submit a new issue.

In a nutshell, I believe updating the `OfflineAudioContext` interface to expose a `encodeAudioData` method would be of use to many users of the Web Audio API.

The `encodeAudioData` method would run the same operation as the `startRendering` method but would also encode the rendered audio to a supported format before returning an array buffer. I'm not expecting any audio formats that require a licensed encoder to be supported, e.g. AAC, but some popular formats including Vorbis could be freely supported.

I imagine the updated `OfflineAudioContext` interface to look something like this ...

```
[Constructor(unsigned long numberOfChannels, unsigned long length, float sampleRate)]
interface OfflineAudioContext : AudioContext {
    Promise<AudioBuffer> startRendering ();
    Promise<ArrayBuffer> encodeAudioData (DOMString mimetype, DOMString codec);
    attribute EventHandler oncomplete;
};
```

An obvious example of use would be ...

```
oac.encodeAudioData("audio/ogg", "vorbis").then(buffer => doSomethingWith(buffer));
```

One more thing, and this is slightly off-topic, but is the `oncomplete` attribute of any real use?

**Comment by cwilso** [comment]
I think this should be on AudioBuffer, not OfflineAudioContext; also the encoding API should mirror the MediaRecorder API (http://w3c.github.io/mediacapture-record/MediaRecorder.html).  It might be extra-credit-nice to support incremental encoding, particularly to an output stream.

**Comment by si-robertson** [comment]
Yep, sounds good, whatever works best for you guys. As far as incremental encoding goes, one idea is to tell the encoder to push the encoded bytes to a [writable stream](https://streams.spec.whatwg.org/#ws-model) if a writable stream is passed to the `encodeAudioData` method ...

````
encodeAudioData (DOMString mimetype, DOMString codec, optional WritableStream stream);
````

The Stream API might not be shipped in web browsers for a while tho.

**Comment by padenot** [comment]
What about using MediaRecorder [0], here? It kind of does what we want,
we just need to make it work offline.

[]: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

**Comment by joeberkovitz** [comment]
Deferring post-V1 when we can treat encoding and decoding in a disciplined way w/r/t architectural layering.

**Comment by rtoy** [comment]
Actually mark as a feature request so we can search for it.

**Comment by mdjp** [comment]
This is best addressed via web codecs.
https://discourse.wicg.io/t/webcodecs-proposal/3662
