### ISSUE TITLE
computedPlaybackRate and pitch

### ISSUE THREAD

**Issue by iccir** [WebAudio/web-audio-api#497]
A question about Section 2.9.1 and Section 2.9.2:

Per the current wording of the specification, both `playbackRate` and `detune` affect the speed of the audio stream.  In all current implementations, this affects the pitch as well.  To anybody with audio experience, this is expected.

However, based on the current wording, would it be possible for an implementor to use a time stretching algorithm to alter the "effective speed" of the AudioBuffer, keep the pitch the same, and still technically be in compliance with the specification.

Specifically: should there be wording that clarifies how the `computedPlaybackRate` actually affects the pitch of the audio.

**Comment by padenot** [comment]
Yes, it's a bit unclear, although having a `detune` attribute clearly _hints_ at pitch change. I'll see if I can find something better to make it explicit that this is expected to simply resample the audio.

In any case, thanks for you comment.

**Comment by iccir** [comment]
I definitely agree that it's hinted at, I'm just trying to figure out where an implementor of the API might say "Oh, I'll just hook it up to this system function here that handles playback rates!" and not realize the intent of the specification.

In other words, I'm being overly paranoid that my company's synthesizer is going to break on some platform in the future :)

**Comment by joeberkovitz** [comment]
Resolution: clear up the language to note that pitch will in fact be altered, not just speed.
