### ISSUE TITLE
AudioParam Automation Example graph missing setTargetAtTime

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#5]
> Originally reported on W3C Bugzilla [ISSUE-17701](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17701) Thu, 05 Jul 2012 15:03:59 GMT
> Reported by Olivier Thereaux
> Assigned to 

The example at the end of the section on AudioParam Automation is giving examples for setValueAtTime, linearRampToValueAtTime, exponentialRampToValueAtTime and setValueCurveAtTime but not setTargetValueAtTime - which is too bad since that one seems to be the one hardest to comprehend.

**Comment by padenot** [comment]
Raymond, assigning to you since you've started.
