### ISSUE TITLE
Web Audio API

### ISSUE THREAD

**Issue by vaidehismart** [WebAudio/web-audio-api#502]
Hi,
I've used web audio API to record voice. But I'm getting message No Web Audio Suport in this browser when I record the voice in Chrome 41 in Iphone 5. Iphone 5 has iOS 8.0.2. Anyone knows the reason?

**Comment by cwilso** [comment]
IOS safari had no getusermedia support

**Comment by vaidehismart** [comment]
But I'm trying to record an audio through Chrome browser.. And chrome supports getusermedia. In desktop chrome, I''m able to record voice. On my Iphone chrome version is 41.0.2272.58

**Comment by cwilso** [comment]
Chrome on iOS - ANY browser on iOS - has Safari's webkit core.  Apple doesn't allow anyone else to ship core web engines.
