### ISSUE TITLE
Section 3.1 has a dead link

### ISSUE THREAD

**Issue by iccir** [WebAudio/web-audio-api#507]
In Section 3.1, the following link is broken:

"In cases where the channel layouts of the outputs do not match, a mix (usually up-mix) will occur according to the [mixing rules](http://webaudio.github.io/web-audio-api/UpMix)"

**Comment by padenot** [comment]
Fixed in https://github.com/WebAudio/web-audio-api/commit/22d59412ef28b859ac3c3eb8a91c82dadcec46df, thanks.
