### ISSUE TITLE
Why we have to call ctx.createBufferSource() every time?

### ISSUE THREAD

**Issue by Mr21** [WebAudio/web-audio-api#508]
Hi :)

Webaudio is an amazing work (like all the others HTML5 technologies)!!
But I discover this one only recently...

I was suprised we have to call `createBufferSource` each time we have to play (`.start()`) a sound.
I search on these issues an answer but I didn't found.

Can you explain me (and for others) why you wrote the API that way?
I suppose is the perfect way but I don't understand why calling `createBufferSource` many times is better.

Thanks!

**Comment by cwilso** [comment]
This is essentially a duplicate of #373.  In short, buffersourcenodes are one-shot to avoid race conditions - that is, modifying the buffersource in one thread while it's playing in the audio thread - while enabling fire-and-forget node usage.

That said, there are scenarios where a reusable buffer playback node would be useful - that's captured, and then was moved to v.next, in #373.

**Comment by Mr21** [comment]
Oh I see, thanks you for this clarification :)
