### ISSUE TITLE
AudioParam rates for BiquadFilterNode are inconsistant

### ISSUE THREAD

**Issue by pendragon-andyh** [WebAudio/web-audio-api#509]
Section 2.23 of the API specification contains the following sentences:
* Both frequency and detune are **a-rate** parameters and are used together to determine ...
* **All** attributes of the BiquadFilterNode are **k-rate** AudioParam.

**Comment by padenot** [comment]
We can just remove then mention of a-rate, I think.

@rtoy, @jipodine do you think there is a use case to have a-rate filters ?

**Comment by rtoy** [comment]
I don't see a reason for a-rate filters, but perhaps I lack imagination.

On Fri, Apr 17, 2015 at 8:48 AM, Paul Adenot <notifications@github.com>
wrote:

> We can just remove then mention of a-rate, I think.
>
> @rtoy <https://github.com/rtoy>, @jipodine <https://github.com/jipodine>
> do you think there is a use case to have a-rate filters ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/509#issuecomment-94013359>
> .
>



-- 
Ray

**Comment by luketeaford** [comment]
Audio rate filters are extremely important for synthesis. It's a well known technique for creating rough timbres. Even a very subtle amount can add a pleasing depth to the sound.

**Comment by hoch** [comment]
@luketeaford Can you provide an example that really makes difference? Although it is specified k-rate, the filter commonly has internal de-zippering on parameters (which operate on top of coefficients) and the output signal usually smoothed out by the nature of memory inside.

Is this about manipulating actual coefficients sample-by-sample basis? If that's the case, it is hard for me to see its usefulness.

**Comment by luketeaford** [comment]
I'm not sure because that is beyond my mathematical understanding. I am doing (to the best of my knowledge anyway) arate filter modulation on my web audio synth and I think the way it sounds is correct.

**Comment by rtoy** [comment]
If it's web audio and if it's using the biquad filter, then it can't be
a-rate. I'm pretty sure every browser does only k-rate.

On Fri, Apr 17, 2015 at 11:29 AM, Luke Teaford <notifications@github.com>
wrote:

> I'm not sure because that is beyond my mathematical understanding. I am
> doing (to the best of my knowledge anyway) arate filter modulation on my
> web audio synth and I think the way it sounds is correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/509#issuecomment-94046438>
> .
>



-- 
Ray

**Comment by jipodine** [comment]
For AM and FM effects, with a modulation above few Hertz, yes it sounds bad with a k-rate, because its sampling rate is only around 300Hz (depending on the AudioContext.sampleRate). I do not know how many people will actually use it, but given the nature of the Web Audio API with its nodes and connections, it is one of the interesting use-cases that are possible right now.

However, we should keep in mind that the biquad is not a Moog, and that quickly varying the coefficients may lead to uncontrolled results, specially across implementations. In particular, I was not able to find in the specification the implementation type of the biquad (direct- or transposed-form, I or II). And the AudioContext.sampleRate is an other factor of variation.

**Comment by rtoy** [comment]
On Sat, Apr 18, 2015 at 3:24 AM, Jean-Philippe Lambert <
notifications@github.com> wrote:

> For AM and FM effects, with a modulation above few Hertz, yes it sounds
> bad with a k-rate, because its sampling rate is only around 300Hz
> (depending on the AudioContext.sampleRate). I do not know how many people
> will actually use it, but given the nature of the Web Audio API with its
> nodes and connections, it is one of the interesting use-cases that are
> possible right now.
>

​Good point. It would certainly be nice, however, if someone had a useful
demo that demonstrates that the sound quality is bad.​


> However, we should keep in mind that the biquad is not a Moog, and that
> quickly varying the coefficients may lead to uncontrolled results,
> specially across implementations. In particular, I was not able to find in
> the specification the implementation type of the biquad (direct- or
> transposed-form, I or II).
>
​Does it really matter what the implementation type is?  They're all
equivalent.  Well, except that round-off effects might be different.​


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/509#issuecomment-94151617>
> .
>



-- 
Ray

**Comment by hoch** [comment]
@jipodine Oh, I missed that one. Yes, FM/AM is a valid use case for a-rate parameters. Also can you elaborate your comments?

> we should keep in mind that the biquad is not a Moog, and that quickly varying the coefficients may lead to uncontrolled results, specially across implementations.

**Comment by hoch** [comment]
@rtoy Not sure how we can compare them inside of Web Audio API. Somehow we have to create a reference file from other applications (which supports a-rate cutoff/gain) and then compare the result. However, what really matters here is they will sound different.

**Comment by jipodine** [comment]
I wanted to say that the biquad filter is good when its parameters are not varying too quickly. The edge-cases may still sound interesting, but may exhibit differences across realisations. In our case, the sample-rate is more an issue than the implementation form of the filter, specially for the k-rate parameters. (But, to a lesser extend, the form also influences the stability.)

I did a quick test with Max/MSP, and I uploaded some sounds here (it is only possible to attach *images* here, we should fill an issue to github)
http://recherche.ircam.fr/anasyn/lambert/web-audio-api/

 - `biq_f103_*` files: sinusoid at 440 Hz feeding a low-pass biquad filter, whose frequency is driven by a sinusoid at 103Hz, from 116 to 412 Hz (unit gain, quality is 5)
 - `biq_q41_*` files: white noise feeding a low-pass biquad filter, whose quality is driven by a sinusoid at 41 Hz, from 1 to 257 (*not the same unit as Web Audio Api*) (cut-off filter 145 Hz, unit gain)
 - `*_a_*` files: parameters driven every 2 samples (not possible for Max/MSP to update every sample)
 - `*_k_*` files: parameters driven every 128 samples
 - `*_48000*` files: sample rate is 48000 Hz
 - `*_44100*` files: sample rate is 44100 Hz

**Comment by rtoy** [comment]
Thank you so much for the examples!

I can't speak about whether these are musically desirable, but your samples
very clearly illustrate the difference and I see (er, hear) that having
a-rate parameters could be useful.

I think there would be a significant cost in implementing these when there
are a-rate parameters, but I am not opposed to having them.

On Tue, Apr 21, 2015 at 3:14 AM, Jean-Philippe Lambert <
notifications@github.com> wrote:

> I wanted to say that the biquad filter is good when its parameters are not
> varying too quickly. The edge-cases may still sound interesting, but may
> exhibit differences across realisations. In our case, the sample-rate is
> more an issue than the implementation form of the filter, specially for the
> k-rate parameters. (But, to a lesser extend, the form also influences the
> stability.)
>
> I did a quick test with Max/MSP, and I uploaded some sounds here (it is
> only possible to attach *images* here, we should fill an issue to github)
> http://recherche.ircam.fr/anasyn/lambert/web-audio-api/
>
>    - biq_f103_* files: sinusoid at 440 Hz feeding a low-pass biquad
>    filter, whose frequency is driven by a sinusoid at 103Hz, from 116 to 412
>    Hz (unit gain, quality is 5)
>    - biq_q41_* files: white noise feeding a low-pass biquad filter, whose
>    quality is driven by a sinusoid at 41 Hz, from 1 to 257 (*not the same
>    unit as Web Audio Api*) (cut-off filter 145 Hz, unit gain)
>    - *_a_* files: parameters driven every 2 samples (not possible for
>    Max/MSP to update every sample)
>    - *_k_* files: parameters driven every 128 samples
>    - *_48000* files: sample rate is 48000 Hz
>    - *_44100* files: sample rate is 44100 Hz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/509#issuecomment-94731355>
> .
>



-- 
Ray

**Comment by luketeaford** [comment]
Yes -- thank you for putting this together!

For my taste, the a-rate parameters definitely sound more musical (and are therefore more useful).

**Comment by hoch** [comment]
Musical tastes are always subjective. In this point, I think we should talk about the tradeoff between two things:
A. Usefulness/practicality of this feature
B. Performance concern

Although I could hear some wobbling because of the capped modulation speed due to the k-rate constraints, I am not still convinced that the advantage of this overwhelming.

The most common use case of the biquad will be creating a parameter equalizer by cascading 4~6 of them, but making it support a-rate automation will be fairly expensive in terms of the computational load (calculating coefficients every sample) and the memory footprint (normally you'll have to pass a 128 sample array for each a-rate parameter). For example, let's say you have 20 individual sources with all 6 bands parameter EQ for them. That is a very common use case for multi-track production.

I am not strongly against this idea, but wanted to argue the efficiency of k-rate model.

**Comment by luketeaford** [comment]
Would it be possible to specify on the bi quad filter whether it takes a
rate or k rate? It could even default to k rate-- but making a rate
available would be great for my purposes!

On Thursday, April 23, 2015, Hongchan Choi <notifications@github.com> wrote:

> Musical tastes are always subjective. In this point, I think we should
> talk about the tradeoff between two things:
> A. Usefulness/practicality of this feature
> B. Performance concern
>
> Although I could hear some wobbling because of the capped modulation speed
> due to the k-rate constraints, I am not still convinced that the advantage
> of this overwhelming.
>
> The most common use case of the biquad will be creating a parameter
> equalizer by cascading 4~6 of them, but making it support a-rate automation
> will be fairly expensive in terms of the computational load (calculating
> coefficients every sample) and the memory footprint (normally you'll have
> to pass a 128 sample array for each a-rate parameter). For example, let's
> say you have 20 individual sources with all 6 bands parameter EQ for them.
> That is a very common use case for multi-track production.
>
> I am not strongly against this idea, but wanted to argue the efficiency of
> k-rate model.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/509#issuecomment-95670370>
> .
>


-- 
http://luketeaford.com

**Comment by hoch** [comment]
Maybe this is a bit related the issue #323.

@luketeaford I guess WG rather wants to have a different filter node for the finer control. (i.e. setting coefficients directly) It might be possible to put the sample-accurate parameter control on top of that.

**Comment by rtoy** [comment]
On Thu, Apr 23, 2015 at 11:05 AM, Hongchan Choi <notifications@github.com>
wrote:

> Maybe this is a bit related the issue #323
> <https://github.com/WebAudio/web-audio-api/issues/323>.
>
> @luketeaford <https://github.com/luketeaford> I guess WG rather wants to
> have a different filter node for the finer control. (i.e. setting
> coefficients directly) It might be possible to put the sample-accurate
> parameter control on top of that.
>

While you could do that, I don't think that helps very much. Say you wanted
to modulate the cutoff frequency quickly.  Setting up the appropriate
automation curves for the coefficients would be tedious.

If we do this, perhaps we should provide functions to map the biquad
parameters (cutoff, gain, Q) to coefficients so that the user would at
least have coefficients consistent with what the biquad filters do.  Or
maybe that should be a library that someone develops.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/509#issuecomment-95673170>
> .
>



-- 
Ray

**Comment by jipodine** [comment]
Of course, it would be nice to provide an a-rate converter from (cutoff, gain, Q) to coefficients. But my concern is the same for the new (general-purpose) biquad, that needs to be efficient also (specially when squashing several filters into one biquad, like double shelving).

I also think that the cost of the a-rate parameters is a lot comparing to the use-cases. But they still exist. So having k-rate parameters by default, with the option to chose a-rate (at instantiation) seems interesting. By the way, this is something that is needed for the AudioWorkers also, isn't it? (Or is it just up to the script to read only the first sample of each block, to get k-rate parameters?)

**Comment by joeberkovitz** [comment]
Resolution: changing biquad params to a-rate.  (AudioWorker doesn't have this problem: accepts full buffers of param values)

**Comment by billhofmann** [comment]
I'll note that the language at the top of the BiquadFilterNode indicates that they are a-rate, though the parameter description says k-rate.

**Comment by billhofmann** [comment]
fixed 790c604

**Comment by g200kg** [comment]
fully a-rate filter params changing might be cpu hogging especially for mobile devices. I think it had better specify about decimation depending on performance.

**Comment by rtoy** [comment]
I don't think a-rate biquads are any worse than, say, a convolver node with a long reverb for cpu usage. 

Specifying decimation vs performance would be hard, and making it interoperable between browsers and devices even harder.

**Comment by g200kg** [comment]
Indeed a convolver will need more CPU but the filter may be used more frequently than convolver. For example, simple Graphic Equalizer App will needs many filter nodes. How about mentioning about approaches on lower-end hardware? For example "2.26 OscillatorNode Interface" describes that related to anti-aliasing, 'It is expected that an implementation will take some care in achieving this ideal, but it is reasonable to consider lower-quality, less-costly approaches on lower-end hardware.'.

**Comment by rtoy** [comment]
I don't think it makes sense to say biquads are a-rate but then allow implementations not to implement them as real a-rate nodes.  

But your comment about OscillatorNodes is interesting.  Now that OscillatorNodes are defined in terms of PeriodicWave, about the only flexibility allowed is how many coefficients are used (internally) in defining the oscillator waveform.  Not sure if we need to specify that or not because if we don't then implementations will produce different results.
