### ISSUE TITLE
source AudioNodes need a `start` event and something like a `isPlaying` state

### ISSUE THREAD

**Issue by Prinzhorn** [WebAudio/web-audio-api#513]
We have an `ended` event, why not have a `started` event? You may ask why that's needed, since calling `start(0)` will start immediately. **But that's not true on mobile**. For example in Safari calling `start(0)` is a NOOP, unless it happens inside a user interaction event such as `touchstart` or `click`. I assume Safari does not behave according to the spec here, but having a `started` event or a `isPlaying` property would help a lot. It's currently impossible to detect if the audio actually started playing. I can call `start(0)` automatically and then a second time inside a click handler and it will _then_ start to play.

**Comment by cwilso** [comment]
Safari does have a requirement for user interaction, it's true; I think that's a mistake, but in any case, that should be addressed by their UA exposing whether audiocontexts are alive or not.

The mobile-Safari-requires-user-interaction issue aside, I'm not convinced there's a strong need for this; you can calculate whether the source has started by doing the time math.

**Comment by Prinzhorn** [comment]
> you can calculate whether the source has started by doing the time math.

Can you? How can I calculate if a looping AudioBufferSourceNode is playing?

**Comment by jernoble** [comment]
@Prinzhorn In a (hypothetical) spec-compliant version of Mobile Safari, you should be able to use the AudioContext's onstatechange notification to see when the context transitioned to "running".  After all, it's the AudioContext which requires user interaction to start, not individual AudioNodes.

**Comment by joeberkovitz** [comment]
@jernoble answer makes sense; no need to amend the specification.
