### ISSUE TITLE
Execution order of ScriptProcessorNodes

### ISSUE THREAD

**Issue by echo66** [WebAudio/web-audio-api#516]
Greetings!

Is there any way to fix the execution order of ScriptProcessorNodes at the same "depth" in a audio graph?

Consider the following code:
```javascript
var c = new AudioContext();

var sp1 = c.createScriptProcessor(256, 1, 1);
var sp2 = c.createScriptProcessor(256, 1, 1);
var sp3 = c.createScriptProcessor(256, 1, 1);

sp1.onaudioprocess = function () {
    console.log("sp1");
};
sp2.onaudioprocess = function () {
    console.log("sp2");
};
sp3.onaudioprocess = function () {
    console.log("sp3");
};

sp1.connect(c.destination);
sp2.connect(c.destination);
sp3.connect(c.destination);
```

Sometimes, the execution order makes the browser print:
sp3
sp1
sp2

Other times:
sp2
sp1
sp3

**Comment by notthetup** [comment]
More specifically than "depth", I think it's an interesting premise to look at the order of connection to the destination.

**Comment by cwilso** [comment]
Can you explain why you think this should be done?

**Comment by echo66** [comment]
I will give you one use case: I implemented a phase vocoder and due to the STFT implementation, when dealing with more than two players/ScriptProcessorNodes, I experienced issues with audio dropouts in one (or more) nodes. To deal with this, I have two (AFAIK) options: 

(a) Increase the buffer size. This decreases the interactivity of the phase vocoder and the problem still persists, if I add more players/ScriptProcessorNodes to the graph.

(b) If I know the execution order of the ScriptProcessorNodes, I can create a strategy to deal with this. For example, assign the players with a "louder" signal to ScriptProcessorNodes less likely to suffer from dropouts. By the way, I say "less likely" because I noticed that first nodes being evaluted don't seem to suffer those dropouts.

**Comment by cwilso** [comment]
I think this will be largely eradicated by the move to AudioWorkers; you'll
either run out of processing time or you won't.  Specifying the order of
scriptprocessor calls is a non-starter, since scriptprocessors are
deprecated anyway; but even in AudioWorkers, specifying that order would be
destructive to audio implementations optimizations.  I would not support
doing this without a stronger use case.

**Comment by echo66** [comment]
I understand your stance, @cwilso . Thanks for your time.
