### ISSUE TITLE
Spec is broken

### ISSUE THREAD

**Issue by silviapfeiffer** [WebAudio/web-audio-api#529]
The spec at http://webaudio.github.io/web-audio-api/ is missing a whole bunch of interface definitions that were there until recently. I believe it has to do with possible recent update of ReSpec. There are now 180 warnings and 5 errors of ReSpec listed at the top right of the spec.

**Comment by notthetup** [comment]
:+1:

**Comment by padenot** [comment]
Should be better now, thanks for the heads up.

**Comment by silviapfeiffer** [comment]
Nice! Thanks!
