### ISSUE TITLE
Impedance mismatch between the Web Worker text and what is possible/needed for the AudioWorker

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#532]
Looking at implementing the AudioWorker related interfaces in Gecko, it has come to our attention that there are a number of fundamental problems in the current text and model.

Quoting the current Web Worker text, available at https://html.spec.whatwg.org/multipage/workers.html:

In 10.1.1 Scope
> "Workers (as these background scripts are called herein) are relatively
> heavy-weight, and are not intended to be used in large numbers. For example, it
> would be inappropriate to launch one worker for each pixel of a four megapixel
> image. The examples below show some appropriate uses of workers."
> "Generally, workers are expected to be long-lived, have a high start-up
> performance cost, and a high per-instance memory cost.""

`AudioWorker`s are not intended to be heavyweight, and it should be possible to create a
large number of them. They can be short or long lived, and should be fast and
efficient to create, once the script is parsed/compiled etc, but this is a one
time cost, and it needs to be asynchronous.

In 10.2.4 Processing model
Step 1:
> "Create a separate parallel execution environment (i.e. a separate thread or
> process or equivalent construct), and run the rest of these steps in that
> context.""

This is not what we need, the script needs to run synchronously with the rest of the nodes,
on the audio thread, per spec and to avoid adding latency.

This points out a fundamental issue in the current model. If we are speccing a Web Worker, it as to work as per `10.2.4`, otherwise, it's something else.

Step 4:
> "Attempt to fetch the resource identified by url, from the origin specified by
> settings object, using parent referrer source as the referrer source (not using
> the referrer source specified by settings object!), and with the blocking flag
> set and the force same-origin flag set."

Following up, this is not possible to implement correctly. There is no way we can do network IO on the audio thread, and the HTML spec mandates this has to be done on the "worker thread".

For example, what about a script that does, when the audio processing event is received, a `importScripts()`: this stops the script in order to do some network operation. The `importScripts`, is, from the script point of view, sync. But that would add a lot of latency, and would cause the audio to underrun, and possibly the system audio back-end to stop the audio stream.

Step 5:
> Let script be a new script.
> Obtain the appropriate script execution environment for the scripting language
> language from settings object.
> Parse/compile/initialise source using that script execution environment, as
> appropriate for language, and thus obtain a code entry-point. If the script was
> not compiled successfully, let the code entry-point be a no-op script, and act
> as if a corresponding uncaught script error had occurred.
> Let script's settings object be settings object.

Same, we can't run those steps in the audio thread, it's simply to expensive.

In short, we cannot rely on the existing infrastructure, like a traditional event loop: audio threads don't execute all the time, they are _called back_ by the system, and are supposed to return (somewhat) quickly. How does processing the event loop work in this context? Is it emptied at the beginning of each processing block? At the beginning of a system callback? At other times?

Another problem is the APIs available to `DedicatedWorkerGlobalScope`

See: https://html.spec.whatwg.org/multipage/workers.html#apis-available-to-workers, notably:

> WorkerGlobalScope implements WindowTimers;
> WorkerGlobalScope implements WindowBase64;

What does `setInterval` or `setTimeout` mean in the context of an audio thread
that has an execution model based on callbacks? Is the API working using the
audio clock, or the normal clock ? It's terribly useless to have those function
anyways, because by essence, in an `AudioWorker`, you get a clock, and you're
called repeatedly, so you're better off doing your own scheduling.

What about `XHR`, `Promise`, `Fetch`? It does not seems desirable to have those available from inside the `AudioWorker` code, but they are `[Exposed=(Window,Worker)]`. The Web Worker specification allow author to create Web Workers from a worker. This is not very useful in this context, because `AudioWorker`s are all running on the same thread anyways for latency reasons.

It seems to be that we need to conceptually build this object on something else than the "Web Workers" concept. Whether we call it *Worker or not can be talked about later :-).

**Comment by cwilso** [comment]
You are quite correct.  My intent was never to actually rely on the Worker implementation.  ("An AudioWorker object is the main-thread representation of a worker 'thread' that supports processing of audio in Javascript. ... These main thread objects cause the instantiation of a Web Worker-like thread context (Described in [Workers]), which executes in the audio thread."  Note the "Worker-like".)  I believe the 

It's therefore a good idea 1) to remove the ": worker"; the bits we want from that interface are already described (postMessage and onmessage), and this would remove all the unnecessary bits like setTimeout, 2) Perhaps pull in a stripped version of Section 4.6 (the Processing Model http://www.w3.org/TR/workers/#processing-model) from Workers, and 3) we can consider renaming it, though I prefer AudioWorker.  AudioThreadProcessor?

**Comment by joeberkovitz** [comment]
Marking as requiring WG review since agreement on this issue is essential to AudioWorker implementation in V1.

**Comment by joeberkovitz** [comment]
I agree that separating this from WebWorkers makes sense given the strictures imposed by the existing WW spec. I think changing the name is important to avoid confusion, and like the name `AudioProcessor` (sort of by analogy with ScriptProcessor -- it also goes well with `AudioProcessingEvent`).

**Comment by duanyao** [comment]
May I ask a question? What is the "audio thread" exactly in the spec? As far as I understand:

1. at most one audio thread for one instance of AudioContext. If so, do multiple AudioContexts have their own audio threads?
2. (almost) all audio processing of an AudioContext happens in this thread.
3. all Audio Workers of an AudioContext run in the same audio thread.

If 3 is mandatory, maybe there are some implementation problems for some UAs. For example, Firefox seems not being able to run multiple Web Workers *concurrently* on one OS thread:

http://stackoverflow.com/questions/9339892/does-a-firefox-workers-limit-exist

>There is no error message because if you create more workers than the limit they just get queued up to to run. The limit is on concurrently running workers, not total workers. If you were setting up workers that actually terminated at some point, you'd see the queued-up ones start running. But you're trying to set up 200 workers all with infinite lifetime... –  Boris Zbarsky 

If actually implemented Audio Workers will not have this limitation, I can image developers would (mis)use Audio Workers for non-audio tasks to workaround the number limit of normal Workers.

**Comment by hoch** [comment]
> 1. at most one audio thread for one instance of AudioContext. If so, do multiple AudioContexts have their own audio threads?

Yes.

> 2. (almost) all audio processing of an AudioContext happens in this thread.

Generally yes. However, it depends on the implementation. Convolution (convovler or HRTF) does require extra threads. Also the script state in ScriptProcessor runs on the main JS thread - and that's why we're deprecating it.

> 3. all Audio Workers of an AudioContext run in the same audio thread.

Ideally, yes. Also this is why @padenot raises the issue because the Worker is designed to create a new thread when instantiated and communicates with the originating thread by posting messages (events). So AudioWorker and WebWorker are quite different and we definitely do not want the thread-hop like this for AudioWorker.

> If actually implemented Audio Workers will not have this limitation, I can image developers would (mis)use Audio Workers for non-audio tasks to workaround the number limit of normal Workers.

Also developers have to be mindful that the `onaudioprocess` is called every 3ms or less depending on the sample rate. Not sure how we can prevent this from happening since [you can define the `onmessage` event in the main thread](http://webaudio.github.io/web-audio-api/#todo-fix-up-this-example.-a-volume-meter-and-clip-detector).

**Comment by hoch** [comment]
@joeberkovitz How about `CustomAudioProcessor`?

**Comment by duanyao** [comment]
Thanks for the detailed explanation, @hoch.

Actually I don't really care about protecting AudioWorker from being misused for non-audio tasks; instead, I think if we can make AudioWorker really lightweight, why shouldn't we make normal WebWorker lightweight too (at least optional)? There are definitely many valid use cases beyond audio processing. I hope web audio WG and web application WG can join the force to make a generalized "lightweight worker" if possible.

**Comment by notthetup** [comment]
I like `CustomAudioProcessor `. I always found myself explaining to new people coming into WebAudio that ScriptProcessor was where you could create your Custom AudioNode (kinda). So having that in the name would help!

**Comment by joeberkovitz** [comment]
TPAC 2015: Remove all remaining references to WebWorker from the spec as part of concluding the AudioWorker specification.
