### ISSUE TITLE
toDataURL / toBlob for AudioContext

### ISSUE THREAD

**Issue by epistemex** [WebAudio/web-audio-api#533]
My apologies if this has been requested previously.

I would like to request a toDataURL() and toBlob() for AudioContext as in the spirit of the canvas element (data extraction). Supported mime-types could be "audio/wav" and "audio/aiff", perhaps even "audio/mpeg" for mp3 although the latter could possibly trigger legal considerations?). Or some format that can be considered platform neutral and cross-platform supported (ogg, flac ...). I'm just throwing out some ideas, and as wav/aiff are widely used in production those would be natural IMO, but on the consumer side perhaps a lossy format and one that isn't tied up to a vendor (MS/Apple) would probably be more considerate. Or all.. (yes, thank you Mam!).

This would make it easy to use a modified audio buffer as source for a regular Audio element which then would provide controls with ease, but more important perhaps, allow modified audio to be saved in a re-distributable format (f.ex from online sample editors, audio normalization, EQ apps etc etc) without the need to manually wrap the data up in a file container.

**Comment by notthetup** [comment]
Ahh! So basically a way to encode an AudioBuffer into a wav/aiff file. I think there are some decent libraries for that, but it is true that having it in the platform would make it more performant.

**Comment by padenot** [comment]
You want [MediaRecorder](http://w3c.github.io/mediacapture-record/MediaRecorder.html). It's available in Firefox, and will be available in other browsers.

Note that we will be adding OfflineAudioContext capabilities to the MediaRecorder.

This [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) explains how to use it.

**Comment by epistemex** [comment]
Hm, I knew about MediaRecorder but I (wrongly) assumed it only recorded streams. This is great news Thanks guys!
