### ISSUE TITLE
PeriodicWave with arrays of length < 2 is useless

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#544]
As currently spec'ed, you can supply a periodic wave with arrays of length 1 or less.  But the first element of each array is ignored, so you basically create an oscillator whose output is zero.  Is this useful?  Or should we throw an error if the arrays have length < 2?

**Comment by karlt** [comment]
rtoy writes:

> As currently spec'ed, you can supply a periodic wave with arrays of length 1
> or less.  But the first element of each array is ignored, so you basically
> create an oscillator whose output is zero.  Is this useful?  Or should we
> throw an error if the arrays have length < 2?

A DC signal would be useful for some situations.
AudioParams are probably the most common candidates.

Perhaps there's a better way to generate a DC offset, but then the
same argument would claim that length 2 is useless because a sine
oscillator could be used instead.

I think it is better to avoid arbitrary unnecessary limits on
parameters.

**Comment by rtoy** [comment]
I'm not opposed to allowing a DC offset, but we'll have to think about what normalization means when there's a DC offset. Normalization would make the DC offset not the value that you specified.

An oscillator seems like a pretty heavy-weight way to make constant.  A 1-sample looping AudioBufferSource would seem more appropriate.  @cwilso has suggested a ConstantNode would be a nice thing to have.

**Comment by karlt** [comment]
rtoy writes:

> I'm not opposed to allowing a DC offset, but we'll have to think about what
> normalization means when there's a DC offset. Normalization would make the DC
> offset not the value that you specified.

Yes, that's a problem will all/any of the coefficients.
I'm not a fan of normalization, but that is https://github.com/WebAudio/web-audio-api/issues/91

With the specified normalization, arrays of length 1 will produce
either 1 or -1, or who knows what if the coefficient is zero.
That's consistent at least.

**Comment by joeberkovitz** [comment]
Resolve: closing since no need to restrict coefficient array length (which could be algorithmically generated).
