### ISSUE TITLE
SetValueCurveAtTime interpolation not specified

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#547]
The description in http://webaudio.github.io/web-audio-api/#widl-AudioParam-setValueCurveAtTime-void-Float32Array-values-double-startTime-double-duration shows how to calculate the value from the values array using an index of N * (t - startTime) / duration into the values array.  This index is very likely not an integer, so it's not clear how to select the actual index.

In chrome, the index is basically floor(0.5 + N * (t - startTime) / duration).

**Comment by joeberkovitz** [comment]
Convert to sample frame boundary (using Ray's suggested formula) and clarify this in spec. Apply similar clarification to description of AudioBuffer's loopStart/loopEnd which already discuss converting to exact sample frame boundaries.
