### ISSUE TITLE
AudioBufferSourceNode.playbackRate should be specified as k-rate and not a-rate

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#55]
> Originally reported on W3C Bugzilla [ISSUE-21592](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21592) Fri, 05 Apr 2013 15:26:40 GMT
> Reported by paul@paul.cx
> Assigned to 

Quote from the spec:

> playbackRate
>
>    The speed at which to render the audio stream. The default 
> playbackRate.value is 1. This parameter is a-rate

WebKit implements this property as being k-rate, and I believe this is in fact just a typo in the spec.

**Comment by billhofmann** [comment]
What is the decision here?  Does it require further discussion?

**Comment by joeberkovitz** [comment]
I don't know, but it looks like k-rate is what everyone has implemented. I am finding that k-rate is sufficient for most frequency modulation in Noteflight. I think we should go with k-rate and leave fancier per-sample modulation to the realm of custom synthesis.

**Comment by padenot** [comment]
Yes, I think we can just close this. `k-rate` has been how it's done for ages now.
