### ISSUE TITLE
BiquadFilterNode getFrequencyResponse on positive gains

### ISSUE THREAD

**Issue by andremichelle** [WebAudio/web-audio-api#563]
I was expecting to see a mirrored frequency response when changing the sign of the gain. For negative gains the response makes sense, but for positive gains it looks broken (mag-values are slightly above 1.0).

Tested on HighShelf, LowShelf and Peaking.

![Filter Response Test](http://files.andre-michelle.com/biquad-lowshelf.png)

**Comment by andremichelle** [comment]
My bad. I misinterpreted the magnitude values as normalised values. In fact they are normalised db values.

**Comment by rtoy** [comment]
Why do you think the magnitude values are normalized dB?  The spec doesn't say so; in fact, it says linear magnitude.

Could you also explain what your graphs are trying to show?

**Comment by rtoy** [comment]
Why do you think the magnitude values are normalized dB?  The spec doesn't say so; in fact, it says linear magnitude.

Could you also explain what your graphs are trying to show?
