### ISSUE TITLE
Event Constructors

### ISSUE THREAD

**Issue by SteveBeckerMSFT** [WebAudio/web-audio-api#566]
Should Web Audio event interfaces include constructors?  This includes:
- OfflineAudioCompletionEvent
- AudioProcessingEvent
- AudioWorkerNodeCreationEvent
- AudioProcessEvent

This would enable JavaScript to construct and dispatch WebAudio events:

``` javascript
var eventObject = new AudioProcessingEvent(
    "audioprocess", 
    {  playbackTime: 1.25, inputBuffer: data  }
    );
eventListener.dispatchEvent(eventObject);
```

**Comment by hoch** [comment]
From my opinion, any of these events should not be allowed to be constructed by user.

- OfflineAudioCompletionEvent: This should be dispatched only when the OAC finished the rendering task.
- AudioProcessingEvent: ScriptProcessorNode is already being deprecated.
- AudioWorker-related events: We can discuss about them after the draft spec is proposed, but I highly doubt that this can be constructed programmatically. Especially the `AudioProcessEvent` is driven by the pulling from the destination node.

**Comment by billhofmann** [comment]
What is the decision here?

**Comment by hoch** [comment]
I thought we talked about allowing the construction of these events. @cwilso mentioned that the web spec generally allows the construction of the object unless it is known to be harmful. However, I don't recall that we have a firm decision on this.

I think we need to revisit/evaluate any harmful case caused by the construction of these events.

**Comment by billhofmann** [comment]
This seems related to #250 - perhaps we should discuss in that context.  Seems like we're saying in general that constructors are ok.

**Comment by joeberkovitz** [comment]
We've decided that these constructors are OK since there's no visible harm they can cause.

**Comment by hoch** [comment]
These two events do not exist in the spec anymore.
- AudioWorkerNodeCreationEvent
- AudioProcessEvent

FWIW, the new AudioWorklet proposal does not introduce new special event. Other old events should be constructible.
