### ISSUE TITLE
Should copyToChannel affect AudioBuffers acquired by an AudioBufferSourceNode/ConvolverNode?

### ISSUE THREAD

**Issue by SteveBeckerMSFT** [WebAudio/web-audio-api#567]
Should copyToChannel affect AudioBuffers that have already been acquired by AudioNodes and used for audio processing?  Here's an example:

```javascript
var bufferSource = context.createBufferSource();
bufferSource.buffer = myAudioBuffer;

// After start(), the buffer source node "acquires the contents of the AudioBuffer"
bufferSource.start(); 

// Should the channel data write impact playback of the bufferSource node above?
myAudioBuffer.copyToChannel(myChannelData, /*channelIndex*/ 0);  
```
For this example, in FireFox, copyToChannel does not affect playback of the already started AudioBufferSourceNode node.  Instead, it creates a new copy of the AudioBuffer for JavaScript and modifies it.  I believe this is consistent with getChannelData().  Should we add this behavior to the spec?  I plan to implement the same behavior as FireFox in Edge.

**Comment by padenot** [comment]
Yes, that's the idea. Once it's started, you cannot change what an `AudioBufferSourceNode` is playing.

We should make it clear in the spec, yes.

**Comment by joeberkovitz** [comment]
Just as a random data point, I was in touch with a developer who had the impression from the spec that `copyToChannel` would alter the playback of a live `AudioBufferSourceNode` so this problem is pretty real and tangible.

**Comment by gerrybeauregard** [comment]
That developer was me!  I had another look at the 22 July draft spec, and I still don't see anything suggesting that copyToChannel would not affect an already-playing buffer.

**Comment by rtoy** [comment]
AFAIK, you don't see it because no one has written it yet.

On Tue, Aug 4, 2015 at 6:03 PM, gerrybeauregard <notifications@github.com>
wrote:

> That developer was me! I had another look at the 22 July draft spec, and I
> still don't see anything suggesting that copyToChannel would not affect an
> already-playing buffer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/567#issuecomment-127809159>
> .
>



-- 
Ray

**Comment by gerrybeauregard** [comment]
Thanks rtoy, that would explain it :-)

Related: I found that I was able to directly modify the channel audio data (as obtained by AudioBuffer.getChannelData()) of a looping AudioBuffer. I was using this feature to create a continuous audio output for synthesis.  Seems to work fine in Chrome and Safari, on MacOS, iOS, and Android. 

But Joe tells me this approach "might not continue working in the long run. The channel data of an AudioBuffer that is actively in use is not supposed to be directly mutable from the main thread".

**Comment by karlt** [comment]
The intent of the section including the following text is that the "immutable channel" data acquired by the implementation is not modified when the "ArrayBuffers containing copies of the data" attached to the AudioBuffer are modified:

"An internal operation acquire the contents of an AudioBuffer is invoked when the contents of an AudioBuffer are needed by some API implementation. This operation returns immutable channel data to the invoker."

copyToChannel() is intended to work with the same ArrayBuffers as getChannelData().

**Comment by joeberkovitz** [comment]
@gerrybeauregard Just to summarize, there's definite concensus that the spec is not at all clear and needs to be fixed. The "buffer acquisition" policy that @karlt mention is not worked around in any way by copyToChannel(), although it's easy to make the mistake of thinking that the reason copyToChannel() exists is to somehow mitigate that policy.
