### ISSUE TITLE
Make the usage of content sniffing for decodeAudioData explicit

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#57]
> Originally reported on W3C Bugzilla [ISSUE-21702](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21702) Mon, 15 Apr 2013 21:46:34 GMT
> Reported by Ehsan Akhgari [:ehsan]
> Assigned to 

We should probably explicitly say in the spec that the buffer passed to decodeAudioData should be sniffed to get the content type, according to the http://mimesniff.spec.whatwg.org/ spec, and that the implementation must reject buffers that do not pass that content sniffing.

This will help in situations like https://bugzilla.mozilla.org/show_bug.cgi?id=861187, where one implementation (Gecko) cannot sniff the content type properly but another (WebKit) can.

**Comment by billhofmann** [comment]
Can we link to https://mimesniff.spec.whatwg.org/?  Presumably we need a versioned snapshot - not sure how to do that besides linking to the github (https://github.com/whatwg/mimesniff/tree/ced82b8e18b153ca06ad9ebc44daa3c80af1c5c4).

**Comment by padenot** [comment]
I'll note that two rather important patches for our use cases are pending against this spec:

- sniffing MP3 not in an ID3 container
- sniffing WebM properly

I've written patches for both, but the spec authors were not answering, last I checked, maybe I should poke them again.
