### ISSUE TITLE
getByteTimeDomainData and getByteFrequencyData are underspecified

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#571]
It's not really clear what `getByteTimeDomainData` does with the floating-point data.  How is the uint8 value derived from the time-domain floating-point data?  Is there some scaling going on? It it just clipping the float?

Same goes for `getByteFrequencyData`, except there are some hints because the `minDecibels` and `maxDecibels` attributes exist.  Perhaps that's enough of a hint.

In either case, I think the parameter description should at least mention something about some kind of scaling is happening, and leave the full description elsewhere.  It's easy to miss the details.

**Comment by notthetup** [comment]
Yes. This is something many users have wondered, what actual processing is going on.
