### ISSUE TITLE
Interaction of automation methods is unclear

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#573]
The [spec entry for automation methods](https://webaudio.github.io/web-audio-api/#the-audioparam-interface) says:

> The following rules will apply when calling these methods:
>
>  * If one of these events is added at a time where there is already an event of the exact same type, then the new event will replace the old one.
>  * If one of these events is added at a time where there is already one or more events of a different type, then it will be placed in the list after them, but before events whose times are after the event. 

It's not really clear, but "time" above probably refers to the `time` parameter in each of the methods.

One odd behaviour in Chrome is that if you do the following (where `g` is a gain node)
```
var g = context.createGain();
g.gain.linearRampToValueAtTime(0, context.currentTime + 1);
```
Chrome doesn't actually do anything.  You need to add a `setValueAtTime(1,0)` to establish a previous event for the linear ramp to use.

It's not clear what happens if a different event type is added at the same time as an existing event.  Should this be allowed?  What does it really mean to have different events at the same time?

In Chrome, you can do this:
```
g.gain.setValueAtTime(1,0);
g.gain.linearRampToValueAtTime(0, 1);
g.gain.exponentialRampToValueAtTime(100, 1);
```
What appears to happen is that you get a linear ramp from time 0 to time 1. Then you get an instantaneous jump to 100.  If you reversed the order of the calls, you get something different: an exponential ramp up to 100 and then an jump to 0 at time 1. I find this odd.

Also, what happens if you do something like:
```
g.gain.setValueAtTime(1,context.currentTime);
g.gain.linearRampToValue(0, 1000 + context.currentTime);
// Start the sources, etc., connecting to this gain.
// Wait 10 sec
g.gain.exponentialRampToValue(10, 100 + context.currentTime);
```
What does the gain curve look like now?  Does the linear ramp continue towards 0, and then at time 100+currentTime, an exponential ramp starts?  Something else?

What should the following do?
```
g.gain.setValueAtTime(1, 1+ context.currentTime);
g.gain.linearRampToValueAtTime(0, 1000 + context.currentTime);
// Wait 100 sec
g.gain.setValueAtTime(100, -10 + context.currentTime)
```

I don't have any real suggestions on how to resolve these.  We could say that the these corner cases are undefined and leave it to the implementation.  But we should be clear on what happens for the most common cases.

**Comment by rtoy** [comment]
Perhaps #130 covers all of this.

**Comment by padenot** [comment]
> What does the gain curve look like now? Does the linear ramp continue towards 0, and then at 
> time 100+currentTime, an exponential ramp starts?

Yes, that would be my expectation.

> I don't have any real suggestions on how to resolve these. We could say that the these corner 
> cases are undefined and leave it to the implementation. But we should be clear on what happens 
> for the most common cases.

It's easy enough to spec this properly by stating an algorithm. What is harder is to agree on how to resolve those edge-cases and to make sure we're covering everythin.

**Comment by karlt** [comment]
On Fri, 14 Aug 2015 09:52:27 -0700, rtoy wrote:

> g.gain.setValueAtTime(1,context.currentTime);
> g.gain.linearRampToValue(0, 1000 + context.currentTime);
> // Start the sources, etc., connecting to this gain.
> // Wait 10 sec
> g.gain.exponentialRampToValue(10, 100 + context.currentTime);
> ```
> What does the gain curve look like now?  Does the linear ramp continue towards
> 0, and then at time 100+currentTime, an exponential ramp starts?  Something
> else?

The two options that had occurred to me were:

1. After the exponentialRampToValueAtTime() call, the timeline
   values are calculated as if the event had always been in the
   timeline.  All values calculated for previous times are forgotten.

   The exponential ramp would begin with value 1 at the time of
   the setValueAtTime event, and the linear ramp would begin
   with value 10 from the time of the exponentialRampToValueAtTime
   event.

   This would be simple.

2. After the exponentialRampToValueAtTime() call, the exponential
   ramp would begin with the current value (from the
   linearRampToValue curve previously in effect before the
   exponentialRampToValueAtTime() call).

   This would avoid the discontinuity on the call to
   exponentialRampToValueAtTime() and so I think would be more
   useful to clients.  It is the continuous change effect that I
   first expected from the name of the method.

I can't imagine a system where the exponentialRampToValueAtTime()
curve would begin at its end time, so please explain if you still
think that should happen.

**Comment by karlt** [comment]
If considering setTargetAtTime() and using that in an attempt to
make continuous smooth transitions, then currentTime may be passed
as the start time, but the intention is that the curve begins from
the intrinsic value at the time when the audio thread processes
the event, a time which may be later than currentTime.

Generating the curve as if it started from currentTime (as with
option 1) would produce a discontinuity because the event did not
exist when the block for currentTime was processed.

Option 2 (with the curve beginning from the value when the event
is received) is the solution that provides the desired behavior,
and similar arguments can be made for other methods/events.

**Comment by rtoy** [comment]
I think your Option 2 makes the most sense because it's continuous.

But here's a funny thing.  The linear ramp is supposed to end at time 1000+currentTime and the exponential ends at time 100 + currentTime.  What happens between these two times?  I can see at least two options:  

1. The linear ramp is effectively removed so the value is held at the value at the end of the exponential ramp.
1. The linear ramp pick again from the end of the exponential and ramps down to 0 at time 1000 + currentTime.

**Comment by karlt** [comment]
rtoy writes:

> But here's a funny thing. The linear ramp is supposed to end at time
> 1000+currentTime and the exponential ends at time 100 + currentTime. What
> happens between these two times? I can see at least two options:
>
>  1. The linear ramp is effectively removed so the value is held at the value
>     at the end of the exponential ramp.
>  2. The linear ramp pick again from the end of the exponential and ramps down
>     to 0 at time 1000 + currentTime.

My expectation was 2 because the linear ramp's event time has not
yet been reached.

Yes, it is a funny scenario, but I think it is most consistent
with being able to insert events before another event already in
the event list.  At least the value at 1000+currentTime
specified by the event at that time is unchanged by the event at
10 + 100+currentTime.

If we were to select 1, then I guess we'd need to rethink event
times as always the start of the transition, which would be
counter-intuitive due to this method indicating the end time.

Perhaps scheduling any event could be specified to cancel all
subsequent events, but that would be quite a change to the intent
of the spec.  I haven't thought through the consequences but I'm
not aware of a need to make that change.

**Comment by joeberkovitz** [comment]
TPAC: rewrite the "override" rules as follows:

DELETE THIS CLAUSE: If one of these events is added at a time where there is already an event of the exact same type, then the new event will replace the old one.

MODIFY THIS CLAUSE by removing the "of a different type" qualifier: If one of these events is added at a time where there is already one or more events, then it will be placed in the list after them, but before events whose times are after the event.

As a general clarifying point, state that automation event scheduling times are not quantized with respect to any sample rate. Formulas for ramps, etc. make use of the exact numerical times supplied (although the a-rate curves that are generated from these formulas to govern nodes' behavior are obviously quantized and interpolated).

**Comment by mrkishi** [comment]
I think this scenario also needs clarification:

```
param.setTargetAtTime(440, time, tc);
param.linearRampToValueAtTime(880, time + 5);

param.setTargetAtTime(440, time, tc);
param.exponentialRampToValueAtTime(880, time + 5);
```

It seems the `setTargetAtTime` calls, when followed by ramps, are equivalent to `setValueAtTime` – at least on Chrome.

**Comment by rtoy** [comment]
@mrkishi : I think this is already spec'ed.  The previous event for the ramp is the event setTargetAtTime.  The ramps start from the time of setTargetAtTime.  Effectively, the setTarget has been removed.
