### ISSUE TITLE
Inconsistent description of audio node .value

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#582]
[Section 2.5.1](http://webaudio.github.io/web-audio-api/#attributes-5) says

> If value is set during a time when there are any automation events scheduled then it will be ignored and no exception will be thrown.

But [Section 2.5.3](http://webaudio.github.io/web-audio-api/#computation-of-value), bullet 1 says

> If the value attribute is set after any automation events have been scheduled, then these events will be removed.

These seem inconsistent with each other.

**Comment by padenot** [comment]
This is changing soon anyways.

**Comment by rtoy** [comment]
Yeah.  I'm closing this now since it's changing soon.
