### ISSUE TITLE
"the Nyquist frequency" used before defining, used in several places

### ISSUE THREAD

**Issue by sole** [WebAudio/web-audio-api#587]
Reading [the docs](http://webaudio.github.io/web-audio-api/#attributes-25) for the BiquadFilterNode there is a mention that the `frequency` range is "from 10Hz to half the Nyquist frequency", without any link whatsoever to what would that Nyquist frequency be. Now this is supposed to be "common DSP knowledge", but since it's something as simple as saying "half the sampling rate", I don't see why this is not added as a footnote or something of the sort to the spec.

Later on the term is [actually defined](http://webaudio.github.io/web-audio-api/#the-oscillatornode-interface) with a "half the sample-rate" when discussing the OscillatorNode.

I'm unsure about the procedure here (do I send a PR? do I just raise the issue?) but I think the docs would get more usable by reworking this into a foot note or something of the sort.

**Comment by hughrawlinson** [comment]
As it already gets defined later on in the spec, it should definitely be put into a footnote and referenced at both places in the spec (or, more simply, just adding it in parentheses in useful places). :+1: from me!

**Comment by cwilso** [comment]
PRs are certainly welcome if you want to make one.

**Comment by rtoy** [comment]
Maybe a glossary section would be good.  If there are enough terms that
need to be defined.

On Tue, Sep 8, 2015 at 8:39 AM, Chris Wilson <notifications@github.com>
wrote:

> PRs are certainly welcome if you want to make one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/587#issuecomment-138603489>
> .
>



-- 
Ray

**Comment by billhofmann** [comment]
+1, for web developers who are not DSP folks.

**Comment by rtoy** [comment]
Don't mind adding a glossary, but I think the spec should be written for
experienced people.

Non-DSP folks or less experienced people would be better served by other
articles written for them.  The spec should be a spec, not a tutorial.

On Wed, Sep 9, 2015 at 12:57 PM, Bill Hofmann <notifications@github.com>
wrote:

> +1, for web developers who are not DSP folks.
>
> From: rtoy [mailto:notifications@github.com]
> Sent: Wednesday, September 09, 2015 12:54 PM
> To: WebAudio/web-audio-api
> Subject: Re: [web-audio-api] "the Nyquist frequency" used before defining,
> used in several places (#587)
>
> Maybe a glossary section would be good. If there are enough terms that
> need to be defined.
>
> On Tue, Sep 8, 2015 at 8:39 AM, Chris Wilson <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > PRs are certainly welcome if you want to make one.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WebAudio/web-audio-api/issues/587#issuecomment-138603489>
>
> > .
> >
>
>
>
> --
> Ray
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WebAudio_web-2Daudio-2Dapi_issues_587-23issuecomment-2D139027506&d=AwMFaQ&c=lI8Zb6TzM3d1tX4iEu7bpg&r=qzKCNHFKJMzZBJ52at1DkA-_8TPxvcij-zS_VXs8c5A&m=psmUzCYF8c8vGqmdwqwe13fMcda0gtx5W0NDICbNEyM&s=dSmjcQd7AsnFx91Wi09HBkH3UyKQOcqX2S9crjkoVw8&e=>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/587#issuecomment-139028428>
> .
>



-- 
Ray

**Comment by padenot** [comment]
I'm defining this in #391. Since I'm referring to the Nyquist frequency all over the place for some AudioParam ranges, I threw a <dfn> in there. I expect to finish #391 shortly.

**Comment by mdjp** [comment]
We already have #45 if we are to add a glossary it should be within the primer/developer doc generated from this issue.
Suggest this is closed as it will be addressed by both #391 and #45.
