### ISSUE TITLE
AudioNode.disconnect() needs to be able to disconnect only one connection

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#6]
> Originally reported on W3C Bugzilla [ISSUE-17793](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17793) Tue, 17 Jul 2012 18:30:24 GMT
> Reported by Chris Wilson
> Assigned to 

(Summary of email conversation in list)

There is currently no way to disconnect node A's connection to node B without disconnecting all connections from node A to other nodes.  This makes it impossible to disconnect node B from the graph without potential side effects, as you have to:

- call disconnect() on node A (which disconnects all its outputs)
- reconnect every connection that node A used to have, EXCEPT the connection to node B.

Not only is this cumbersome, it will be problematic in the future when we solve the related issue of unconnected streams - which is currently exhibiting incorrect behavior in Chrome (it pauses the audio stream), but is underspecified in the spec today.  (filing separate bug).  Disconnecting then reconnecting would have to have no side effects.  (It works okay today, but not ideal - can click.)

Recommended solution:
- there should be a way to remove a single connection (by supplying the destination node to be disconnected, since there can only be one connection to a given destination node [tested]).

E.g.: the IDL for disconnect should read:

        void disconnect(in [Optional] AudioNode destination, in [Optional] unsigned long output = 0)
            raises(DOMException);

this lets us keep most compatibility - node.disconnect() will still remove all connections.

**Comment by hoch** [comment]
From the teleconference and the discussion after, I would like to propose:

1) For invalid input/output indices, we should throw `IndexSizeError`.
2) For invalid destination `AudioNode` or `AudioParam`, we should throw `InvalidAccessError`.

http://www.w3.org/TR/dom/#domerror

@cwilso @padenot What do you think?

**Comment by cwilso** [comment]
LGTM.

**Comment by padenot** [comment]
Yep, LGTM as well.

**Comment by hoch** [comment]
- Preview: http://hoch.github.io/web-audio-api/#idl-def-AudioNode
- Pull request: https://github.com/WebAudio/web-audio-api/pull/479

**Comment by hoch** [comment]
The proposal above at https://github.com/WebAudio/web-audio-api/issues/6#issuecomment-60702415 was not really well-defined for all possible cases. Please refer the IDL in the pull-request #479 I created.

**Comment by sebpiq** [comment]
This is great to have this ...

A little concern though : is there any (sane) way to automatically detect that this is indeed implemented? Cause if you use it while not implemented, it's going to fail silently, and just disconnect all your connections (which you probably didn't expect).

**Comment by rtoy** [comment]
One possible way:  node1.disconnect(node2) where you know node1 wasn't
connected to node2.  This is required to throw an error now. I don't think
that happened before.  At least in Chrome 42 beta, no error is thrown. I
didn't try any other browser.


On Fri, Mar 20, 2015 at 2:00 AM, Sebastien Piquemal <
notifications@github.com> wrote:

> This is great to have this ...
>
> A little concern though : is there any (sane) way to automatically detect
> that this is indeed implemented? Cause if you use it while not implemented,
> it's going to fail silently, and just disconnect all your connections
> (which you probably didn't expect).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/6#issuecomment-83959402>
> .
>



-- 
Ray

**Comment by sebpiq** [comment]
Yeah but if an error is not raised, that would not really tell me that you can disconnect a single connection ... instead of doing that, I might as well test the browser versions!

The other hack I was thinking of is using an `OfflineAudioWorker`, but it sounds like going through a lot of trouble ...

**Comment by hoch** [comment]
@sebpiq Yes. I should have thought about that. I agree that we don't have a 'sane' way of sniffing this. For the time being, the browser version check is the most concise solution.

Here's the snippet based on @rtoy's idea:
~~~
function hasSelectiveDisconnect() {
  var c = new OfflineAudioContext(1,1,44100);
  try {
    c.createGain().disconnect(c.destination);
    return false;
  } catch (error) { 
    return true;  
  }
}

console.log(hasSelectiveDisconnect());
~~~
For this case, `OfflineAudioContext` is slightly better than the real-time one, because the browser might have a limitation on the number of real-time contexts can be running or constructed.

**Comment by sebpiq** [comment]
Yeah ... I was doing something more verbose like so : 

```javascript

var _hasSelectiveDisconnect = function() {
  var context = new OfflineAudioContext(1, 10, 44100)
    , bufferNode = context.createBufferSource(), gain = context.createGain()
    , buffer = context.createBuffer(1, 1, 44100)
  buffer.getChannelData(0)[0] = 1
  bufferNode.buffer = buffer
  bufferNode.connect(gain)
  bufferNode.connect(context.destination)
  bufferNode.start(0)
  gain.connect(context.destination)
  bufferNode.disconnect(gain)
  context.oncomplete = function(event) {
    _hasSelectiveDisconnectResult = (!!event.renderedBuffer.getChannelData(0)[0])
  }
  context.startRendering()
}, _hasSelectiveDisconnectResult = null
_hasSelectiveDisconnect()
```

**Comment by cwilso** [comment]
Fixed.
