### ISSUE TITLE
BiquadFilterNode.getFrequencyResponse is under-specified

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#60]
> Originally reported on W3C Bugzilla [ISSUE-21857](https://www.w3.org/Bugs/Public/show_bug.cgi?id=21857) Sat, 27 Apr 2013 16:17:52 GMT
> Reported by Ehsan Akhgari [:ehsan]
> Assigned to 

It's not clear at what time this method should sample the AudioParams, what the expected sizes of its arguments should be, etc.

**Comment by joeberkovitz** [comment]
@padenot I assigned this to you for tracking purposes because you already started to work on it back in November. If your work on this is finished can you create a PR for it so it can be closed? It seems either done or very close to done.

**Comment by padenot** [comment]
Yes, I'm picking this up soon.
