### ISSUE TITLE
Valid rolloff factors for Panner?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#606]
The spec doesn't say what the valid values for the rolloff factor are.

I think that for the linear and inverse models, the rolloff should be contrained between (0, 1]. (I suppose 0 could be allowed if we want them to degenerate into a constant independent of distance.)

For the exponential, the rolloff can be any positive number. (0 could be allowed too.)

A error (InvalidStateErro) should be thrown if the user tries to set the rolloff factor to an invalid value.  Or if the panner type is set with an rolloff factor that would be invalid.

**Comment by karlt** [comment]
I wonder whether deprecation of PannerNode is sufficient here.
Are roll-off and distance models something that the
client can take care of with GainNode and a little client-side maths?

**Comment by karlt** [comment]
rtoy writes:

> A error (InvalidStateErro) should be thrown if the user tries to set the
> rolloff factor to an invalid value.  Or if the panner type is set with an
> rolloff factor that would be invalid.

If this part of the PannerNode API is going to be kept, it would be nice to
allow the type and value to be set in any order, which would suggest that the
same bounds are enforced for all models.  Instead of throwing exceptions, the
implementation could use a value obtained by constraining to the range
appropriate for the model.

**Comment by rtoy** [comment]
Chrome metrics show that there are lots of users of the PannerNode (along with many uses of webkitAudioContext instead of AudioContext).  I suspect it will be a long time before the PannerNode can actually be removed from chrome.  Until it goes away, people still need to know what happens. I assume similar issues exist for the upcoming SpatializerNode too.

I suppose client side math and gain nodes could get the distance models implemented, but the same could be said for most of the nodes in WebAudio.

For the linear and inverse models, limiting the rolloff to [0,1] makes sense. I'm not sure limiting that for the exponential makes sense.  You wouldn't then be able to have an inverse square law.

**Comment by karlt** [comment]
Yes, negative rolloff is probably not useful in any of the models.

An arbitrarily large rolloff factor is fine in both inverse and
exponential models, I think.

For the linear model, it is negative gains that can cause
surprises.  Although constraining the rolloff factor can avoid
that, I think it would be less restrictive to instead clamp the
distanceGain to be >= 0.

A domain of [0,∞] for rolloff in all models, together with the
clamping of d in
https://github.com/rtoy/web-audio-api/commit/31b9f642fd98a1888382df0da1a602f94f1bc8dc
and clamping distanceGain >= 0 (explicitly required with linear),
would almost be enough to provide a range of [0,1] for distanceGain.

The remaining awkward situation is the linear model with
d_max < d_ref.  (https://github.com/WebAudio/web-audio-api/issues/611)

**Comment by rtoy** [comment]
I find it much more intuitive for the linear model to restrict the rolloff to [0,1] than to allow any positive value and force clamping of the gain to positive.

I do agree that all positive (non-negative?) rolloff for the inverse and exponential are fine.

**Comment by rtoy** [comment]
Now that we specify a nominal range for everything (or at least `AudioParam`s), I think we should also specify nominal ranges for these and clamp them to the nominal range when used.  I think this also means that there is no constraint on the actual value; the clamping happens internally as part of the algorithm.
