### ISSUE TITLE
Behavior of exponentialRampToValue when the previous event is less than equal to 0

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#612]
http://webaudio.github.io/web-audio-api/#widl-AudioParam-exponentialRampToValueAtTime-void-float-value-double-endTime says an error must be thrown if the value parameter is not strictly positive.  This is easy to understand and immediately indicates that the event is not inserted.

However, the description for the value parameter also says the exception must be thrown if the previous value (the start value V0) is not positive.  In practice, this error cannot be thrown until the exponentialRamp is being processed.  After the error is thrown, what should happen?  The formula is undefined for negative V0, but the event is already in the timeline.  

Should the timeline just hold the value from the end of the previous event?  That seems like the only reasonable thing to do and behaves as if the exponentialRamp were never inserted into the timeline.

**Comment by padenot** [comment]
Yes I think you're right.

**Comment by rtoy** [comment]
One other thing.  The formula is well-defined if both V0 and V1 are strictly negative.  Should that be allowed?  Then we have a problem if V0 and V1 have opposite signs, but we can throw an error in that case and just hold the previous value.

**Comment by padenot** [comment]
That seems useful to me for some AudioParams.

**Comment by joeberkovitz** [comment]
TPAC 2015: Modify spec to only throw if value is exactly zero. Redefine the formula to distinguish the case where V0 and V1 have opposite signs, in which case the value of the formula is V0 (i.e preserve the previous value). In case where both are strictly negative, arrange for the formula to invert both V0 and V1 and then invert its result.

**Comment by rtoy** [comment]
I think we also said that we only throw for exponentialRampToValue(0, time).  That is, the error is only thrown if the value for the ramp is 0.  This implies that if v0 is 0 (or has opposite sign), no error is thrown because it's only knowable at the time the exponential is being run.  Throwing seems less useful at that point because there's nothing the application can do about it.

**Comment by joeberkovitz** [comment]
Yes, that is my recollection too.
