### ISSUE TITLE
setTargetAtTime should clarify legal range of values for timeConstant

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#616]
At the moment there is no clear legal range for the `timeConstant` value of `AudioParam.setTargetAtTime()`. Zero or negative values clearly should not be allowed.

**Comment by rtoy** [comment]
Agreed.

**Comment by karlt** [comment]
Negative values don't produce a result consistent with the
intention of the method.

Zero, however, makes sense as the limit as the timeConstant
approaches zero.

Note that the parameter is "float" and so requiring an exception
to be thrown on zero would require any javascript wanting to avoid
exceptions to explicitly test against the minimum number
representable in float.  The implementation would also need to be
careful that subnormal floats were not flushed to zero before the
test to determine whether to throw the exception.

**Comment by rtoy** [comment]
Allowing 0 is acceptable to me.  It's put a little burden on the implementation to compute the limit correctly, but it's not hard.
