### ISSUE TITLE
Warnings and errors when running tidy

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#619]
When I run `make tidy`, I get the following output:

    line 96 column 5 - Error: <section> is not recognized!
    line 96 column 5 - Warning: discarding unexpected <section>
    line 120 column 5 - Warning: discarding unexpected </section>
    line 121 column 5 - Error: <section> is not recognized!
    line 121 column 5 - Warning: discarding unexpected <section>
    line 121 column 24 - Warning: discarding unexpected </section>
    line 122 column 5 - Error: <section> is not recognized!
    line 122 column 5 - Warning: discarding unexpected <section>
    line 126 column 7 - Error: <section> is not recognized!
    line 126 column 7 - Warning: discarding unexpected <section>
    line 157 column 7 - Warning: discarding unexpected </section>
    line 158 column 7 - Error: <section> is not recognized!
    line 158 column 7 - Warning: discarding unexpected <section>
    line 269 column 9 - Error: <section> is not recognized!

Is this expected?

**Comment by padenot** [comment]
I dont' think so, I'll fix those, it was tidy-clean when I landed it.

**Comment by rtoy** [comment]
Thanks, Paul.

I assume that it's expected that people submitting pull requests should run tidy before submitting pull requests.  Is that right?

**Comment by padenot** [comment]
Indeed. I have automation set up to know when we break something if we want that. We could also run other things there, like link checking or respec error count. It's very straightforward.

**Comment by rtoy** [comment]
Automation would be cool.  Then we would know which PR broke things.  And that might make it easier for submitters if they don't have to have tidy on their machines.

**Comment by rtoy** [comment]
Also, is it possible to get tidy not to fill paragraphs containing math formulas?  It makes it pretty hard to read the TeX formulas now if they were split over several lines for readability.

**Comment by padenot** [comment]
I've found a hack to do that, I'm preparing a pull request that will:
- implement the hack
- reformat all the math formulas so that they are neatly aligned with `\\`
