### ISSUE TITLE
Enable travis-ci to ensure that `tidy` errors don't creep in

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#623]
It would be good to have a travis-ci setup so that we don't add new tidy errors in the document.

I'm willing to do this, but I'd have to be an owner of the WebAudio or maybe just the web-audio-api repo to flip the right switch on travis.

I've done all the rest already (I had it setup on my fork).

**Comment by hoch** [comment]
:+1:

**Comment by rtoy** [comment]
+100!

When this is set up, will travis-ci cause the PR to be rejected (not applied)?  Or will we get notified that some PR merge fails?  Do we have to check a website or will we get emails (emails preferred)?

**Comment by padenot** [comment]
We can do whatever we want, it is a very flexible system. They way I have it setup for now (in my fork) is that it sends an email when it fails, as well as having a "badge" that indicates if the build passes or fail, to put (for example) in the readme. I know a lot of project have hooks or bots that post in PRs as wwell.

**Comment by rtoy** [comment]
I think your current setup sounds like a good start, and I'm happy with just that for now.  Seems like a reasonable trade-off.

**Comment by padenot** [comment]
@mdjp, you're an admin here, could you flip the switch on my account so I can set this up ?

**Comment by mdjp** [comment]
@padenot switch is flipped - you are an owner.
