### ISSUE TITLE
Specify the processing model for the Web Audio API

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#628]
We'll be tracking what still needs to be done for the section "Processing model" that has been sitting in my fork for some time. Having it in the main document is going to be useful to spec more things (including, but not limited to, AudioWorker).

The current status of this can be previewed here: https://padenot.github.io/web-audio-api/

**Comment by padenot** [comment]
What needs to be done here:
- [x] Annotate exceptions as synchronous sections
- [ ] Annotate non-exception synchronous sections
- [ ] Spec the ordering more tightly, and in particular how to detect cycles
- [ ] Spec operations that can happen to a control message queue (push swap pop isempty)

**Comment by joeberkovitz** [comment]
Close when PRs for AudioWorker are merged.

**Comment by rtoy** [comment]
Section 3.1 (Background) says "this section is non-normative".  It's not clear if it means section 3.1 or all of section 3.  Section 3.2 says "MUST" have a control thread and one rendering thread.  I don't think anyone is doing this today, but I can imagine more than one rendering thread.

I want the spec to make it clear that this control message queue is NOT required.

**Comment by padenot** [comment]
This has now been merged and can be closed I think.

**Comment by rtoy** [comment]
I'm ok with closing this and opening new issues for whatever we find.

**Comment by padenot** [comment]
Closing.
