### ISSUE TITLE
Specify the nominal range for SpatialPannerNode's AudioParam

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#640]

**Comment by joeberkovitz** [comment]
TPAC 2015: define all AudioParams in the two 3-vectors to have a nominal range of [-Inf, +Inf].

**Comment by rtoy** [comment]
If the nominal range is (-Inf, +Inf), do we actually need to say anything? I would expect a float param to allow all possible values unless otherwise specified.

**Comment by padenot** [comment]
I prefer explicit over implicit for specs.
