### ISSUE TITLE
Conflict on resuming context

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#642]
Here is the behavior on resuming a realtime context.

> The promise is rejected if the context has been closed. If the context is **not currently suspended**, the promise will **resolve**.

For offline context, we have

> If the context is **not currently suspended** or the rendering has not started, the promise is **rejected** with InvalidStateError.

Which one is more reasonable?

**Comment by padenot** [comment]
The first behaviour has been shipping for some time, I'd say we can't really change it now.

**Comment by hoch** [comment]
I agree. @rtoy WDYT?

**Comment by rtoy** [comment]
Yeah, I wouldn't want to change the existing online context behavior of resume.

I don't have any objections if resume on offline contexts behaves differently.  The use cases are different and suspend is already different (time arg required).

**Comment by hoch** [comment]
Honestly, resuming a running context is not that really meaningful. Especially In OfflineAudioContext, changing audio graph or scheduling things will be done much faster than realtime, so doing something after the resuming is not the recommended usage.

**Comment by joeberkovitz** [comment]
TPAC 2015: Change the behavior of OfflineAudioContext to match the online one, i.e. resolve the promise if the context is in a running state and reject only if it is closed.

Since both AudioContexts will now inherit from a single interface it would be strange to vary this behavior even though the use cases are somewhat different.

**Comment by hoch** [comment]
I forgot to bring up another question: what should we do about __resuming a context that has not been started__?

I think we should reject the promise.

**Comment by padenot** [comment]
Yes, for the Offline case. For the online case, this would behave normally, but is kind of useless.

**Comment by hoch** [comment]
For this issue, PR #656 is on the review.

**Comment by hoch** [comment]
The spec has changed and the PR #656 is not applicable any more. I am removing In the PR Review label.

**Comment by hoch** [comment]
Oh, I forgot to close this: https://github.com/WebAudio/web-audio-api/pull/1096.
