### ISSUE TITLE
Chaining AudioNode.connect() and AudioParam's automation methods

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#650]
This is related to issue #258 and PR 44ebce6044882da08c41f30a835b3564c922a407.

Currently what we have in the spec is:
```js
AudioNode connect (AudioNode destination, ...);
AudioParam connect (AudioParam destination, ...);
```

I believe we've discussed the first method in the meeting, but have we agreed on the second one? Actually second one looks a bit weird.

```js
osc.connect(filter.frequency)
  .linearRampToValue(880, context.currentTime + 2.0);
```

Since we cannot chain the automation method, the chaining fun ends here. Also it is a bit weird to see the change of flow from `connect() -> linearRampToValue()`. Personally, I would like to have connecting AudioNode to AudioParam not return anything.

In addition to that, chaining AudioParam methods would be a nice addition.

```js
var now = context.currentTime;
lowpass.frequency.setValueAtTime(220, now)
  .exponentialRampToValueAtTime(880, now + 1.0)
  .linearRampToValueAtTime(440, now + 2.0);
```

It saves a bit of typing and improves the flow of code. This is kind of what I have been doing with [my library](https://github.com/hoch/spiral/blob/master/examples/audioparam-automation.html) and I think it is quite convenient.

**Comment by padenot** [comment]
Agreed. Similarly, it's very easy to do and looks nice.

**Comment by hoch** [comment]
So here's my proposal:

```webidl
partial interface AudioNode : EventTarget {
    AudioNode  connect (AudioNode destination, optional unsigned long output = 0, 
                        optional unsigned long input = 0);
    void connect (AudioParam destination, optional unsigned long output = 0);
}
```
Connecting to an `AudioNode` returns the destination node whereas connecting to an `AudioParam` returns nothing.

```webidl
partial interface AudioParam {
    AudioParam setValueAtTime (float value, double startTime);
    AudioParam linearRampToValueAtTime (float value, double endTime);
    AudioParam exponentialRampToValueAtTime (float value, double endTime);
    AudioParam setTargetAtTime (float target, double startTime, float timeConstant);
    AudioParam setValueCurveAtTime (Float32Array values, double startTime, 
                                    double duration);
    AudioParam cancelScheduledValues (double startTime);
};
```
Unlike `AudioNode::connect`, these methods return the `AudioParam` object itself.

**Comment by mrkishi** [comment]
Once we have instanceable `AudioParam`s and `AudioParam.connect(AudioNode | AudioParam)`, won't it be weird being able to chain one but not the other?

**Comment by hoch** [comment]
I agree. So should we just allow free-for-all connection and chaining?

```js
var now = context.currentTime;
osc.connect(amp)
  .gain.exponentialRampToValueAtTime(1000, now + 3.0)
  .connect(mod.frequency);
```
I know this is an extreme example, but I do not think this code is better than what we have now. I've messed around a bit with the idea, the code gets cryptic quickly over few lines.

Also once you go into the AudioParam, there is no going back up one level (originating AudioNode) unless we introduce something like `AudioParam::parentAudioNode`.

**Comment by hoch** [comment]
@mrkishi WG went over the TAG review/suggestion in the TPAC 2015, we generally agreed that AudioParam should not be instanceable, at least in V1.

**Comment by mrkishi** [comment]
Oh, nevermind, then, as we'll have to keep using gain nodes.

**Comment by hoch** [comment]
@padenot @rtoy Should we discuss this in the next teleconf? It would be really great if this can be marked as 'ready for editing' and I am happy to file a PR for that.

**Comment by rtoy** [comment]
If we're chaining connect, would it make sense to allow chaining of disconnect?  That has a certain symmetry to it.

**Comment by hoch** [comment]
Connecting nodes is usually a common and repetitive task, but disconnecting explicitly is relatively rare in my opinion. Although I agree with your observation on the current asymmetry, I would like to see the actual use case or benefit of it.

**Comment by hoch** [comment]
After the discussion with @rtoy, I think this needs to be added:
- If the connection or automation fails (i.e. invalid arguments), throw an exception and stop the propagation. Also the method returns `null`.

Thus the interface needs to be slightly changed:
```webidl
partial interface AudioNode : EventTarget {
    AudioNode?  connect (AudioNode destination, optional unsigned long output = 0, 
                         optional unsigned long input = 0);
    void connect (AudioParam destination, optional unsigned long output = 0);
};

partial interface AudioParam {
    AudioParam? setValueAtTime (float value, double startTime);
    AudioParam? linearRampToValueAtTime (float value, double endTime);
    AudioParam? exponentialRampToValueAtTime (float value, double endTime);
    AudioParam? setTargetAtTime (float target, double startTime, float timeConstant);
    AudioParam? setValueCurveAtTime (Float32Array values, double startTime, 
                                     double duration);
    AudioParam? cancelScheduledValues (double startTime);
};
```

**Comment by hoch** [comment]
Oops. Sorry, I was wrong. Please ignore the previous comment.

The return type does not have to be `nullable` because the method won't get executed returning nothing at all if invalid arguments provided. (even with try/catch)

So we should just keep the return type as AudioNode/AudioParam, not nullable.

**Comment by hoch** [comment]
This issue does not have a solid decision regarding one aspect:
```webidl
partial interface AudioNode : EventTarget {
    AudioNode  connect (AudioNode destination, optional unsigned long output = 0, 
                         optional unsigned long input = 0);
    void connect (AudioParam destination, optional unsigned long output = 0);
};
```

@cwilso @joeberkovitz Could you please chime in on this? I suggested the second method should not return anything.

**Comment by joeberkovitz** [comment]
@hoch I agree that chaining the second form of `connect(AudioParam destination, ...)` is weird, in that it doesn't quite feel like "chaining" to transition to a completely different flavor of object. So I agree that the return type should be `void`.

**Comment by rtoy** [comment]
Closed via PR #660.

**Comment by cwilso** [comment]
Gah, sorry,missed this one.  As I think we will end up supporting connect()
on AudioParams, I think we should return it here.

**Comment by rtoy** [comment]
@cwilso To be clear, you want node.connect(param) to return the param which @joeberkovitz  says is weird in https://github.com/WebAudio/web-audio-api/issues/650#issuecomment-156562833

**Comment by cwilso** [comment]
Sure.  But AudioParam will add two connect()s, in much the same manner.  In retrospect, AudioParam should probably just inherit from AudioNode, and that would solve all these problems.  :)

**Comment by hoch** [comment]
@cwilso I know we have talked about this several times, but I am not entirely convinced yet. So, AudioParam can (or is supposed to) be controlled by an explicit value, an automation method or a continuous signal. What is the benefit of having output value of AudioParam? In other words, what is the meaning of getting value from AudioParam which you are in control of?

I think you are envisioning AudioParam as a control signal generator (like CV)? This can be done with a dc offset buffer and a gain node, so do you want to simplify this?

**Comment by cwilso** [comment]
You've identified the use case I think we should be doing, and the hacky
workaround.  :)

**Comment by hoch** [comment]
Heh. I thought it is too simple to use the word 'workaround'. :)

**Comment by cwilso** [comment]
But it's not, really - you have to
1) create an AudioBuffer
2) set the AudioBuffer value to 1
3) create a Gain node
4) create an AudioBufferSource node
5) set the ABS.buffer to the AudioBuffer
6) connect the ABS to the Gain
7) connect the Gain to the destination
8) start the AudioBufferplaying
9) call AudioParam scheduling methods on the Gain.
    vs 
1) create an AudioParam
2) connect it to the destination
3) call AudioParam scheduling methods on it
