### ISSUE TITLE
Incorrect formula for setValueCurveAtTime

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#657]
The formula for setValueCurveAtTime (http://localhost:7100/#widl-AudioParam-setValueCurveAtTime-void-Float32Array-values-double-startTime-double-duration) says

    floor(N/Td*(t-T0))

I think this is incorrect.  It should say (N-1)/Td.  When t - T0 = Td the index k is N, but the maximum index into the curve is actually N-1 because it only has N elements.

**Comment by karlt** [comment]
rtoy writes:

> The formula for setValueCurveAtTime
> says
>
>     floor(N/Td*(t-T0))
>
> I think this is incorrect.

Something is wrong, yes, if the V array uses zero-based indexing.

But I wonder whether the "linearly interpolating between V[k] and
V[k+1]" is thinking in terms of one-based indexing.

If N is 1, then would it make sense to linearly interpolate from
the value the curve has at T0 (from the default value or previous
events) to the single provided value at T0 + TD?

It would be kinda tidy to have the interval between values be N/TD.

For zero-based indexing, this might be spec'd by "linearly
interpolating between V[k-1] and V[k], if k > 0, or between V0 and
V[0] if k = 0, where V0 is the value at the time T0."
c.f. linearRampToValueAtTime

**Comment by rtoy** [comment]
On Wed, Nov 4, 2015 at 3:27 PM, Karl Tomlinson <notifications@github.com>
wrote:

> rtoy writes:
>
> > The formula for setValueCurveAtTime
> > says
> >
> > floor(N/Td*(t-T0))
> >
> > I think this is incorrect.
>
> Something is wrong, yes, if the V array uses zero-based indexing.
>
> But I wonder whether the "linearly interpolating between V[k] and
> V[k+1]" is thinking in terms of one-based indexing.
>

​Perhaps the very first version was thinking that, but when I changed it to
the current (incorrect) formula, I was definitely thinking of 0-based
indexing of the curve array.​


>
> If N is 1, then would it make sense to linearly interpolate from
> the value the curve has at T0 (from the default value or previous
> events) to the single provided value at T0 + TD?
>

​I think we've already specified that N cannot be 1.  There has to be at
least two points in the curve.​


>
> It would be kinda tidy to have the interval between values be N/TD.
>
> For zero-based indexing, this might be spec'd by "linearly
> interpolating between V[k-1] and V[k], if k > 0, or between V0 and
> V[0] if k = 0, where V0 is the value at the time T0."
> c.f. linearRampToValueAtTime
>

​Perhaps.  I think it's easier for people to think that at T0, the value is
curve[0], and at T0+TD, the value is exactly curve[N-1].  I believe this
works out if you change the formula to be floor((N-1)/Td*(t-T0)).​


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/657#issuecomment-153903302>
> .
>



-- 
Ray
