### ISSUE TITLE
The AudioBufferSourceNode.prototype.buffer setter doesn't handle null correctly

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#666]
https://webaudio.github.io/web-audio-api/#AudioBufferSourceNode

"This attribute can only be set once, or a InvalidStateError must be thrown."

This needs clarification. Setting `buffer` to null when it already null should arguably do nothing, while trying to set `buffer` to anything when it is not null should throw InvalidStateError. The way it's written, this should throw:
```JavaScript
var source = context.createBufferSource();
source.buffer = null;
source.buffer = null;
```

And that would make no sense.

**Comment by foolip** [comment]
Always throwing when setting to null would also work, and is effectively what Chrome does.

**Comment by padenot** [comment]
The intent was that setting a new AudioBuffer throws, setting it back to null does not throw. Setting any other type throws all the time, setting it to null multiple times works. We need to adjust the prose here.

**Comment by foolip** [comment]
Can you spell that out as the steps of an algorithm? I can't make sense of "setting it back to null does not throw" because then you can always change from one buffer to another by first setting it to null.

As implemented in Chromium, the setter always throws if the internal buffer member (what the buffer attribute returns) is not null.

Note that you don't need to spell out "Setting any other type throws all the time" in prose because that's ensured by having `AudioBuffer?` as the type in the WebIDL block.

**Comment by padenot** [comment]
Yes, this will be spelled out as an algorithm.
