### ISSUE TITLE
The ConvolverHandler.prototype.buffer setter doesn't handle null

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#667]
https://webaudio.github.io/web-audio-api/#ConvolverNode

"A mono, stereo, or 4-channel AudioBuffer containing the (possibly multi-channel) impulse response used by the ConvolverNode. The AudioBuffer must have 1, 2, or 4 channels or a NotSupportedError exception must be thrown. This AudioBuffer must be of the same sample-rate as the AudioContext or a NotSupportedError exception must be thrown. At the time when this attribute is set, the buffer and the state of the normalize attribute will be used to configure the ConvolverNode with this impulse response having the given normalization. The initial value of this attribute is null."

This doesn't say what should happen if `buffer` is set to null. In Chrome it silently does nothing. Should it be possible to clear the buffer by setting it to null?

See also https://github.com/WebAudio/web-audio-api/issues/666

**Comment by rtoy** [comment]
I think this is covered in #436, particularly https://github.com/WebAudio/web-audio-api/issues/436#issuecomment-151037348.

The issue is closed, but perhaps it should be reopened until the spec is updated with appropriate text.

**Comment by foolip** [comment]
Yeah, reopening that and closing this would WFM. FWIW, https://github.com/WebAudio/web-audio-api/issues/436#issuecomment-151037348 isn't detailed enough for me to tell precisely how the setters should work, but I can review after the spec changes have been made.

**Comment by joeberkovitz** [comment]
Copy the behavior of AudioBufferSourceNode w/r/t setting of `buffer` to ConvolverNode and WaveShaperNode. Indicate that setting a `null` buffer causes the node to produce silence from then on out.
