### ISSUE TITLE
Clarify what "stability" means in playbackCategory description

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#670]
This was brought up on blink-dev.  In the description of AudioContextPlaybackCategory (https://webaudio.github.io/web-audio-api/#idl-def-AudioContextPlaybackCategory) we have:

    balanced	Balance audio output latency and stability/power consumption. 

What does "stability" actually mean here?

**Comment by billhofmann** [comment]
Good question.  Glad to see people are reading this :)  This was transcribed directly from our discussion.  I'd propose we just strike "stability/", since the balance is between latency and power consumption.

**Comment by rtoy** [comment]
Works for me.
