### ISSUE TITLE
decodeAudioData() results are different on different OS

### ISSUE THREAD

**Issue by wyudong** [WebAudio/web-audio-api#678]
When I decode an audio file using `decodeAudioData()` of Web Audio API, I got a weird problem: the decode results will depend on the operating system. Did anyone encounter the same problem, or know the reason why?

I made a quick [demo](http://plaay.in/decode-audio-data/decode.html) and tested it on Mac OS (10.11) and Windows 7 and the browsers are both Chrome (v46.0+), but their results are different. To visualize the results:

<img width="608" alt="wave" src="https://cloud.githubusercontent.com/assets/5687273/11716758/189a691c-9f87-11e5-807e-02bb33048b60.png">

Everyone can run this demo, just click the "LOAD" button and the results will be logged in the console.

**Comment by padenot** [comment]
Please open a bug on Chrome's [bug tracker](https://code.google.com/p/chromium/issues/list), this is an issue in the implementation, not in the specification.

**Comment by rtoy** [comment]
For completeness, the difference is because the sample rate is different between the two systems.  decodeAudioData is working as intended by resampling the audio file to the context rate.
