### ISSUE TITLE
Inconsistency on cone inner and outer angles for PannerNode

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#682]
The [spec](http://webaudio.github.io/web-audio-api/#widl-PannerNode-coneInnerAngle) currently says the cone angles are taken modulo 360.  The spec also says the default angle is 360.

If we follow the spec, the default angles are then treated as 0 deg. In particular, the outer angle is 0, which means the sound is reduced to coneOuterGain (defaulting to 0), except if you're directly pointed at the listener.

With Chrome (and Safari), if the inner and outer angles are both 360, no cone effects are applied. That is, the source is treated as omni-directional.  Firefox appears to do the same thing.

Proposal:  Add text to say the if the inner and outer angles are both 360, the source is treated as omnidirectional.

**Comment by karlt** [comment]
rtoy writes:

> The
> [spec](http://webaudio.github.io/web-audio-api/#widl-PannerNode-coneInnerAngle)
> currently says the cone angles are taken modulo 360.  The spec also says the
> default angle is 360.

I think the bug is in the "modulo 360" part.
The algorithm in the "Sound Cones" section does not interpret
the value using modulo 360, and I can't think of a good reason for
it to do so.

Removing ", and the value is used modulo 360" helps.

**Comment by rtoy** [comment]
See #356.

**Comment by rtoy** [comment]
I think if we change the default values from 360 to 0, then everything should be ok, including the algorithm which says if the angles are both 0, then no cone is specified.

**Comment by karlt** [comment]
I suggest fixing this bug by reverting b4e6cd0.

These "angles" are not directions in the usual sense but more like
fields of view.  It doesn't make sense to treat those modulo 360,
because 361 includes the first 360 degrees and then starts to
covers it again.  Increasing a value from 360 to 361 should not
reduce the field of view, but it won't have any effect.

rtoy writes:

> I think if we change the default values from 360 to 0, then everything should
> be ok, including the algorithm which says if the angles are both 0, then no
> cone is specified.

The expected coverage of 0 is nothing.  That is different from the
expected coverage of 360+, which is everything.

**Comment by rtoy** [comment]
Feel free to file a bug saying we shouldn't take the angles modulo 360.  Please specify how that is also supposed to work for angles greater than 360. (Maybe disallowing such things?)

**Comment by rtoy** [comment]
Issue #695 supersedes this, and makes this not an issue.  Closing.
