### ISSUE TITLE
Editorial: could consider upgrading MathJax to 2.6?

### ISSUE THREAD

**Issue by kojiishi** [WebAudio/web-audio-api#688]
Could you please consider upgrading MathJax to 2.6?

MathJax prior to 2.6 emits a thin border only for Chrome, which used to be ignored, but became visible when [Chrome fixed an interop issue](http://crbug.com/229428).

MathJax 2.6 has [a fix for this issue](https://github.com/mathjax/MathJax/issues/1300).

**Comment by rtoy** [comment]
Ideally, we'll need W3C to update their site with MathJax 2.6.

**Comment by bert-github** [comment]
I'll upgrade MathJax on the W3C site to 2.6.1 (Thanks for your e-mail, Rtoy!)
