### ISSUE TITLE
Add OfflineAudioContext length attribute

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#690]
It would be rather nice if an OfflineAudioContext included (read-only) attributes for the number of channels and the length that was used to create the context.

Yes, I know I can go look through the code to find out how it was constructed, but it would certainly be nice to be to do a little introspection and just ask the context what the values were.  Yes, I can also render the context and look at the resulting buffer, but I want to do this before rendering is done.

**Comment by karlt** [comment]
rtoy writes:

> It would be rather nice if an OfflineAudioContext included (read-only)
> attributes for the number of channels and the length that was used to create
> the context.

Number of channels is available through destination.channelCount:

"For anAudioDestinationNode in an OfflineAudioContext, the
channelCount is determined when the offline context is created and
this value may not be changed."

I think you are right that the length is not available until
completion of rendering.

**Comment by rtoy** [comment]
Ah, I always forget there's a context.destination.
