### ISSUE TITLE
Playback category/latency differs from MediaCapture latency

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#692]
The spec currently says the latency hint is given by the playbackCategory that takes an enum, as decided in #348.  However the [MediaCapture latency hint](http://w3c.github.io/mediacapture-main/getusermedia.html#sec-track-properties) (Search for latency) is a float.

Should we make these consistent?  If so, this basically reverts #348 back to use a float hint as was originally proposed in #348.

This issue came up in an intent to ship on blink-dev.

**Comment by padenot** [comment]
We should open an issue on the MediaCapture spec and tell them to change this. Having a double here makes no sense considering the variety of platforms that exist.

**Comment by joeberkovitz** [comment]
@padenot to file issue against Media Capture to explore their rationale -- closing this bug.
