### ISSUE TITLE
Behavior when setting playbackCategory to an invalid value

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#694]
The spec currently doesn't say what happens if you specify a playbackCategory that isn't one of the specified values.  I think this is ok, but if, in the future, we add a new category, there's no way to tell if the browser supports this; you just have to hope it did something useful.

Can we add something to allow detection?  Either throw a NotSupportedError for invalid values, or have a read-only attribute for the category?

**Comment by billhofmann** [comment]
Hmmm.  What is general WebIDL behavior?  I’d expect a fail.

**Comment by padenot** [comment]
This is handled at the WebIDL level.

**Comment by rtoy** [comment]
Closing.
