### ISSUE TITLE
revert backward incompatible change to cone angles, restoring previous behavior of empty cone for value of 0

### ISSUE THREAD

**Issue by karlt** [WebAudio/web-audio-api#695]
b4e6cd0 made an unnecessary backward-incompatible change from specifying that a value of 0 is empty to specifying that the value is the full sphere.  It also introduced issue #682, as well as inconsistencies between the attribute descriptions on the the sound cones algorithm when the values are greater than 360.  The behavior previously spec'd by the sound cones algorithm, with 0 empty and >= 360 full sphere, was sensible.

**Comment by rtoy** [comment]
I'm ok with this change.  I find it a little confusing to call them angles if they don't wrap around like angles normally do, though.

But the algorithm is pretty clear that if you choose angles greater than 360, the sound cone behaves pretty much as if it were omnidirectional.

**Comment by mdjp** [comment]
Decision - range is 0 - 360 values outside this range are undefined and have no effect.

**Comment by rtoy** [comment]
Umm, you can't say it's undefined and then also say it has no effect.  I would prefer to just say it's undefined.  Then we don't have to update the algorithm in http://localhost:7100/#Spatialization-sound-cones to handle this case.
