### ISSUE TITLE
Property bag option for AudioNode constructors

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#696]
This is a meta bug for the AudioNode constructors mentioned in pull request #250.

I think in general, the names of the properties should match the names of the attributes, and there should be one for each attribute, but each node needs to be examined to make sure that makes sense.

**Comment by hoch** [comment]
A proposal for AudioNode IDL change:
https://github.com/WebAudio/web-audio-api/issues/697#issuecomment-184799851

**Comment by mdjp** [comment]
See individual issues.

**Comment by rtoy** [comment]
All the related issues are closed.  Close this, finally.
