### ISSUE TITLE
Property bag for ScriptProcessor

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#699]
ScriptProcessors are deprecated; do we still need a constructor? I assume so.

In that case, in addition to the known attributes, we need to add numberOfInputs, and numberOfOutputs, which are required.

#696

**Comment by mdjp** [comment]
Deprecated, not required.

**Comment by rtoy** [comment]
Per https://github.com/WebAudio/web-audio-api/issues/699#issuecomment-207028722, we can close this since we don't need a constructor for this deprecated node.
