### ISSUE TITLE
Clarify influence/reference to OpenAL, IPR considerations

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#70]
> Originally reported on W3C Bugzilla [ISSUE-22969](https://www.w3.org/Bugs/Public/show_bug.cgi?id=22969) Thu, 15 Aug 2013 08:39:43 GMT
> Reported by Olivier Thereaux
> Assigned to 

The Web Audio API makes several references (mostly in informational text) about OpenAL and the spec editor has often mentioned it as one of the inspirations for the architecture of the API.

OpenAL was “ done in spirit of open source and implementations distributed in LGPL“ but the licensing/IPR is not clear - and most of the people involved with OpenAL have since moved on.

The Audio WG should review the current spec and assess whether:

* Whether the web audio API is significantly inspired by Open AL
* Whether OpenAL should be formally referred to in the specification
* Depending on the above, whether there are any IPR concerns in the architectural lineage between OpenAL and WebAudioAPI

**Comment by billhofmann** [comment]
NOTE that there are currently only two references to OpenAL - Section 6.1 first paragraph ("A common feature requirement for modern 3D games is the ability to dynamically spatialize and move multiple audio sources in 3D space. Game audio engines such as OpenAL, FMOD, Creative's EAX, Microsoft's XACT Audio, etc. have this ability.") and Section 7.2 ("A key feature of many game audio engines (OpenAL, FMOD, Creative's EAX, Microsoft's XACT Audio, etc.) is a reverberation effect"...).  This issue would *seem* to be addressed.

**Comment by joeberkovitz** [comment]
@billhofmann looks to me like we're good; closing now.
