### ISSUE TITLE
Property bag for ChannelSplitter/ChannelMerger

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#700]
These nodes have no attributes, but the constructors need to specify the number of inputs/outputs.  So the property bag for the constructor needs numberOfOutputs(?) for splitter and numberOfInputs for merger.

#696

**Comment by hoch** [comment]
ChannelSplitter/Merger are identical with AudioNode in terms of the constructor option.

**Comment by mdjp** [comment]
F2F numberOfIn/Outputs should be in the property bag.
