### ISSUE TITLE
Property bag for IIRFilter

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#701]
The IIRFilter node has no attributes.  To create one, the feedforward and feedback coefficients need to be specified, so these should be the names of the properties.  (These are the names of the parameters for createIIRFilter.)

#696

**Comment by hoch** [comment]
```webidl
dictionary IIRFilterOptions : AudioNodeOptions {
    sequence<double> feedforward;
    sequence<double> feedback;
};

[Constructor(AudioContext audioContext, optional IIRFilterOptions iirFilterOptions)]
partial interface IIRFilterNode {
}
```

**Comment by mdjp** [comment]
F2F: Agreed

**Comment by rtoy** [comment]
Looks right, except IIRFilterOptions can't be optional because you have to specify some filter coefficients.  This also means that feedforward and feedback members of the dictionary are required.
