### ISSUE TITLE
Property bag for PeriodicWave

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#703]
A PeriodicWave has no attributes but createPeriodicWave requires two arrays and an optional constraint.  So perhaps the properties are real, imag (from the parameter names for createPeriodicWave), and disableNormalization (to match the optional constraint).

#696

**Comment by hoch** [comment]
```webidl
dictionary PeriodicWaveOptions {
    <sequence>float real,
    <sequence>float imag,
    optional PeriodicWaveConstraints periodicWaveConstraints
};

[Constructor(AudioContext audioContext, PeriodicWaveOptions periodicWaveOptions)]
partial interface PeriodicWave {
}
```

- For this object, the options cannot be optional.

**Comment by mdjp** [comment]
F2F: Agreed with caveat that if real or imag are undefined they will default to array of 0s.

**Comment by rtoy** [comment]
If both real and imag are not given, we should signal an error?

I think the dictionary should look more like this:

    dictionary PeriodicWaveOptions: PeriodicWaveConstraints {
       Float32Array real;
       Float32Array imag;
    }

I think the former would require me to write something like

     {real: realArray, imag: imagArray, {disableNormalization: true}}

I think it's better to say

     {real: realArray, imag: imagArray, disableNormalization: true}

And while we're at it, can we use `sequence<float>` instead of `Float32Array`?
