### ISSUE TITLE
No mention of what AudioNode.connect() returns.

### ISSUE THREAD

**Issue by jan-ivar** [WebAudio/web-audio-api#708]
AudioNode.connect() supposedly returns the destination object. At least I think so because:

1. I infer it from the *other* `connect` method (there are two) explicitly saying it does *not* return it.
2. It's what the Firefox implementation does today.
3. It's quite [handy for chaining](https://jsfiddle.net/jib1/7wd2z8rz/): `nodes.reduce((a, b) => a && a.connect(b));`

However there's no explicit mention of what it returns, which led [MDN to get it wrong](https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/connect%28AudioNode%29$revision/988065), so there probably should be.

**Comment by hoch** [comment]
I believe this is explicit enough on the spec. Take a look at the IDL for AudioNode.

```webidl
AudioNode connect (AudioNode destination, optional unsigned long output = 0
              , optional unsigned long input = 0
              );
```

**Comment by mdjp** [comment]
After working group discussion agreed with comment from @hoch this is already specified.

**Comment by jan-ivar** [comment]
Sorry, I missed your comment 4 days ago, where exactly. How is that explicit in any way? It says it returns a value of type `AudioNode` but there's no mention of which one, `this` or `destination`. Am I missing something?

**Comment by jan-ivar** [comment]
Apparently I'm not allowed to reopen. Paging @hoch and @mdjp.

**Comment by jan-ivar** [comment]
As I mentioned in https://github.com/WebAudio/web-audio-api/issues/708#issue-128686551 MDN had it returning `this` which is wrong.

**Comment by hoch** [comment]
Thanks for pointing that out. In the review process of the PR(https://github.com/hoch/web-audio-api/commit/bfa4fa044a009d719423bf857fa4fb07fb52f489), somehow we decided to remove the description of method chaining.

I am opening the issue and will review your PR.

By the way, if you found something wrong with MDN, probably this is not the right place to report.

**Comment by skratchdot** [comment]
Agreed. Spec is ambiguous. Could return `source/this` or `destination`.  Implementors involved with the spec might understand the meaning, but it's not clear from: http://webaudio.github.io/web-audio-api/#widl-AudioNode-connect-AudioNode-AudioNode-destination-unsigned-long-output-unsigned-long-input

The function returns `void` when `input` is not passed in.  It returns `AudioNode` when `input` is passed in.  A simple description next the to `Return type: AudioNode` would fix the ambiguity.

change:
```html
<div>
  <em>Return type: </em>
  <code>
    <a href="#idl-def-AudioNode" class="idlType"><code>AudioNode</code></a>
  </code>
</div>
```

to:
```html
<div>
  <em>Return type: </em>
  <code>
    <a href="#idl-def-AudioNode" class="idlType"><code>AudioNode</code></a>
  </code>
  (the `destination` node)
</div>
```

**Comment by hoch** [comment]
Unfortunately that's not possible because `Return type:` is generated by respec. I rather add more text to the description of method.

**Comment by jan-ivar** [comment]
> By the way, if you found something wrong with MDN, probably this is not the right place to report.

I'd already fixed MDN.

**Comment by jan-ivar** [comment]
> The function returns void when input is not passed in. It returns AudioNode when input is passed in.

Um, that doesn't seem right. Aren't the two methods distinguished by the interface type of the first argument?

In Firefox, `a.connect(b)` returns `b`: https://jsfiddle.net/7wd2z8rz/

**Comment by skratchdot** [comment]
@jan-ivar - good point.  I was just going off the docs there, and that's what it looked like.  Might be a misunderstanding from a quick read on my part (another reason I think the ambiguity should be addressed).

**Comment by skratchdot** [comment]
Seems like we just need to update the 2 places that it says `connect` returns `void`: http://webaudio.github.io/web-audio-api/#widl-AudioNode-connect-void-AudioParam-destination-unsigned-long-output

**Comment by rtoy** [comment]
Just to be clear, connect(AudioParam) does not return the AudioParam.  It was decided against as being a bit strange.  connect(AudioNode) does return the node.

If you think this is wrong, please file a new bug since this bug is closed.

**Comment by skratchdot** [comment]
Ah. I see that now. Sorry for the unclear reading / understanding on my part.  Makes sense now.
