### ISSUE TITLE
Say listener attribute is deprecated

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#717]
The section http://webaudio.github.io/web-audio-api/#AudioListener says it's deprecated.  We should probably also say that in http://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-listener to be explicit.  And it should also say it's for the PannerNode since also have SpatialPannerNode now.

**Comment by mdjp** [comment]
agreed on call

**Comment by rtoy** [comment]
Need to wait for the resolution of #749.

**Comment by rtoy** [comment]
Resolution of #749, We can close this.  The AudioListener is not deprecated.
