### ISSUE TITLE
5.1 to mono downmixing

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#718]
The downmixing formula in http://webaudio.github.io/web-audio-api/#down-mix for 5.1 to mono says

    output = 0.7071 * (input.L + input.R) + input.C + 0.5 * (input.SL + input.SR)

This explicitly says 0.7071, but presumably it really meant sqrt(1/2).  I think the formula should say sqrt(1/2) instead of 0.7071.  If you're testing downmixing, 0.7071 vs sqrt(1/2) makes a difference.

**Comment by hoch** [comment]
+1

**Comment by rtoy** [comment]
Fixed by PR #720
