### ISSUE TITLE
Analyser downmixing unclear

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#719]
In issue #86 (in particular https://github.com/WebAudio/web-audio-api/issues/86#issuecomment-148107986), it was decided that the AnalyserNode downmix to mono.  The spec currently says so.

But the text doesn't link to the downmixing rules so it's not clear how downmixing is to be done. If the downmixing rules (http://webaudio.github.io/web-audio-api/#channel-up-mixing-and-down-mixing) are followed, then we get into the following situation.

If the source has 3 channels, the rules state that since this isn't defined, the rule is to use the discrete channel interpretation.  This means the first channel is used.

From what I remember on the original discussion at the F2F, we wanted the analyser node to include the effect of all the channels, so using the first channel seems counter to this desire.

In any case, we need to specify this more clearly.  Either follow the downmixing rules already specified or specify a new rule only for the analyser.

**Comment by padenot** [comment]
It looks like we need to define more mixing rules.

**Comment by rtoy** [comment]
I don't think we really need more downmixing rules; the rules are explicit.  This issue is based on my memory of the F2F where we said the analyser should mix all of the channels together where it seemed implicit that we wanted contributions from all channels. Do we want to just leave the analyser to say that the channels are downmixed according to the rules or just say we average all the channels together.  Chrome does the averaging today.

**Comment by rtoy** [comment]
Just briefly clarify the spec to say the downmixing rules.

**Comment by rtoy** [comment]
Reopening.  The PR #733 goes part way, but I think we need to say that the downmixing is, first, independent of the channelCount, channelCountMode, and channelInterpretation of the node.  Second, we should say the downmixing happens with channelCount = 1, channelCountMode = "max", and channelInterpretation = "speakers".

I think we don't want the node settings to change the downmixing.
