### ISSUE TITLE
Interdependence between playbackRate and detune

### ISSUE THREAD

**Issue by fooSolver** [WebAudio/web-audio-api#723]
At current time the parameter _playbackRate_ and _detune_ are having the same effect on the replay of  an audio source.
Is it expectable, that in future releases the parameter:
•	**playbackRate** – will speed up or slow down the replay of an audio source without having influence on the pitch,
and/or
•	**detune** – will transpose in half-note-steps the replay of an audio source without having an effect on the speed of the replay?
Or does it make more sense to work on a ‘self-made’ solution by programming an algorithm and implement it with _Audio Workers_ ?

**Comment by hoch** [comment]
I think your suggestion makes sense, but not sure how this issue should be handled considering the group is trying to wrap up the first version of the spec.

As you pointed out, this probably will be labeled as `v.next`.

**Comment by rtoy** [comment]
Such changes would break backward compatibility, so I am opposed to changing how playbackRate and detune work.

**Comment by mattlima** [comment]
I don't want breaking changes either but how about an IFFT node? Would be a nice thing to have in order to be able to do this kind of thing.

**Comment by joeberkovitz** [comment]
We can add this as a future feature but it won't be based on `playbackRate` or `detune`.

**Comment by Jun711** [comment]
@joeberkovitz as of current Web Audio API, is there any way to change audio's playbackRate without changing its pitch? [code I used to try AudioBufferSourceNode.playbackRate](https://github.com/mdn/webaudio-examples/blob/master/offline-audio-context-promise/index.html)
