### ISSUE TITLE
Clarify Up/Downmix procedure

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#724]
Consider the following example:
Node A (1ch) => Node C (2ch)
Node B (4ch) => Node C (2ch)
(channelCountMode = "max", interpretation = "speakers")

According to the spec here: http://webaudio.github.io/web-audio-api/#channel-up-mixing-and-down-mixing, and my interpretation on the example above is:
1. Get `computedNumberOfChannel` - it will be 4 (by Node B) and Node C will have the channel count of 4 upon the connection from Node B.
2. Upmix A => C with the 'mono-to-quad' rule.
3. Duplicate B => C.
4. Sum the result of 2 and 3. The output will have 4 channels.

The other possible (probably incorrect) interpretation is:
1. Upmix A => C with 'mono-to-stereo' rule, since `computedNumberOfChannels` is 2 between A and C.
2. Duplicate B => C after the channel conformation from 2 to 4.

I guess the ambiguous part in the spec is: "For each input of an AudioNode..." in the mixing rule section. IMO, we don't need to compute `computedNumberOfChannels` for every iteration of incoming connections.

**Comment by rtoy** [comment]
Your first interpretation is what I would expect.  I don't understand what you mean by not computing `computedNumberOfChannels` for every iteration.

**Comment by hoch** [comment]
Yeah, it is sort of a made-up example. The point is calculating `computedNumberOfChannels` for every incoming connection and apply mixing rules individually.

`computedNumberOfChannels` should be computed upfront and the mixing rule applies based on that number. Does this make sense?

**Comment by hoch** [comment]
I guess I was confused about the term 'input' here. After a bit of thinking, I believe the specification is fine.
