### ISSUE TITLE
Multiple calls to getFloatFrequencyData

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#729]
Consider the following bit of code:

```
var context = new OfflineAudioContext(1, 44100, 44100);
var osc = context.createOscillator();

osc.frequency.setValueAtTime(261.6, 0.0);

var a = context.createAnalyser();
a.fftSize = 32;

osc.connect(a);
a.connect(context.destination);

osc.start();

context.suspend(128/context.sampleRate).then(function () {
 var f1 = new Float32Array(a.frequencyBinCount);
 var f2 = new Float32Array(a.frequencyBinCount);

 a.getFloatFrequencyData(f1);
 a.getFloatFrequencyData(f2);

 console.log(f1);
 console.log(f2);

 context.resume();
});
```

What should the console log contain?  Currently on Chrome, Edge, and Firefox, the values of f1 and f2 are different.  Why?  Because each call to getFloatFrequencyData computes (the same) FFT again and applies the smoothing again.

I find this behavior odd.  I think f1 and f2 should return exactly the same values because I'm asking for the FFT at exactly the same time.  There shouldn't be additional smoothing applied for each call.

I concede that the spec doesn't explicitly allow or forbid either of the behaviors.

One use case (from @hoch) where it might really matter is if you want to do getByteFrequencyData and getFloatFrequencyData at the same time.  The byte value is used for an animation and the float value is used for further detailed analysis and processing.  Ideally, the values should be consistent, but they're not; one has an extra smoothing applied.

**Comment by padenot** [comment]
Agreed, this is a bug.

**Comment by rtoy** [comment]
I'll try to write up something to say that multiple calls at the same context time return the same data.

**Comment by padenot** [comment]
Multiple call in the same stable state should return the same data, even.

**Comment by hoch** [comment]
However, "multiple call in the same stable state" is only possible with OfflineAudioContext.suspend(time). In the realtime audio context, we cannot guarantee the 'stable state' of two consecutive JS function calls.

**Comment by mdjp** [comment]
F2F Resolution: getFrequencyData() should return the same value for multiple calls for the same currentTime
The spec should define this behaviour.
