### ISSUE TITLE
PannerNode's setVelocity should be removed (part of doppler effects)

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#730]
With https://github.com/WebAudio/web-audio-api/issues/372 doppler effects were removed, removing `setVelocity` and other things from `AudioListener`. `setVelocity` remains on `PannerNode`, and it is claimed that "This velocity relative to the listener's velocity is used to determine how much doppler shift (pitch change) to apply."

@rtoy

**Comment by padenot** [comment]
We've considering removing this in gecko, but there is a very clear web compat issue, so we're waiting.

**Comment by rtoy** [comment]
Chrome removed the doppler effect some time ago.  The attributes are still
there, but will be removed sometime soon.

On Wed, Feb 24, 2016 at 5:22 AM, Paul Adenot <notifications@github.com>
wrote:

> We've considering removing this in gecko, but there is a very clear web
> compat issue, so we're waiting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/730#issuecomment-188252666>
> .
>



-- 
Ray

**Comment by rtoy** [comment]
I also see we've left in  the section on Doppler shift: https://webaudio.github.io/web-audio-api/#Spatialization-doppler-shift.  This needs to be removed as well (along with a few other places where we mention doppler).

Since the doppler effect has been removed, PannerNode.setVelocity doesn't make sense.

**Comment by foolip** [comment]
Indeed, the code in https://webaudio.github.io/web-audio-api/#Spatialization-doppler-shift has actually been removed from Blink now as it was dead code: https://codereview.chromium.org/1734483002/patch/1/10005

(That also made PannerNode's setVelocity explicitly a no-op.)

**Comment by mdjp** [comment]
F2F: No web compat issue setVelocity will be removed
