### ISSUE TITLE
SpatialPanner automation of orientation, forward, and up

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#741]
In the SpatialPanner, the orientation of the source is a 3D vector, and each component can be individually automated.  Consider the use case of a rotating (directed) source (like a lighthouse).  To automate this, you have to break up the rotation into a series of line segments so that you can automate each coordinate linearly so that you stay roughly on a circle.

This is certainly doable, but it would be much easier if, instead of an cartesian coordinate system, we used elevation and azimuth.  For the rotating source, we can just linearly automate the azimuth and it rotates at a constant rate around the circle.

The forward and up vectors for the SpatialListener also have similar issues.  If the listener wants to rotate around, the x,y,z coordinates need to be automated in pieces to get the rotation.  But if an azimuth and elevation were used, the automation would be simple and smooth.

Should we consider using azimuth and elevation parameters to specify the orientation, forward, and up directions instead of cartesian coordinates?  I guess this replaces the cartesian system with a polar system.

**Comment by hoch** [comment]
We agreed it is better to use the spherical coord system for the orientation and the up vector in our offline discussion, but I think we might want to go with the cartesian for the backward compatibility.

SpatialPannerNode should be able to substitute PannerNode with the minimum effort.

**Comment by mdjp** [comment]
closing with no further action
