### ISSUE TITLE
Mixed long and unsigned long used for channels

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#747]
On `AudioBuffer`, `numberOfChannels` is `long` although e.g. `getChannelData` takes a `unsigned long channel` argument. `numberOfChannels` is also `unsigned long` in Blink, so that's probably what the spec should say too.

@rtoy

**Comment by padenot** [comment]
I agree, negative value don't make sense here.

**Comment by rtoy** [comment]
In addition, the length attribute for an AudioBuffer is long. It should probably unslgned long.

**Comment by foolip** [comment]
Yep. Internally in Blink it's size_t though, is it actually guaranteed by anything other than OOM to stay within UINT32_MAX?

**Comment by rtoy** [comment]
I do not know why Blink uses size_t. I'm pretty sure there's no additional check for the range.

**Comment by billhofmann** [comment]
size_t would definitely *not* be the right thing to use except for buffer sizes.  Agree for lengths and counts that an unsigned value is appropriate, whether long or not.
