### ISSUE TITLE
PannerNode attributes of type float should be double?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#751]
The attributes for things like refDistance, cone angles, and so on for the PannerNode (and SpatialPannerNode) are specified to be of type float.  However, Chrome, Firefox, and Safari actually implement them as double.

Should the types of the attributes be double?  This is not a big deal, but if you set the refDistance to 100.1, when you read it back, you won't get 100.1 because 100.1 is a double that gets converted to a float which loses some bits.  The conversion back to double fills in the bits with 0's, producing a different value.

**Comment by padenot** [comment]
Yeah, not a big deal but let's align with what has been shipped for a while here.
