### ISSUE TITLE
Need to define what happens if a detached ArrayBuffer is passed to decodeAudioData

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#757]
Spec currently says:

> Neuter the audioData ArrayBuffer in such a way that JavaScript code may not access or modify the data anymore.

which presumably means to use ES6 `DetachArrayBuffer` but that asserts that it's only used on non-detached array buffers.

Then it talks about attempts to decode data, but if the passed-in thing was detached there is no data to be had at all.

Most importantly, should the promise be rejected with a EncodingError in this case, or a TypeError of the sort ES tends to throw when working with detached buffers?

Maybe it doesn't matter too much since browsers don't implement this part of ES anyway, instead treating detached buffers as normal 0-length buffers...

**Comment by mdjp** [comment]
If array buffer has been neuterd then promise rejected with type error.
