### ISSUE TITLE
Nominal range for biquad gain parameter is too low

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#760]
The nominal range for the biquad gain parameter is [-40,40].  This seems rather low.  We don't limit the possible values for the gain of a gain node, so I don't see why this should be restricted in any way.  Well, except that the biquad gain is in dB (see #759), so there is an actual upper limit to prevent overflow.  This limit is closer to 300 than 40.

**Comment by mdjp** [comment]
Change range [-inf,inf]

**Comment by rtoy** [comment]
On second thought, do we really want the upper limit to be inf?  Since the gain is in dB, that pretty much guarantees that the output of the filter will be either Infinity or NaN. The actual max dB value is closer to 770.  This gives a linear gain of about 3.16e38, near the largest representable single-precision float.

Negative values are ok because it just means the linear gain is very, very close to 0.

Maybe a case of garbage in/garbage out?
