### ISSUE TITLE
Missing nominal ranges for AudioParams

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#762]
I thought we had this all covered in #620, but I guess we missed some.

- AudioBufferSource
 - playbackRate
 - detune
- BiquadFilter
 - frequency
 - detune
- Oscillator
 - frequency
 - detune

I guess `frequency` and `detune` parameters for the `Oscillator` and `BiquadFilter` are covered by the the computedFrequency section, so there should be links from the individual attributes to that section.  Even so, it seems `frequency` should say the range is [0, Nyquist].  detune could probably be [-Nyquist, Nyquist].  All subject to the computedFrequency section of course.

But the `playbackRate` and `detune` for an `AudioBufferSource` have no specified nominal ranges.  Not sure what would be acceptable ranges for this.  It appears that Chrome has a computed playback rate (combining `playbackRate` and `detune`) to the range [0, 1024].

**Comment by rtoy** [comment]
Proposal:  `playbackRate` range is [0, 5] and `detune` is [-2400, 2400].  This assumes playing something 5 times faster is more than enough.  The `playbackRate` doesn't include negatives values right now because #95 hasn't been resolved.  When it is, we can update the lower limit then.

I also forgot that `detune` is in cents, so for the `BiquadFilterNode` and `OscillatorNode`, a nominal range of [-2400, 2400] is ok.  (Two octave change.  Is that large enough?)

**Comment by hoch** [comment]
I gave some thoughts and I feel like we should not put too much constraint on these numbers. Any of implementation does not support the time-correction on pitch change (and never will in the form of AudioBufferSourceNode), so at least we should allow developers to explore different parameters.

In that sense, 5x on `playbackRate` and `detune` over 4 octaves are fairly narrow.

**Comment by rtoy** [comment]
Propose some values. I don't really care; we just need something for the min/max attributes for `playbackRate` and `detune`.  In any case, it needs to be consistent with computedPlaybackRate as noted in #764.

**Comment by pendragon-andyh** [comment]
I agree if "nominal" means the normally-expected range of values. However I
don't think these should be the same as hard-limits ...

I need detune to support a much larger range than +/- 2 octaves. Classic
analogue synths often use 1 volt per octave. It is not unusual to have the
voltage modulate over at least a 5 volt range. The detune param gives the
correct curve - but needs to allow at least 6000 cents.

Internally playback rate and detune are used to calculate float
index-increment values that can easily safely be pushed from 0 to almost
half of the sample rate.  Those are the real limits that might benefit from
clamping.

Nominal values are useful as a teaching aid and (if we have min and max
values on params) for auto-discovery. Hard-limits should be stated
separately.

I guess what I am trying to say is that we should not artificially
constrain the api if it is not entirely necessary.

**Comment by rtoy** [comment]
As currently spec'ed, the nominal ranges are, in fact, the limits.  I
believe in all cases except one (BiquadFilterNode.gain), the nominal ranges
are the widest possible values, even if they might be practically useful
such as GainNode.gain is (-inf, inf).

I'm perfectly ok if detune range is (-inf, inf).  We just need to pick
something.  And since we're exposing the limits to the user, we can even
give the minimum acceptable range and allow browsers to choose larger
ranges if desired.

On Thu, Mar 17, 2016 at 5:54 PM, Andy Harman <notifications@github.com>
wrote:

> I agree if "nominal" means the normally-expected range of values. However I
> don't think these should be the same as hard-limits ...
>
> I need detune to support a much larger range than +/- 2 octaves. Classic
> analogue synths often use 1 volt per octave. It is not unusual to have the
> voltage modulate over at least a 5 volt range. The detune param gives the
> correct curve - but needs to allow at least 6000 cents.
>
> Internally playback rate and detune are used to calculate float
> index-increment values that can easily safely be pushed from 0 to almost
> half of the sample rate. Those are the real limits that might benefit from
> clamping.
>
> Nominal values are useful as a teaching aid and (if we have min and max
> values on params) for auto-discovery. Hard-limits should be stated
> separately.
>
> I guess what I am trying to say is that we should not artificially
> constrain the api if it is not entirely necessary.
> On 16 Mar 2016 20:22, "rtoy" <notifications@github.com> wrote:
>
> > Proposal: playbackRate range is [0, 5] and detune is [-2400, 2400]. This
> > assumes playing something 5 times faster is more than enough. The
> > playbackRate doesn't include negatives values right now because #95
> > <https://github.com/WebAudio/web-audio-api/issues/95> hasn't been
> > resolved. When it is, we can update the lower limit then.
> >
> > I also forgot that detune is in cents, so for the BiquadFilterNode and
> > OscillatorNode, a nominal range of [-2400, 2400] is ok. (Two octave
> > change. Is that large enough?)
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WebAudio/web-audio-api/issues/762#issuecomment-197529906
> >
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/issues/762#issuecomment-198147879>
>



-- 
Ray

**Comment by rtoy** [comment]
Proposal:  frequency is, of course, [0, Nyquist].  

Instead of unbounded, maybe detune should be -20 to 20 octaves? (detune range of [-24000, 24000]). If you detune up by 20 octaves from 1 Hz center, you're at 1 Mhz or so.

**Comment by mdjp** [comment]
AudioBufferSource
        playbackRate [-100,100]
        detune [-inf,inf]
    BiquadFilter
        frequency [0,niquist]
        detune [-inf,inf]
    Oscillator
        frequency [0,niquist]
        detune [-inf,inf]

**Comment by hoch** [comment]
Sorry for resurrecting this but, I have a slight issue: `AudioParam.min` seems to be too short. Can we make `AudioParam.minValue`? So the interface will look like:

```webidl
partial interface AudioParam {
           attribute float value;
  readonly attribute float defaultValue;
  readonly attribute float minValue;
  readonly attribute float maxValue;
}
```

**Comment by joeberkovitz** [comment]
+1 from my point of view - that is more consistent
