### ISSUE TITLE
computedPlaybackRate nominal range is [-100, 100]?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#764]
`computedPlaybackRate` is described in the paragraphs just before http://webaudio.github.io/web-audio-api/#looping-AudioBufferSourceNode.  The nominal range is [-100,100].  This presupposes that the playback rate can be negative.  I think we've agreed on doing this, but we haven't formally addressed all of the issues in #95.

A playback rate of 100 seems rather excessive.  In any case, this needs to coordinated with #762.

**Comment by mdjp** [comment]
Agreed range is -100, 100
