### ISSUE TITLE
Behavior of automations and nominal ranges?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#766]
How should automations behave when they go outside the nominal range?  For example, the gain for a `BiquadFilter` has a nominal range currently of [-40, 40].  If we do `gain.linearRampToValueAtTime(-100, t)`, what happens?  Is it clamped to -40 at the time of the call so the ramp goes to -40 at time t? Or does the ramp have the specified slope until some time t1 where the ramp reaches -40 and then remains constant at -40?

**Comment by rtoy** [comment]
Consider this use case still using the biquad gain parameter.

    gain.setValueAtTime(0, 0);
    gain.linearRampToValueAtTime(-100, 1);
    gain.linearRampToValueAtTime(0, 2);

If the clamping happens internally so that the gain reaches -40 at t1 < 1 and stays there, what should the second ramp do?  Start at -40 at time 1 and ramp to 0 by time 2?  But clearly the user expected at time 1, the gain should be -100 so should the gain actually look like a line from -100 to 0, but is clipped to -40?

Either of these could work, but maybe the easiest way to explain the behavior is just to do the clamping at the time of the call.  And since we expose the min/max values now, there's no excuse for making the automation go past the limits.

**Comment by mdjp** [comment]
F2F resolution clamp internally after computation.
