### ISSUE TITLE
Formulas for lowpass and highpass are incorrect

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#769]
In https://webaudio.github.io/web-audio-api/#filters-characteristics, the formulas for the lowpass and highpass filters depend on the term `alpha_b`.  But the formula for `alpha_b` depends on `G`, the gain AudioParam of the filter.  This is wrong.  The lowpass and highpass filters depend on `Q`, not `G`.

The relevant code from Chrome (and similarly for other browsers because we all agree) is:

        // Compute biquad coefficients for lowpass filter
        resonance = std::max(0.0, resonance); // can't go negative
        double g = pow(10.0, 0.05 * resonance);
        double d = sqrt((4 - sqrt(16 - 16 / (g * g))) / 2);

The `resonance` term is related to `Q`.  I think a simple replacement of the `G` with the correct expression in the `alpha_b` equation will fix this.

**Comment by rtoy** [comment]
These is even more confusing.  Based on the code, the resonance (`Q`) is in dB for the lowpass and highpass filters.  But for the other filters, `Q` is linear.  We need to say this in the spec as well.

**Comment by rtoy** [comment]
If #771 is fixed, then this is irrelevant and should be closed.

**Comment by AntonKhorev** [comment]
This is a typo. `alpha_B` should be replaced with `alpha_Q`. You can get the same frequency response for IIRFilterNode as for lowpass biquad filter if you read `alpha_B` as `alpha_Q` in the formulas for `a_0` and `a_2`.

**Comment by rtoy** [comment]
No, it is not a typo.  We explicitly made a decision a while ago to follow what all of the actual implementations were doing and not what the Audio EQ Cookbook was doing.  However, see issue #771, which is closely related.

**Comment by AntonKhorev** [comment]
This decision contradicts other part of the spec. [Here](http://webaudio.github.io/web-audio-api/#idl-def-BiquadFilterType.lowpass) lowpass filter depends on *Q* and not on *gain*, but its [characteristics](http://webaudio.github.io/web-audio-api/#filters-characteristics) depend on *gain* and not on *Q*. Implementations (Firefox and Chrome) use *Q*.

Do you want to say that implementations use formulas with *G* replaced by *Q* and not with `alpha_B` replaced by `alpha_Q`?

**Comment by rtoy** [comment]
There are two issues here.  The spec currently says `alpha_B` which depends on `G`.  But as you point out these filters actually depend on `Q`.  This issue is about fixing the text in the spec to do what implementations currently do, as mentioned in https://github.com/WebAudio/web-audio-api/issues/769#issue-143007107.

Thus, keep `alpha_B`, but change the definition of `alpha_B` to use `Q` and not `G`.  

However, #771 says doing so means there are valid filters that can't be presented.  And #771 proposes essentially what you say:  use `alpha_Q` instead of `alpha_B`.  This is a breaking change that causes audible differences, even to my poor old ears.

**Comment by mdjp** [comment]
Use Audio Cookbook but use Q in Db.

**Comment by mdjp** [comment]
wont fix
