### ISSUE TITLE
Some lowpass and highpass cannot be represented

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#771]
Consider a lowpass filter with coefficients:

    [a0, a1, a2] = [1, - 1.90291091031659, 0.9052674831504781]
    [b0, b1, b2] = [5.89143208472077e-4, 0.001178286416944154, 5.89143208472077e-4], 

This is a perfectly valid low pass filter.  (This was derived from a lowpass analog filter of the form 1/(1+2*s*T + (s*T)^2) with cutoff of 380 Hz and a sampling rate of 48000 using a bilinear transformation.) 

The magnitude response looks like
![maxplot](https://cloud.githubusercontent.com/assets/663356/14000293/e356324a-f0fd-11e5-823f-6640dd6a751b.png)

However, this filter is not representable using our lowpass biquad.  From b1, we can determine that w0 =  0.04854931272065959.  From our biquad formulas, a2 = (1-alpha_b)/(1+alpha_b).  Thus, alpha_b = .04972137386865789.  And the formula for alpha_b, we have alpha_b = sin(w0)/2*f(G).  Thus, f(G) = 2.049.

But look at the formula for f(G):  f(G) = sqrt((4-sqrt(16-16/G^2))/2).  G cannot be less than 1 because we'd be taking the square root of a negative number.  A quick plot shows that f(G) has a max at G=1 with a value of sqrt(2).  But we want f(G) = 2.049. And this is independent of whether G represents the gain or Q parameter as mentioned in #769.

Thus, we have a lowpass filter that is not representable by our biquad filter.

**Comment by rtoy** [comment]
Proposal:  Use the Audio EQ Cookbook equation where we replace alpha_b with alpha_Q = sin(w0)/(2*Q).  The lowpass and highpass filters are the only places where we differ from the cookbook.

With this formulation, we can easily derive Q = 0.488, and we can represent this filter using our biquad formulation.

A nice side-effect is that Q is now always a linear value between 0 and infinity for all of the biquad filters.  Currently, it is in dB for the lowpass and highpass filters as mentioned in #769.  The default value of Q of 1 would also make a lot more intuitive sense since it's not in dB anymore.

This change will, of course, break any existing use of lowpass biquads.  I did not check to see if this makes a noticeable change in the sound quality.

But I think we need to make this breaking change; we can't have a lowpass biquad filter that can't represent all lowpass filters.  I also did not check to see if the lowpass filter could be implemented using some combination of a different lowpass filter combined with some other highpass, bandpass or lowpas filter.

**Comment by padenot** [comment]
We _really_ need to have a listen or do some measurements before changing this, but I agree this is something we should consider, good find and write-up.

Maybe we could have a quick chat in Atlanta about that ?

**Comment by rtoy** [comment]
Sure, we can chat at the F2F.  However, I don't think we can leave the filters as they are.  We can't just prevent users from creating some perfectly valid filters that are designed from an analog filter using a bilinear transformation.

It's also bizarre that Q is in dB for some filter type and linear for others.

As for listening, I think the equations between the two schemes will allow us to simulate what the other would sound like without having to hack up your favorite browser.

**Comment by rtoy** [comment]
Here's the relationship between the two.  Let Qnew be the new Q (proposed) solution, and Qoldlin be the current Q value, linearized.  Then

    Qoldlin = 4/sqrt(16-(4-2/Qnew^2))^2)

And `Qold = 20*log10(Qoldlin)`

Or if you want to go the other way 

    Qnew = 1/sqrt((4-sqrt(16-16/Qoldlin^2))/2)

I'll try some listening tests soon.

**Comment by rtoy** [comment]
Check out http://rtoy.github.io/webaudio-hacks/more/biquad/biquad-lowpass-q.html

Enter Q values into one box or the other.  The other box will show you the equivalent Q value for the other implementation.

You will find that the differences are audible.

Making this change is going to suck.  But I think it sucks more that a user can design a lowpass filter that WebAudio can't implement. (Well, with a biquad.  IIR would work, but you can't automate that.)

At least there's always a conversion from the existing filter to the new.

**Comment by AntonKhorev** [comment]
It won't be a breaking change if a new filter type is introduced. Or maybe two new types: one that works like 'lowpass' does now, but reads *gain* parameter, and another one like in Cookbook.

**Comment by rtoy** [comment]
No browser I know of implements lowpass filters using the gain; that is really a typo in the spec.

**Comment by AntonKhorev** [comment]
They don't implement it using *gain*, but maybe they should if they want a parameter in decibels.

**Comment by rtoy** [comment]
I think making all browsers implement it using the gain parameter instead of the Q parameter would break far more applications than just implementing the proposal herein. And you'd then have to explain why the gain parameter can't be negative dB.

What exactly are you trying to achieve here?

**Comment by AntonKhorev** [comment]
How a new filter type would break anything?

**Comment by AntonKhorev** [comment]
Don't they already do clamping for `resonance` [as seen in the source code excerpt you provided](https://github.com/WebAudio/web-audio-api/issues/769#issue-143007107)?

**Comment by rtoy** [comment]
Sorry, you said *two* new types; I thought you meant modify one and add another.

Yeah, that won't break anything, but now there would be 3 lowpass filters type and 3 high pass filter types, all biquads, but strangely different and where appropriate choice of parameters can sometimes turn one into another.  All because we screwed up the original definition. I'm not in favor of this; I'd much rather just fix it once and for all with just 1 lowpass and 1 highpass.

As for the clamping, yes, the current implementations do clamp to 0 dB.  If you want your new filters actually to use gain instead of Q in the original formulas, you can still clamp to 0 dB. But that seems like a really strange thing to do with a parameter named gain which I would have expected to be able to amplify or reduce the signal.

**Comment by AntonKhorev** [comment]
I assume that the lowpass filter was implemented as it exists now because someone wanted a controllable resonance. Maybe they wanted to control the peak magnitude like in the 'peaking' filter, but they picked a "wrong" parameter which is not supposed to be in decibels.

With two additional types you'll have to choose only between those two types depending on what parameters do you want.

**Comment by mdjp** [comment]
Use Audio Cookbook but use Q in Db.

**Comment by rtoy** [comment]
As a side note, the existing definition has the nice property that if you set the Q parameter to q, then it can be shown that the resulting lowpass/highpass filter has a peak value of q dB.

In addition, if you look at the cookbook definition for the (analog) lowpass filter the denominator is `s^2+s/Q+1`, it can be shown that if Q <= 1/2, the quadratic can be factored into two real linear terms so that the lowpass filter can be presented as the sum of two 1st order filters so that it's not really a biquad anymore.

**Comment by rtoy** [comment]
For completeness, see http://rtoy.github.io/webaudio-hacks/more/biquad/biquad-lowpass-q.html?usedB=true to compare the responses between the old and new filters, as chosen here.  For most values of Q (in dB), the two filters have quite similar responses.
