### ISSUE TITLE
AudioWorklet examples (1): Importing scripts

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#776]
# IDL 

```webidl
partial interface Window {
    readonly attribute Worklet audioWorklet;
};

interface AudioWorklet {
    Promise<void> import(DOMString url);
};
```

# Examples

According to [Worklet](https://drafts.css-houdini.org/worklets/#worklet) specification, it imports a JavaScript code to register a certain functionality to the document. (Global scope) We have few options with respect to where `AudioWorklet` belongs, but I believe these two patterns are most acceptable:

- Pattern 1: `AudioWorklet` lives under `window` namespace.
```js
var audioWorklet = window.audioWorklet;
```

- Pattern 2:  `AudioWorklet` lives under `AudioContext` instance.
```js
var audioContext = new AudioContext();
var audioWorklet = audioContext.audioWorklet;
```

Then we call `import()` method to load the script within `AudioWorkletGlobalScope`. Note that this call returns a Promise.

```js
audioWorklet.import('myGainNode.js').then(function () {
  // Any task depends on myGainNode.js.
});
```

Multiple dependency on script files can be handled with `Promise.all()`.
```js
Promise.all([
  audioWorklet.import('myAudioNodeA.js'),
  audioWorklet.import('myAudioNodeB.js')
]).then(doAudioStuff);
```

**Comment by cwilso** [comment]
Probably should be under AudioContext, since it might have
samplerate-specific data?

**Comment by hoch** [comment]
I believe the pattern 1 is better because:
1. We can load all the dependencies before `AudioContext` actually starts running.
2. Once the script is loaded, all the audio context can share the definition of imported AudioNodes.

**Comment by hoch** [comment]
@cwilso I think AudioWorkletNode code should be independent to buffer size and sample rate. What use case do you have in mind?

**Comment by rtoy** [comment]
I think you need the sample rate if you want to implement, say, an oscillator.

**Comment by hoch** [comment]
`AudioNode` has a member of `context` according to the spec. So you should be able to access the context's sample rate within the definition of `AudioWorkletNode` class by `this.context.sampleRate`.

We should discuss this in #778.

**Comment by mdjp** [comment]
F2F resolution: Pattern 1 AudioWorklet to live under window namespace.

**Comment by mdjp** [comment]
Closing as discussed on call 14 July 2016
