### ISSUE TITLE
AudioWorklet examples (3): Defining AudioWorkletNode

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#778]
# IDL

```webidl
interface AudioWorkletGlobalScope : WorkletGlobalScope {
  readonly attribute sampleRate;
  readonly attribute bufferLength;
  void registerAudioWorkletProcessor (DOMString name, Function classConstructor);
};

interface AudioParamDescriptor {
  readonly attribute DOMString name;
  readonly attribute float defaultValue = 0;
  readonly attribute float minValue = -Infinity;
  readonly attribute float maxValue = Infinity;
}

// Represent the interface from audio thread. (defined in AudioWorkletGlobalScope)
partial interface AudioWorkletProcessor {
  readonly attribute sequence<AudioParamDescriptor> parameterDescriptors;
  void process (Float32Array[][] inputs, Float32Array[][] outputs, Object parameters);
}
```

# Examples

The definition of AudioWorkletProcessor must be declared in a separate source file. When the script files are imported, it is evaluated within `AudioWorkletGlobalScope`.

```js
// A separate JS file
registerAudioWorkletProcessor('Foo', class extends AudioWorkletProcessor {

  // Per-class AudioParam definition.
  get parameterDescriptors () {
    return [{
      name: 'gain',
      defaultValue: 0.707
    }, {
      /* more descriptors... */
    }];
  }

  // The constructor accepts the initialization data. Calling super() constructor is 
  // required for the initialization of AudioParams.
  constructor (options) {
    super();
    this.gain.value = options.gain;
    /* other initialization tasks */
  }

  // And audio process callback.
  process (inputs, outputs, parameters) {
    // Get |gain| array from gain AudioParam.
    var gainArray = parameters.gain;

    // Multichannel passthrough with gain control.
    for (var output = 0; output < outputs.length; output++) {
      for (var channel = 0; channel < channels.length; channel++) {
        var inputChannel = inputs[output][channel];
        var outputChannel = outputs[output][channel];
        for (var i = 0; i < out.length; i++) {
          outputChannel[i] = inputChannel[i] * gainArray[i];
        }
      }
    }
  }

});
```

**Comment by hoch** [comment]
My notes on this:

1. Instantiating `AudioParam` object in the class definition is going to be the key issue. I don't think it is possible to do that without introducing some magic method - like `defineParameters` above.
2.  `process()` method here does not support multiple inputs/outputs, but we can follow what cwilso@ originally proposed in the current spec.
3. Nothing prevents authors from registering multiple classes in a single JS file. That makes this pattern below possible. Not sure if we allow this. Furthermore, not sure if we can prevent this from happening.
```js
/* some script file */
var globalHack = {};

registerAudioWorklet('Foo', class {
// somewhere in the code
globalHack.value = 1;
});

registerAudioWorklet('Bar', class {
// somewhere in the code
var value = globalHack.value;
});
```

**Comment by cwilso** [comment]
Anywhere you register a <custom node class>, you're going to want to preload data - e.g., an impulse response, or a wavetable for an oscillator.  That data is going to need to be readied according to the samplerate - i.e., it's probably cached according to the audiocontext.  I'm a little worried about leaving that per-sample-rate work as an exercise for the custom node type implementor - I think they'll likely cheat a lot.  :)

**Comment by hoch** [comment]
@cwilso That's a fair point. Not sure how to handle any kind of server interaction (such as XHR) inside of `AudioWorkletNode` definition. Also I believe these assets (IR, wavetable, samples) are static across the same class of `AudioWorkletNode`. Can we use something like `static` keyword to declare this kind of asset?

I believe any kind of preparation needs to be done in the constructor.

```js
registerAudioWorkletNode('Foo', class {
   // This object is identical across all the instances of Foo node. (read-only)
   static Wavetable wavetable;

   /* other stuffs */
});
```

**Comment by itsjoesullivan** [comment]
> The definition of AudioWorkletNode must be declared in a separate source file.

Are there restrictions on where this file can live, i.e. does it need to be served from the same domain?

**Comment by hoch** [comment]
@itsjoesullivan I wasn't sure, but please take a look at this section.

https://drafts.css-houdini.org/worklets/#worklet-section

For me, it does read that we should support serving script files from other domain. However, I am not sure about dynamically crafting JS code into a string and parse/evaluate that with `AudioWorklet`. If we want that, we have to push the feature to Worklet spec.

@bfgeek Ian, Can you confirm this?

**Comment by padenot** [comment]
It should be possible to make a DataURL using `URL.createObjectURL`, maybe from a string ?

**Comment by padenot** [comment]
Tentative audioparam definition:
```js
// A separate JS file// A separate JS file
registerAudioWorkletNode('Foo', class {
  // The constructor accepts the initialization data.
  constructor (options) {
    this.parameters.gain = new AudioParam({min: 0, max: 10, rate: "k-rate", default: 1.0});
  }

  // And audio process callback.
  process (inputs, outputs, parameters) {
    // Get |gain| array from gain AudioParam.
    var gain = parameters.gain;

    // Stereo passthrough with gain control.
    for (var channel = 0; channel < outputs.length; channel++) {
      for (var i = 0; i < outputs[0].length; i++) {
        outputs[channel][i] = inputs[channel][i] * gain[i];
      }
    }
  }
});
```

**Comment by mdjp** [comment]
To be reviewed for next conference call.

**Comment by itsjoesullivan** [comment]
Thanks for investigating. I think that accepting a DataURL would be sufficient. I'm not sure if that is built in to the current worklet spec by defining the argument the worklet interface accepts as a `DOMString`. The [web workers spec](https://www.w3.org/TR/workers/#dedicated-workers-and-the-worker-interface) is a little more explicit:

> For example, scripts can be external files with the same scheme, host, and port as the original page, or data: URLs, or same-origin blob: URLs.

**Comment by bfgeek** [comment]
> Are there restrictions on where this file can live, i.e. does it need to be served from the same domain?

@itsjoesullivan No restrictions apart from what we need from a CSP standpoint. (Haven't written this yet).

@padenot Yup a `URL.createObjectUrl` will work. For testing we've been doing a lot of:

```html
<html>
<body>
<script id="audio" type="text/audio-worklet">
registerAudioWorkletNode('Foo', class { });
</script>

<script>
audioWorklet.import(URL.createDataUrl(
    new Blob([document.getElementById('audio').textContent]));
</script>
</body>
</html>
```

**Comment by joeberkovitz** [comment]
@hoch Is there any reason why node definition would not also work with the ES5 `prototype`-based approach to defining constructors and methods? I don't see any.

**Comment by hoch** [comment]
@joeberkovitz Nothing set in the stone yet, but what would be the benefit of it? By the time when we get Worklet infrastructure for all the browsers, we will have pretty solid ES6 support everywhere. Currently the worklet infrastructure is already being built on top of ES6's module loading and other features. If we desperately want to have ES5 support on this, we might have to upstream our concern to change the worklet spec.

**Comment by joeberkovitz** [comment]
@hoch I was not saying there would be any intrinsic benefit to ES5 interop, it was more a matter of making the backwards-compatible nature of the API clear to those who don't have much familiarity with ES6 yet. 

It sounds from what you're saying that ES6 modules are required to make use of Worklets at all. (I had not noticed this in the Worklets spec, but perhaps I missed it -- can you point me at the relevant bit?)

**Comment by hoch** [comment]
@joeberkovitz Perhaps it is not clearly defined in [the spec](https://drafts.css-houdini.org/worklets/#worklet-section) yet, but you can see `import()` method now has the argument of `moduleURL`. Perhaps @bfgeek can answer this question better.

@bfgeek WDYT?

**Comment by bfgeek** [comment]
Oh, you can totally still use ES5-like prototype based classes. I.e. this will work:

```js
var MyNode = function() { };
MyNode.prototype.process = function(...) { };

registerAudioWorkletNode('mynode', MyNode);
```

The primary difference with worklets is how code is loaded, you can still use ES5-like things if you want.

**Comment by hoch** [comment]
@bfgeek That's great! I thought ES6 class style is the requirement for Worklet.

@joeberkovitz Does this mean we have to rewrite all the examples in pre-ES6 style? I sort of prefer to have the example in ES6 style, but I guess it's up to WG's decision.

**Comment by joeberkovitz** [comment]
@hoch I don't think we need to port the examples to ES5. However, we should state explicitly that we are not relying on any ES6-specific language features.

**Comment by joeberkovitz** [comment]
@bfgeek Actually, are ES6 modules a requirement for Worklets also? Or can one load ES5 script files as defaulted modules that export everything? (I am not super familiar with this aspect of ES6 yet, so perhaps the answer's obvious.)

**Comment by hoch** [comment]
@joeberkovitz A tiny note; but ES5-style does not support `static` keyword. I am hoping to use `static` for the resource loading at construction time. Otherwise, we need magic methods to make that happens.

**Comment by bfgeek** [comment]
`static` is basically a shorthand for:

```js
var MyClass = function() { };
MyClass.staticProperty = ['an', 'array'];

// same as:
var MyClass = class {
  static staticPropert = ['an', 'array']; // TC39 should be adding this syntax soon(tm).
};
```

When `import()` occurs the code is effectively loaded like this:

```js
(function() {
   'use strict';
   // Code from file goes here.
})();
```

If that makes sense. So to use a library you'll need to es6-import it; or es5 prepend it to the script.

**Comment by hoch** [comment]
@bfgeek Yes, that was my guess. However, we still have the problem of 'magic method' for defining AudioParam before the constructor. Also I want to repeat @joeberkovitz's question: does Worklet spec require the ES6 module pattern for importing a script?

**Comment by hoch** [comment]
We also discussed this idea (sort if inspired by Polymer). This is not in ES6-style, but has more control over the construction process.

```js
registerAudioWorkletNode('foo' {
  /* class-wide AudioParamDescriptor */
  parameters: [{
    name: 'gain',
    defaultValue: 0.707
  }],

  /* at this point, this.parameters are accessible */
  constructor: function (options) {
    this.parameters.gain.value = options.gain;
  },

  process: function () { /* processing audio */ }
});
```

**Comment by joeberkovitz** [comment]
@hoch I'm having trouble understanding why we need a magic method that gets called before construction. Too much magic, maybe :)

Why can't we have `AudioWorkletGlobalScope ` expose a global `defineParameters` function available to the class definition that the constructor must call before doing anything else?  i.e.:

```js
registerAudioWorkletNode('foo', class {
  constructor: function (options) {
    // define parameters before using them, even in the ctor
    defineParameters(this, [{name: 'gain', defaultValue: 0.707}];
    this.parameters.gain.value = options.gain;
  },

  process: function () { /* processing audio */ }
});
```
I am also concerned that the magic-method concept doesn't work if we have AudioWorklet classes that extend superclasses, whereas the above approach would allow superclasses and subclasses to separately define their own parameters, each in its own constructor.

**Comment by hoch** [comment]
@joeberkovitz Sorry that I was not clear enough about the issue. It is problematic because we are making developers responsible for defining AudioParam manually. Also that means you can call that method basically anywhere in the `AudioWorkletGlobalScope`. I am not sure what should happen in that case. Of course we can put some text in the spec like 'do not do this outside of contstructor!' (which is somewhat sad.)

I believe the parameters should be ready before the constructor code gets executed, however, it is our decision to make. If everyone is fine with having a manual method rather than internal (magical) process, I am fine with that too.

**Comment by joeberkovitz** [comment]
@hoch I think it's preferable to let our node classes be "non-magical" and employ the ordinary features of JS, whether ES5 or ES6. We can spec well-defined behaviors that constrain the points in the object's lifecycle when these things can be called, which doesn't seem terribly sad to me.

I did overlook an important question, though. Was it the WG's intention to allow parameters to be magically defined on a per-instance basis, or per-class basis? If the answer is "per-class", then the parameter definitions should be packaged in a static getter, not defined as part of the instance construction as in my example.

Furthermore, to get around the need to force developers to call some special function at the head of their constructor to set up `this.parameters`, we can package this initialization in a superclass (and require that node classes extend this class). That way, one simply calls `super()` at the start of the constructor, and everything gets initialized nicely.

So...

```js
registerAudioWorkletNode('foo', class extends AudioWorkletNode {
  // audio framework will look for this static getter on the class and define parameters accordingly
  // for all nodes of this type
  static get paramDefinitions() {
    return [{name: 'gain', defaultValue: 0.707}]
  }

  constructor: function (options) {
    // this initializes the node, and sets up this.parameters as per the above definitions
    super();

    this.parameters.gain.value = options.gain;
  },

  process: function () { /* processing audio */ }
});```

In effect, the AudioWorkletNode class's constructor calls some utility function in the global scope that takes care of doing the parameter setup. This pattern also extends nicely if we want to add other kinds of initialization in the future.

**Comment by hoch** [comment]
Of course what I am proposing is 'per-class' approach. I don't think 'per-instance' style is particularly beneficial since you already can do the 'per-instance' initialization in the constructor.

I and @bfgeek briefly discussed about the idea of using `super()` and the static getter. However, basically what it does it making `super()` do the magic for you. That is, the prototype constructor of `AudioWorkletNode` reads the static getter of a derived instance and initializes `this.parameters` for you.

I don't see this is a problem though. Perhaps this pattern is better than using an extra magic method for the parameters.

**Comment by joeberkovitz** [comment]
Agreed. I see the `super()` as merely a nice way of packaging whatever required initialization should take place. And as you point out, what it does is not really magical: one could presumably include the same code by hand. (The initialization of `this.parameters` does have to be performed by a builtin at some level, but the call to that builtin function is simply wrapped by `super()` in this case.)

**Comment by hoch** [comment]
Just realized `this.parameters` is not the right way to do this. What we want is `myWorkletNode.gain.value = 0.5`, rather than `myWorkletNode.parameters.gain.value = 0.5;`

Other than that, I think we reached a reasonable conclusion. I will update the IDL and the example above.

**Comment by hoch** [comment]
Here's a tiny experiment with ES6 class inheritance:

```js
class Foo {
  
  get descriptor () {
    return 'Foo';
  }
  
  constructor () {
    console.log('Foo::constructing = ' + this.descriptor);
  }
}

class Bar extends Foo {
  
  get descriptor () {
    return 'Bar';
  }
  
  constructor () {
    super(); // This is necessary for `this` to be accessble.
    console.log('Bar::constructing = ' + this.descriptor);
  }
}

var bar = new Bar();

// Result:
// Foo::constructing = Bar
// Bar::constructing = Bar
```

I am afraid we cannot use `static` because the static getter cannot be reached via `this` keyword. You have to use `ClassName.staticGetter` to get the value and this pattern will not work with `super()` pattern. On the other hand, the plain getter works fine so we might want to use it.

**Comment by hoch** [comment]
FWIW, Chromium 52 ships with [ES6/ES7 by default](http://blog.chromium.org/2016/04/es6-es7-in-browser.html). I think this will happen much faster than AudioWorklet across all the browsers.

**Comment by joeberkovitz** [comment]
+1 Agree non-static is way to go here, the priority is on having inheritance work.

**Comment by hoch** [comment]
Also I added `sampleRate` and `bufferLength` to `AudioWorkletGlobalScope`. In this way, you do not have to query them through `this.context`. I think being able to introspect the whole context from the inside of `AudioWorkletNode` is problematic.

**Comment by rtoy** [comment]
Being covered in PR #869.  Closing.
