### ISSUE TITLE
BaseAudioContext is constructible?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#780]
http://webaudio.github.io/web-audio-api/#BaseAudioContext says `BaseAudioContext` has a constructor.  Is this what we want? I thought only `AudioContext` and `OfflineAudioContext` were constructible.

**Comment by mdjp** [comment]
F2F Agreed. Remove constructor.

**Comment by rtoy** [comment]
Duplicate of #748.  Closing.
