### ISSUE TITLE
Expose latency of an audio worklet as a property (if known)

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#785]
Raised by Norbert Schnell at WAC2016

Assumes we expose latency on other nodes. Undefined for some. It is latency, not tail.

**Comment by rtoy** [comment]
I've forgotten what exactly is being requested here.  Is this requesting a specific fixed attribute for all AudioWorklets to use?  Otherwise, I don't really know what this means.  Only the author of the Worklet knows the actual latency of the worklet.

**Comment by padenot** [comment]
I think that if we end up exposing the processing latency of `AudioNode`s, we could devise a way for the author of the worklet to publish its latency on the main thread.

It can certainly be done by post-messaging a value though.

**Comment by joeberkovitz** [comment]
Dependent on #786
