### ISSUE TITLE
Frequency domain and hop size (analyser node)

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#788]
Raised at WAC2015 & WAC2016. Moving FFT data across nodes. Max an PD don't have this. Chuck has it?

**Comment by svgeesus** [comment]
http://chuck.cs.princeton.edu/doc/language/uana.html
<hongchan> (I'll just put it here for the reference, ChucK with UAna

**Comment by joeberkovitz** [comment]
Unclear what this issue is asking for. Closing.

We already have a frequency-domain issue elsewhere: #468
