### ISSUE TITLE
Custom node

### ISSUE THREAD

**Issue by svgeesus** [WebAudio/web-audio-api#789]
Raise at WAC2016.

**Comment by hoch** [comment]
Wait, is this about Composite AudioNode? (Subclassing/Composition)

**Comment by hoch** [comment]
This is related to (or even a duplicate of) #251.

**Comment by hoch** [comment]
Again, I think this issue can be closed. #251 is marked as 'ready for editing.'

**Comment by hoch** [comment]
@joeberkovitz Could close this one with the chair hat on? :)

**Comment by joeberkovitz** [comment]
Closing since duplicated by #113
