### ISSUE TITLE
(DelayNodeSmoothing): DelayNode smoothing

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#79]
> Originally reported on W3C Bugzilla [ISSUE-17340](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17340) Tue, 05 Jun 2012 11:33:16 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-47 (DelayNodeSmoothing): DelayNode smoothing [Web Audio API]

http://www.w3.org/2011/audio/track/issues/47

Raised by: Philip Jägenstedt
On product: Web Audio API

The spec requires that "the implementation must make the transition smoothly" but does not define how.

For example, if the delay value is a sinusoid (AudioNode connected to AudioParam) or an even a linear ramp (linearRampToValueAtTime), what must happen? If the value changes fast enough, does the sound play backwards?

Related to https://www.w3.org/2011/audio/track/issues/42

**Comment by padenot** [comment]
This is blocked on #76.

**Comment by joeberkovitz** [comment]
This was closed by #393
