### ISSUE TITLE
Context stuck in suspended state on iOS

### ISSUE THREAD

**Issue by Hanley1** [WebAudio/web-audio-api#790]
I'm creating an AudioBufferSourceNode, connecting it to the context's destination, starting it. It runs fine and plays in the desktop environment, but when I load it on iOS, either Safari or Chrome, it doesn't play. I found that the AudioContext is stuck in a "suspended" state. I tried calling resume() but the promise stays stuck as "pending", so the context never changes to "running".

iOS 9.3.1. Is anyone else experiencing this? Is there something different that has to be done for the iOS environment?

**Comment by hoch** [comment]
This is not the place for reporting bug/error, but might want to take a look at [this](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/PlayingandSynthesizingSounds/PlayingandSynthesizingSounds.html#//apple_ref/doc/uid/TP40009523-CH6-SW5). The article says:

> Note: On iOS, the Web Audio API requires sounds to be triggered from an explicit user action, such as a tap. Calling noteOn() from an onload event will not play sound.

**Comment by Hanley1** [comment]
Ah sorry about that. Thanks for the tip, I'll check that out. Where would one go to report web-audio-api bugs/errors?
