### ISSUE TITLE
The biquad filter coefficients expressions are wrong

### ISSUE THREAD

**Issue by mohayonao** [WebAudio/web-audio-api#791]
I thought the expressions of the biquad filter coefficients are wrong in this specification.

1. The `alpha` of LPF/HPF/BPF is defined as `sin(w0)/(2*Q)` in [Audio EQ Cookbook](http://www.musicdsp.org/files/Audio-EQ-Cookbook.txt). This value is defined as `aQ` in the web audio specification, but use `aB`.

2. The `b0` and `b2` of BPF are missing multiplication factor `Q`.

| type    |:x:          | :o:             |
|---------|-------------|-----------------|
| LPF/HPF | a0 = 1 + aB | a0 = 1 + **aQ** |
| LPF/HPF | a2 = 1 - aB | a0 = 1 - **aQ** |
| BPF     | b0 = aQ     | b0 = **Q**aQ    |
| BPF     | b2 = -aQ    | b0 = -**Q**aQ   |

Red ovals represent this issue's points.

<img width="894" alt="2016-04-10 19 27 35" src="https://cloud.githubusercontent.com/assets/158075/14409574/5c1d02be-ff52-11e5-9eea-2d4a81def592.png">

<img width="952" alt="expr22" src="https://cloud.githubusercontent.com/assets/158075/14409542/19cc5596-ff51-11e5-99ce-d23bd0b48647.png">

In the Audio EQ Cookbook

```
Then compute a few intermediate variables:

  alpha = sin(w0)/(2*Q)                                       (case: Q)
        = sin(w0)*sinh( ln(2)/2 * BW * w0/sin(w0) )           (case: BW)
        = sin(w0)/2 * sqrt( (A + 1/A)*(1/S - 1) + 2 )         (case: S)



LPF:        H(s) = 1 / (s^2 + s/Q + 1)

            b0 =  (1 - cos(w0))/2
            b1 =   1 - cos(w0)
            b2 =  (1 - cos(w0))/2
            a0 =   1 + alpha
            a1 =  -2*cos(w0)
            a2 =   1 - alpha



HPF:        H(s) = s^2 / (s^2 + s/Q + 1)

            b0 =  (1 + cos(w0))/2
            b1 = -(1 + cos(w0))
            b2 =  (1 + cos(w0))/2
            a0 =   1 + alpha
            a1 =  -2*cos(w0)
            a2 =   1 - alpha

BPF:        H(s) = s / (s^2 + s/Q + 1)  (constant skirt gain, peak gain = Q)

            b0 =   sin(w0)/2  =   Q*alpha
            b1 =   0
            b2 =  -sin(w0)/2  =  -Q*alpha
            a0 =   1 + alpha
            a1 =  -2*cos(w0)
            a2 =   1 - alpha
```

**Comment by rtoy** [comment]
The spec does not use the Audio EQ cookbook formulas for all filters. (There was a typo in the formulas, but not the one you mention here.)

See #769 and #771 in particular.

**Comment by AntonKhorev** [comment]
It was resolved by changing the coefficients to something else. Now there are two versions of coefficients. How do I know which ones are used by the browser?

Now I have to keep both versions [in my tool](http://antonkhorev.github.io/webaudio-starter/en/base/): click `Add biquad filter`, click one of `Clone` buttons, then compare frequency responses.

**Comment by rtoy** [comment]
Unfortunately you have to test the output of the biquad to see which equations were used. However, we were careful to make the new filter produce similar response as the old for the same AudioParam values.  http://rtoy.github.io/webaudio-hacks/more/biquad/biquad-lowpass-q.html@usedB=true shows the responses for both the old and new filters.  They're quite close for most values of Q, but not all.

**Comment by rtoy** [comment]
Issue #771 is closed, and resolves this issue as well.

Closing.

**Comment by rtoy** [comment]
For completeness, see https://github.com/GoogleChrome/web-audio-samples/wiki/Detection-of-lowpass-BiquadFilter-implementation for a method of detecting which implementation you have and for a method of converting from one implementation to another.
