### ISSUE TITLE
Nominal playbackRate is too small

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#797]
Here is a real use-case where the `AudioBufferSourceNode` `playbackRate` is too small:  https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/webaudio/audiobuffersource-detune-modulation.html&l=45 and https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/webaudio/resources/audiobuffersource-testing.js&l=112

In this test, hongchan@ wants a precise sawtooth wave and sets the playback rate to 440 to generate a 440 Hz sawtooth.  (This is also a use-case for mathmatical oscillator waveforms that aren't band-limited.)

We should widen the nominal range for the playbackRate.

**Comment by hoch** [comment]
Yeah, I should've caught this and raised it in the F2F meeting. Thanks for finding it!

**Comment by rtoy** [comment]
Is [-Nyquist, Nyquist] too small?

**Comment by rtoy** [comment]
Or maybe the best solution is to say that all implementations must support [-100, 100], but implementations can support a wider range, as given by the min and max attributes.

**Comment by joeberkovitz** [comment]
On telcon of 5 May, WG attendees proposed +/- Infinity since the buffer could be arbitrarily large.
