### ISSUE TITLE
How to calculate cents value of detune property to change the frequency of note

### ISSUE THREAD

**Issue by shivrajsa** [WebAudio/web-audio-api#814]
I want to change the frequency of note from its original frequency using detune property.
I am trying to understand how to calculate cents for changing note frequency to required frequency.

For example frquency of C# is 277.1826192, if want to change its frequency to 
1. 275.6219814
2. 279.0672562
How should I calculate cents value for detune property? please guide.

**Comment by rtoy** [comment]
This is not a general WebAudio support list.  You should ask on StackOverflow or other forums.

However, having said that, http://webaudio.github.io/web-audio-api/#the-oscillatornode-interface gives the formula for the computed frequency of an oscillator in terms of the frequency and detune.  You should be able to figure out the detune value now for what you want.
