### ISSUE TITLE
setValueCurveAtTime should throw if the curve has non-finite values

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#815]
We don't explicitly say it but invalid values such as NaN or Infinity in the curve for setValueCurveAtTime should throw an exception.  We don't allow such values in the AudioParam value setter or any of the other automation methods.

(Is there a WebIDL way to constrain the values of the elements of an array?  That would be ideal.)

**Comment by mdjp** [comment]
Agreed.

**Comment by padenot** [comment]
I'm asking around, will follow up.

**Comment by padenot** [comment]
In light of <https://github.com/heycam/webidl/issues/126> I suggest we simply convert the signature to `sequence<float>` and let WebIDL deal with the problem.

**Comment by rtoy** [comment]
I'm fine with that because it's a lot easier to use interactively.  Perhaps this is a bug in chrome's idl but createIIRFilter([1, NaN], [1, Infinity]) signals only because the internal implementation manually checks for non-finite numbers.
