### ISSUE TITLE
createDoubleBuffer / createTripleBuffer

### ISSUE THREAD

**Issue by epistemex** [WebAudio/web-audio-api#816]
Would it be feasible to implement a `createDoubleBuffer `/ `createTripleBuffer `source node that cycles 2-3 buffer which can be filled with any data desired?

It could provide a "fillbuffer" event when a buffer has been consumed with access to the 1-2 other buffers (for reading, mixing etc.). (option could be to auto-clear/"null" the buffer after consumption).

I am aware of the JavaScript processor node but having buffers at larger sizes and cycling "forever" until stopped will, I think, provide great flexibility in regards to streaming, mixing, generating (can anyone say "tape loop") and perhaps also give larger room pre-processing some data using web workers etc. In any case, just a thought.

**Comment by hoch** [comment]
Seems like a good idea, but you can implement this 'round-robin' buffering mechanism in AudioWorkletNode. Still I would love to hear what other people think.

**Comment by rtoy** [comment]
Can't this be done using an 2-3 AudioBufferSource's and appropriate scheduling?

**Comment by padenot** [comment]
This can be done either with `ScriptProcessorNode`, `AudioWorkletNode`, or `AudioBufferSourceNode`, I don't think we will add another node for this purpose.

**Comment by epistemex** [comment]
Thanks guys - I understand `ScriptProcessorNode `is being deprecated? But I will check them all out.

**Comment by rtoy** [comment]
Adding label so WG can review this.

**Comment by rtoy** [comment]
Oops. This was closed.  Removing label.
