### ISSUE TITLE
Property ownership of outputTimeStamp and outputLatency

### ISSUE THREAD

**Issue by hoch** [WebAudio/web-audio-api#817]
Background:
Recently @pozdnyakov submitted the [intent to blink-dev](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/-d2ewB7k3Zg) for the implementation.

First, I would like to note that I wholeheatedly welcome the idea, discussion, PR from outside of working group. In [the original PR](https://github.com/WebAudio/web-audio-api/pull/754), I expressed my concern against the location of these new properties being AudioDestinatioNode but the PR made its way into the spec.

The following is what's planned in the intent:
AudioDestinationNode.outputTimeStamp.contextTime
AudioDestinationNode.outputTimeStamp.performanceTime
AudioDestinationNode.outputLatency

Currently we have (or firmly decided):
AudioContext.currentTime
AudioContext.baseLatency

In short, we will have two different places to query the timing information. The argument for this design was 'AudioDestinatioNode should be treated as the device output'. However, I believe this is an interpretation based on Chromium's implementation - and the implementation should not dictate the API design. The audio destination node is the output of graph, and it does not represent the actual hardware device. Conceptually the destination node is a passive element just like any other node. It is not responsible for advancing time or calculating the expected latency.

On the other hand, we already placed the time information in the context, and this we cannot change. (it has been there since day one of Web Audio API). I believe the context is the right place to query the time/latency information.

By all means, I really appreciate @pozdnyakov's effort on this, so I hope we could solve this issue as soon as possible.

**Comment by pozdnyakov** [comment]
Would you like to move both properties (`outputTimeStamp` and `outputLatency`) to context or  `outputLatency` can be left at `AudioDestinatinoNode` (the intention to add output latency to `AudioDestinatinoNode` originally came from @padenot https://github.com/WebAudio/web-audio-api/issues/12#issuecomment-143260345)? 

IMO it is quite natural to have output device properties at `AudioDestinatinoNode` as spec says that it "can often be considered as an audio output device which is connected to speakers". However I do not mind  moving the attributes to context  if WG decides that is a better way, my only concern is the time required for the specification changes.

**Comment by hoch** [comment]
Thanks for considering this - I should've followed up in the PR and that is my fault.

First, I would like to note that the spec should dictates the implementation, not the other way around.  A naive metaphor to a 'speaker' seems okay, but it does not mean AudioDestinationNode is the primary driver of the audio graph. In Chrome's implementation, ADN somehow has the actual rendering code, which is closely related to the advancement of time thus it might be reasonable to add the latency calculation code here. (and there is ongoing refactoring efforts to fix this) However, this is only the implementation detail and should not creep into the spec from my perspective.

The bottom line is: _AudioNode is a logical atomic unit of sound generation/processing and we should do our best not to make a node special than others._ Associating a node to the hardware layer directly makes it difficult for us to draw a line between high-level API and underlying hardware. That is my primary concern.

Here are some questions to think; 1) Should the output hardware (i.e. speakers) actively track the audio graph to get these value? 2) Why do we scatter these timing information to here and there when you already need to query a context to get the current time and the base latency? 3) What about MediaStreamDestinationNode? Shouldn't we add the same properties to this node as well? If not, why?

**Comment by rtoy** [comment]
Presumably the required spec change is small.  It won't talk long to get the changes in. If it takes a long time, it's the editors' fault.  Gently remind them as needed.

**Comment by pozdnyakov** [comment]
@hoch how would you like to proceed with this? would you make a PR or should I provide it myself?

**Comment by hoch** [comment]
Would love to hear feedback from @padenot and @joeberkovitz.

**Comment by joeberkovitz** [comment]
After reading @hoch's comments, I feel these properties do really belong to `AudioContext`. An approach could have existed at the beginning to associate `AudioDestinationNode` with the physical audio output, but the API didn't do that, and I can't see a good reason to change that approach midstream.

I'll try to answer @hoch's questions:

> 1) Should the output hardware (i.e. speakers) actively track the audio graph to get these value?

I thought it was more the other way around: that the audio graph made use of information from the output hardware.

> 2) Why do we scatter these timing information to here and there when you already need to query a context to get the current time and the base latency?

If there is only one real "output device" associated with a context, then I can't think of a reason to split up the API in this way. On the other hand, if multiple output devices could be used in the same context via different `AudioDestinationNodes`, then I would agree that `outputTimestamp`  belongs with the ADNs and not the contexts. But I don't think that this is possible without other far-reaching changes.

 3) What about MediaStreamDestinationNode? Shouldn't we add the same properties to this node as well? If not, why?

In a way, this fits with my response to item 2 above. I would ask, is `MediaStreamDestinationNode` a like another output device in the graph, with its own latency, and so forth? In a way it might seem to be, but I don't think it's possible to know anything about what is on the other end of the stream, and therefore how can one know anything about output latency or timestamps?

So, because of its non-physicality as a device, I would argue this is why we don't add the same properties to this node also.

**Comment by hoch** [comment]
@joeberkovitz Thanks for the response. I think we can move forward now.

@pozdnyakov Because this project has been your work from the beginning, I think it is better coming from you. Or if you want me to work on this, I do not mind as well. Any case, thanks for your contribution!

**Comment by pozdnyakov** [comment]
ok, let's move these attributes to context. However I have a question

> So, because of its (MediaStreamDestinationNode's) non-physicality as a device, I would argue this is why we don't add the same properties to this node also.

It's not quite clear yet to me what `context.outputTimeStamp` and `context.outputLatency` will return if `MediaStreamDestinationNode` is used as a destination. @hoch @joeberkovitz @rtoy what would you expect?

**Comment by rtoy** [comment]
I think that should be a different issue, distinct from this one.  That probably shouldn't block this issue from moving the attributes to the context.

**Comment by hoch** [comment]
I believe `context.outputTimeStamp` and `context.outputLatency` should stick to its local device, that is AudioDestinatioNode. `MediaStreamDestinatioNode` cannot be a sole destination for the graph. If you create a context, there will be always a `AudioDestinationNode` running the graph. Also it is impossible to report a meaningful estimated latency from peer connections. (Please correct me if I am wrong.)

**Comment by joeberkovitz** [comment]
@hoch I agree. To restate, an `AudioContext` always has an associated output device (even if nothing is routed to its `AudioDestinationNode`) and this is what the `outputTimeStamp` and `outputLatency` describe. In fact, in the future when output device selection is available, it's expected that the device will need to be identified as part of constructing an `AudioContext` instance.

**Comment by rtoy** [comment]
As the spec currently stands, here is another reason to have the time stamp and latency moved to the online audio context:  I don't think it makes sense for them on an offline context.  As part of the `AudioDestinationNode`, the offline context would inherit these attributes.  But https://github.com/WebAudio/web-audio-api/issues/824#issuecomment-221414938 suggest adding an OfflineAudioDestinationNode, which would also fix this issue.

**Comment by joeberkovitz** [comment]
@pozdnyakov I think the commit above is flawed in that the new attributes were moved to the `BaseAudioContext` interface. As @rtoy just pointed out, there is no meaning to `outputTimeStamp` and `outputLatency` in an `OfflineAudioContext` (which would inherit them from `BaseAudioContext`). So I think these attributes belong only in the `AudioContext` subclass.
