### ISSUE TITLE
Ability to schedule cleanup of GainNodes

### ISSUE THREAD

**Issue by itsjoesullivan** [WebAudio/web-audio-api#818]
I'd like to request a method to schedule the retirement of GainNodes. My specific use case is that I am trying to create one-time-use objects that share some common audio nodes with other objects. For instance, a factory creating drum hit nodes in which each instance has its own oscillators which are connected to a filter shared by all instances:

```
shared:                            -> filterNode
                                  /             \
                                 /               \
one-time-use:      oscillatorNode                 -> gainNode
```
(or, [example](http://output.jsbin.com/cuponacafe))

The gainNode is important, because it can be used to connect the instance to the consumer's audio graph in a one-time-use fashion. It's also important that it come after the filter. But when the oscillatorNode has run its course and is no longer "playing", that gainNode will not automatically be collected, because filterNode is still live. gainNode may be silenced, but I believe even when silenced it continues to eat up CPU cycles.

In a regular AudioContext, the OscillatorNode's onended property can be used to disconnect the filter from the gainNode, at which point the gainNode should disappear, but is it a good idea to rely on that behavior? Will that be honored in an OfflineAudioContext? Or is suspend/resume the approach to take to clean up this edge case when using an OfflineAudioContext?

It seems like a more general solution would be to be able to schedule a GainNode to stop as we can with an OscillatorNode or an AudioBufferSourceNode, where cleanup would happen along the lines of how it works when a [playing reference](https://webaudio.github.io/web-audio-api/#lifetime-AudioNode) disappears.

I imagine this feature has been discussed before, but perhaps not with this use case in mind. For now, onended is a workable solution, but in the long run I think there's a good reason to be able to explicitly retire GainNodes, and maybe any AudioNode.

**Comment by hoch** [comment]
So this doesn't work for you?

```js
filterNode.disconnect(gainNode);
gainNode.disconnect();
gainNode = null;
```

**Comment by itsjoesullivan** [comment]
> ```javascript
> filterNode.disconnect(gainNode);
> ```

is sufficient once the node has done its work, but that needs to be executed after the fact. An OscillatorNode's `onended` property seems like a good enough place to do that in an AudioContext, although it feels weird to do scheduling-type things that use the main thread, but I'm not sure what `onended` behavior is in an OfflineAudioContext. If `onended` doesn't get executed synchronously within an OfflineAudioContext's rendering (essentially doing a suspend/resume?), those live GainNodes would create a performance hit during rendering. In the worst case, some of those GainNodes might not actually be silenced, leading to unexpectedly different results between an AudioContext and an OfflineAudioContext acting on the same set of events.

I don't know about the silent hint, but it sounds promising -- can you direct me to a resource on it?

**Comment by rtoy** [comment]
`onended` isn't currently synchronous in Chrome in offline contexts.  Best bet:  If the source is scheduled to end at time t, instead of onended, use suspend(t) to synchronously do what you would have done with onended.

The silence hint is an internal optimization in Chrome.  If all inputs are known to be silent, the node can just set the hint and output all zeroes instead of doing the normal processing.  This is a win for complex nodes that would have all zero output for all zero input.

**Comment by hoch** [comment]
I don't think `onended` will be synchronous even for the distant future. It is a regular DOM event, so it is asynchronous by default. For OAC, you have suspend/resume with k-rate precision so you suspend and then resume the rendering when the `onended` event fires.

I can certainly point you to the place where silent hint happens in our implementation, but it is literally a implementation detail. The specification does not enforce the optimization like this, more importantly developers should not rely on or expect a certain behavior (i.e. timing or scope) of browser GC.

**Comment by rtoy** [comment]
Adding label so the WG can review this.

**Comment by itsjoesullivan** [comment]
Thanks for providing feedback on this issue. Let me try to encapsulate things discussed for the working group's consumption:

There's a situation where nodes can have served their purpose but still be alive according to the [spec](https://webaudio.github.io/web-audio-api/#lifetime-AudioNode). Specifically, this is when the node in question has a source node upstream with some long-lived (via a normal javascript reference) node in between. This approach may be an anti-pattern, but at first glance it seems like a way to avoid setting up the audio graph of a monophonic sound for every note (instead, just setting it up once when the instrument is initialized and re-using it).

In AudioContext world, the downstream node's source node's `onended` event is an opportunity to clean it up (by deleting it). In OfflineAudioContextMode, `onended` won't behave the same way--it will wait until rendering is complete or for a suspension, or at least it may do so. For very complex renders (or very slow machines), it may be important to be cleaning up the graph as you go. From what @rtoy and @hoch mentioned, in an OfflineAudioContext we can suspend the render periodically to either adjust the graph or allow for `onended` listeners to execute. So, using `onended` events (with periodic suspends if you're in an OfflineAudioContext) is a pretty good solution to this problem.

A different solution would be to provide a method to AudioNodes to allow them to signal their completion and schedule their removal (e.g. `gainNode.stop(when)`). It's pretty tidy, or seems to be.

Anyway, thanks again for the insights, and when you've got an opportunity please consider providing such a method to AudioNodes.

**Comment by rtoy** [comment]
Per teleconf:  Browsers should be smarter about doing this optimization.  The spec doesn't need to change for this.  We leave it up to each browser to do a better job of optimization.

**Comment by joeberkovitz** [comment]
Closing since @rtoy's response is agreed by WG
