### ISSUE TITLE
Behavior of setValueCurveAtTime followed by linearRampToValue?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#821]
Let's say you have a gain node, `g`, and do the following

```
g.gain.setValueCurveAtTime([1,0, .5], .1, .1);
g.gain.linearRampToValueAtTime(2, .5)
```

What's the expected output? I was expecting the curve to exist between times 0.1 and 0.2.  Then the linear ramp starts at time 0.2 with a value of 0.5 and ramps up to 2 at time 0.5.

However, the [spec is fairly clear on this](http://webaudio.github.io/web-audio-api/#widl-AudioParam-linearRampToValueAtTime-AudioParam-float-value-double-endTime).  The ramp starts at `T0`, the time of the previous event, which is  the start time of the setValueCurve.  This effectively removes the effect of the setValueCurve event.

This seems wrong. I think the ramp should start from the end of the setValueCurve.

**Comment by rtoy** [comment]
If we want the linear ramp to start at the end, we could say that `setValueCurveAtTime(curve, t0, td)` also adds an implicit `setValueAtTime(curve[N-1], t0 + td)`.  This would make the previous event for the linearRamp to be the last value of the curve at the end of the curve automation.

**Comment by padenot** [comment]
Yes I fully agree.
