### ISSUE TITLE
Video elements can be connected to Web Audio but can't be disconnected

### ISSUE THREAD

**Issue by digitarald** [WebAudio/web-audio-api#822]
For single page apps it is an important use case to reuse an audio context and its nodes while switching out the video input that plays back with spatial audio. Right now the only way on modern browsers is using `AudioContext::close`.

This would be solved with an API to disconnect the old video element and free its `MediaElementAudioSourceNode`.

Thoughts, @padenot ?

**Comment by padenot** [comment]
This probably works already. Ramp down the gain on the old HTMLMediaElement and ramp up the gain on the new one. Once this is done, simply reset the HTMLMediaElement by setting its source to an empty string or something like that, free up all references, and everything will be cleaned up.

I don't think we need a new API for this, but maybe I'm missing something ?

**Comment by digitarald** [comment]
👍 that matches what I did in the past and what I recommended as a solution.

> I don't think we need a new API for this, but maybe I'm missing something ?

This depends of what you described is expected and well defined behavior?

**Comment by padenot** [comment]
So, per spec, if `src` is not set, or set to an invalid source, the node should send a single channel of silence, so I don't think this is what we want here.

Maybe we could use `captureStream` and `MediaStreamAudioSourceNode` can be used, from [Media Capture from DOM Elements](https://w3c.github.io/mediacapture-fromelement). This is speced in a way that if the source is reset, the `MediaStream` ends. But then, `MediaStreamAudioSourceNode` also has this clause where a single channel of silence has to be sent "If there is no valid audio track".

This is not very useful. 

In particular, if you `src=""` on an `HTMLMediaElement`, and drop all references to it, along with the refs to the `MediaElementAudioSourceNode`, there is no way there can be something meaningful coming through this `HTMLMediaElement` in the future, so we should be able to GC and release everything. The spec forces us to send a stream of silence.

Same goes for the `MediaStreamAudioSourceNode` case. If the `MediaStream` it uses ends, it cannot be restarted, and if all refs to it are dropped and the refs to the `MediaStreamAudioSourceNode` are also dropped, we should be able to release everything.

In practice, this might be what Gecko does, but I'll double check tomorrow.

**Comment by joeberkovitz** [comment]
We'll change the spec to say that if the HTMLMediaElement becomes unreferenced and has a src of null, the node can be released.
