### ISSUE TITLE
OfflineAudioContext destination channelCount and channelCountMode changes?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#824]
The channelCount and channelCountMode are normally writable.  But what about the AudioDestinationNode for an OfflineAudioContext? 

I don't know how to make sense to create an offline context of, say, 7 channels, and then change the channelCount to 3.  We've already created a 7-channel buffer to hold the result, so what does it mean to have a channelCount of 3?

Also, the default channelCountMode is "explicit" for the destination.  What if I change to "max"?  Using the above example, if I now feed in a 10-channel source, the "max" setting kind of implies that output will have 10 channels.  But the buffer has already been created.

For simplicity, I propose that channelCount and channelCountMode cannot be changed for an offline context.  I think it's fine to allow the user to change the channelnterpretation to get the desired mixing effects (or not).

**Comment by hoch** [comment]
Just to be clear, `channelCount` and `channelCountMode` are members of AudioDestinationNode. I think it would be slightly easier to create a `OfflineAudioDestinationNode` to apply these constraints.

**Comment by padenot** [comment]
I agree.

**Comment by rtoy** [comment]
I think the conclusion is that we no longer want to add an `OfflineAudioDestinationNode`, based on comments in #856 and from the blink-dev intent to implement.

The constraints on the channel count and mode for the offline destination is handled in #968, fixed by #999.

**Comment by rtoy** [comment]
Closing this. I think #968 and #999 cover this issue and we don't need to do anything here.
