### ISSUE TITLE
`value` setter vs. `setValueAtTime` on `AudioParam`

### ISSUE THREAD

**Issue by padenot** [WebAudio/web-audio-api#828]
The new text for the [`value` setter](http://webaudio.github.io/web-audio-api/#widl-AudioParam-value) of `AudioParam` goes like this:

> The parameter's floating-point value. This attribute is initialized to the defaultValue.
> If value is set during a time when there are any automation events scheduled then
> it will be ignored and no exception will be thrown.

What is the meaning of "during a time where" ? Is it synonymous to

1. if any automation methods have been called with success on the `AudioParam` ?
1. if any automation events are scheduled in the strict future, after `AudioContext.currentTime` ?
1. if any automation events are scheduled in the future, at and after `AudioContext.currentTime` ?
1. something else ?

How would that work ?

1. is backward compatible I believe.
2. and 3. depending on the next paragraph's concerns, this means that you can't do:

```
gain.gain.value = 1.0;
gain.gain.value = 2.0;
```

if the currentTime has changed.

> The effect of setting this attribute is equivalent to calling setValueAtTime() with the current 
> AudioContext's currentTime and the requested value. Subsequent accesses to this attribute's 
> getter will return the same value.

Does that count as having called an automation method (since the call is somewhat forwarded to `setValueAtTime`), or is it special in the sense that it has the _effect_ of a `setValueAtTime`, but does not insert an event ?

**Comment by padenot** [comment]
cc @urbansolution for the Gecko side.

**Comment by rtoy** [comment]
I think in chrome, it's your option 1: any automation.

Well, except for the goofy behavior that if you call the setter when setTargetAtTime is running, the value does take affect causing setTargetAtTime to start ramping with a new starting value from the setter.

This particular behavior will change once the value setter becomes equivalent to setValueAtTime.

As for the part of effectively calling setValueAtTime, I'm not sure.  In chrome, any automation event causes the param processing to go through the slow path.  This could be optimized away with a bit of work, but touching the automation code is always error prone.

**Comment by padenot** [comment]
Repeatedly setting `.value` has to keep working, and should be ignored when an automation method has been called.

`.value` has to be _internally_ considered as having a time associated with it, but should not prevent setting `.value` again, so it's a bit like `setValueAtTime`, but does not count as an "automation event". 

It would be taken into account by other automation methods. Consider the following where `gain` is a `GainNode`:

```
gain.gain.value = 3.0;
gain.gain.linearRampToValueAtTime(0.0, ac.currentTime + 3.0);
```

This would make a ramp from 3.0 to 1.0 over the course of 3 seconds, starting immediately. More over,

```
gain.gain.value = 1.0;
gain.gain.value = 2.0;
```

would work fine, the effective value of the gain after this would be 2.0.

Does that make sense ?

**Comment by rtoy** [comment]
I follow everything you've said and agree, up to the final value=1 and value=2.  Are these in isolation, separate from the linearRamp setting?  If so, I agree.  If not, can you explain further?

And we've agreed that the .value setter is the effectively setValueAtTime at currentTime.  Are you saying you want the setter to be like setValueAtTime, but differ some how?

**Comment by padenot** [comment]
Yes, sorry, all examples are in isolation, I should have made this clear.

The setter should behave exactly like `setValueAtTime(value, audiocontext.currentTime);`, except that setting the value using the setter does not "count" has being an automation method, so setting the value again after setting it a first time should work, i.e.:

> If value is set during a time when there are any automation events scheduled then
> it will be ignored and no exception will be thrown.

does not apply to setting the value repeatedly, even though it should behave in every other respect like `setValueAtTime`, that is an automation method.

Does that make sense?

**Comment by rtoy** [comment]
Yes, thanks for the clarification.  

Since the setter should behave like setValueAtTime(), I think we should just get rid of the text about not working with other automation events.  Then it we can say it is setValueAtTime() and everything follows.

In chrome this has a performance impact, but that's an implementation issue, not a spec issue.

**Comment by padenot** [comment]
Right. This has web-compat issues, though, since setting the value after having used automation methods now has an effect. Maybe it's not breaking much code.

**Comment by rtoy** [comment]
That would be my guess.  For the people where it mattered, they've either cancelled automations or used setValueAtTime anyway.
