### ISSUE TITLE
Rename outputTimeStamp to outputTimestamp for consistency with other specs

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#829]
Gamepad, Geolocation, MSE, WebRTC, Notifications and WebVR have names where the S in timestamp is not capitalized:
https://w3c.github.io/gamepad/#gamepad-interface
https://dev.w3.org/geo/api/spec-source.html#position_interface
https://w3c.github.io/media-source/#sourcebuffer (timestampOffset)
https://w3c.github.io/webrtc-pc/#rtcstats-dictionary
https://notifications.spec.whatwg.org/#api
https://mozvr.com/webvr-spec/#vrpose

**Comment by rtoy** [comment]
Yes, let's be consistent.  (I guess it depends on whether you think timestamp is one word or two.)

**Comment by pozdnyakov** [comment]
This issue has been fixed together with #830

**Comment by rtoy** [comment]
Fixed by #830, as mentioned in https://github.com/WebAudio/web-audio-api/issues/829#issuecomment-224820621
