### ISSUE TITLE
Does outputTimeStamp return a new object every time?

### ISSUE THREAD

**Issue by foolip** [WebAudio/web-audio-api#830]
https://webaudio.github.io/web-audio-api/#widl-AudioContext-outputTimeStamp

From the prose it's not clear if a new object is returned every time, or if the same attribute is returned every time. There's a similar situation with media elements where the HTML spec goes to some length to ensure that the attribute does not change while a script is running:
https://html.spec.whatwg.org/multipage/embedded-content.html#official-playback-position

Something similar would probably make outputTimeStamp less useful, so a method that returns the most recent data every time is probably better.

This problem seems to frequently come up on the web platform, see https://w3ctag.github.io/design-principles/#attributes-like-data

@domenic @travisleithead

**Comment by foolip** [comment]
So I guess `outputTimestamp()` or just `outputTime()` to match `currentTime`?

**Comment by pozdnyakov** [comment]
@foolip thanks for pointing this out, `outputTimeStamp` is indeed supposed to return a new value, so should be converted to a method, I'd prefer `outputTime()` name (guess and that also fixes https://github.com/WebAudio/web-audio-api/issues/829), @rtoy wdyt?

**Comment by rtoy** [comment]
I think I'd still prefer outputTimestamp() to outputTime().
