### ISSUE TITLE
Mathjax displayed formulas are broken

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#831]
The current spec no longer displays equations correctly.  It looks like Mathjax is not processing the displayed equations (those surrounded by $$).

Inline equations are still displayed correctly.

**Comment by rtoy** [comment]
Removing the `<pre>` tags around displayed equations makes them displayed correctly.  But that is not a solution because those tags are needed to prevent tidy from mangling the TeX equations.

**Comment by padenot** [comment]
Fixed in d6430b09.
