### ISSUE TITLE
a-rate attributes for Position & Orientation in `PannerNode`

### ISSUE THREAD

**Issue by c-schwartz** [WebAudio/web-audio-api#837]
In [PannerNode](http://webaudio.github.io/web-audio-api/#idl-def-PannerNode) we can read :
 
> positionX of type AudioParam, readonly
    Sets the x coordinate position of the audio source in a 3D Cartesian system. The default value is 0. This parameter is a-rate.
 
> positionY of type AudioParam, readonly
    Sets the y coordinate position of the audio source in a 3D Cartesian system. The default value is 0. This parameter is a-rate.
 
> positionZ of type AudioParam, readonly
    Sets the z coordinate position of the audio source in a 3D Cartesian system. The default value is 0. This parameter is a-rate.
 
> orientationX of type AudioParam, readonly
    Describes the x component of the vector of the direction the audio source is pointing in 3D Cartesian coordinate space. Depending on how directional the sound is (controlled by the cone attributes), a sound pointing away from the listener can be very quiet or completely silent. The default value is 1. This parameter is a-rate.
 
> orientationY of type AudioParam, readonly
    Describes the y component of the vector of the direction the audio source is pointing in 3D cartesian coordinate space. The default value is 0. This parameter is a-rate.
 
> orientationZ of type AudioParam, readonly
    Describes the Z component of the vector of the direction the audio source is pointing in 3D cartesian coordinate space. The default value is 0. This parameter is a-rate
 
 
So all those attributes are a-rate.
 
But, it would be too expensive to change the parameters of an HRTF panner every sample. That is why I propose to keep k-rate attributes for HRTF.

**Comment by rtoy** [comment]
FWIW, Chrome doesn't make the HRTF panner a-rate. We have no current plans to do so.

**Comment by padenot** [comment]
That makes sense. We should spec it this way, and Gecko is going to implement the equal-power as a-rate, and leave the HRTF as k-rate.

**Comment by padenot** [comment]
Does everybody agree that this is the right way to proceed ? Having an a-rate convolver is quite hard and very very expensive.

**Comment by rtoy** [comment]
I'm ok with this.  My rough estimate is that an a-rate HRTF is about 30 times more complex.
