### ISSUE TITLE
Attribute sections are missing lots of text

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#840]
For example, https://webaudio.github.io/web-audio-api/#attributes-9 has an attribute section that is missing the descriptions of the actual attributes.  The methods appear to be ok, but the attributes are broken.  But not all attribute sections are broken; https://webaudio.github.io/web-audio-api/#attributes-4 looks ok.

I can only assume that this is caused by a ReSpec update.  I checked out a version of the WebAudio spec from a month or two ago, and it has the same broken behavior.

**Comment by skratchdot** [comment]
It seems as though each `<dd>` tag needs to be wrapped in a `<p>`. For instance, changing:
https://github.com/WebAudio/web-audio-api/blob/518378772176367376c114edb912b1bdd0c75ced/index.html#L3551-L3553
```
<dd>
    Duration of the PCM audio data in seconds.
</dd>
```
to
```
<dd>
    <p>Duration of the PCM audio data in seconds.</p>
</dd>
```
Seems to fix the issue.

I'd be up for submitting a PR, but I'm not sure if index.html is auto-generated from some other data (and the bug will crop back up again).  I could potentially write a script that checks to make sure the `<dd>` tags are formatted correctly as well...

**Comment by rtoy** [comment]
Thanks for looking into that.  That seems like a reasonable solution.

I also checked out a local copy of respec and tried a few different things.  From what I can tell, respec 3.3.2 and 3.3.1 produce broken specs.  The last version that seems to work is 3.2.97.  (There are only a few tags between these versions:  3.2.98, 3.2.99, 3.3.1, 3.3.2)

Perhaps we can file an issue against respec on this.

**Comment by padenot** [comment]
@marcoscaceres, is that expected?

**Comment by marcoscaceres** [comment]
Looking into it

**Comment by marcoscaceres** [comment]
So, we deprecated "old school WebIDL" about a year ago and I think moving to jQuery v3 (ReSpec v3.3.2) made things worse... and yeah, I eff'd up some git tags as you noticed. Options are, from least painful: 
 
 1. Do what @rtoy suggests in: https://github.com/WebAudio/web-audio-api/issues/840#issuecomment-226040570. 
 1.  target a particular ReSpec release version (not great).
 1.  Modernize your WebIDL usage (should take a couple of hours of work). 

I say start with 1, and I can help with 3 if you would like. But we need to do 3 in one go because, even though it's just editorial, it will change a lot of markup and that's not great if you have PRs coming in. Thankfully, you only have 3 there.  

Let me know how you want to proceed. I've got time this week to help.

**Comment by rtoy** [comment]
I've talked this over with @padenot and would prefer option 2: target a particular ReSpec version (probably 3.2.97).  Why?  We're both busy, and the group really want to go to CR soon (end of summer).  After CR, we can then do the necessary conversion afterwards.

@padenot, please correct me if I misunderstood our discussion.

**Comment by skratchdot** [comment]
@marcoscaceres - I'm working on a script that converts the current "old style" web audio api declarations to the newer respec/bikeshed format (i.e. converting `<dl title="idlType ObjectName" class="idl" />` to `<pre class="idl" />`).

So far, there are 51 IDL items specified:
```
{ enum: 9,
  interface: 34,
  callback: 2,
  Constructor: 3,
  dictionary: 3 }
```
NOTE: the 3 `Constructor` values are actually interfaces, but for now, my "translate" script treats them differently.

Anyways, I'm starting small with the `enum` values and I'd like your help.  The first enum I'm translating is "AudioContextLatencyCategory": https://webaudio.github.io/web-audio-api/index.html#idl-def-AudioContextLatencyCategory

Notice that there are 2 sections that are generated by the following html:
```
        <dl title="enum AudioContextLatencyCategory" class="idl">
          <dt>
            balanced
          </dt>
          <dd>
            Balance audio output latency and power consumption.
          </dd>
          <dt>
            interactive
          </dt>
          <dd>
            Provide the lowest audio output latency possible without glitching.
            This is the default.
          </dd>
          <dt>
            playback
          </dt>
          <dd>
            Prioritize sustained playback without interruption over audio
            output latency. Lowest power consumption.
          </dd>
        </dl>
```
The sections are the "WebIDL" and "Enumeration description" sections.

If I change that html to:
```
<pre id="enum-AudioContextLatencyCategory" class="idl">
    enum AudioContextLatencyCategory {
      // Balance audio output latency and power consumption.
      "balanced",
      // Provide the lowest audio output latency possible without glitching.
      // This is the default.
      "interactive",
      // Prioritize sustained playback without interruption over audio
      // output latency. Lowest power consumption.
      "playback"
    };
</pre>
```
It still only spits out the "WebIDL" section (descriptions aren't automatically pulled from the comments).

I'm guessing I can remove the comments, and add a 2nd html sibling to the `<pre />` tag that spits out the "Enumeration Description" table.  Can you please let me know what that HTML should look like (so I can update my script)?

Thanks!!!

**Comment by skratchdot** [comment]
Well, I just went ahead and converted the single `<dl />` into both a `<pre />` followed by a `<table />`.  You can check out the branch I'm working on called [transform-idl](https://github.com/skratchdot/web-audio-api/tree/transform-idl).

The enum conversion stuff is here:
https://github.com/skratchdot/web-audio-api/tree/transform-idl/idl/enum

There are 2 files for each IDL I converted.  The `.html` is the original content from `index.html` and the `.idl` is the converted WebIDL html.

So far I've only converted all the `enums` (and I haven't spot checked all 9 of them yet).  Now that I have the basic script working, the other types should be fairly easy to convert.  Then I'll have to spot-check everything, and clean up the content.  I wouldn't submit all the intermediary files in a PR, but wanted to do an initial check-in so you guys could view it via the github web interface.

Here's the 9 converted enums written to a new `index-new.html` file (NOTE: this would not be in the final pull request- just adding it so you can preview the work):
https://github.com/skratchdot/web-audio-api/blob/transform-idl/index-new.html

On the web:
New: https://cdn.rawgit.com/skratchdot/web-audio-api/76bd36eeb118bf761064c4c13527d90e905a2166/index-new.html
Current: https://cdn.rawgit.com/skratchdot/web-audio-api/76bd36eeb118bf761064c4c13527d90e905a2166/index.html

**Comment by marcoscaceres** [comment]
@skratchdot I was going to suggest using the `dl` instead of comments - awesome stuff! 👍

**Comment by rtoy** [comment]
Landed a fix so that the current spec isn't broken, pending a better solution.

We're just using a local copy of ReSpec that appears to work.

**Comment by rtoy** [comment]
3.2.97 is a bit old and is missing some features like automatically generating the IDL for dictionaries.

I'm going to do what @skratchdot suggested in https://github.com/WebAudio/web-audio-api/issues/840#issuecomment-226032263.

PR coming soon.
