### ISSUE TITLE
Need description of latency expectation in AudioProcessEvent

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#85]
> Originally reported on W3C Bugzilla [ISSUE-17350](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17350) Tue, 05 Jun 2012 11:41:13 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-59 (AudioProcessingEventScheduling): AudioProcessingEvent scheduling [Web Audio API]

http://www.w3.org/2011/audio/track/issues/59

Raised by: Philip Jägenstedt
On product: Web Audio API

How close to AudioContext.currentTime is AudioProcessingEvent.playbackTime expected to be when the audioprocess event is fired?

May a compliant implementation fire events arbitrarily far ahead of time in an arbitrary order? Presumably Web authors will make assumptions that the event is fired as close as possible to "now", so the spec should require this.

**Comment by joeberkovitz** [comment]
Please see https://github.com/WebAudio/web-audio-api/pull/625#issuecomment-156121619 for a relevant question on the definition of `currentTime` and its interaction with suspend/resume. Respond in the PR please.
