### ISSUE TITLE
In case of setTargetAtTime's timeConstant is zero

### ISSUE THREAD

**Issue by g200kg** [WebAudio/web-audio-api#850]
The spec defines that the timeConstant of AudioParam.setTargetAtTime() is strictly positive or a TypeError exception must be thrown.

But it is more intuitive and convenient if it change the value immediately when the timeConstant is zero.

##
Just for information, current browsers cannot handle timeConstant=0 normally. it will not throw exception. but it stop sound generation or cause incomprehensible error.

**Comment by rtoy** [comment]
Can you describe a use case for this?

If current browsers don't throw an exception when timeConstant is zero, then it's a bug in the browser.

**Comment by g200kg** [comment]
For example in envelope implementation, probably it will use mainly setTargetAtTime().

Though the each time parameters (attack, decay, release) include or not the value zero
is depends on synth's design policy, the code should always divide the cases if it include zero.
like followings:

if(tc>0)
  vca.gain.setTargetAtTime(0, time, tc);
else
  vca.gain.setValueAtTime(0, time);

This can be simplified into just one line if tc=zero is allowed.

vca.gain.setTargetAtTime(0,time,tc);

**Comment by rtoy** [comment]
While I certainly understand the convenience of just using setTargetAtTime with a time constant of 0, I don't find it really compelling.  It seems to me that if you're trying to ramp something smoothly, you would never set the tc to 0. It might be something small like 1 ms or .1 ms, but never zero.

But I'm not a musician nor do I make synthesizers, so apply the appropriate weight to these comments.

**Comment by g200kg** [comment]
Thank you.
In fact, this is not serious problem.

Just as a user, I hope API to accept wide range parameters within reasonable than put out the error. And the behavior of setTargetAtTime when (lim tc => 0) is same as setValueAtTime.

The current spec has enough formula plausibility. This is just a possibility that can be omitted a few lines in some cases.

**Comment by rtoy** [comment]
I'm not strongly opposed to allowing 0; it just seems odd to me.  I'll let others weigh in on this.

**Comment by toyoshim** [comment]
I also feel allowing 0 is convenient as g200kg suggested.

Here is a snippet how I implemented ADSR envelop by using GainNode.

keyon: velocity => {
  const now = context.currentTime;
  env.gain.cancelScheduledValues(0);
  env.gain.setValueAtTime(0, now);
  env.gain.linearRampToValueAtTime(velocity, now + A);
  env.gain.setTargetAtTime(velocity * S, now + A, D);
}

keyoff: () => {
  const releaseLevel = env.gain.value;
  env.gain.cancelScheduledValues(0);
  env.gain.setValueAtTime(releaseLevel, now);
  env.gain.setTargetAtTime(0, now, R);
}

There, D and R could be a user configurable parameters that might be 0.

Of course, I can do if (D === 0) ... else ... there. But it's inconvenient. Other workaround is not using D and R, but using D + delta, R + delta. But it isn't beautiful, and could not know actual working minimum value as the delta.

**Comment by rtoy** [comment]
I'm ok with allowing a time constant of 0 which means that the output will change instantly to the final value.

I guess the thing to decide is exactly how this behaves.  If I do `setValueAtTime(v, t, 0)` and `t` is on a frame sampling time, what is the output?  Is it `v` at time `t` or at time `t` + 1 frame?  I think `v` at time `t` is, perhaps, the right answer.

**Comment by padenot** [comment]
@rtoy, I agree (But I think you meant `setTargetAtTime` instead of `setValueAtTime`).

This way, `setTargetAtTime(v, t, 0)` does the same thing than `setValueAtTime(v, t)`, which is what I would expect.

**Comment by mdjp** [comment]
TPAC 2016 F2F - Allow time constant of 0.
