### ISSUE TITLE
AudioBufferSource channelCount, mode, interpretation?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#860]
Since `AudioBufferSourceNode` inherits from `AudioNode`, it has `channelCount`, `channelCountMode`, and `channelIntepretation`.  

The spec doesn't say anything about these for an `AudioBufferSourceNode`.  Should it?  Can they be set?  Do they have any effect on the node?  These need to be clarified.

Is there any relationship between channelCount and the channelCountMode of the `AudioBuffer` that is assigned to the `buffer` attribute?

**Comment by hoch** [comment]
Good point. I believe `AudioBuffer` attributes definitely should be transferred to `AudioBufferSourceNode`.

**Comment by padenot** [comment]
Yes I think it makes sense.

**Comment by rtoy** [comment]
Why?  `channelCount` is for the determining how to mix the input of which there are none for an `AudioBufferSourceNode`.

**Comment by rtoy** [comment]
Actually, https://webaudio.github.io/web-audio-api/#widl-AudioNode-channelCount says this has no affect for source nodes. (Same deal for `channelCountMode` and `channelInterpretation`).

Closing this (invalid)
