### ISSUE TITLE
(HardwareScalability): Hardware Scalability section is vague and incomplete

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#88]
> Originally reported on W3C Bugzilla [ISSUE-17372](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17372) Tue, 05 Jun 2012 11:56:34 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-87 (HardwareScalability): Hardware Scalability section is vague and incomplete [Web Audio API]

http://www.w3.org/2011/audio/track/issues/87

Raised by: Philip Jägenstedt
On product: Web Audio API

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#hardware-scalability

This section contains normative (RFC2119) language but looks like it's design requirements that were input to creating the spec and or implementation. A number of different approaches are mentioned, but none are required. There are a few particularly strange statements:

"The system should gracefully degrade to allow audio processing under resource constrained conditions without dropping audio frames."

"First of all, it should be clear that regardless of the platform, the audio processing load should never be enough to completely lock up the machine."

"The system should be able to run on a range of hardware, from mobile phones and tablet devices to laptop and desktop computers."

What is the system? Are these really intended to be normative requirements?

"In order to avoid audio breakup, CPU usage must remain below 100%."

This certainly doesn't look like a normative requirement, it's just "must" used in a non-RFC2119 way.

These may-level requirements are worrying:

"It may also be exposed through a cpuUsage attribute of AudioNode for use by JavaScript."

"An AudioNode can have a priority attribute to help determine the relative importance of the voices."

Either AudioNode expose the attributes, or it does not.

There are more issues, but we recommend to drop the section entirely. If any of it should remain, we will have to go over it in more detail.

**Comment by padenot** [comment]
I fixed this with #499 a while back, closing.
