### ISSUE TITLE
Add a method to reset the internal state of native nodes

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#9]
> Originally reported on W3C Bugzilla [ISSUE-18676](https://www.w3.org/Bugs/Public/show_bug.cgi?id=18676) Fri, 24 Aug 2012 10:33:30 GMT
> Reported by Jussi Kalliokoski
> Assigned to 

Proposed originally in http://lists.w3.org/Archives/Public/public-audio/2012JulSep/0614.html

A bit of clarification though, this method should bring the nodes to a state that is effectively the same as if they had not received any input data yet.

**Comment by svgeesus** [comment]
Convolver, filter, dynamic compressor have memory and cannot currently be flushed

**Comment by mdjp** [comment]
Closing, lack of feedback.
