### ISSUE TITLE
(WaveShaperNodeCurveLength): WaveShaperNode curve length limit

### ISSUE THREAD

**Issue by olivierthereaux** [WebAudio/web-audio-api#90]
> Originally reported on W3C Bugzilla [ISSUE-17365](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17365) Tue, 05 Jun 2012 11:52:13 GMT
> Reported by Philip Jägenstedt
> Assigned to 

Audio-ISSUE-79 (WaveShaperNodeCurveLength): WaveShaperNode curve length limits [Web Audio API]

http://www.w3.org/2011/audio/track/issues/79

Raised by: Philip Jägenstedt
On product: Web Audio API

https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#WaveShaperNode

The behavior is not defined when the curve is 0 or 1 values long. It would also be useful to clarify how the values are mapped to the -1 -> +1 range. The assumption seems be that the values are spread with equal spacing, such that a curve with an odd number of values has the middle value corresponding to 0 and a curve with an even number of values has the two middle values corresponding to values around 0.

Finally, is there an upper limit to the curve length? Presumably there is not.

**Comment by rtoy** [comment]
Fixed by pull request #388.
