### ISSUE TITLE
Value setter description in Computation of Value

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#901]
In https://webaudio.github.io/web-audio-api/#computation-of-value, bullet item 1 for the `ComputedValue` says

> If the value attribute is set after any automation events have been scheduled, then these events will be removed. 

I don't think this is what anyone does nor is it what we really want.  The value setter has never removed events from the time line.  This is also inconsistent with our desire to make the value setter equivalent to a call to `setValueAtTime` which doesn't remove any events.

I think this sentence should be removed.

**Comment by joeberkovitz** [comment]
Let's fix this.
