### ISSUE TITLE
AudioNode stop / disconnect doesn't free memory 

### ISSUE THREAD

**Issue by DracotMolver** [WebAudio/web-audio-api#904]
Hi there. I'm doing the nex when i press play button 
```javascript
public function play(){
 let xhtr = new XMLHttpRequest()  
   xhtr.open('GET', `file://${filePath}`, !0)
   xhtr.responseType = 'arraybuffer'
   xhtr.onload = () => {
     audioContext.decodeAudioData(xhtr.response, buffer => {
       source = audioContext.createBufferSource()
       source.buffer = buffer
       source.connect(audioContext.desteni)
       source.start(0)
       source.onended = () => {
         setNextSong() 
       }
     })
   }
   xhtr.send(null)
 }
}
```

and when the next song comes - it triggers onended event -. works perfectly, because the prev song is no longer playing anymore and the new one started calling the setNextSong(), which is like this:

```javascript
public function setNextSong(){
 source.stop(0) 
 source.disconnect()
 play()
}
```
but the thing is that when I'm watching into the terminal using top command line, I realize that the memory is getting higher. First started at 1,5 % of Mem. but then it's 2.3 and so on, and even the CPU is getting higher. I'm doing something wrong?, I must delete or set to null the AudioContext and create a new one?

**Comment by rtoy** [comment]
I think the spec is pretty clear that source nodes that have stopped playing should be GCed.  Your example drops references to old sources, so they should be collected.  If they're not, then it's a bug in the browser you're using and you should file a bug against the browser.

**Comment by DracotMolver** [comment]
I know the source should be GCed. Thanks, I will keep looking what it is. Maybe it's my code.

**Comment by DracotMolver** [comment]
Ok. It's the rest of my code. Here's the info form W3C
2.4.3 Lifetime

This section is informative.

An implementation may choose any method to avoid unnecessary resource usage and unbounded memory growth of unused/finished nodes. The following is a description to help guide the general expectation of how node lifetime would be managed.

An AudioNode will live as long as there are any references to it. There are several types of references:

A normal JavaScript reference obeying normal garbage collection rules.
A playing reference for both AudioBufferSourceNodes and OscillatorNodes. These nodes maintain a playing reference to themselves while they are currently playing.
A connection reference which occurs if another AudioNode is connected to it.
A tail-time reference which an AudioNode maintains on itself as long as it has any internal processing state which has not yet been emitted. For example, a ConvolverNode has a tail which continues to play even after receiving silent input (think about clapping your hands in a large concert hall and continuing to hear the sound reverberate throughout the hall). Some AudioNodes have this property. Please see details for specific nodes.
Any AudioNodes which are connected in a cycle and are directly or indirectly connected to the AudioDestinationNode of the AudioContext will stay alive as long as the AudioContext is alive.

NOTE
The uninterrupted operation of AudioNodes implies that as long as live references exist to a node, the node will continue processing its inputs and evolving its internal state even if it is disconnected from the audio graph. Since this processing will consume CPU and power, developers should carefully consider the resource usage of disconnected nodes. In particular, it is a good idea to minimize resource consumption by explicitly putting disconnected nodes into a stopped state when possible.
