### ISSUE TITLE
Number of supported channels for DynamicsCompressor?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#906]
The `DynamicsCompressorNode` says `channelCount` can be anything.  But it looks like Chrome only supports mono or stereo (from a quick glance at the code)  Presumably other browsers also only support mono or stereo too.

Should we limit `channelCount` to be 1 or 2?

**Comment by padenot** [comment]
How about we allow anything, but throw if the implementation only supports 1 and 2 ? NotSupportedError would fit.

**Comment by rtoy** [comment]
Works for me. I do like allowing browsers to compete and extend functionality in this way, while allowing developers to detect if the functionality is available.

**Comment by rtoy** [comment]
As mentioned in today's teleconference, I'm going to summarize the issues here.  This includes the very closely related issue in #908.

First, no browser (probably) supports more than 2 channels.  And @hoch says Chrome outputs silence if the input has more than two channels.  Also, the `channelCountMode` is "explicit" so that the node is supposed to up/down mix to the value specified by `channelCount`.  This is fine if these values are not changed.

But currently Chrome, Edge, Firefox, and Safari have `channelCountMode` set to "max", which means that input channels are processed and passed to the output with the same number of channels.

So perhaps the solution to this is to kind of capture what implementations are doing today (for a node that is completely unspecified!):

- `channelCount` can only be set to 1 or 2, defaulting to 2, and throwing a NotSupportedError if an attempt is made to set it to a different value.
- `channelCountMode` is set to "clamped-max" (to preserve the "max" behavior) and cannot be changed.  A NotSupportedError (?) is thrown if an attempt is made to change it.

@padenot suggested above about allowing more channels. Although I had said I'm ok with that, I'm rethinking this.  I suspect no browser will do this.  And there have been a couple of proposals that got positive reviews for adding new compressor, expander, and noise gate nodes where we would actually specify the behavior and then deprecate the dynamics compressor.

**Comment by mdjp** [comment]
For V1 we will spec that the node supports Mono->Mono + Stereo->Stereo.

**Comment by rtoy** [comment]
So, what does https://github.com/WebAudio/web-audio-api/issues/906#issuecomment-248881672 really mean?

Does this mean that `channelCount` can only be 1 or 2, and throw errors otherwise? Should `channelCountMode` be set to "clamped-max" and not be changeable?  I think these settings imply that we only support mono->mono and stereo->stereo, with the default mixing rules so that mono might be upmixed to stereo before the compressor, and multichannel inputs will be downmixed to mono or stereo before the compressor.  The output would be stereo at most.

Does that make sense?

**Comment by rtoy** [comment]
I think this needs clarification from the group. I can't quite figure out what Mono->mono and stereo->stereo really means and how that interacts with the channelCount stuff.

**Comment by joeberkovitz** [comment]
Putting on hold until compressor is speced.

**Comment by padenot** [comment]
If we input energy estimation is linked between channel, then a compressor node that supports more than stereo is needed. This is a common feature of multi-channel compressors.

Otherwise, this can be implemented with a splitter, a number of compressors, and a merger.

**Comment by hoch** [comment]
> this can be implemented with a splitter, a number of compressors, and a merger.

True, but I have never seen any multichannel compressor works that way. It will distort the spatial image of the sound for starters - which defeats the purpose of multichannel stream.

As you pointed out in the call, we should spec it in a more generic/extensible form, so we can support the proper multichannel compression later.

**Comment by joeberkovitz** [comment]
From F2F: document as 1 and 2 are the only allowed channel counts.
