### ISSUE TITLE
DynamicsCompressor channelCountMode value?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#908]
The spec currently says `channelCountMode` is "explicit".  But Chrome and Firefox currently say it is "max".  I didn't check, but presumably Safari and Edge also say "max".

If this these other browsers also use "max", I propose the spec should be changed to match what these browsers actually do. However updating each browser to use "explicit" is probably quite simple, but there's a (very small?) chance of changing the output of the compressor node if someone has a strange configuration of sources connected to the compressor input.

**Comment by rtoy** [comment]
See the discussion in #906, which is very closely related.

**Comment by mdjp** [comment]
For V1 we will spec that the node supports Mono->Mono + Stereo->Stereo.

**Comment by joeberkovitz** [comment]
From F2F: change the setting to `max`
