### ISSUE TITLE
The case for subsample-accurate start()

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#915]
Bob: Can I create a sine wave using WebAudio? I only got as far as

```
var context = new AudioContext();
```

Alice: Of course! You can just add the following:

```
var osc = context.createOscillator();
osc.connect(context.destination);
osc.start();
```

Bob:  Hey, that's cool.  But I actually want the first quarter wave of the signal to be zero.  Can we do that?
Alice:  That's not hard either.  We can just add a gain node to zero out that part like so:

```
var osc = context.createOscillator();
var g = context.createGain();
g.gain.setValueAtTime(0, 0);
var quarterWaveTime = (1/4)/osc.frequency.value;
g.gain.setValueAtTime(1, quarterWaveTime);
osc.connect(g);
g.connect(context.destination);
osc.start();
```

Bob: That's exactly what I wanted!  Thanks so much!  But you know, that looks like a cosine wave that starts after a quarter wave.  Can I do that too with WebAudio?
Alice:  Sure.  You have to use a custom oscillator to create a cosine wave, but it's not hard:

```
var osc2 = context.createOscillator();
var wave = context.createPeriodicWave(Float32Array.from([0, 1]), Float32Array.from([0, 0]));
osc2.setPeriodicWave(wave);
osc2.connect(context.destination);
var quarterWaveTime = (1/4)/osc2.frequency.value;

osc2.start(quarterWaveTime);
```

Bob:  That's so cool!  But is it really same?  How can I tell?
Alice:  Of course it's the same!  Just to prove it we can take the two bits of code, add another gain node and subtract one from the other like so:

```
var osc = context.createOscillator();
var g = context.createGain();
g.gain.setValueAtTime(0, 0);
var quarterWaveTime = (1/4)/osc.frequency.value;
g.gain.setValueAtTime(1, quarterWaveTime);
osc.connect(g);

var osc2 = context.createOscillator();
var wave = context.createPeriodicWave(Float32Array.from([0, 1]), Float32Array.from([0, 0]));
osc2.setPeriodicWave(wave);
var quarterWaveTime = (1/4)/osc2.frequency.value;

var inverter = context.createGain();
inverter.gain.value = -1;
osc2.connect(inverter);

g.connect(context.destination);
inverter.connect(context.destination);
osc.start();
osc2.start(quarterWaveTime);
```

Bob:  Thanks Alice, but my machine must be broken.  When I try this with hoch.github.io/canopy and paste your code in and use a sampleRate of 24000, I don't get zero output.  In fact it looks like a sine wave of amplitude 0.04 or so:
<img width="995" alt="screen shot 2016-07-26 at 7 55 06 pm" src="https://cloud.githubusercontent.com/assets/663356/17162425/ebad5246-536a-11e6-89af-443e252989be.png">

Alice:  Oh.

What happened?  Assuming that automations are sampled at frame boundaries, which is what Chrome does, the example using gain automation is truly what we want.  But the start time of the oscillator in the second case isn't sample accurate.  The delayed cosine wave started with an output value of 1 at a sample-frame boundary.  if it had started at the actual start time, and we sampled the resulting continuous signal at the sample-frame points, the resulting difference would have been much, much closer to zero.  I'd show a plot, but no browser I know of implements sample-accurate start for oscillators.

This would also a problem for AudioBufferSourceNodes if we don't have sample-accurate start.  If you replaced the oscillators with source nodes with buffers created using `Math.sin` and `Math.cos` as you would expect to use, the difference wouldn't be zero either.  (I leave the reader to test this out;  I haven't actually tried it.)

**Comment by rtoy** [comment]
Actually, does this need to be specified?  I always assumed that WebAudio should behave as if we were sampling a continuous waveform.  Hence, the oscillator start issue is actually a bug in the implementation.

But we have stated that `loopEnd` and `loopStart` round to the nearest frame in #336.  That contradicts this assumption.

**Comment by mdjp** [comment]
Resolution: loopEnd & loopStart to be changed to be sub sample accurate.
