### ISSUE TITLE
Finite looping with post-loop release sound

### ISSUE THREAD

**Issue by gagern** [WebAudio/web-audio-api#916]
Suppose I have a sample consisting of three parts, A-B-C, and part B is denoted as the loop via `loopStart` and `loopEnd`. Using the current draft, there appears to be no way to schedule a fixed number of repeats, or equivalently exiting the loop at a given time in the future.

It is possible to simply `stop(…)` the source at a point in the future, but doing so will stop it at whatever point it is at that moment, and not play the post-loop portion C of the sound. It is also possible to set the `loop` property to false in order to cause a loop exit, but that request cannot be scheduled, so timing depends on load on the controller thread and latency of the inter-thread communication.

Use cases for such a feature have been discussed before, e.g. in https://github.com/WebAudio/web-audio-api/issues/157#issuecomment-24244567 by Chris Rogers (referring to [UC 6: wavetable synthesis of a virtual music instrument](https://dvcs.w3.org/hg/audio/raw-file/b409a1ffc600/reqs/Overview.html) which apparently got superseded by [Music Creation Environment with Sampled Instruments](https://dvcs.w3.org/hg/audio/raw-file/e590df8302d0/reqs/Overview.html#music-creation-environment-with-sampled-instruments)) and https://github.com/WebAudio/web-audio-api/issues/267#issuecomment-27038047 by Douglas Gore.

In https://github.com/WebAudio/web-audio-api/issues/157#issuecomment-24244574 Joe Berkovitz stated that for many practical applications in soundfont synthesis, a release envelope combined with current looping is sufficient to model a release. ~~But looking at the Fluid R3 soundfont I have here, I see that there are many samples with something in the order of 400 samples past the end of the loop. One sample for timpani even has 2925 samples after the loop. So I'd say there is a real use case for post-loop sound.~~ _Edit:_ I realized that I didn't take the `sampleModes` of the sound font into account: no instrument _in that font_ is actually using sample mode 3 which is what I'm requesting here. I don't know about other sound fonts, though, or other applications.

I guess the most reasonable extension which does not break backwards compatibility would be adding a method `exitLoop([when])` to the `AudioBufferSourceNode`. An alternative might be accepting a numeric repeat cound to be assigned to the `loop` attribute, but that might break existing code which passes numbers and relies on auto-coercion.

**Comment by rtoy** [comment]
`absn.start(when, offset, duration)` should control when the loop exits, roughly.  Specifying a duration is the same as saying `stop(when + duration)`.  This will cause the looping to end.

To get the rest of the buffer to play, you can create a new `AudioBufferSourceNode`, using the same `AudioBuffer`, and do  `start(when + duration, loopEnd)` which will play the AudioBuffer from loopEnd to the end of the buffer.

I think this will achieve what you want.  All bets are off, though, if you're doing automations and such with `playbackRate`.

**Comment by mdjp** [comment]
No response to last comment. We assume this satisfied the requestors issue.  If not please raise a new issue on V2.
