### ISSUE TITLE
Interaction of suspend/resume and processing model is unclear

### ISSUE THREAD

**Issue by joeberkovitz** [WebAudio/web-audio-api#919]
The Processing Model does not refer to the AudioContext's `state`, and the definition in https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-state does not itself reference any effect on the Processing Model.

The suspend/resume documentation alone https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-suspend-Promise-void talks about the effects of `state` changes. It feels as though we are missing a link that describes the linkage between control thread `state` change and the behavior of the rendering thread.

**Comment by joeberkovitz** [comment]
@padenot I assigned you to look at this because of your remarks on #656

**Comment by padenot** [comment]
What I'm planning to do here:
- Add a state on the rendering thread, set by the control message that suspends/resume/closes
- Before computing an audio block, and in particular before swapping the message queue, if we are suspending, simply yield.
- When resuming, kick off rendering new blocks of audio. We will still have the old message queued.
- Add an informative paragraph about how things are in reality, with an audio callback that renders multiple blocks at once, etc.

Sounds good?

**Comment by joeberkovitz** [comment]
@padenot This sounds good. Can you draft language prior to the F2F?

**Comment by mdjp** [comment]
Agreed TPAC 2016 F2F
