### ISSUE TITLE
Unclear description in MediaStreamAudioDestinationNode

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#929]
In https://webaudio.github.io/web-audio-api/#the-mediastreamaudiodestinationnode-interface, the last sentence says:

> Any connections to the input are up-mixed/down-mixed to the number of channels of the input.

What does that mean? I'm guessing this really means that the inputs are mixed according to the settings of the channelCount, mode, and interpretation, like all nodes. Hence this sentence doesn't really need to be here at all, but if we want it, then it should be made clearer.

**Comment by padenot** [comment]
I think we can simply remove this.
