### ISSUE TITLE
ConvolverNode behavior underspecified and inconsistent

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#942]
From the [diagram](https://webaudio.github.io/web-audio-api/#Convolution-channel-configurations), it looks like there are six possible configurations of the `ConvolverNode`.  Some issues:

- The general N-input/K-convolvers/M-outputs is not possible and should be removed.
- It's impossible to distinguish the 1-input/1-convolver/1-output case from the 1-input/1-convolver/2-output case.  (Chrome and FF apparently both do the latter).  
- The relationship between channelCount and number of channels in the impulse response is not specified.
  - What happens with a stereo input and a mono impulse response?  Chrome outputs silence because it's not well defined.

Proposal:

- Remove the general case from the diagram
- Remove the mono to copied stereo case. (**This is a breaking change!**)
  - Alternatively, remove the mono case, which I think isn't implemented by anyone.
  - I find the mono to copied stereo case really confusing. (I was doing a test with two cascaded convolvers mono response with an oscillator input.  No audio is heard because the 2-channel input and mono response isn't specified.)
- The channelCount of the node is set based on the number of channels in the impulse response. Then channelCount = min(2, channels in impulse response).
 
With these changes, I think it's possible to reason exactly what will happen based on the channelCount, mode, and interpretation.  For example, the case of n-channel input with a one channel response has a channelCount = 1, so the input is mixed to mono, producing a mono output.  Easy!

**Comment by hoch** [comment]
To see the solution from a different angle:

| Buffer channel count  | Computed channel count |
| :---: | :---: |
| 1  | 1  |
| 2  | 2  |
| 4 | 2 |
| Other | NotSupportedError |
In this way, we can safely apply a mixing rule based on the computed channel count (where the count mode is `clamped-max` and the interpretation is `speaker`).

**Comment by rtoy** [comment]
Another case:  Consider a stereo input and a mono channel response.  What should happen?  If the response sets the channelCount (to 1 in this case), then the stereo input is down-mixed to mono and there's a mono input.  I think is this reasonable, but is it what we want?  I can imagine that it might be better to have a stereo input and output with the mono channel response upgraded internally to a stereo response with with identical responses on each channel.

**Comment by mdjp** [comment]
rtoy to consider and we will take this up on day 2 TPAC 2016

**Comment by rtoy** [comment]
Maybe the following will work. If the number of channels in the response is 1, automatically duplicate it to support stereo with the second channel identical to the given response.

Fix the `channelCount` to 2 and the `channelCountMode` to "explicit". Then mono inputs get upmixed to stereo and multichannel gets downmixed to stereo.  Then the output can always be stereo because the number of channels in the impulse response is 2 or 4.  If 4, we do true-stereo mixing.  Otherwise, it's basic stereo convolver.

I think this makes everything work, and preserves the existing behavior where mono inputs produce stereo output.  An implementation can optimize the mono input, one response case by doing mono convolver and duplicating the mono output to both the left and right channels. Chrome,  I think, does this already.

**Comment by rtoy** [comment]
Just to be clear, the proposal in https://github.com/WebAudio/web-audio-api/issues/942#issuecomment-248970420 was accepted.
