### ISSUE TITLE
Clarify "connection" in lifetime

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#944]
In item 3 of https://webaudio.github.io/web-audio-api/#lifetime-AudioNode, clarify that "connectIon" really refers to input connections.  

Maybe provide an example?

**Comment by joeberkovitz** [comment]
What about the case where AudioNode A is connected to an AudioParam exposed by AudioNode B? Does A keep B alive in this case?

**Comment by hoch** [comment]
I think it has to. However, I am not sure that is what we're doing currently.
