### ISSUE TITLE
min and max attributes of AudioParam

### ISSUE THREAD

**Issue by AntonKhorev** [WebAudio/web-audio-api#946]
`min` and `max` attributes of AudioParam were renamed to `minValue` and `maxValue`, but section 2.6 still says "Each AudioParam includes min and max attributes"

**Comment by rtoy** [comment]
I think this depends on whether you interpret "min and max attributues" to mean that their actual names are "min" and "max".  Nevertheless, it's probably less confusing to use `minValue` and `maxValue` (with links).

**Comment by AntonKhorev** [comment]
They are inside `<code>` elements like actual names.
