### ISSUE TITLE
BaseAudioContext.close() should not be defined

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#948]
In the current spec, https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-close-Promise-void defines a `close` method for a `BaseAudioContext`.  An `OfflineAudioContext` is a `BaseAudioContext` but you can't close an offline context.

I think the `close` method needs to be moved from `BaseAudioContext` to `AudioContext`.

**Comment by hoch** [comment]
+1
