### ISSUE TITLE
[TAG] AudioWorkletNode constructor creates things but then throws them away

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-audio-api#952]
It says to run a variety of constructors and create a variety of objects, but it does not store them anywhere for later use by the spec or from script. Thus, a conforming UA could just not do anything at all, as that would be observably equivalent.

I think you want to do something more like https://drafts.css-houdini.org/css-paint-api-1/#draw-a-paint-image

**Comment by hoch** [comment]
Yes, I am introducing the 'node instance set' for each AudioContext. I'll be uploading the PR after #945 is landed.

**Comment by hoch** [comment]
Fixed by #946. Two internal storage areas were added to hold the ownership of `AudioWorkletProcessor` and `AudioWorkletNode`.
