### ISSUE TITLE
[TAG] The AudioWorklet class seems redundant

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-audio-api#954]
All it does is define an import() method, but that is already defined by its base class, Worklet.

Instead, like https://drafts.css-houdini.org/css-paint-api-1/#dom-window-paintworklet, it seems best to not have this class at all, and just use Worklet.

**Comment by hoch** [comment]
Yes, it makes sense. Will fix that.

**Comment by hoch** [comment]
Fixed by #963.
