### ISSUE TITLE
[TAG] VUMeterNode's onmessage does not work

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-audio-api#955]
https://webaudio.github.io/web-audio-api/#vu-meter-node

This is an interesting case. Methods on classes cause property definition; they do not trigger setters. So the onmessage here will not work.

This is a bit unfortunate as I imagine it might trip up developers. We have had discussions about this when designing class properties (/cc @littledan).

I don't think there's much you can do here at a spec design level. I guess it's just best to change the example to move that to the constructor, so instead of defining an onmessage method, you do

``` js
  this.onmessage = event => {
    if (event.data.hasOwnProperty('volume'))
      this._volume = event.data.volume;
  };
```

in the constructor.

(This needs to be done for both classes in the example.)

**Comment by hoch** [comment]
I see. Fixing it is trivial, but being able to set up `onmessage` as a part of the class definition is actually quite nice. Hopefully we can have something similar in the future. :)
