### ISSUE TITLE
Respec warning about missing link to node name to processor definition map

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#958]
Respec currently produces a warning message:

> Found linkless <a> element with text 'node name to processor definition map' but no matching <dfn>.

**Comment by hoch** [comment]
@domenic 

I have a question. This `node name to processor definition map` cannot be captured in the IDL nor an example, because it is not exposed to user in anyway. We only refer this object to explain who keeps (owns) the data. What is the best practice for something like this?

**Comment by rtoy** [comment]
From an editorial view point, I'm fine if you just add `<dfn></dfn>` around the definition of this term, wherever it is.  This should get rid of the warning.

Or you can just remove the `<a>` tag.

I'll leave it to you and @domenic to determine what to say about this term.

**Comment by domenic** [comment]
Yeah, marking it up with a `<dfn>` makes sense. You'll need to say which user-exposed object it belongs to; I believe the correct object is the AudioWorkletGlobalScope.

Some specs formalize this as saying that the AudioWorkletGlobalScope stores the map as an internal slot, e.g. globalScope.[[nodeNameToProcessorDefinitionMap]]. But most of them just say something like "Every AudioWorkletGlobalScope has a node name to processor definition map" and then refer to "globalScope's associated node name to processor definition map".

**Comment by hoch** [comment]
Sounds good!

**Comment by rtoy** [comment]
This no longer happens, so I'm closing this.  Don't know which PR fixed this.
