### ISSUE TITLE
Default sample rate for AudioBuffer constructor?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#962]
It would be useful in the AudioBuffer constructor to allow sampleRate to default to the context sample rate if it's not specified.  Thus,
```
new AudioBuffer(context, {numberOfChannels: 1, length: 1})
```
behaves as if had said
```
new AudioBuffer(context, {numberOfChannels: 1, length: 1, sampleRate: context.sampleRate})
```

**Comment by padenot** [comment]
yes, that makes sense.

**Comment by rtoy** [comment]
Also useful to let numberOfChannels default to 1.  But there's no obviously universal default for length, so that's required.

**Comment by hoch** [comment]
Yes, the minimum number of channel that the system can provide for you is 1. Plus, the calling the constructor is a clear intention of 'I want to create something that can be played.'
