### ISSUE TITLE
AudioNode.channelCount needs to describe special cases

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#968]
As mentioned in https://groups.google.com/a/chromium.org/d/msg/blink-dev/J8XLxEnkLP0/MuwkC40kAQAJ, we can't really specify the special handling of the channelCount mode in the way that's specified; it's not possible in WebIDL.

Instead, in the description of channelCount, we need to specify here all the special cases, mentioned in https://groups.google.com/a/chromium.org/d/msg/blink-dev/J8XLxEnkLP0/MkSJpENGAQAJ

Perhaps it would be good enough to just list the nodes that have special cases and link to the relevant section of the spec that describe the behavior for the node.

**Comment by rtoy** [comment]
This also applies to `channelCountMode` and `channelInterpretation`.

**Comment by padenot** [comment]
Yes, I think the way you started to do it in your branch makes sense.

**Comment by rtoy** [comment]
Let's not add `OfflineAudioDestinationNode` and add the constraints in the AudioNode section.

I'll close #856.
