### ISSUE TITLE
AudioContextInfo.playbackTime name and connotation

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#969]
`AudioContextInfo` has a `playbackTime`. Why is this not called `currentTime`?  The description says it is equal to `context.currentTime`.  I think this is a bit confusing too because the `AudioProcessingEvent` for a ScriptProcessorNode as a `playbackTime`, but it means something different.

Also, https://hoch.github.io/web-audio-api/#widl-AudioContextInfo-sampleRate says `sampleRate` "represents" the context sampleRate. It doesn't represent it. It is the same value as the context sampleRate. (Minor editorial clarification.)

**Comment by hoch** [comment]
The issue has been fixed by #1066.
