### ISSUE TITLE
Funny order of AudioNode sections?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#973]
The current spec has the following sections in this order:
- BaseAudioContext
- AudioContext
- OfflineAudioContext
- AudioNode
- AudioDestinationNode
- AudioParam
- GainNode
- DelayNode
- AudioBuffer
- AudioBufferSource
- MediaElementAudioSource
- AudioWorklet
- ScriptProcessor
- AudioProcessingEvent
- Panner
- AudioListener
- StereoPanner
- Convolver
- Analyser
- ChannelMerger
- ChannelSplitter
- DynamicsCompressor
- BiquadFilter
- IIRFilter
- WaveShaper
- Oscillator
- PeriodicWave
- MediaStreamAudioSource
- MediaStreamAudioDestination

I find this order to be really strange.  I think that the list of AudioNode's should just be in alphabetical order instead of the current randomness.  Perhaps also have AudioParam and AudioBuffer before AudioNode. Possibly move the Media nodes to the very end since they're only for AudioContexts.

**Comment by rtoy** [comment]
Proposed order:

 - BaseAudioContext
 - AudioContext
 - OfflineAudioContext
 - AudioBuffer
 - AudioParam
 - AudioNode
 - Analyser
 - AudioBufferSource
 - AudioDestinationNode
 - AudioListener
 - AudioProcessingEvent
 - AudioWorklet
 - BiquadFilter
 - ChannelMerger
 - ChannelSplitter
 - Convolver
 - DelayNode
 - DynamicsCompressor
 - GainNode
 - IIRFilter
 - MediaElementAudioSource
 - MediaStreamAudioDestination
 - MediaStreamAudioSource
 - Oscillator
 - Panner
 - PeriodicWave
 - ScriptProcessor
 - StereoPanner
 - WaveShaper

Might be useful to separate out the Media* methods to a separate section, or moving them to the very end.

**Comment by rtoy** [comment]
`PeriodicWave` isn't an `AudioNode` either, so not sure where best to place it. Before the `AudioNode` section? A subsection of `OscillatorNode`?

**Comment by padenot** [comment]
@rtoy, I think you suggestions make sense, and I think we should implement the four suggestions you make, as well as reworking the order. I think `OscillatorNode` should be next to the `OscillatorNode`.

**Comment by rtoy** [comment]
I assume you mean `PeriodicWave` next to `OscillatorNode`.

I don't plan on making any of these changes until after TPAC; too many PRs in flight now. Once things have died down a bit.

**Comment by hoch** [comment]
The relationship between components are already visible through the link in the text, so I don't think they need to be organized based on the meaning/role/function. If this is up to me:

- AudioContexts.
- Everything else in alphabetical order.

I believe we should not bring a half-baked hierarchy or structure unless it is significantly beneficial.

**Comment by rtoy** [comment]
I think `AudioNode` should be first, followed alphabetically by all other nodes, including `AudioWorklet`.  For the things that aren't `AudioNodes`, I don't care too much, but placing them at the top-level along with nodes in the section after `AudioNodes` seems a bit weird, but ok.

**Comment by mdjp** [comment]
TPAC 2016 

    AudioContexts.
    Everything else in alphabetical order.

**Comment by rtoy** [comment]
Essentially https://github.com/WebAudio/web-audio-api/issues/973#issuecomment-248055288

**Comment by rtoy** [comment]
I think this should be a v1 blocker. While not really necessary, I wouldn't want to ship the spec with the nodes in essentially random order in the spec.

**Comment by rtoy** [comment]
And Re: https://github.com/WebAudio/web-audio-api/issues/973#issuecomment-248877154, I agree about everything in alphabetical order, except I think it makes sense to do AudioNode and AudioParam before all the other nodes. Otherwise, you'll read about AnalyserNode before you know what an AudioNode and AudioParam are.

**Comment by rtoy** [comment]
Tagging as V1 blocker; remove if it's not appropriate.

**Comment by mdjp** [comment]
Note - this is the last issue to be addressed before CR - it will require spec wide editorial changes so will cause issues with inflight prs.

**Comment by joeberkovitz** [comment]
Matt and I are questioning whether this is actually a V1 Blocker, and we need to get to CR which means clearing more important work from our plates.

**Comment by rtoy** [comment]
I guess it's not really a blocker.  But I find the current order horrendous. It shouldn't be very hard to do, once the order is decided, which we decided at TPAC. I would kind of like AudioNode and AudioParam after the contexts, then alphabetical everything, because it's kind of funny to have the fundamental AudioNode and AudioParam after AudioBufferSourceNode.

**Comment by joeberkovitz** [comment]
We don't mind doing it, we just feel it can be done last (and could even be applied as part of feedback during CR).
