### ISSUE TITLE
ChannelSplitterNode channelCount/Mode/Intepretation settings?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#975]
As currently spec'ed the [ChannelSplitterNode](http://localhost:7100/#the-channelsplitternode-interface) has a default count of 2, mode of "max", and interpretation of "speakers", and these can be changed. (A mode of "max" means the count is ignored, in case you forget, like I did.)

Allowing this complicated behavior for the splitter node complicates how to reason about the splitter's behavior.  It would be much simpler if we just said the count is the number of outputs, mode is "explicit", and interpretation is "discrete".  Then, the inputs are simply summed, and we take just the first n channels to go to the n outputs.

If the complicated behavior is needed, just stick an appropriate gain node before the splitter.

I think there are three alternatives here:

1. Leave things as is (allowing garbage in/garbage out)
1. Change the defaults to number of outputs, "explicit", "discrete"
1. Like 2, but don't allow the user to change the defaults.

I think I prefer the last option (as a user, not implementor). This also makes the splitter more like the merger where things are fixed and it is easy to reason about the behavior.

**Comment by mdjp** [comment]
Reviewed and option 3 was the preference choosen TPAC F2F 2016.
