### ISSUE TITLE
AudioBuffer buffer can be null for AudioBufferSourceOptions and ConvolverOptions

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#980]
For both `AudioBufferSourceOptions` and `ConvolverOptions`, the dictionary contains the member 

```
  AudioBuffer buffer
```

It is valid for the buffer to be `null`, so we should write
```
  AudioBuffer? buffer
```

**Comment by padenot** [comment]
Yes, I thought we had another issue about if we want it to be nullable, and what happens when you null it. I don't remember whether we decided.

**Comment by rtoy** [comment]
@padenot I believe it was for `.buffer` setter.

**Comment by rtoy** [comment]
`OscillatorOptions.periodicWave` has the same issue; it can be null.

**Comment by rtoy** [comment]
`WaveShaperOptions.curve` can be null.

One of `PeriodicWaveOptions.real` or `PeriodicWaveOptions.imag` can be null.
