### ISSUE TITLE
Should AudioWorkletNodeOptions inherit from AudioNodeOptions?

### ISSUE THREAD

**Issue by rtoy** [WebAudio/web-audio-api#984]
Currently, https://webaudio.github.io/web-audio-api/#AudioWorkletNodeOptions describes the dictionary by adding three members, `channelCount`, `channelCountMode`, and `channelInterpretation`.  Other than the default values, these are identical to `AudioNodeOptions`.

Also, https://webaudio.github.io/web-audio-api/#AudioWorkletNode has slightly different introductory text. All other nodes have a `<pre>` block describing the `'numberOfInputs`, `numberOfOutputs`, `channelCount`, `channelCountMode`, and `channelInterpretation`.

Perhaps it's best to follow the existing structure of the other nodes.

**Comment by hoch** [comment]
SGTM. I've been meaning to work on this. Perhaps after TPAC?

**Comment by hoch** [comment]
@rtoy @joeberkovitz WDYT?

```
dictionary AudioWorkletNodeOptions : AudioNodeOptions {
  unsigned long numberOfInputs = 1;
  unsigned long numberOfOutputs = 1;
}
```

**Comment by joeberkovitz** [comment]
This makes sense to me.
