### ISSUE TITLE
AudioNode constructors needs to actually be specified

### ISSUE THREAD

**Issue by bzbarsky** [WebAudio/web-audio-api#986]
I don't see anything that specifies what this constructor actually does.  There needs to be something.

**Comment by padenot** [comment]
Those should be defined in terms of the factory methods, and setting some specific attributes for each node, that needs to be specced. This factory method call and setting the attribute should be done atomically.

A thing to watch out for is that for the `ConvolverNode`, the `normalize` attribute has to be set before the buffer, otherwise the buffer won't be normalized according to the intent of the author.

**Comment by padenot** [comment]
@rtoy, I've tried something here: <https://rawgit.com/WebAudio/web-audio-api/2b4b86e548bf5b9e55cdedf7ba5036d142bfce43/index.html#the-audionode-interface>, search for, "AudioNodes can be created in two ways".

Does that sound like something that would work ? We would move the default values to the dictionaries.

**Comment by rtoy** [comment]
That looks great! I was wondering if we could define it just once in the AudioNode section instead of having to define it for every single node.

**Comment by padenot** [comment]
That's was the intent indeed, but I'm not too sure if I caught all special cases.

**Comment by rtoy** [comment]
Yeah, we'll have to verify it, but the convolver is the only node I can think of that has this ordering constraint.

I have only one issue with this approach.  I assume that in the future after v1, the factory method for new nodes won't be defined anymore, so this algorithm will no longer work.  But perhaps we can fix that when that day comes.

**Comment by padenot** [comment]
Yes, we will have to invoke the ctor directly in this case, or something.

**Comment by rtoy** [comment]
One additional complication:  `ConvolverOptions` uses `disableNormalization`, but the node attribute is called `normalize`.

**Comment by padenot** [comment]
That's fine, it's already in a special case anyways. I'll change that now.
