### ISSUE TITLE
Problem with OscillatorNode.setPeriodicWave() or  OscillatorNode.type

### ISSUE THREAD

**Issue by FlavouredGeorge** [WebAudio/web-audio-api#992]
My issue goes as this and, due to being based on my hearing only, could be called subjective, thought I encourage you to run the code and hear for yourself.
It boils down to the fact that, when trying to recreate the Oscillator Node's "sine" sound I am only able to do so using an array which consists of 3 samples, whenever I try to more accurately approximate a sine wave the sound becomes heavily distorted compared the the node's sine wave, here is the code:

/*
*Testing
*/
let ac = new AudioContext();
let osc = ac.createOscillator();
let gainNode = ac.createGain();

let length = ; <- Varrying this gives surprising results
let shape = [];

for(let i = 1; i < (length+1); ++i)
{
  n = (i - (length+1)/2)/((length+1)/2)
  shape.push(Math.sin(n))
}

console.log(shape)
let ft = new DFT(length); <- From dsp.js
ft.forward(shape);
var real = new Float32Array(length);
var imag = new Float32Array(length);

for(let i =0; i < length; ++i)
{
  real[i] = ft.real[i];
  imag[i] = ft.imag[i];
}
let wave = ac.createPeriodicWave(real, imag);

osc.setPeriodicWave(wave);
//osc.type = 'sine'; <- Used for testing the actual sine wave

osc.frequency.value = 220;

osc.connect(gainNode);
gainNode.gain.value = 0.1;
gainNode.connect(ac.destination);

osc.start();
osc.stop(2);

/*
*Testing
*/

Ok, I'm no experts in sound but, to my knowledge, a sine sounds kind of "Smooth" (being only on one frequency and all), however, in the code above, when I varry the variable "length" I get quite the unexpected effect of the sound getting progressively "rougher" when I increase it. so for example, with:

length = 3 (Which basically means I have a wave shape of ~[-0.48, 0, 0.48]) gives me the exact same sound as osc.type='sine';

length = 1281(should be very close to a 'real' sine, gives me a distorted granular buzz)

Am I not understanding the way this PeriodicWave is supposed to work ? Also, is there no way to set the wave shape of the oscillator directly from an amplitude X time graph rather than a amplitude x fq one.

**Comment by rtoy** [comment]
This seems not to be an issue with the WebAudio spec itself.  Perhaps you can ask on http://stackoverflow.com/questions/tagged/web-audio or other places on how `PeriodicWave` is supposed to work.

If you want a specific waveform, just use an `AudioBufferSourceNode` with your waveform, possibly also looping it.  `PeriodicWave` only works with in the frequency domain.

**Comment by FlavouredGeorge** [comment]
Unless I am mistaken and DFT from dsp.js isn't a Fourier Transform (or I have completely forgotten how FT works), the real(amp) and imag(phase) arrays I have should be in the frequency domain... so what exactly am I "getting wrong" here. 

I'm not saying that I'm not making a fallacy in the code I am writing, but where exactly is it ?

**Comment by rtoy** [comment]
I didn't look in any detail.  But this issue tracker is for issues with the spec, not the implementation. As far as I can tell, you haven't raised an issue with the spec itself.  I believe all browsers are implementing `PeriodicWave` and `OscillatorNode` correctly. 

A question on stackoverflow with a snippet showing the problem would be very helpful to you. (I lurk there.)

**Comment by FlavouredGeorge** [comment]
Understood, also, my code was indeed faulty, very sorry to have bothered you mate.

**Comment by rtoy** [comment]
No problem.  Glad you resolved the issue with your code.
